(()=>{'use strict';const $=id=>document.getElementById(id),q=new URLSearchParams(location.search),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),safe=v=>/^(https:\/\/|\/(?!\/))/.test(String(v||''))?v:'',date=v=>String(v||'').slice(0,10).split('-').reverse().join('/');let day,context,division=Number(q.get('division'))||1,tab=q.get('tab')||'pre',busy=false;
const fixtureId=q.get('fixture'),url=id=>'./?world=GW001&fixture='+id,reportUrl=id=>'../competitions/match.html?world=GW001&fixture='+id;
async function get(path){const r=await fetch(path,{cache:'no-store'}),j=await r.json();if(!r.ok||j.ok===false)throw Error('Dati temporaneamente non disponibili');return j}
function logo(src){return safe(src)?'<img class="club-logo" src="'+esc(src)+'" alt="">':''}
function photo(id,name){return Number(id)>0?'<a class="portrait" href="../players/profile.html?world=GW001&player='+Number(id)+'"><img src="https://cdn.soccerwiki.org/images/player/'+Number(id)+'.png" alt="'+esc(name)+'" loading="lazy"></a>':''}
function p(text){return '<p>'+esc(text)+'</p>'}
function interview(x){return '<article class="interview"><div class="interview-head">'+photo(x.id,x.name)+'<div><span class="eyebrow">INTERVISTA SIMULATA</span><h3>'+esc(x.name)+'</h3><div class="person-team">'+logo(x.logo)+'<span>'+esc(x.role)+'</span></div></div></div>'+x.qas.map(a=>'<div class="qa"><h4>'+esc(a.q)+'</h4><blockquote>«'+esc(a.a)+'»</blockquote></div>').join('')+'</article>'}
function market(c){return '<section class="market"><h3>'+esc(c.name)+'</h3><p><b>'+c.previous.position+'° in '+esc(c.previous.division_name)+' · '+c.previous.points+' punti</b><br>'+esc(c.movement==='promoted'?'Promosso in '+c.division_name:c.movement==='relegated'?'Retrocesso in '+c.division_name:'Confermato in '+c.division_name)+'</p><div class="market-count"><span><b>'+c.in.length+'</b> arrivi</span><span><b>'+c.out.length+'</b> uscite</span></div><details><summary>Il mercato registrato</summary>'+['in','out'].map(k=>'<h4>'+(k==='in'?'Arrivi':'Uscite')+'</h4>'+(c[k].length?c[k].map(t=>'<p><a href="../players/profile.html?world=GW001&player='+t.id+'">'+esc(t.name)+'</a><small>'+esc(date(t.date))+' · '+esc(k==='in'?'da '+t.from:'a '+t.to)+(t.amount?' · '+esc(t.amount):'')+'</small></p>').join(''):'<p>Nessun movimento registrato nel periodo.</p>')).join('')+'</details></section>'}
function score(f){return f.home_score!=null&&f.away_score!=null?esc(f.home_score)+' – '+esc(f.away_score):'VS'}
function matchHeader(f,div){return '<div class="match-context">'+esc(div)+' · '+esc(date(f.match_date))+'</div><div class="club-score"><div>'+logo(f.home_logo_url)+'<h2>'+esc(f.home_name)+'</h2><small>'+esc(f.home_imc_manager_name||'')+'</small></div><strong>'+score(f)+'</strong><div>'+logo(f.away_logo_url)+'<h2>'+esc(f.away_name)+'</h2><small>'+esc(f.away_imc_manager_name||'')+'</small></div>'}
function actions(f){return '<div class="club-actions">'+(f.home_score!=null?'<a href="'+reportUrl(f.sm_fixture_id)+'">Open Match Report</a>':'<span>Match Report in attesa</span>')+'<a href="'+url(f.sm_fixture_id)+'">Open The Club →</a></div>'}
function synopsis(f){return ['home','away'].map(s=>{const c=context.clubs[f[s+'_sm_club_id']];return f[s+'_name']+': '+(c?.previous?c.previous.position+'° in '+c.previous.division_name+(c.movement==='promoted'?', promosso':c.movement==='relegated'?', retrocesso':''):'dati precedenti non disponibili')}).join(' · ')}
function index(){const divisions=day.divisions;if(!divisions.some(x=>x.id===division))division=divisions[0].id;const d=divisions.find(x=>x.id===division);$('content').innerHTML='<section class="opening"><span class="eyebrow">L’APERTURA · GIORNATA 1</span><h2>Si riparte da zero.<br>Non dalla stessa storia.</h2><p>Torino difende il primo posto della Platinum, Atalanta riparte dal secondo posto a due punti dalla vetta. Sei club salgono di divisione e sei scendono: le aspettative cambiano, insieme alle rose.</p><p>Per ogni partita, le domande ai manager nascono dalla classifica finale della stagione 1 e dal mercato registrato tra l’11 e il 27 settembre. Le voci dei protagonisti sono ricostruzioni narrative, non dichiarazioni autentiche.</p></section><nav class="division-tabs" aria-label="Divisioni">'+divisions.map(x=>'<button data-division="'+x.id+'" aria-pressed="'+(x.id===division)+'" class="'+(x.id===division?'active':'')+'">'+esc(x.name)+'</button>').join('')+'</nav><div class="edition-heading"><h2>'+esc(d.name)+'</h2><span>5 partite · 5 prepartita</span></div><div class="fixture-list">'+d.fixtures.map(f=>'<article class="fixture">'+matchHeader(f,d.name)+'<p class="fixture-story">'+esc(synopsis(f))+'</p><p class="fixture-state">'+(f.live.ready?'Dopopartita disponibile':'Prepartita disponibile · Dopopartita in attesa dei report')+'</p>'+actions(f)+'</article>').join('')+'</div>';
 document.querySelectorAll('[data-division]').forEach(b=>b.onclick=()=>{division=Number(b.dataset.division);q.set('division',division);history.replaceState(null,'','?'+q);index()});}
async function detail(){const d=day.divisions.find(x=>x.fixtures.some(f=>String(f.sm_fixture_id)===fixtureId));if(!d){$('content').innerHTML='<section class="opening"><h2>Questa partita non fa parte dell’edizione.</h2><p>La prima edizione di The Club copre le 20 partite della giornata 1 della stagione 2.</p><a href="./?world=GW001">Apri l’edizione completa →</a></section>';return}const f=d.fixtures.find(f=>String(f.sm_fixture_id)===fixtureId);let report=null,reportError=false;if(f.home_score!=null)try{report=await get('../competitions/match.php?world=GW001&fixture='+fixtureId)}catch(e){reportError=true}
 if(!q.get('tab')&&report?.report_available)tab='post';const pre=ClubEditorial.pre(f,context),post=report?ClubEditorial.post(report):null;
 const prevHTML='<section class="story-body"><span class="eyebrow">PRIMA DELLA PARTITA</span><h2>'+esc(pre.title)+'</h2>'+pre.paragraphs.map(p).join('')+'</section><div class="background-grid">'+(pre.backgrounds||[]).map(market).join('')+'</div><p class="source-note">Mercato fotografato alla preparazione dell’edizione: '+esc(date(context.market_from))+'–'+esc(date(context.market_to))+'. '+esc(context.market_note)+' '+esc(context.standings_note)+'</p><section class="interview-section"><h2>Le dichiarazioni prepartita</h2>'+pre.interviews.map(interview).join('')+'</section>';
 let postHTML='<section class="opening"><span class="eyebrow">DOPO LA PARTITA</span><h2>La parola passa al campo.</h2><p>'+(reportError?'Il report è temporaneamente non raggiungibile. Riproviamo automaticamente.':'Analisi, interviste ai due manager e ai giocatori e premio MVP saranno disponibili quando verranno caricati il risultato e il Match Report di questo incontro.')+'</p><p>Controllo automatico ogni 60 secondi.</p></section>';
 if(post){postHTML='<section class="story-body"><span class="eyebrow">IL DOPOPARTITA</span><h2>'+esc(post.title)+'</h2>'+post.paragraphs.map(p).join('')+(post.note?'<p class="source-note">'+esc(post.note)+'</p>':'')+'</section>'+post.interviews.map(interview).join('');if(post.mvp){const m=post.mvp;postHTML+='<section class="mvp"><span class="eyebrow">'+(m.official?'MVP · MATCH REPORT':'MVP · SCELTA DELLA REDAZIONE')+'</span><h2>Il migliore in campo</h2><p>'+esc(m.player.player_name)+' · Voto '+esc(m.player.rating??'—')+' · '+Number(m.player.goals||0)+' gol · '+Number(m.player.assists||0)+' assist.</p>'+(!m.official?'<p class="source-note">Il report non indica un MVP. Scelta per voto più alto, poi gol e assist; in parità viene mostrato il primo giocatore nell’ordine del report.</p>':'')+interview(m.interview)+'</section>'}postHTML+='<section class="story-body"><h2>Cosa resta</h2><p>Prima giornata: '+(Number(f.home_score)>Number(f.away_score)?esc(f.home_name)+' parte con tre punti, '+esc(f.away_name)+' resta a zero.':Number(f.home_score)<Number(f.away_score)?esc(f.away_name)+' parte con tre punti, '+esc(f.home_name)+' resta a zero.':'un punto per '+esc(f.home_name)+' e '+esc(f.away_name)+'.')+' Il nuovo campionato comincia da qui.</p><a href="../competitions/view.html?world=GW001&season=2&competition='+encodeURIComponent(f.competition_key)+'">Apri la competizione →</a></section>'}
 $('content').innerHTML='<article class="fixture detail-header">'+matchHeader(f,d.name)+actions(f)+'</article><nav class="article-tabs" aria-label="Prima e dopo la partita"><button data-tab="pre" class="'+(tab==='pre'?'active':'')+'" aria-pressed="'+(tab==='pre')+'">Prepartita</button><button data-tab="post" class="'+(tab==='post'?'active':'')+'" aria-pressed="'+(tab==='post')+'">Dopopartita</button></nav><div id="pre-section"'+(tab!=='pre'?' hidden':'')+'>'+prevHTML+'</div><div id="post-section"'+(tab!=='post'?' hidden':'')+'>'+postHTML+'</div>';
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;q.set('tab',tab);history.replaceState(null,'','?'+q);$('pre-section').hidden=tab!=='pre';$('post-section').hidden=tab!=='post';document.querySelectorAll('[data-tab]').forEach(x=>{x.classList.toggle('active',x.dataset.tab===tab);x.setAttribute('aria-pressed',String(x.dataset.tab===tab))})});}
async function load(){if(busy||document.hidden)return;busy=true;const open=[...document.querySelectorAll('details')].map(d=>d.open),scroll=window.scrollY;try{const [a,b]=await Promise.all([get('../matchday/data.php?world=GW001&season=2&day=1'),context?Promise.resolve(context):get('context.json?v=1')]);day=a;context=b;$('edition').textContent='Stagione 2 · Giornata 1 · '+date(day.date);$('status').textContent=day.total+' prepartita · '+day.ready+' report completi · Aggiornamento automatico ogni 60 secondi';if(fixtureId)await detail();else index();document.querySelectorAll('details').forEach((d,i)=>d.open=open[i]||false);document.querySelectorAll('#content img').forEach(i=>i.onerror=()=>i.hidden=true);if(scroll)window.scrollTo(0,scroll)}catch(e){$('status').textContent='Edizione temporaneamente non disponibile. Nuovo tentativo automatico tra 60 secondi.'}finally{busy=false}}
load();setInterval(load,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});})();
