(()=>{'use strict';const $=id=>document.getElementById(id),q=new URLSearchParams(location.search),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),safe=v=>/^(https:\/\/|\/(?!\/))/.test(String(v||''))?v:'',date=v=>String(v||'').slice(0,10).split('-').reverse().join('/');let day,division=Number(q.get('division'))||1,busy=false;
const embedded=q.get('embedded')==='1';if(embedded){document.body.classList.add('embedded');document.querySelector('.club-path a').href='./?world=GW001&embedded=1'}
const fixtureId=q.get('fixture'),url=id=>'./?world=GW001&fixture='+id+(embedded?'&embedded=1':''),reportUrl=id=>'../competitions/match.html?world=GW001&fixture='+id;
async function get(path){const r=await fetch(path,{cache:'no-store'}),j=await r.json();if(!r.ok||j.ok===false)throw Error('Dati temporaneamente non disponibili');return j}
function logo(src){return safe(src)?'<img class="club-logo" src="'+esc(src)+'" alt="">':''}
function photo(id,name){return Number(id)>0?'<a class="portrait" href="../players/profile.html?world=GW001&player='+Number(id)+'"><img src="https://cdn.soccerwiki.org/images/player/'+Number(id)+'.png" alt="'+esc(name)+'" loading="lazy"></a>':''}
function p(text){return '<p>'+esc(text)+'</p>'}
function interview(x){return '<article class="interview"><div class="interview-head">'+photo(x.id,x.name)+'<div><span class="eyebrow">INTERVISTA SIMULATA</span><h3>'+esc(x.name)+'</h3><div class="person-team">'+logo(x.logo)+'<span>'+esc(x.role)+'</span></div></div></div>'+x.qas.map(a=>'<div class="qa"><span class="qa-label">LA DOMANDA</span><h4>'+esc(a.q)+'</h4><span class="qa-label answer-label">LA RISPOSTA</span><blockquote>«'+esc(a.a)+'»</blockquote></div>').join('')+'</article>'}
function score(f){return f.home_score!=null&&f.away_score!=null?esc(f.home_score)+' – '+esc(f.away_score):'VS'}
function matchHeader(f,div){return '<div class="match-context">'+esc(div)+' · '+esc(date(f.match_date))+'</div><div class="club-score"><div>'+logo(f.home_logo_url)+'<h2>'+esc(f.home_name)+'</h2><small>'+esc(f.home_imc_manager_name||'')+'</small></div><strong>'+score(f)+'</strong><div>'+logo(f.away_logo_url)+'<h2>'+esc(f.away_name)+'</h2><small>'+esc(f.away_imc_manager_name||'')+'</small></div></div>'}
function actions(f){if(embedded)return '';return '<div class="club-actions">'+(f.home_score!=null?'<a href="'+reportUrl(f.sm_fixture_id)+'">Open Match Report</a>':'<span>Match Report in attesa</span>')+'<a href="'+url(f.sm_fixture_id)+'">Open The Club →</a></div>'}
function postBody(f,post,reportError){
 let postHTML='<section class="story-body"><span class="eyebrow">DOPO LA PARTITA</span><h2>La parola passa al campo.</h2><p>'+(reportError?'Il report è temporaneamente non raggiungibile. Riproviamo automaticamente.':'Analisi, interviste ai due manager e ai giocatori e premio MVP saranno disponibili quando verranno caricati il risultato e il Match Report di questo incontro.')+'</p><p>Controllo automatico ogni 60 secondi.</p></section>';
 if(post){postHTML='<section class="story-body"><span class="eyebrow">IL DOPOPARTITA</span><h2>'+esc(post.title)+'</h2>'+post.paragraphs.map(p).join('')+(post.note?'<p class="source-note">'+esc(post.note)+'</p>':'')+'</section>'+post.interviews.map(interview).join('');if(post.mvp){const m=post.mvp;postHTML+='<section class="mvp"><span class="eyebrow">'+(m.official?'MVP · MATCH REPORT':'MVP · SCELTA DELLA REDAZIONE')+'</span><h2>Il migliore in campo</h2><p>'+esc(m.player.player_name)+' · Voto '+esc(m.player.rating??'—')+' · '+Number(m.player.goals||0)+' gol · '+Number(m.player.assists||0)+' assist.</p>'+(!m.official?'<p class="source-note">Il report non indica un MVP. Scelta per voto più alto, poi gol e assist; in parità viene mostrato il primo giocatore nell’ordine del report.</p>':'')+interview(m.interview)+'</section>'}postHTML+='<section class="story-body"><h2>Cosa resta</h2><p>Prima giornata: '+(Number(f.home_score)>Number(f.away_score)?esc(f.home_name)+' parte con tre punti, '+esc(f.away_name)+' resta a zero.':Number(f.home_score)<Number(f.away_score)?esc(f.away_name)+' parte con tre punti, '+esc(f.home_name)+' resta a zero.':'un punto per '+esc(f.home_name)+' e '+esc(f.away_name)+'.')+' Il nuovo campionato comincia da qui.</p><a href="../competitions/view.html?world=GW001&season=2&competition='+encodeURIComponent(f.competition_key)+'">Apri la competizione →</a></section>'}
return postHTML;}
async function fillPost(f,node){try{const report=await get('../competitions/match.php?world=GW001&fixture='+encodeURIComponent(f.sm_fixture_id));if(node.isConnected)node.innerHTML=postBody(f,ClubEditorial.post(report,f.preview||{}),false)}catch(e){if(node.isConnected)node.innerHTML=postBody(f,null,true)}}
function index(){const divisions=day.divisions;if(!divisions.some(x=>x.id===division))division=divisions[0].id;const d=divisions.find(x=>x.id===division);$('content').innerHTML='<nav class="division-tabs" aria-label="Divisioni">'+divisions.map(x=>'<button data-division="'+x.id+'" aria-pressed="'+(x.id===division)+'" class="'+(x.id===division?'active':'')+'">'+esc(x.name)+'</button>').join('')+'</nav><div class="fixture-list">'+d.fixtures.map((f,i)=>'<article class="fixture">'+matchHeader(f,d.name)+'<details class="match-interviews" data-interviews="'+f.sm_fixture_id+'"'+(i===0?' open':'')+'><summary>Leggi il dopopartita <span>Analisi · Interviste · MVP</span></summary><div data-post="'+f.sm_fixture_id+'">'+(f.live.ready?'<p class="fixture-story" role="status">Caricamento dopopartita…</p>':postBody(f,null,false))+'</div></details><div class="club-actions">'+(f.home_score!=null?'<a target="_top" href="'+reportUrl(f.sm_fixture_id)+'">Open Match Report</a>':'<span>Match Report in attesa</span>')+'</div></article>').join('')+'</div>';
 document.querySelectorAll('[data-division]').forEach(b=>b.onclick=()=>{division=Number(b.dataset.division);q.set('division',division);history.replaceState(null,'','?'+q);index()});
 return Promise.all(d.fixtures.filter(f=>f.live.ready).map(f=>fillPost(f,document.querySelector('[data-post="'+f.sm_fixture_id+'"]'))));}
async function detail(){const d=day.divisions.find(x=>x.fixtures.some(f=>String(f.sm_fixture_id)===fixtureId));if(!d){$('content').innerHTML='<p>Questa partita non fa parte dell’edizione.</p>';return}const f=d.fixtures.find(f=>String(f.sm_fixture_id)===fixtureId);$('content').innerHTML='<article class="fixture detail-header">'+matchHeader(f,d.name)+actions(f)+'</article><div id="post-section"><p>Caricamento dopopartita…</p></div>';await fillPost(f,$('post-section'));}
async function load(){if(busy||document.hidden)return;busy=true;const open=[...document.querySelectorAll('details')].map(d=>d.open),scroll=window.scrollY;try{day=await get('../matchday/data.php?world=GW001&season=2&day=1');$('edition').textContent='Stagione 2 · Giornata 1 · '+date(day.date);$('status').textContent=day.total+' partite · '+day.ready+' report completi · Aggiornamento automatico ogni 60 secondi';let rendered;if(fixtureId)rendered=detail();else rendered=index();document.querySelectorAll('details').forEach((d,i)=>{if(i<open.length)d.open=open[i]});document.querySelectorAll('#content img').forEach(i=>i.onerror=()=>i.hidden=true);if(scroll)window.scrollTo(0,scroll);await rendered}catch(e){$('status').textContent='Edizione temporaneamente non disponibile. Nuovo tentativo automatico tra 60 secondi.'}finally{busy=false}}
if(embedded){let pending=false;const resize=()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;parent.postMessage({type:'the-club-height',height:Math.ceil(document.querySelector('main').getBoundingClientRect().bottom+window.scrollY+16)},location.origin)})};new ResizeObserver(resize).observe(document.body);window.addEventListener('load',resize)}
load();setInterval(load,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});})();
