(()=>{'use strict';
const number=v=>v!==null&&v!==''&&v!==undefined&&Number.isFinite(Number(v))?Number(v):null;
const minute=v=>{const m=String(v??'').match(/^(\d+)(?:\+(\d+))?$/);return m?Number(m[1])+Number(m[2]||0):null};
const other=s=>s==='home'?'away':'home';
function form(rows){return {n:rows.length,w:rows.filter(r=>r.outcome==='V').length,d:rows.filter(r=>r.outcome==='N').length,l:rows.filter(r=>r.outcome==='P').length,gf:rows.reduce((a,r)=>a+Number(r.gf),0),ga:rows.reduce((a,r)=>a+Number(r.ga),0)}}
function pre(f,context={}){const p=f.preview,h=p.h2h,home=form(p.home_form),away=form(p.away_form),first=!p.home_table?.played&&!p.away_table?.played;
 const lead=first?`${f.home_name} e ${f.away_name} ripartono da zero punti. La prima giornata apre il campionato: i precedenti raccontano il passato, ma la classifica deve ancora prendere forma.`:`${f.home_name} arriva con ${p.home_table?.points??0} punti, ${f.away_name} con ${p.away_table?.points??0}. La sfida mette a confronto due percorsi e offre l’occasione di cambiare il passo del campionato.`;
 const history=h.played?`${h.played} precedenti disponibili: ${h.home_wins} vittorie per ${f.home_name}, ${h.away_wins} per ${f.away_name} e ${h.draws} pareggi. L’ultima sfida è terminata ${h.last.score}, ${h.last.home}–${h.last.away}.`:'Non ci sono scontri diretti precedenti disponibili nel database.';
 const paragraphs=[lead,history];for(const s of ['home','away']){const x=s==='home'?home:away;if(x.n)paragraphs.push(`${f[s+'_name']}: ${x.w} ${x.w===1?'vittoria':'vittorie'}, ${x.d} ${x.d===1?'pareggio':'pareggi'} e ${x.l} ${x.l===1?'sconfitta':'sconfitte'} nelle ultime ${x.n} partite disponibili prima della giornata, considerando tutte le competizioni e anche la stagione precedente. ${x.gf} gol fatti e ${x.ga} subiti.`)}
 const interviews=[];for(const s of ['home','away']){const x=s==='home'?home:away,name=f[s+'_imc_manager_name'];if(!name)continue;let question,answer;
 if(x.n&&x.l>=3){question=`${x.l} sconfitte nelle ultime ${x.n} partite: quanto conta ripartire contro ${f[other(s)+'_name']}?`;answer=`Quel bilancio non ci soddisfa. Questa partita ci offre una nuova occasione: vogliamo dare una risposta sul campo, senza portarci dietro il peso dei risultati precedenti.`}
 else if(x.n&&x.w>=3){question=`${x.w} vittorie nelle ultime ${x.n}: come si dà continuità contro ${f[other(s)+'_name']}?`;answer=`I risultati ci danno fiducia, ma non ci regalano nulla oggi. Contro ${f[other(s)+'_name']} dobbiamo guadagnarci ogni punto: voglio una squadra che riparta con la stessa voglia.`}
 else {question=first?`Si riparte da zero: che segnale vuole dalla sua squadra?`:`Cosa può lasciare questa sfida al vostro campionato?`;answer=first?`L’inizio conta, ma una stagione non si decide alla prima partita. Vogliamo partire con personalità e costruire qualcosa che duri, un incontro alla volta.`:`Vogliamo dare continuità al lavoro e portare a casa punti. ${f[other(s)+'_name']} è il problema di oggi: prima pensiamo a questa partita, poi guarderemo la classifica.`}
 interviews.push({name,role:'Manager · '+f[s+'_name'],logo:f[s+'_logo_url'],qas:[{q:question,a:answer}]});}
 const leaders=['home','away'].flatMap(s=>(p[s+'_players']||[]).filter(x=>x.played>0).map(x=>({...x,side:s}))).sort((a,b)=>b.goals-a.goals||b.assists-a.assists||(b.rating||0)-(a.rating||0));
 if(leaders.length){const x=leaders[0];interviews.push({name:x.name,id:x.id,role:'Giocatore · '+f[x.side+'_name'],logo:f[x.side+'_logo_url'],qas:[{q:x.goals?`${x.goals} gol in ${x.played} presenze nella stagione prima di questa giornata: che obiettivo si dà?`:'Qual è la priorità alla vigilia di questa partita?',a:`Voglio aiutare ${f[x.side+'_name']} a partire bene. Il contributo individuale conta se serve alla squadra: contro ${f[other(x.side)+'_name']} dobbiamo conquistare il risultato insieme.`}]})}
 const backgrounds=[];
 for(const side of ['home','away']){const c=context.clubs?.[f[side+'_sm_club_id']],name=f[side+'_name'];if(!c?.previous)continue;const last=c.previous,move=c.movement==='promoted'?`Promosso in ${c.division_name}`:c.movement==='relegated'?`Retrocesso in ${c.division_name}`:`Riparte in ${c.division_name}`;backgrounds.push({...c,side,name});paragraphs.unshift(`${name} ha chiuso la stagione 1 al ${last.position}° posto in ${last.division_name}, con ${last.points} punti in ${last.played} partite. ${move}. ${last.position===1?'Primo posto nel campionato precedente.':last.position===2?'Secondo posto, a '+last.gap_to_first+' punti dalla vetta.':''}`);
 const manager=interviews.find(x=>x.role==='Manager · '+name);if(manager){let question,answer;if(c.movement==='relegated'){question=`Il club scende dalla ${last.division_name} dopo il ${last.position}° posto: che risposta cerca?`;answer=`La retrocessione pesa, ma non può essere il nostro unico pensiero. Oggi comincia un altro campionato: dobbiamo trasformare la delusione in voglia di ripartire, a partire da ${f[other(side)+'_name']}.`}else if(c.movement==='promoted'){question=`Dal ${last.position}° posto in ${last.division_name} alla promozione in ${c.division_name}: come affronta il salto?`;answer=`La promozione è un risultato da portare con orgoglio, non una garanzia per oggi. Cambia il livello del confronto: vogliamo dimostrare di poterci stare, senza perdere ambizione.`}else if(last.position===1){question=`Il club riparte dal primo posto in ${last.division_name}: quanto pesa difendere quel risultato?`;answer=`Vincere cambia le aspettative, ma i punti tornano a zero. Vogliamo tenere quella fame e accettare che ogni avversario ci metterà alla prova, cominciando da ${f[other(side)+'_name']}.`}else if(last.position===2){question=`Secondo posto a ${last.gap_to_first} punti dalla vetta: è uno stimolo o un rimpianto?`;answer=`È una base importante e anche un promemoria di quanto ogni punto possa contare. L’ambizione è crescere: non vogliamo vivere di rimpianti, ma dare un seguito a quel percorso.`}else{question=`${last.position}° posto e ${last.points} punti nella stagione 1: da cosa vuole ripartire?`;answer=`Quel piazzamento ci dice dove eravamo, non dove dobbiamo fermarci. Vogliamo migliorare il nostro percorso e oggi abbiamo la prima occasione per dare un segnale.`}
 const incoming=c.in.slice(0,3).map(x=>x.name).join(', '),outgoing=c.out.slice(0,2).map(x=>x.name).join(', ');const marketQ=`Il mercato registra ${c.in.length} arrivi${incoming?' — '+incoming+' tra gli ultimi':''} e ${c.out.length} uscite${outgoing?' — tra cui '+outgoing:''}. Qual è la priorità?`;const marketA=c.in.length?`${c.in[0].name}${c.in.length>1?' e gli altri nuovi arrivi portano':' porta'} possibilità da costruire sul campo. Il mercato cambia la rosa, ma non assegna punti: la priorità è trovare intesa e trasformare queste possibilità in un contributo per la squadra.`:c.out.length?'Le uscite cambiano gli equilibri della rosa. Dobbiamo valorizzare chi c’è e trovare risposte sul campo: oggi conta il gruppo a disposizione.':'La continuità è il nostro punto di partenza in questo periodo. Vogliamo far crescere il contributo del gruppo, senza aspettare che la soluzione arrivi necessariamente dal mercato.';
 manager.qas=[{q:question,a:answer},{q:marketQ,a:marketA}];}
 }
 const newcomer=backgrounds.map(c=>({p:c.new_player,c})).find(x=>x.p);if(newcomer&&!interviews.some(x=>Number(x.id)===Number(newcomer.p.id))){const {p,c}=newcomer;interviews.push({name:p.name,id:p.id,role:'Nuovo arrivo · '+c.name,logo:f[c.side+'_logo_url'],qas:[{q:`Il tuo passaggio da ${p.from} è registrato il ${p.date.split('-').reverse().join('/')}. Con quale obiettivo affronti questa nuova esperienza?`,a:`Voglio conquistarmi spazio e dare una mano a ${c.name}. Arrivare è soltanto il primo passo: adesso conta entrare negli equilibri del gruppo e farmi trovare pronto quando ci sarà bisogno.`}]})}
 return {title:first?'Una nuova stagione, quaranta storie da riscrivere.':'Due percorsi, una partita da giocare.',paragraphs,interviews,backgrounds};}
function matchInterviews(d,events,mvp,official,history){
 const f=d.match,players=(d.players||[]).filter(p=>['home','away'].includes(p.team_side)),stats=d.team_stats||{};
 const hash=t=>[...String(t)].reduce((h,c)=>(h*31+c.charCodeAt(0))>>>0,7);
 const pick=(key,options)=>options[hash(f.sm_fixture_id+':'+key)%options.length];
 const name=s=>f[s+'_name'],score=s=>Number(f[s+'_score']),result=f.home_score+'–'+f.away_score;
 const pen=number(f.penalty_home_score)!==null&&number(f.penalty_away_score)!==null;
 const agg=number(f.aggregate_home_score)!==null&&number(f.aggregate_away_score)!==null;
 const winner=pen?(Number(f.penalty_home_score)>Number(f.penalty_away_score)?'home':Number(f.penalty_home_score)<Number(f.penalty_away_score)?'away':null):score('home')>score('away')?'home':score('away')>score('home')?'away':null;
 const states={home:0,away:0};const timeline=events.map(e=>{const before={...states};states[e.team_side]++;return {...e,before,after:{...states}}});
 const mentions=p=>timeline.filter(e=>!Number(e.own_goal)&&Number(e.sm_player_id)===Number(p.sm_player_id));
 const played=p=>number(p.minutes)>0||Number(p.starter)>0||number(p.sub_on_minute)!==null;
 const output=[];
 for(const s of ['home','away']){
  const o=other(s),manager=f[s+'_imc_manager_name']||f[s+'_manager_name'];if(!manager)continue;
  const own=timeline.filter(e=>e.team_side===s),conceded=timeline.filter(e=>e.team_side===o),last=timeline.at(-1);
  const won=winner===s,lost=winner===o,trailed=timeline.some(e=>e.after[s]<e.after[o]);let q,a;
  if(pen){q=`${result}, poi ${f.penalty_home_score}–${f.penalty_away_score} ai rigori: cosa le resta di questa sfida con ${name(o)}?`;a=won?`Stasera ${name(o)} ci ha portati fino ai rigori. Passare da quel ${result} all'esultanza finale è una liberazione, ma il punteggio della partita ci dice anche quanto il confronto sia rimasto aperto.`:`Il ${result} ci aveva lasciati ancora dentro la partita. Uscirne ai rigori contro ${name(o)} fa male: siamo arrivati a giocarci tutto dal dischetto, senza riuscire a chiudere dalla nostra parte.`;}
  else if(won&&trailed){const equal=own.find(e=>e.after[s]===e.after[o]),goahead=own.filter(e=>e.before[s]===e.before[o]).at(-1);q=`Siete passati dallo svantaggio al ${score(s)}–${score(o)}: dove ha girato la partita?`;a=`Il gol di ${equal?.player_name||own[0].player_name} al ${equal?.minute||own[0].minute}′ ci ha rimessi in corsa. ${goahead?`Poi ${goahead.player_name}, al ${goahead.minute}′, ci ha portati avanti.`:''} Mi tengo la risposta a ${name(o)}, ma anche il richiamo: abbiamo dovuto rincorrere prima di poter festeggiare.`;}
  else if(score(s)===score(o)&&last&&minute(last.minute)>=80){const saved=last.team_side===s;q=saved?`${last.player_name} al ${last.minute}′: quanto cambia il giudizio questo ${result}?`:`Il ${result} arriva con ${last.player_name} al ${last.minute}′: due punti sfuggiti nel finale?`;a=saved?`Senza quella rete avremmo un'altra sensazione addosso. ${last.player_name} ci ha riportati in parità quando il tempo contro ${name(o)} era poco: il punto va accolto, insieme alle difficoltà che ci hanno costretti a inseguire.`:`Sì, il gol di ${last.player_name} al ${last.minute}′ pesa. Avevamo il vantaggio, poi ${name(o)} ci ha raggiunti: adesso prevale il rammarico per non essere riusciti a tenere quel risultato.`;}
  else if(lost&&timeline.some(e=>e.after[s]>e.after[o])){const turn=conceded.filter(e=>e.after[o]>e.after[s]&&e.before[o]===e.before[s]).at(-1);q=`Eravate avanti, poi il ${score(s)}–${score(o)} finale: che cosa lascia questa rimonta subita?`;a=`Avevamo costruito un vantaggio contro ${name(o)} e non siamo riusciti a difenderlo. ${turn?`La rete di ${turn.player_name} al ${turn.minute}′ ci ha messi nella posizione di dover rincorrere.`:''} Il rimpianto nasce da lì: questa partita ci era passata tra le mani.`;}
  else {const opener=timeline[0];q=pick(s+'resultQ',[`${name(s)}–${name(o)}, ${score(s)}–${score(o)}: qual è la prima lettura a caldo?`,`${manager}, partiamo dal ${score(s)}–${score(o)} contro ${name(o)}: soddisfazione o qualcosa da rivedere?`,`Che fotografia dà questo ${score(s)}–${score(o)} della partita con ${name(o)}?`]);a=won?pick(s+'win',[`Contro ${name(o)} ci prendiamo un ${score(s)}–${score(o)} che conta. ${opener?`La prima rete, al ${opener.minute}′, ha mosso una partita ancora sullo zero a zero.`:''} La soddisfazione c'è; rivedremo anche ciò che ci ha permesso di arrivare a questo finale.`,`Il ${score(s)}–${score(o)} premia ${name(s)}, e stasera ce lo godiamo. ${own.at(-1)?`L'ultima nostra rete è di ${own.at(-1).player_name} al ${own.at(-1).minute}′: anche quel momento fa parte della lettura della gara.`:''} Il risultato è il punto di partenza della nostra analisi, non la cancella.`]):lost?pick(s+'loss',[`Il ${score(s)}–${score(o)} contro ${name(o)} lascia delusione. ${conceded[0]?`La rete subita al ${conceded[0].minute}′ è un episodio da cui ripartire nel rileggere la gara.`:''} Non voglio mettere tutto nello stesso sacco: dobbiamo distinguere quello che ha funzionato da quello che ci è mancato.`,`Stasera ${name(o)} ha chiuso davanti e a noi resta quel ${score(s)}–${score(o)}. ${score(s)===0?'Non aver segnato rende ancora più chiaro il lavoro da fare davanti.':`I nostri ${score(s)} gol non sono bastati: il problema va guardato anche dall'altra parte del campo.`} È una sconfitta da affrontare con lucidità.`]):score(s)===0?`Lo zero a zero con ${name(o)} ci lascia una porta inviolata e nessun gol fatto. Sono due facce della stessa serata: una base da tenere e qualcosa da migliorare per ottenere di più.`:`Il ${result} con ${name(o)} racconta una partita in cui entrambe abbiamo trovato la rete, senza chiudere davanti. ${own.at(-1)?`Per noi l'ultimo gol è arrivato con ${own.at(-1).player_name} al ${own.at(-1).minute}′.`:''} Il punto resta, insieme agli episodi sui quali potevamo fare meglio.`;}
  const qas=[{q,a}],ss=stats[s]||{},os=stats[o]||{};
  if(number(ss.shots_on_target)!==null&&number(os.shots_on_target)!==null){const st=Number(ss.shots_on_target),ot=Number(os.shots_on_target);q=pick(s+'shotsQ',[`${st} tiri nello specchio contro ${ot}${number(ss.total_shots)!==null?', su '+ss.total_shots+' tentativi complessivi':''}: il problema è stato arrivare al tiro o sfruttarlo?`,`${name(o)} ha chiuso con ${ot} tiri in porta, voi con ${st}: quanto spiega questo dato il ${result}?`,`Guardiamo le porte: ${st} conclusioni nello specchio per voi, ${ot} per ${name(o)}. Che indicazione ne ricava?`]);a=st===0?`Non abbiamo centrato la porta di ${name(o)}. È il dato che mi pesa: prima ancora di discutere il risultato, dobbiamo riuscire a dare un esito alle azioni che costruiamo.`:st>ot?(won?`I ${st} tiri nello specchio contro i loro ${ot} accompagnano il nostro ${score(s)}–${score(o)}. Mi piace aver dato un seguito alle azioni: la vittoria nasce anche dal fatto che siamo riusciti a far lavorare la loro porta.`:`Abbiamo centrato la porta ${st} volte, ${name(o)} ${ot}, ma il risultato è ${score(s)}–${score(o)}. È lì che sta il rammarico: avere più conclusioni nello specchio non ci ha consentito di chiudere davanti.`):st<ot?(won?`Con ${st} conclusioni nello specchio siamo arrivati a ${score(s)} gol, mentre ${name(o)} ne ha messe ${ot} nello specchio. Ci teniamo la concretezza, sapendo che concedere quel volume va comunque analizzato.`:`I ${ot} tiri in porta di ${name(o)}, contro i nostri ${st}, aiutano a leggere le difficoltà della serata. Dobbiamo lavorare sia su ciò che concediamo sia su quanto riusciamo a produrre.`):`Nello specchio siamo pari, ${st} a ${ot}, mentre il tabellino dice ${result}. È un confronto utile: contare i tiri non basta, bisogna riguardare come si è arrivati a quelle conclusioni.`;qas.push({q,a});}
  else if(number(ss.possession)!==null){qas.push({q:`${ss.possession}% di possesso contro ${name(o)}: siete riusciti a trasformarlo in pericolosità?`,a:`Quel ${ss.possession}% descrive quanto abbiamo avuto il pallone; il ${score(s)}–${score(o)} dice come è finita. La parte da riguardare è il passaggio tra le due cose, cioè cosa siamo riusciti a costruire quando la palla era nostra.`});}
  const red=players.find(p=>p.team_side===s&&Number(p.red_card)>0)||players.find(p=>p.team_side===o&&Number(p.red_card)>0);
  const impact=players.filter(p=>p.team_side===s&&number(p.sub_on_minute)!==null&&(Number(p.goals)>0||Number(p.assists)>0)).sort((a,b)=>Number(b.goals)-Number(a.goals))[0];
  const lead=players.filter(p=>p.team_side===s&&played(p)).sort((a,b)=>(Number(b.goals)*3+Number(b.assists))-(Number(a.goals)*3+Number(a.assists))||Number(b.rating||0)-Number(a.rating||0))[0];
  if(red){const ours=red.team_side===s,when=number(red.red_card_minute)!==null?` al ${red.red_card_minute}′`:'';qas.push({q:`L'espulsione di ${red.player_name}${when}: quanto entra nell'analisi del ${result}?`,a:ours?`Il rosso a ${red.player_name}${when} è un passaggio che dobbiamo rivedere. Ci ha tolto un uomo contro ${name(o)}; non voglio però usarlo per evitare di parlare anche del resto della partita.`:`Il rosso a ${red.player_name}${when} ha lasciato ${name(o)} in inferiorità. È un elemento della gara, ma il ${score(s)}–${score(o)} va letto anche attraverso quello che siamo riusciti a fare noi.`});}
  else if(impact){qas.push({q:`${impact.player_name}, dentro al ${impact.sub_on_minute}′: ${Number(impact.goals)||0} gol e ${Number(impact.assists)||0} assist. È la risposta che cercava dalla panchina?`,a:`${impact.player_name} ha lasciato un contributo concreto: ${Number(impact.goals)||0} gol e ${Number(impact.assists)||0} assist dopo l'ingresso al ${impact.sub_on_minute}′. ${won?'È una parte della vittoria che voglio sottolineare.':lost?'Non ci è bastato per cambiare l’esito, ma il suo apporto rimane.':'Dentro questo pareggio c’è anche il suo ingresso.'}`});}
  else if(lead){qas.push({q:pick(s+'leadQ',[`${lead.player_name}: ${Number(lead.goals)||0} gol, ${Number(lead.assists)||0} assist${number(lead.rating)!==null?', voto '+lead.rating:''}. Che peso ha avuto nella vostra gara?`,`Un nome su cui fermarsi è ${lead.player_name}${number(lead.rating)!==null?', valutato '+lead.rating:''}: come legge la sua prova contro ${name(o)}?`]),a:Number(lead.goals)>0?`${lead.player_name} ha firmato ${Number(lead.goals)===1?'una rete':lead.goals+' reti'} nel nostro ${score(s)}–${score(o)}. ${won?'Quel contributo pesa sul risultato, ed è giusto riconoscerlo.':lost?'La sconfitta non cancella quello che ha fatto, anche se avrebbe voluto un finale diverso.':'Il suo contributo ci ha aiutati a restare dentro la partita.'}`:Number(lead.assists)>0?`I ${lead.assists} assist di ${lead.player_name} sono un contributo preciso alle nostre reti contro ${name(o)}. È giusto mettere in evidenza anche chi prepara il gol, oltre a chi lo segna.`:`La prova di ${lead.player_name}${number(lead.rating)!==null?', da '+lead.rating+' in pagella':''} è un elemento da conservare dentro questo ${score(s)}–${score(o)}. Il giudizio sul singolo e quello sulla squadra vanno tenuti insieme.`});}
  if(qas.length<2)qas.push({q:`Da quale dato riparte dopo il ${score(s)}–${score(o)} con ${name(o)}?`,a:`Dai ${score(s)} gol fatti e dai ${score(o)} subiti: dobbiamo riguardare entrambe le fasi, senza lasciare che una sola impressione sostituisca l'intera partita.`});
  const mh=history.manager_h2h,ch=history.h2h,opponentManager=f[o+'_imc_manager_name']||f[o+'_manager_name'];
  let historical=null;
  if(mh?.available&&mh.played===0&&opponentManager){historical={q:`Primo confronto ${mh.incomplete?'registrato nell’archivio':'tra voi'} con ${opponentManager}: che ricordo lascia questo ${score(s)}–${score(o)}?`,a:won?`Il primo incrocio${mh.incomplete?' documentato':''} con ${opponentManager} si chiude con un ${score(s)}–${score(o)} a nostro favore. È un bel modo di iniziare questo confronto, ma una partita è un punto di partenza: la prossima avrà una storia propria.`:lost?`Avrei voluto iniziare questo confronto${mh.incomplete?' documentato':''} con ${opponentManager} con un altro esito. Il ${score(s)}–${score(o)} resta il primo riferimento: quando ci ritroveremo, ripartiremo anche da ciò che questa partita ci ha mostrato.`:`Il primo confronto${mh.incomplete?' documentato':''} con ${opponentManager} resta in equilibrio, ${score(s)}–${score(o)}. Nessuno dei due chiude davanti: è un primo capitolo che lascia già qualcosa da riprendere alla prossima sfida.`};}
  else if(mh?.available&&mh.played>0&&opponentManager){const w=mh[s+'_wins'],l=mh[o+'_wins'];historical={q:`Prima di oggi, nei ${mh.played} confronti documentati con ${opponentManager}, aveva ${w} ${w===1?'vittoria':'vittorie'} e ${l} ${l===1?'sconfitta':'sconfitte'}. Questo ${score(s)}–${score(o)} che cosa aggiunge?`,a:won&&w===0?`Nei precedenti disponibili non avevo ancora vinto contro ${opponentManager}. Questo ${score(s)}–${score(o)} cambia quel bilancio: mi fa piacere, soprattutto per quello che abbiamo ottenuto oggi come squadra.`:lost&&l===0?`Contro ${opponentManager} non risultavano sconfitte nei nostri ${mh.played} precedenti. Oggi arriva il ${score(s)}–${score(o)}: è un richiamo a non pensare che i confronti passati risolvano quello presente.`:`Avevamo ${w} ${w===1?'vittoria':'vittorie'}, ${mh.draws} ${mh.draws===1?'pareggio':'pareggi'} e ${l} ${l===1?'sconfitta':'sconfitte'} nei confronti documentati con ${opponentManager}. Oggi ci aggiungiamo questo ${score(s)}–${score(o)}: lo storico dà contesto, ma il giudizio deve partire dalla partita di stasera.`};}
  else if(ch?.played){historical={q:`Tra i club c’erano ${ch.played} precedenti: ${ch[s+'_wins']} ${ch[s+'_wins']===1?'vittoria':'vittorie'} per ${name(s)}, ${ch[o+'_wins']} per ${name(o)} e ${ch.draws} ${ch.draws===1?'pareggio':'pareggi'}. Il ${score(s)}–${score(o)} dà continuità o cambia qualcosa?`,a:`Il confronto con ${name(o)} aveva già quei ${ch.played} capitoli. ${won&&ch[s+'_wins']===0?'Oggi arriva la prima vittoria nei precedenti disponibili, e questo aggiunge soddisfazione.':`Ora c’è anche il ${score(s)}–${score(o)} di questa sera.`} Per noi il valore dello storico è capire il percorso, senza togliere peso a ciò che è successo oggi.`};}
  if(historical&&(!mh?.played||(!red&&!impact&&hash(f.sm_fixture_id+':'+s+'history')%3===0))){if(qas.length>=3)qas[mh?.played===0&&(red||impact)?1:2]=historical;else qas.push(historical);}
  output.push({name:manager,role:'Manager · '+name(s),logo:f[s+'_logo_url'],qas:qas.slice(0,3)});
 }
 function playerInterview(p,isMvp){const s=p.team_side,o=other(s),g=Number(p.goals)||0,ass=Number(p.assists)||0,own=mentions(p),sub=number(p.sub_on_minute)!==null;let q,a;
  if(own.length){const e=own.find(e=>e.after[s]>e.after[o]&&e.before[s]===e.before[o])||own.find(e=>e.after[s]===e.after[o])||own[0];const equal=e.after[s]===e.after[o],ahead=e.before[s]===e.before[o];const moment=equal?'il pareggio':ahead?'il vantaggio':`il ${e.after.home}–${e.after.away}`;q=pick(p.sm_player_id+'goalQ',[`Al ${e.minute}′ firmi ${moment}${g>1?', in una serata da '+g+' gol':''}: che peso dai a quella rete?`,`${p.player_name}, torniamo al ${e.minute}′: il tuo gol vale ${moment}. Come lo rileggi dopo il ${result}?`]);a=pick(p.sm_player_id+'goalA',[`Quando arriva ${moment}, la sensazione cambia. La mia rete al ${e.minute}′ entra in un ${result} contro ${name(o)}${winner===s?' che possiamo festeggiare':winner===o?' che purtroppo non ci premia':' che ci lascia un punto'}: è dentro quel risultato che la giudico.`,`Il gol al ${e.minute}′ ci ha dato ${moment}. ${winner===s?`Per questo me lo godo insieme alla vittoria contro ${name(o)}.`:winner===o?`Avrei voluto che portasse a un esito diverso contro ${name(o)}: resta la delusione per il ${result}.`:`È il mio contributo a questo ${result}, anche se avrei voluto chiudere davanti.`}`]);}
  else if(g){q=`${g} ${g===1?'gol':'gol'} contro ${name(o)}: come valuti la tua serata nel ${result}?`;a=`Segnare ${g===1?'una volta':g+' volte'} contro ${name(o)} conta, ma guardo il ${result}. ${winner===s?'Oggi le mie reti stanno dentro una vittoria e posso esserne contento.':'Il contributo personale resta, insieme alla voglia di ottenere di più come squadra.'}`;}
  else if(ass){q=`${ass} ${ass===1?'assist':'assist'} contro ${name(o)}: soddisfatto di come hai aiutato chi era davanti alla porta?`;a=`Ho contribuito con ${ass} ${ass===1?'assist':'assist'} alle nostre reti. ${winner===s?`Nel ${result} contro ${name(o)} c'è anche questo, ed è una bella soddisfazione.`:`Poi guardo il ${result} contro ${name(o)}: il contributo c'è, ma avrei voluto un finale migliore.`}`;}
  else if(Number(p.red_card)>0){q=`Il rosso${number(p.red_card_minute)!==null?' al '+p.red_card_minute+'′':''} pesa sulla tua serata contro ${name(o)}: come la commenti?`;a=`Lasciare i compagni con un uomo in meno contro ${name(o)} mi dispiace. Il ${result} è il risultato di tutta la partita, ma l'espulsione resta una parte della mia prova che devo riguardare.`;}
  else {q=`${number(p.rating)!==null?'Voto '+p.rating+', ':''}${p.minutes??'—'} minuti contro ${name(o)}: quale sensazione ti lascia il ${result}?`;a=`Ho giocato ${p.minutes??'i miei'} minuti in questo ${result} contro ${name(o)}. ${winner===s?'La vittoria dà valore anche al lavoro che non finisce nel tabellino dei marcatori.':winner===o?'La sconfitta pesa più del giudizio individuale: vorrei che la mia prova aiutasse la squadra a ottenere altro.':'Il pareggio ci lascia qualcosa, insieme alla sensazione che ci fosse ancora da cercare.'}`;}
  const qas=[{q,a}];
  if(sub)qas.push({q:`Sei entrato al ${p.sub_on_minute}′${number(p.minutes)!==null?', giocando '+p.minutes+' minuti':''}: cosa porti via da questo spezzone?`,a:`Entrare al ${p.sub_on_minute}′ contro ${name(o)} significava avere quel tempo a disposizione. ${g||ass?`Sono riuscito a lasciare ${g} gol e ${ass} assist: questo è il contributo concreto del mio ingresso.`:`Il mio spezzone è finito dentro il ${result}; lo rileggo pensando a quanto sono riuscito a dare in quei minuti.`}`});
  else if(g&&ass)qas.push({q:`Oltre ${g===1?'al gol':'ai '+g+' gol'}, ${ass} assist: quanto conta riuscire a incidere in entrambi i modi?`,a:`Contro ${name(o)} sono arrivati sia ${g===1?'il gol':'i '+g+' gol'} sia ${ass===1?'l’assist':ass+' assist'}. Mi piace poter dare un contributo anche alla rete di un compagno: nel ${result} ci sono entrambe le cose.`});
  else {const ss=stats[s]||{},focus=g?`${g} ${g===1?'gol':'gol'}`:ass?`${ass} assist`:number(p.rating)!==null?`un voto di ${p.rating}`:`${p.minutes??90} minuti`;
   const choices=[{q:`La tua prova porta ${focus}, il risultato è ${score(s)}–${score(o)}: combaciano il giudizio personale e quello sulla squadra?`,a:`Ho chiuso con ${focus} contro ${name(o)}. ${winner===s?'Oggi riesco a guardare il mio contributo insieme alla vittoria.':winner===o?'Il mio contributo non cambia la sconfitta: il risultato che cercavamo era un altro.':'Il contributo personale mi lascia qualcosa di positivo, ma il pareggio rimane il giudizio del campo.'}`},{q:`${p.player_name}, dopo ${number(p.minutes)!==null?p.minutes+' minuti':'questa partita'} e ${focus}, che cosa ti lascia il confronto con ${name(o)}?`,a:`Contro ${name(o)} ho chiuso con ${focus}${number(p.minutes)!==null?' in '+p.minutes+' minuti':''}. Il ${score(s)}–${score(o)} ${winner===s?'ci permette di portare a casa anche la soddisfazione collettiva.':winner===o?'lascia il rammarico di non aver trasformato questo contributo in un risultato utile.':'ci lascia un punto: la mia prova fa parte di questo equilibrio.'}`}];
   if(number(ss.shots_on_target)!==null)choices.push({q:`${name(s)} ha centrato la porta ${ss.shots_on_target} volte. Come collochi il tuo contributo (${focus}) nella partita della squadra?`,a:`I ${ss.shots_on_target} tiri nello specchio di ${name(s)} e il mio contributo (${focus}) sono due pezzi della stessa serata. ${winner===s?`Contro ${name(o)} siamo riusciti a farli pesare nel ${score(s)}–${score(o)}.`:`Contro ${name(o)} il risultato è ${score(s)}–${score(o)}: voglio che il contributo personale ci aiuti a ottenere di più.`}`});
   if(number(ss.possession)!==null)choices.push({q:`${ss.possession}% di possesso per ${name(s)}: sei soddisfatto del contributo che hai dato quando avevate palla?`,a:`In una partita con il ${ss.possession}% di possesso abbiamo chiuso ${score(s)}–${score(o)} contro ${name(o)}. Il mio contributo (${focus}) è il punto da cui posso riguardare la mia prestazione: mi interessa quanto riesco a dare alla squadra, non soltanto quanto teniamo il pallone.`});
   qas.push(pick(p.sm_player_id+'teamLens',choices));}

  if(isMvp)qas.push({q:official?`Migliore in campo${number(p.rating)!==null?', voto '+p.rating:''}: cosa pesa di più tra il premio e questo ${result}?`:`La nostra scelta MVP cade su di te${number(p.rating)!==null?', voto '+p.rating:''}: ti riconosci in questo giudizio?`,a:pick(p.sm_player_id+'mvp',[`Il riconoscimento mi fa piacere${number(p.rating)!==null?', quel '+p.rating+' è un bel giudizio sulla mia partita':''}. ${winner===s?`Poterlo accompagnare alla vittoria contro ${name(o)} gli dà un altro sapore.`:`Resta il ${result} con ${name(o)}: il premio personale non cambia ciò che chiediamo al risultato di squadra.`}`,`Mi tengo il premio e la prova contro ${name(o)}${number(p.rating)!==null?', valutata '+p.rating:''}. ${g||ass?`I miei ${g} gol e ${ass} assist sono il contributo che sono riuscito a dare.`:'È un riconoscimento al contributo che ho dato in questa partita.'} ${winner===s?'La cosa più bella è celebrarlo dopo una vittoria.':'Avrei voluto festeggiarlo con una vittoria.'}`])});
  return {name:p.player_name,id:p.sm_player_id,role:(isMvp?'MVP · ':'Giocatore · ')+name(s),logo:f[s+'_logo_url'],qas};
 }
 const candidates=[];for(const s of ['home','away']){const p=players.filter(p=>p.team_side===s&&played(p)&&(!mvp||Number(p.sm_player_id)!==Number(mvp.sm_player_id))).sort((a,b)=>(Number(b.goals)*5+Number(b.assists)*3+Number(b.red_card))-(Number(a.goals)*5+Number(a.assists)*3+Number(a.red_card))||Number(b.rating||0)-Number(a.rating||0)||Number(b.minutes||0)-Number(a.minutes||0))[0];if(p)candidates.push(p)}
 output.push(...candidates.map(p=>playerInterview(p,false)));return {interviews:output,mvp:mvp?{player:mvp,official,interview:playerInterview(mvp,true)}:null};
}

function post(d,history={}){const f=d.match,players=d.players||[],stats=d.team_stats||{},h=number(f.home_score),a=number(f.away_score);if(h===null||a===null)return null;
 const penalties=number(f.penalty_home_score)!==null&&number(f.penalty_away_score)!==null,aggregate=number(f.aggregate_home_score)!==null&&number(f.aggregate_away_score)!==null;
 const win=h>a?'home':h<a?'away':null;let result=`${f.home_name}–${f.away_name} ${h}–${a}`;if(penalties)result+=`, rigori ${f.penalty_home_score}–${f.penalty_away_score}`;if(aggregate)result+=`, aggregato ${f.aggregate_home_score}–${f.aggregate_away_score}`;
 const goals=(stats.scorers||[]).filter(x=>['home','away'].includes(x.team_side)&&minute(x.minute)!==null).slice().sort((x,y)=>minute(x.minute)-minute(y.minute));const goalCounts={home:0,away:0};for(const g of goals)goalCounts[g.team_side]++;const coherent=goalCounts.home===h&&goalCounts.away===a;const usable=coherent?goals:[];
 let comeback=false,sh=0,sa=0;for(const g of usable){if(win&&(win==='home'?sh<sa:sa<sh))comeback=true;g.team_side==='home'?sh++:sa++;}const last=usable.at(-1),late=last&&minute(last.minute)>=85;
 const title=penalties?'La partita non basta: decidono i rigori.':win?(comeback?`${f[win+'_name']}, una vittoria in rimonta.`:`${f[win+'_name']} si prende la partita.`):(late?'Il pareggio arriva nel finale.':h===0?'Nessun gol, un punto per parte.':'Equilibrio nel risultato, storie diverse sul campo.');
 const paragraphs=[`${result}. ${win?`${f[win+'_name']} chiude davanti nel punteggio${comeback?', dopo essere stata in svantaggio':''}.`:penalties?'L’equilibrio del risultato viene risolto dal dischetto.':'Le due squadre chiudono in parità.'}`];
 const mh=history.manager_h2h,ch=history.h2h;
 if(mh?.available){const hn=f.home_imc_manager_name||f.home_manager_name,an=f.away_imc_manager_name||f.away_manager_name;if(hn&&an){if(mh.played===0)paragraphs.push(`PRIMO CONFRONTO ${mh.incomplete?'REGISTRATO':'TRA I DUE MANAGER'} — ${hn} e ${an} aprono il loro confronto con il ${h}–${a}. Non risultano sfide precedenti tra loro nell’archivio disponibile del GW, considerando tutte le stagioni e le squadre allenate.${mh.incomplete?' Alcune partite storiche non hanno entrambi gli ID manager: si tratta del primo incrocio documentato, non di una prima assoluta certificata.':''}`);else paragraphs.push(`Il confronto tra manager, prima di questa giornata: ${mh.played} precedenti documentati tra ${hn} e ${an}, con ${mh.home_wins} ${mh.home_wins===1?'vittoria':'vittorie'} del primo, ${mh.away_wins} del secondo e ${mh.draws} ${mh.draws===1?'pareggio':'pareggi'}. Il ${h}–${a} di oggi aggiunge un nuovo capitolo, senza essere incluso in quei conteggi.`);}}
 if(ch?.played){paragraphs.push(`Prima di oggi i club si erano affrontati ${ch.played} volte: ${ch.home_wins} ${ch.home_wins===1?'vittoria':'vittorie'} per ${f.home_name}, ${ch.away_wins} per ${f.away_name}, ${ch.draws} ${ch.draws===1?'pareggio':'pareggi'}.${ch.last?` L’ultima sfida, il ${String(ch.last.date).slice(0,10).split('-').reverse().join('/')}, era finita ${ch.last.home} ${ch.last.score} ${ch.last.away}.`:''} ${win&&ch[win+'_wins']===0?`Il ${h}–${a} porta la prima vittoria di ${f[win+'_name']} nei confronti disponibili.`:''}`);}
 if(!d.report_available)return {title,paragraphs,interviews:[],mvp:null,note:'Match Report non ancora disponibile: analisi, interviste e MVP si completeranno dopo il caricamento.'};
 if(usable.length){const g=usable[0];paragraphs.push(`${g.player_name}${Number(g.own_goal)?' con un autogol':''} modifica per primo il risultato al ${g.minute}′, a favore di ${f[g.team_side+'_name']}. ${usable.slice(1).map(x=>`${x.player_name}${Number(x.own_goal)?' (autogol)':''} al ${x.minute}′`).join('; ')}${usable.length>2?' completano la sequenza delle reti.':usable.length===2?' completa la sequenza delle reti.':''}`)}else if(h+a>0)paragraphs.push('La sequenza degli eventi gol non è completa: l’analisi non attribuisce svolte o minuti non verificati.');
 const hs=stats.home||{},as=stats.away||{};if(number(hs.total_shots)!==null&&number(as.total_shots)!==null){let text=`Il confronto al tiro: ${hs.total_shots} tentativi per ${f.home_name}, ${as.total_shots} per ${f.away_name}.`;if(number(hs.shots_on_target)!==null&&number(as.shots_on_target)!==null)text+=` Nello specchio ${hs.shots_on_target}–${as.shots_on_target}.`;if(number(hs.possession)!==null&&number(as.possession)!==null)text+=` Possesso ${hs.possession}%–${as.possession}%.`;paragraphs.push(text);if(win){const ws=stats[win],ls=stats[other(win)];if(number(ws.total_shots)!==null&&number(ls.total_shots)!==null&&number(ws.total_shots)<number(ls.total_shots))paragraphs.push('Il risultato premia la squadra che ha tirato meno: il volume dei tentativi, da solo, non spiega l’esito. I numeri invitano a distinguere quantità e concretezza, senza dedurre la qualità delle occasioni dai soli tiri.')}}
 const contributors=players.filter(p=>number(p.sub_on_minute)!==null&&(Number(p.goals)>0||Number(p.assists)>0));for(const p of contributors)paragraphs.push(`${p.player_name}, entrato al ${p.sub_on_minute}′, contribuisce con ${Number(p.goals)||0} gol e ${Number(p.assists)||0} assist. Un apporto dalla panchina registrato nel report.`);
 for(const p of players.filter(x=>Number(x.red_card)>0))paragraphs.push(`${p.player_name} viene espulso${number(p.red_card_minute)!==null?' al '+p.red_card_minute+'′':''}. Il report registra il cartellino; non gli attribuiamo automaticamente la causa del risultato.`);
 const official=players.filter(p=>Number(p.man_of_match)>0),rated=players.filter(p=>number(p.rating)>0).sort((x,y)=>Number(y.rating)-Number(x.rating)||Number(y.goals)-Number(x.goals)||Number(y.assists)-Number(x.assists));const mvp=official[0]||rated[0]||null;
 const generated=matchInterviews(d,usable,mvp,official.length>0,history);return {title,paragraphs,...generated,note:!coherent&&h+a>0?'Eventi gol incompleti: il risultato ufficiale rimane il riferimento.':null};}
window.ClubEditorial={pre,post};
})();
