(()=>{'use strict';
const number=v=>v!==null&&v!==''&&v!==undefined&&Number.isFinite(Number(v))?Number(v):null;
const minute=v=>{const m=String(v??'').match(/^(\d+)(?:\+(\d+))?$/);return m?Number(m[1])+Number(m[2]||0):null};
const other=s=>s==='home'?'away':'home';
function form(rows){return {n:rows.length,w:rows.filter(r=>r.outcome==='V').length,d:rows.filter(r=>r.outcome==='N').length,l:rows.filter(r=>r.outcome==='P').length,gf:rows.reduce((a,r)=>a+Number(r.gf),0),ga:rows.reduce((a,r)=>a+Number(r.ga),0)}}
function pre(f,context={}){const p=f.preview,h=p.h2h,home=form(p.home_form),away=form(p.away_form),first=!p.home_table?.played&&!p.away_table?.played;
 const lead=first?`${f.home_name} e ${f.away_name} ripartono da zero punti. La prima giornata apre il campionato: i precedenti raccontano il passato, ma la classifica deve ancora prendere forma.`:`${f.home_name} arriva con ${p.home_table?.points??0} punti, ${f.away_name} con ${p.away_table?.points??0}. La sfida mette a confronto due percorsi e offre l’occasione di cambiare il passo del campionato.`;
 const history=h.played?`${h.played} precedenti disponibili: ${h.home_wins} vittorie per ${f.home_name}, ${h.away_wins} per ${f.away_name} e ${h.draws} pareggi. L’ultima sfida è terminata ${h.last.score}, ${h.last.home}–${h.last.away}.`:'Non ci sono scontri diretti precedenti disponibili nel database.';
 const paragraphs=[lead,history];for(const s of ['home','away']){const x=s==='home'?home:away;if(x.n)paragraphs.push(`${f[s+'_name']}: ${x.w} ${x.w===1?'vittoria':'vittorie'}, ${x.d} ${x.d===1?'pareggio':'pareggi'} e ${x.l} ${x.l===1?'sconfitta':'sconfitte'} nelle ultime ${x.n} partite disponibili prima della giornata, considerando tutte le competizioni e anche la stagione precedente. ${x.gf} gol fatti e ${x.ga} subiti.`)}
 const interviews=[];for(const s of ['home','away']){const x=s==='home'?home:away,name=f[s+'_imc_manager_name'];if(!name)continue;let question,answer;
 if(x.n&&x.l>=3){question=`${x.l} sconfitte nelle ultime ${x.n} partite: quanto conta ripartire contro ${f[other(s)+'_name']}?`;answer=`Quel bilancio non ci soddisfa. Questa partita ci offre una nuova occasione: vogliamo dare una risposta sul campo, senza portarci dietro il peso dei risultati precedenti.`}
 else if(x.n&&x.w>=3){question=`${x.w} vittorie nelle ultime ${x.n}: come si dà continuità contro ${f[other(s)+'_name']}?`;answer=`I risultati ci danno fiducia, ma non ci regalano nulla oggi. Contro ${f[other(s)+'_name']} dobbiamo guadagnarci ogni punto: voglio una squadra che riparta con la stessa voglia.`}
 else {question=first?`Si riparte da zero: che segnale vuole dalla sua squadra?`:`Cosa può lasciare questa sfida al vostro campionato?`;answer=first?`L’inizio conta, ma una stagione non si decide alla prima partita. Vogliamo partire con personalità e costruire qualcosa che duri, un incontro alla volta.`:`Vogliamo dare continuità al lavoro e portare a casa punti. ${f[other(s)+'_name']} è il problema di oggi: prima pensiamo a questa partita, poi guarderemo la classifica.`}
 interviews.push({name,role:'Manager · '+f[s+'_name'],logo:f[s+'_logo_url'],qas:[{q:question,a:answer}]});}
 const leaders=['home','away'].flatMap(s=>(p[s+'_players']||[]).filter(x=>x.played>0).map(x=>({...x,side:s}))).sort((a,b)=>b.goals-a.goals||b.assists-a.assists||(b.rating||0)-(a.rating||0));
 if(leaders.length){const x=leaders[0];interviews.push({name:x.name,id:x.id,role:'Giocatore · '+f[x.side+'_name'],logo:f[x.side+'_logo_url'],qas:[{q:x.goals?`${x.goals} gol in ${x.played} presenze nella stagione prima di questa giornata: che obiettivo si dà?`:'Qual è la priorità alla vigilia di questa partita?',a:`Voglio aiutare ${f[x.side+'_name']} a partire bene. Il contributo individuale conta se serve alla squadra: contro ${f[other(x.side)+'_name']} dobbiamo conquistare il risultato insieme.`}]})}
 const backgrounds=[];
 for(const side of ['home','away']){const c=context.clubs?.[f[side+'_sm_club_id']],name=f[side+'_name'];if(!c?.previous)continue;const last=c.previous,move=c.movement==='promoted'?`Promosso in ${c.division_name}`:c.movement==='relegated'?`Retrocesso in ${c.division_name}`:`Riparte in ${c.division_name}`;backgrounds.push({...c,side,name});paragraphs.unshift(`${name} ha chiuso la stagione 1 al ${last.position}° posto in ${last.division_name}, con ${last.points} punti in ${last.played} partite. ${move}. ${last.position===1?'Primo posto nel campionato precedente.':last.position===2?'Secondo posto, a '+last.gap_to_first+' punti dalla vetta.':''}`);
 const manager=interviews.find(x=>x.role==='Manager · '+name);if(manager){let question,answer;if(c.movement==='relegated'){question=`Il club scende dalla ${last.division_name} dopo il ${last.position}° posto: che risposta cerca?`;answer=`La retrocessione pesa, ma non può essere il nostro unico pensiero. Oggi comincia un altro campionato: dobbiamo trasformare la delusione in voglia di ripartire, a partire da ${f[other(side)+'_name']}.`}else if(c.movement==='promoted'){question=`Dal ${last.position}° posto in ${last.division_name} alla promozione in ${c.division_name}: come affronta il salto?`;answer=`La promozione è un risultato da portare con orgoglio, non una garanzia per oggi. Cambia il livello del confronto: vogliamo dimostrare di poterci stare, senza perdere ambizione.`}else if(last.position===1){question=`Il club riparte dal primo posto in ${last.division_name}: quanto pesa difendere quel risultato?`;answer=`Vincere cambia le aspettative, ma i punti tornano a zero. Vogliamo tenere quella fame e accettare che ogni avversario ci metterà alla prova, cominciando da ${f[other(side)+'_name']}.`}else if(last.position===2){question=`Secondo posto a ${last.gap_to_first} punti dalla vetta: è uno stimolo o un rimpianto?`;answer=`È una base importante e anche un promemoria di quanto ogni punto possa contare. L’ambizione è crescere: non vogliamo vivere di rimpianti, ma dare un seguito a quel percorso.`}else{question=`${last.position}° posto e ${last.points} punti nella stagione 1: da cosa vuole ripartire?`;answer=`Quel piazzamento ci dice dove eravamo, non dove dobbiamo fermarci. Vogliamo migliorare il nostro percorso e oggi abbiamo la prima occasione per dare un segnale.`}
 const incoming=c.in.slice(0,3).map(x=>x.name).join(', '),outgoing=c.out.slice(0,2).map(x=>x.name).join(', ');const marketQ=`Il mercato registra ${c.in.length} arrivi${incoming?' — '+incoming+' tra gli ultimi':''} e ${c.out.length} uscite${outgoing?' — tra cui '+outgoing:''}. Qual è la priorità?`;const marketA=c.in.length?`${c.in[0].name}${c.in.length>1?' e gli altri nuovi arrivi portano':' porta'} possibilità da costruire sul campo. Il mercato cambia la rosa, ma non assegna punti: la priorità è trovare intesa e trasformare queste possibilità in un contributo per la squadra.`:c.out.length?'Le uscite cambiano gli equilibri della rosa. Dobbiamo valorizzare chi c’è e trovare risposte sul campo: oggi conta il gruppo a disposizione.':'La continuità è il nostro punto di partenza in questo periodo. Vogliamo far crescere il contributo del gruppo, senza aspettare che la soluzione arrivi necessariamente dal mercato.';
 manager.qas=[{q:question,a:answer},{q:marketQ,a:marketA}];}
 }
 const newcomer=backgrounds.map(c=>({p:c.new_player,c})).find(x=>x.p);if(newcomer&&!interviews.some(x=>Number(x.id)===Number(newcomer.p.id))){const {p,c}=newcomer;interviews.push({name:p.name,id:p.id,role:'Nuovo arrivo · '+c.name,logo:f[c.side+'_logo_url'],qas:[{q:`Il tuo passaggio da ${p.from} è registrato il ${p.date.split('-').reverse().join('/')}. Con quale obiettivo affronti questa nuova esperienza?`,a:`Voglio conquistarmi spazio e dare una mano a ${c.name}. Arrivare è soltanto il primo passo: adesso conta entrare negli equilibri del gruppo e farmi trovare pronto quando ci sarà bisogno.`}]})}
 return {title:first?'Una nuova stagione, quaranta storie da riscrivere.':'Due percorsi, una partita da giocare.',paragraphs,interviews,backgrounds};}
function post(d){const f=d.match,players=d.players||[],stats=d.team_stats||{},h=number(f.home_score),a=number(f.away_score);if(h===null||a===null)return null;
 const penalties=number(f.penalty_home_score)!==null&&number(f.penalty_away_score)!==null,aggregate=number(f.aggregate_home_score)!==null&&number(f.aggregate_away_score)!==null;
 const win=h>a?'home':h<a?'away':null;let result=`${f.home_name}–${f.away_name} ${h}–${a}`;if(penalties)result+=`, rigori ${f.penalty_home_score}–${f.penalty_away_score}`;if(aggregate)result+=`, aggregato ${f.aggregate_home_score}–${f.aggregate_away_score}`;
 const goals=(stats.scorers||[]).filter(x=>['home','away'].includes(x.team_side)&&minute(x.minute)!==null).slice().sort((x,y)=>minute(x.minute)-minute(y.minute));const goalCounts={home:0,away:0};for(const g of goals)goalCounts[g.team_side]++;const coherent=goalCounts.home===h&&goalCounts.away===a;const usable=coherent?goals:[];
 let comeback=false,sh=0,sa=0;for(const g of usable){if(win&&(win==='home'?sh<sa:sa<sh))comeback=true;g.team_side==='home'?sh++:sa++;}const last=usable.at(-1),late=last&&minute(last.minute)>=85;
 const title=penalties?'La partita non basta: decidono i rigori.':win?(comeback?`${f[win+'_name']}, una vittoria in rimonta.`:`${f[win+'_name']} si prende la partita.`):(late?'Il pareggio arriva nel finale.':h===0?'Nessun gol, un punto per parte.':'Equilibrio nel risultato, storie diverse sul campo.');
 const paragraphs=[`${result}. ${win?`${f[win+'_name']} chiude davanti nel punteggio${comeback?', dopo essere stata in svantaggio':''}.`:penalties?'L’equilibrio del risultato viene risolto dal dischetto.':'Le due squadre chiudono in parità.'}`];
 if(!d.report_available)return {title,paragraphs,interviews:[],mvp:null,note:'Match Report non ancora disponibile: analisi, interviste e MVP si completeranno dopo il caricamento.'};
 if(usable.length){const g=usable[0];paragraphs.push(`${g.player_name}${g.own_goal?' con un autogol':''} modifica per primo il risultato al ${g.minute}′, a favore di ${f[g.team_side+'_name']}. ${usable.slice(1).map(x=>`${x.player_name}${x.own_goal?' (autogol)':''} al ${x.minute}′`).join('; ')}${usable.length>1?' completano la sequenza delle reti.':''}`)}else if(h+a>0)paragraphs.push('La sequenza degli eventi gol non è completa: l’analisi non attribuisce svolte o minuti non verificati.');
 const hs=stats.home||{},as=stats.away||{};if(number(hs.total_shots)!==null&&number(as.total_shots)!==null){let text=`Il confronto al tiro: ${hs.total_shots} tentativi per ${f.home_name}, ${as.total_shots} per ${f.away_name}.`;if(number(hs.shots_on_target)!==null&&number(as.shots_on_target)!==null)text+=` Nello specchio ${hs.shots_on_target}–${as.shots_on_target}.`;if(number(hs.possession)!==null&&number(as.possession)!==null)text+=` Possesso ${hs.possession}%–${as.possession}%.`;paragraphs.push(text);if(win){const ws=stats[win],ls=stats[other(win)];if(number(ws.total_shots)!==null&&number(ls.total_shots)!==null&&number(ws.total_shots)<number(ls.total_shots))paragraphs.push('Il risultato premia la squadra che ha tirato meno: il volume dei tentativi, da solo, non spiega l’esito. I numeri invitano a distinguere quantità e concretezza, senza dedurre la qualità delle occasioni dai soli tiri.')}}
 const contributors=players.filter(p=>number(p.sub_on_minute)!==null&&(Number(p.goals)>0||Number(p.assists)>0));for(const p of contributors)paragraphs.push(`${p.player_name}, entrato al ${p.sub_on_minute}′, contribuisce con ${Number(p.goals)||0} gol e ${Number(p.assists)||0} assist. Un apporto dalla panchina registrato nel report.`);
 for(const p of players.filter(x=>Number(x.red_card)>0))paragraphs.push(`${p.player_name} viene espulso${number(p.red_card_minute)!==null?' al '+p.red_card_minute+'′':''}. Il report registra il cartellino; non gli attribuiamo automaticamente la causa del risultato.`);
 const official=players.filter(p=>Number(p.man_of_match)>0),rated=players.filter(p=>number(p.rating)>0).sort((x,y)=>Number(y.rating)-Number(x.rating)||Number(y.goals)-Number(x.goals)||Number(y.assists)-Number(x.assists));const mvp=official[0]||rated[0]||null;
 const interviews=[];for(const s of ['home','away']){const name=f[s+'_imc_manager_name']||f[s+'_manager_name'];if(!name)continue;const won=win===s,lost=win&&win!==s;let q,answer;
 if(penalties){const pw=Number(f[s==='home'?'penalty_home_score':'penalty_away_score'])>Number(f[s==='home'?'penalty_away_score':'penalty_home_score']);q='Una partita arrivata ai rigori: con quale sensazione la lascia?';answer=pw?'Arrivare fino ai rigori e riuscire a spuntarla è una liberazione. È stato un confronto aperto fino all’ultimo.':'Perdere ai rigori lascia amarezza. Eravamo ancora in partita: adesso pesa soprattutto quanto siamo stati vicini a un esito diverso.'}
 else if(won&&comeback){q='Siete stati sotto e avete vinto: cosa resta della rimonta?';answer='La soddisfazione di aver cambiato un risultato che si era complicato. Essere andati sotto pesa meno adesso, ma dovremo rileggere anche quella parte della partita.'}
 else if(!win&&late){const equalized=last.team_side===s;q=equalized?'Un pareggio trovato nel finale: quanto vale?':'Un pareggio subito nel finale: prevale il rammarico?';answer=equalized?'Per come è arrivato, questo punto ha un peso speciale. Il gol nel finale cambia la sensazione con cui usciamo dalla partita.':'Sì, eravamo vicini a chiuderla davanti. Il finale lascia amarezza: un punto resta, ma in questo momento pensiamo a quello che ci è sfuggito.'}
 else {q=won?'Qual è il valore di questa vittoria?':lost?'Da dove si riparte dopo questa sconfitta?':'Come giudica questo pareggio?';answer=won?`Vincere contro ${f[other(s)+'_name']} ci dà soddisfazione. Il risultato è dalla nostra parte: ora conta dare continuità, senza pensare che basti una partita.`:lost?`Il risultato ci lascia delusi. Dobbiamo ripartire da ciò che è successo contro ${f[other(s)+'_name']}, senza cercare alibi né trasformare una sconfitta in un giudizio su tutto.`:'Prendiamo il punto, sapendo che un pareggio può lasciare letture diverse. La partita va valutata per intero: il risultato da solo non racconta ogni passaggio.'}
 interviews.push({name,role:'Manager · '+f[s+'_name'],logo:f[s+'_logo_url'],qas:[{q,a:answer}]});}
 const candidates=players.filter(p=>!mvp||Number(p.sm_player_id)!==Number(mvp.sm_player_id)).filter(p=>Number(p.goals)>0||Number(p.assists)>0||number(p.sub_on_minute)!==null).sort((x,y)=>(Number(y.goals)*3+Number(y.assists))-(Number(x.goals)*3+Number(x.assists))||Number(y.rating||0)-Number(x.rating||0)).slice(0,2);
 function playerInterview(p,isMvp){const goals=Number(p.goals)||0,assists=Number(p.assists)||0,sub=number(p.sub_on_minute)!==null;const q=sub?`Sei entrato al ${p.sub_on_minute}′${goals?', segnando '+goals+' gol':assists?', con '+assists+' assist':''}: come leggi il tuo contributo?`:goals?`${goals} gol contro ${f[other(p.team_side)+'_name']}: che sensazione ti lascia la partita?`:assists?`${assists} assist: quanto conta contribuire anche all’ultimo passaggio?`:`Che significato ha per te questa prestazione?`;return {name:p.player_name,id:p.sm_player_id,role:(isMvp?'MVP · ':'Giocatore · ')+f[p.team_side+'_name'],logo:f[p.team_side+'_logo_url'],qas:[{q,a:win===p.team_side?'La soddisfazione più grande è aver aiutato la squadra a vincere. Il mio contributo assume valore dentro questo risultato.':win?'Il contributo personale non cancella la delusione per la sconfitta. Avrei voluto che servisse a portare a casa un risultato diverso.':'Sono contento di aver dato un contributo, ma resta la voglia di andare oltre il pareggio. Il risultato della squadra viene prima di quello individuale.'},...(isMvp?[{q:'Il riconoscimento di migliore in campo: a chi lo dedichi?',a:'Alla squadra. Un premio individuale fa piacere, ma dentro una partita nessuno fa tutto da solo.'}]:[])]}}
 interviews.push(...candidates.map(p=>playerInterview(p,false)));return {title,paragraphs,interviews,mvp:mvp?{player:mvp,official:official.length>0,interview:playerInterview(mvp,true)}:null,note:!coherent&&h+a>0?'Eventi gol incompleti: il risultato ufficiale rimane il riferimento.':null};}
window.ClubEditorial={pre,post};
})();
