(()=>{'use strict';const $=id=>document.getElementById(id),q=new URLSearchParams(location.search),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),date=v=>String(v||'').slice(0,10).split('-').reverse().join('/'),safe=v=>/^(https:\/\/|\/(?!\/))/i.test(v||'')?v:'',number=v=>v==null?'—':esc(v);let D=null,division=Number(q.get('division'))||1,active=q.get('fixture')?'club':['live','club'].includes(q.get('tab'))?q.get('tab'):q.get('tab')==='post'?'club':'preview',loading=false,epoch=0;
function params(){const p=new URLSearchParams({world:'GW001'});for(const k of ['season','day','fixture'])if(q.get(k))p.set(k,q.get(k));p.set('division',division);return p}
function url(){q.set('division',division);q.set('tab',active);history.replaceState(null,'','?'+q)}
function form(rows){return '<div class="md-form">'+(rows.length?rows.map(r=>'<i class="'+esc(r.outcome)+'" title="'+esc(date(r.date)+' · '+r.opponent+' · '+r.gf+'–'+r.ga)+'">'+r.outcome+'</i>').join(''):'<small>Nessun precedente</small>')+'</div>'}
function team(r,s){const t=r.preview[s+'_table'];return '<div class="md-side">'+(safe(r[s+'_logo_url'])?'<img src="'+esc(r[s+'_logo_url'])+'" alt="Logo '+esc(r[s+'_name'])+'" loading="lazy">':'')+'<h2>'+esc(r[s+'_name'])+'</h2><small>'+esc(r[s+'_imc_manager_name']||'Manager IMC non assegnato')+'</small><div class="standing">'+(t?.position?number(t.position)+'° · ':'')+number(t?.points)+' PT · '+number(t?.played)+' PG</div>'+form(r.preview[s+'_form'])+'</div>'}
function venue(rows){if(!rows.length)return 'Nessuna partita disponibile.';let v=0,n=0,p=0,gf=0,ga=0;for(const r of rows){v+=r.outcome==='V';n+=r.outcome==='N';p+=r.outcome==='P';gf+=r.gf;ga+=r.ga}return rows.length+' partite · '+v+' V / '+n+' N / '+p+' P<br>Gol '+gf+' fatti · '+ga+' subiti'}
function players(rows){if(!rows.length)return '<p class="md-note">Nessun dato giocatori disponibile nella stagione prima di questa giornata.</p>';const leaders=[['Gol','goals'],['Assist','assists'],['Media voto','rating']];return leaders.map(([label,key])=>{const valid=rows.filter(r=>key==='rating'?r.ratings>0:r[key]>0).sort((a,b)=>b[key]-a[key]||b.played-a.played);if(!valid.length)return '';const p=valid[0];return '<div class="md-player"><small>'+label+' · '+number(key==='rating'?Number(p.rating).toFixed(2):p[key])+'</small><a href="../players/profile.html?world=GW001&player='+p.id+'">'+esc(p.name)+'</a><small>'+p.played+' presenze'+(key==='rating'?' · '+p.ratings+' voti':'')+'</small></div>'}).join('')}
function stakes(r){const h=r.preview.home_table,a=r.preview.away_table;if(!h?.played&&!a?.played)return 'Prima giornata: entrambe partono da zero punti e cercano i primi tre punti della stagione.';const diff=(h?.points||0)-(a?.points||0);if(diff===0)return 'Squadre a pari punti: chi vince si porta tre punti davanti all’avversaria.';const behind=diff>0?r.away_name:r.home_name;return Math.abs(diff)<3?'Con una vittoria '+behind+' supererebbe l’avversaria in punti.':Math.abs(diff)===3?'Con una vittoria '+behind+' raggiungerebbe l’avversaria in punti.':'Le due squadre sono separate da '+Math.abs(diff)+' punti. '+behind+' può ridurre il distacco a '+(Math.abs(diff)-3)+'.'}
function narrative(r){const n=ClubPreMatch.story(r);return '<div class="md-detail club-story conversational"><span class="eyebrow">THE CLUB · PRE MATCH</span><h2>'+esc(n.title)+'</h2><div class="club-flow">'+n.beats.map(b=>b.type==='studio'?'<blockquote class="studio-voice"><span>DALLO STUDIO</span>“'+esc(b.text)+'”</blockquote>':b.type==='transition'?'<p class="club-transition">'+esc(b.text)+'</p>':'<p>'+esc(b.text)+'</p>').join('')+'</div><aside class="club-question"><b>THE CLUB QUESTION</b><p>'+esc(n.question)+'</p></aside></div>'}
function managerHistory(r){const h=r.preview.manager_h2h;if(!h?.available)return '<p>Storico manager non disponibile.</p>';return '<h3>H2H manager · Tutte le stagioni</h3><p>'+esc(r.home_imc_manager_name||'Manager casa')+' / '+esc(r.away_imc_manager_name||'Manager ospite')+'</p><p>'+h.played+' precedenti documentati · '+h.home_wins+' vittorie / '+h.draws+' pareggi / '+h.away_wins+' vittorie</p>'+(h.last?'<p>Ultimo confronto: '+esc(date(h.last.date))+' · '+esc(h.last.home)+' '+esc(h.last.score)+' '+esc(h.last.away)+'</p>':'<p><b>Primo confronto documentato tra i manager.</b></p>')+(h.incomplete?'<p class="md-note">Alcune partite storiche non hanno entrambi gli ID manager: il conteggio riguarda i precedenti identificabili.</p>':'')}
function metric(label,a,b){return '<div class="lab-row"><span>'+esc(label)+'</span><b>'+number(a)+'</b><b>'+number(b)+'</b></div>'}
function deepDive(r){const p=r.preview,h=p.h2h,hp=p.home_performance||{},ap=p.away_performance||{},lastH=hp.current?.last,lastA=ap.current?.last;
 const head='<div class="lab-head"><span></span><b>'+esc(r.home_name)+'</b><b>'+esc(r.away_name)+'</b></div>';
 const season=(x,k)=>x?.[k]?.played?x[k]:{};
 const partita=head+metric('Possesso medio S'+Math.max(1,D.season-1),(season(hp,'previous').possession??'—')+'%',(season(ap,'previous').possession??'—')+'%')+metric('Tiri medi S'+Math.max(1,D.season-1),season(hp,'previous').shots,season(ap,'previous').shots)+metric('In porta S'+Math.max(1,D.season-1),season(hp,'previous').on_target,season(ap,'previous').on_target)+metric('Possesso S'+D.season,(season(hp,'current').possession??'—')+'%',(season(ap,'current').possession??'—')+'%')+metric('Tiri S'+D.season,season(hp,'current').shots,season(ap,'current').shots);
 const moment='<div class="md-comparison"><div><h3>'+esc(r.home_name)+'</h3><p>'+(lastH?'Ultima: '+esc(lastH.gf+'–'+lastH.ga+' vs '+lastH.opponent)+'<br>'+lastH.possession+'% possesso · '+lastH.shots+' tiri · '+lastH.on_target+' in porta':'Nessun Match Report precedente in stagione')+'</p><p>'+venue(p.home_venue)+'</p></div><div><h3>'+esc(r.away_name)+'</h3><p>'+(lastA?'Ultima: '+esc(lastA.gf+'–'+lastA.ga+' vs '+lastA.opponent)+'<br>'+lastA.possession+'% possesso · '+lastA.shots+' tiri · '+lastA.on_target+' in porta':'Nessun Match Report precedente in stagione')+'</p><p>'+venue(p.away_venue)+'</p></div></div>';
 const storia='<h3>H2H club</h3><p>'+h.played+' precedenti · '+h.home_wins+' vittorie '+esc(r.home_name)+' · '+h.draws+' pareggi · '+h.away_wins+' vittorie '+esc(r.away_name)+'</p>'+managerHistory(r)+'<h3>Cosa c’è in palio</h3><p>'+esc(stakes(r))+'</p>';
 const lab='<h3>Le domande dello studio</h3><p>'+(lastH&&hp.previous?.played?'• '+esc(r.home_name)+' manterrà i '+lastH.possession+'% di possesso dell’ultima uscita rispetto al '+hp.previous.possession+'% medio della scorsa stagione?<br>':'')+(lastA&&ap.previous?.played?'• '+esc(r.away_name)+' riuscirà a migliorare i '+lastA.on_target+' tiri nello specchio dell’ultima partita rispetto ai '+ap.previous.on_target+' medi della scorsa stagione?<br>':'')+'• Quale delle due riuscirà a imporre più a lungo il proprio modo di giocare?</p><div class="md-comparison"><div><b>'+esc(r.home_name)+'</b>'+players(p.home_players)+'</div><div><b>'+esc(r.away_name)+'</b>'+players(p.away_players)+'</div></div>';
 return '<div class="deep-tabs"><button class="active" data-deep="match">La partita</button><button data-deep="moment">Il momento</button><button data-deep="history">La storia</button><button data-deep="lab">The Club Lab</button></div><div class="deep-panel" data-panel="match">'+partita+'</div><div class="deep-panel" data-panel="moment" hidden>'+moment+'</div><div class="deep-panel" data-panel="history" hidden>'+storia+'</div><div class="deep-panel" data-panel="lab" hidden>'+lab+'</div>'}
function fixture(r){return '<article class="md-card"><div class="md-card-head"><b>'+esc(D.divisions.find(d=>d.id===division)?.name)+'</b><span>'+esc(date(r.match_date))+'</span></div><div class="md-versus">'+team(r,'home')+'<div class="md-vs">VS</div>'+team(r,'away')+'</div>'+narrative(r)+'<details data-fixture="'+r.sm_fixture_id+'"><summary>Approfondisci il Pre Match <span>Analisi · Storia · The Club Lab</span></summary><div class="md-detail">'+deepDive(r)+'</div></details></article>'}
function bindDeepTabs(){document.querySelectorAll('.deep-tabs').forEach(nav=>nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{nav.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));const root=nav.parentElement;root.querySelectorAll('.deep-panel').forEach(p=>p.hidden=p.dataset.panel!==b.dataset.deep)}))}
function render(){const open=new Set([...document.querySelectorAll('details[open]')].map(x=>x.dataset.fixture));const ds=D.divisions||[];if(!ds.some(d=>d.id===division))division=ds[0]?.id||1;$('divisions').innerHTML=ds.map(d=>'<button data-division="'+d.id+'" class="'+(d.id===division?'active':'')+'" aria-pressed="'+(d.id===division)+'">'+esc(d.name)+'</button>').join('');$('fixtures').innerHTML=(ds.find(d=>d.id===division)?.fixtures||[]).map(fixture).join('')||'<p class="md-note">Nessuna giornata di campionato disponibile per questa stagione.</p>';$('fixtures').querySelectorAll('details').forEach(d=>d.open=open.has(d.dataset.fixture));$('fixtures').querySelectorAll('img').forEach(i=>i.onerror=()=>i.hidden=true);bindDeepTabs();$('divisions').querySelectorAll('button').forEach(b=>b.onclick=()=>{division=Number(b.dataset.division);url();render()});}
function show(){document.querySelectorAll('[data-tab]').forEach(b=>{const on=b.dataset.tab===active;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});$('preview-panel').hidden=active!=='preview';$('live-panel').hidden=active!=='live';$('club-panel').hidden=active!=='club';if(active==='club'){const available=Boolean(D?.divisions?.length);$('club-unavailable').hidden=available;$('club-frame').hidden=!available;const clubHref='post.html?'+params()+'&embedded=1';if(available&&$('club-frame').getAttribute('src')!==clubHref)$('club-frame').src=clubHref;}const href='../matchday/live.html?'+params();$('live-full').href=href;if(active==='live'&&$('live-frame').getAttribute('src')!==href)$('live-frame').src=href;else if(active!=='live')$('live-frame').removeAttribute('src');url()}
async function load(){if(loading||document.hidden)return;loading=true;const version=++epoch;try{const r=await fetch('../matchday/data.php?'+params(),{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error('Impossibile caricare la giornata.');if(version!==epoch)return;D=j;q.set('season',D.season);if(D.day)q.set('day',D.day);if(q.get('fixture')){const found=D.divisions.find(d=>d.fixtures.some(f=>String(f.sm_fixture_id)===q.get('fixture')));if(found)division=found.id;}$('day-title').textContent='Stagione '+D.season+(D.day?' · Giornata '+D.day+' · '+date(D.date):'');$('season').innerHTML=D.seasons.map(s=>'<option value="'+s.imc_season+'">Stagione '+s.imc_season+'</option>').join('');$('season').value=D.season;$('season').disabled=false;$('day').innerHTML=D.days.map(d=>'<option value="'+d.number+'">Giornata '+d.number+' · '+date(d.date)+'</option>').join('');$('day').value=D.day;$('day').disabled=!D.days.length;$('md-status').textContent=(D.total||0)+' partite · '+(D.ready||0)+' Match Report pronti per il Live · Aggiornamento automatico ogni 60 secondi';render();show();}catch(e){$('md-status').textContent='Dati temporaneamente non disponibili. Nuovo tentativo automatico tra 60 secondi.';}finally{loading=false}}
window.addEventListener('message',e=>{if(e.origin===location.origin&&[ $('club-frame').contentWindow,$('live-frame').contentWindow].includes(e.source)&&e.data?.type==='club-division'){const next=Number(e.data.division);if(D?.divisions.some(d=>d.id===next)){division=next;q.delete('fixture');url();render();}return;}if(e.origin!==location.origin||e.source!==$('club-frame').contentWindow||e.data?.type!=='the-club-height')return;const h=Number(e.data.height);if(Number.isFinite(h)&&h>=0)$('club-frame').style.height=Math.min(24000,Math.max(700,h))+'px'});
$('season').onchange=()=>{q.delete('fixture');q.set('season',$('season').value);q.delete('day');location.href='?'+q};$('day').onchange=()=>{q.delete('fixture');q.set('day',$('day').value);location.href='?'+q};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.tab;show()});load();setInterval(load,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});
})();
