(()=>{'use strict';const L=window.ClubPreMatchLibrary||{},H=t=>[...String(t)].reduce((h,c)=>(h*33+c.charCodeAt(0))>>>0,5381),P=(k,a)=>a?.length?a[H(k)%a.length]:'',R=(t,v)=>Object.entries(v).reduce((s,[k,x])=>s.replaceAll('{'+k+'}',x??''),t),S=n=>{const a=String(n||'').trim().split(/\s+/);return a.length>1?a.at(-1):a[0]||''};
function story(f){const p=f.preview||{},h=p.home_table||{},a=p.away_table||{},hf=p.home_form||[],af=p.away_form||[],k=String(f.sm_fixture_id),gap=Math.abs((h.points||0)-(a.points||0)),leader=(h.points||0)>=(a.points||0)?f.home_name:f.away_name,chaser=leader===f.home_name?f.away_name:f.home_name,beats=[],hp=p.home_performance||{},ap=p.away_performance||{};
 const perf=(name,x,tag)=>{const last=x.current?.last,prev=x.previous;if(last&&prev?.played){const dp=last.possession-prev.possession,ds=last.shots-prev.shots;if(Math.abs(dp)>=8||Math.abs(ds)>=4){const rising=dp>5&&ds>2;beats.push({type:'narrator',text:rising?name+' nell’ultima partita ha alzato il volume: '+last.possession+'% di possesso e '+last.shots+' tiri, contro medie della scorsa stagione di '+prev.possession+'% e '+prev.shots+'. Un segnale interessante, adesso da confermare.':name+' arriva da una prestazione diversa dalla propria identità della scorsa stagione: '+last.possession+'% di possesso e '+last.shots+' tiri, mentre l’anno scorso viaggiava a '+prev.possession+'% e '+prev.shots+' conclusioni.'});beats.push({type:'studio',text:rising?'Migliorerà ancora o manterrà questo livello di dominio?':'È una variazione momentanea o stiamo vedendo una squadra diversa?'})}}};
 const candidates=[];for(const [name,x,tag] of [[f.home_name,hp,'h'],[f.away_name,ap,'a']]){const l=x.current?.last,pr=x.previous;if(l&&pr?.played)candidates.push({name,x,score:Math.abs(l.possession-pr.possession)+Math.abs(l.shots-pr.shots)*2,tag})}candidates.sort((a,b)=>b.score-a.score);if(candidates[0])perf(candidates[0].name,candidates[0].x,candidates[0].tag);
 if(!beats.length){const x=hp.previous?.played?hp:ap,name=hp.previous?.played?f.home_name:f.away_name;if(x.previous?.played)beats.push({type:'narrator',text:name+' porta con sé un’identità costruita nella scorsa stagione: '+x.previous.possession+'% di possesso medio, '+x.previous.shots+' tiri e '+x.previous.on_target+' conclusioni nello specchio a partita. Oggi il primo tema è capire quanto di quella squadra ritroveremo.'});else beats.push({type:'narrator',text:P(k+'open',L.open)})}
 const ctx={gap,leader,chaser,home:f.home_name,away:f.away_name};if((h.played||a.played)&&gap<=6)beats.push({type:'narrator',text:R(P(k+'gap',L.gap),ctx)});
 const addForm=(team,rows,x)=>{if(rows.length<2)return;const w=rows.filter(r=>r.outcome==='V').length,l=rows.filter(r=>r.outcome==='P').length,n=rows.length;if(w>=Math.max(2,l+1))beats.push({type:'narrator',text:R(P(k+x+'form',L.form),{team,w,n})});else if(l>=Math.max(2,w+1))beats.push({type:'narrator',text:R(P(k+x+'bad',L.bad),{team,l,n})})};addForm(f.home_name,hf,'h');addForm(f.away_name,af,'a');
 const mh=p.manager_h2h,hm=S(f.home_imc_manager_name),am=S(f.away_imc_manager_name);if(hm&&am&&mh?.available&&mh.played){beats.push({type:'transition',text:P(k+'tr2',L.trans)});beats.push({type:'narrator',text:R(P(k+'mgr',L.mgr),{hm,am,played:mh.played,hw:mh.home_wins,aw:mh.away_wins,d:mh.draws,next:mh.played+1})})}
 const title=candidates[0]?(candidates[0].score>=12?'Qualcosa è cambiato. Adesso va confermato.':'Da dove ripartono, prima di tutto.'):P(k+'open',L.open),team=leader,question=candidates[0]?'Quello visto nell’ultima partita diventerà il nuovo standard di '+candidates[0].name+'?':R(P(k+'question',L.question),{...ctx,team,hm,am});
 return {title,beats,question,kind:'performance'};}
function response(f){const s=story(f),h=Number(f.home_score),a=Number(f.away_score);return {question:s.question,answer:h===a?'Il campo non le separa: '+h+'–'+a+'.':(h>a?f.home_name:f.away_name)+' chiude davanti: '+h+'–'+a+'.'};}window.ClubPreMatch={story,response,library:L};})();