const SUPABASE_URL='https://toanuzojdkfjgucztpze.supabase.co';
const SUPABASE_KEY='sb_publishable_DYmVU7yEavK_ddsdNMUjcg_a7HesB-l';
const GAME_WORLD_ID='GW009';
let cloudArchives=[];

async function cloudRequest(path,{method='GET',body=null,prefer='return=representation'}={}){
  const headers={'apikey':SUPABASE_KEY,'Authorization':`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json'};
  if(prefer)headers['Prefer']=prefer;
  const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method,headers,body:body?JSON.stringify(body):null});
  if(!response.ok){const text=await response.text();throw new Error(text||`HTTP ${response.status}`)}
  const text=await response.text();return text?JSON.parse(text):null;
}
function cloudCode(){const d=new Date();return `DRAW-${d.getFullYear()}-${String(Date.now()).slice(-8)}`}
function setCloudStatus(text,ok=true){const el=$('cloudStatus');if(el){el.textContent=text;el.dataset.ok=ok?'1':'0'}}
async function ensureCloudDraw(){
  if(state.cloudDrawId)return state.cloudDrawId;
  const code=state.cloudDrawCode||cloudCode();
  const rows=await cloudRequest('gw_division_draws',{method:'POST',body:{draw_code:code,game_world_id:GAME_WORLD_ID,season_id:null,draw_title:'GW009 Division Draw',draw_status:state.assignments.length?'in_progress':'draft',total_teams:state.teams.length,total_divisions:DIVISIONS.length,initial_teams:state.teams,initial_divisions:DIVISIONS,final_result:{},started_at:state.startedAt,created_by:'MNG001'}});
  const row=Array.isArray(rows)?rows[0]:rows;state.cloudDrawId=row.draw_id;state.cloudDrawCode=row.draw_code;save();return state.cloudDrawId;
}
async function syncCloudDraw(showMessage=false){
  try{
    setCloudStatus('Cloud Nexus: sincronizzazione…');
    const id=await ensureCloudDraw();
    await cloudRequest(`gw_division_draw_items?draw_id=eq.${encodeURIComponent(id)}`,{method:'DELETE',prefer:'return=minimal'});
    if(state.assignments.length){
      const items=state.assignments.map(a=>({draw_id:id,draw_order:a.number,team_id:null,team_name:a.team,division_id:null,division_code:a.division.replace('Division ','DIV00'),division_name:a.division,team_rotation:a.teamRotation??null,division_rotation:a.divisionRotation??null,animation_duration:a.animationDuration||4800,pause_after:a.pauseAfter||900,confirmed:true,confirmed_at:a.time}));
      await cloudRequest('gw_division_draw_items',{method:'POST',body:items});
    }
    const status=state.remaining.length===0?'completed':(state.assignments.length?'in_progress':'draft');
    const result=Object.fromEntries(DIVISIONS.map(d=>[d,state.assignments.filter(a=>a.division===d).map(a=>a.team)]));
    await cloudRequest(`gw_division_draws?draw_id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:{draw_status:status,final_result:result,completed_at:status==='completed'?new Date().toISOString():null},prefer:'return=minimal'});
    setCloudStatus(`Cloud Nexus: sincronizzato · ${state.cloudDrawCode}`,true);
    if(showMessage)alert(`Sorteggio salvato su Nexus Cloud.\n${state.cloudDrawCode}`);
    return true;
  }catch(error){console.error(error);setCloudStatus('Cloud Nexus: sincronizzazione non riuscita',false);if(showMessage)alert('Salvataggio cloud non riuscito. La copia locale è rimasta intatta.');return false}
}
async function fetchCloudArchives(){
  const wrap=$('cloudArchiveList');wrap.innerHTML='<div class="empty-state">Caricamento dal cloud…</div>';
  try{
    const draws=await cloudRequest(`gw_division_draws?game_world_id=eq.${GAME_WORLD_ID}&select=*&order=created_at.desc`);
    cloudArchives=draws||[];renderCloudArchive();setCloudStatus(`Cloud Nexus: ${cloudArchives.length} sorteggi disponibili`,true);
  }catch(error){console.error(error);wrap.innerHTML='<div class="empty-state">Impossibile caricare il cloud.</div>';setCloudStatus('Cloud Nexus: errore di connessione',false)}
}
function renderCloudArchive(){
  const wrap=$('cloudArchiveList');wrap.innerHTML='';
  if(!cloudArchives.length){wrap.innerHTML='<div class="empty-state">Nessun sorteggio nel cloud.</div>';return}
  cloudArchives.forEach(s=>{const item=document.createElement('article');item.className='archive-item';item.innerHTML=`<h4>${escapeHtml(s.draw_title||'GW009 Division Draw')}</h4><div class="archive-meta">${escapeHtml(s.draw_code)} · ${s.draw_status} · ${new Date(s.created_at).toLocaleString('it-IT')}</div><div class="archive-actions"><button class="primary-btn" data-cloud-action="play" data-id="${s.draw_id}">Riproduci</button><button class="secondary-btn" data-cloud-action="json" data-id="${s.draw_id}">Esporta JSON</button></div>`;wrap.appendChild(item)})
}
async function loadCloudSession(drawId){
  const draw=cloudArchives.find(x=>x.draw_id===drawId);if(!draw)throw new Error('Sorteggio non trovato');
  const items=await cloudRequest(`gw_division_draw_items?draw_id=eq.${encodeURIComponent(drawId)}&select=*&order=draw_order.asc`);
  return{format:'IMC_WHEEL_SESSION',version:'2.6.0',id:draw.draw_id,title:draw.draw_title||'GW009 Division Draw',createdAt:draw.started_at||draw.created_at,savedAt:draw.completed_at||draw.created_at,teams:draw.initial_teams||DEFAULT_TEAMS,divisions:draw.initial_divisions||DIVISIONS,capacity:CAPACITY,assignments:(items||[]).map(x=>({number:x.draw_order,team:x.team_name,division:x.division_name,time:x.confirmed_at,teamRotation:Number(x.team_rotation)||0,divisionRotation:Number(x.division_rotation)||0,animationDuration:Number(x.animation_duration)||4800,pauseAfter:Number(x.pause_after)||900})),events:[]}
}

const DEFAULT_TEAMS=['Alcione Milano','Union Clodiense','Imperia','Battipagliese','Turris','Ostia Mare','Ischia Isolaverde','Ragusa','Torres','Renate','Paganese','Barletta','Locri','Asti','Folgore Caratese','Agropoli','Savoia','Scafatese','Casarano','Manfredonia','Vibonese','Milazzo','Desenzano','Giulianova','Lumezzane','Paternò','Giugliano','Imolese','Città di Gela','Enna'];
const DIVISIONS=['Division 1','Division 2','Division 3'];
const CAPACITY=10;
const COLORS=['#0B103A','#009246','#CE2B37','#FFFFFF','#20335F','#E9EDF5'];
const STATE_KEY='imcWheelStateV250';
const ARCHIVE_KEY='imcWheelArchiveV250';
let state=loadState();
let archives=loadArchives();
let spinning=false;
let pendingDraw=null;
let replay={session:null,index:0,timer:null,playing:false};
let autoRun={active:false,paused:false,stopped:false,timer:null};
let viewerMode=false,viewerDrawId=null,viewerPoll=null;
const SPEEDS={ceremony:{spin:6200,popup:2600,gap:1200},standard:{spin:4400,popup:1700,gap:700},fast:{spin:2400,popup:800,gap:350}};

const $=id=>document.getElementById(id);
const teamCanvas=$('teamWheel');
const divisionCanvas=$('divisionWheel');
const spinBtn=$('spinBtn');
const replayTeamCanvas=$('replayTeamWheel');
const replayDivisionCanvas=$('replayDivisionWheel');
const undoBtn=$('undoBtn');

function initialState(teams=DEFAULT_TEAMS){return{sessionId:crypto.randomUUID?.()||String(Date.now()),startedAt:new Date().toISOString(),teams:[...teams],remaining:[...teams],assignments:[],events:[],cloudDrawId:null,cloudDrawCode:null}}
function loadState(){try{const x=JSON.parse(localStorage.getItem(STATE_KEY));if(x&&Array.isArray(x.teams)&&Array.isArray(x.remaining)&&Array.isArray(x.assignments)){x.events=x.events||[];return x}}catch(e){}return initialState()}
function loadArchives(){try{const x=JSON.parse(localStorage.getItem(ARCHIVE_KEY));return Array.isArray(x)?x:[]}catch(e){return[]}}
function save(){localStorage.setItem(STATE_KEY,JSON.stringify(state));localStorage.setItem(ARCHIVE_KEY,JSON.stringify(archives))}
function divisionCounts(assignments=state.assignments){return Object.fromEntries(DIVISIONS.map(d=>[d,assignments.filter(a=>a.division===d).length]))}
function availableDivisions(){const c=divisionCounts();return DIVISIONS.filter(d=>c[d]<CAPACITY)}
function fitText(ctx,text,maxWidth,start=28){let size=start;while(size>10){ctx.font=`700 ${size}px Inter, sans-serif`;if(ctx.measureText(text).width<=maxWidth)return size;size--}return size}
function drawWheel(canvas,items){const ctx=canvas.getContext('2d'),w=canvas.width,cx=w/2,cy=w/2,r=w*.46;ctx.clearRect(0,0,w,w);ctx.save();ctx.translate(cx,cy);const list=items.length?items:['—'],arc=Math.PI*2/list.length;list.forEach((item,i)=>{ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,i*arc,(i+1)*arc);ctx.closePath();ctx.fillStyle=COLORS[i%COLORS.length];ctx.fill();ctx.strokeStyle='#D9DEE8';ctx.lineWidth=4;ctx.stroke();ctx.save();ctx.rotate(i*arc+arc/2);ctx.translate(r*.62,0);ctx.rotate(Math.PI/2);const dark=['#0B103A','#009246','#CE2B37','#20335F'].includes(COLORS[i%COLORS.length]);ctx.fillStyle=dark?'#fff':'#0B103A';const label=item.length>23?item.slice(0,21)+'…':item;ctx.font=`700 ${fitText(ctx,label,r*.58,items.length>18?22:31)}px Inter`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,0,0);ctx.restore()});ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.strokeStyle='#0B103A';ctx.lineWidth=14;ctx.stroke();ctx.restore()}
function render(){drawWheel(teamCanvas,state.remaining);drawWheel(divisionCanvas,availableDivisions());$('remainingCount').textContent=state.remaining.length;$('assignedCount').textContent=state.assignments.length;$('teamCounter').textContent=state.remaining.length;spinBtn.disabled=spinning||!!pendingDraw||state.remaining.length===0;undoBtn.disabled=spinning||!!pendingDraw||state.assignments.length===0;renderBoard('divisionColumns',state.assignments,true);renderOfficialProgress();renderLiveHistory();save()}

function renderOfficialProgress(){const done=state.assignments.length,total=state.teams.length||30,pct=total?done/total*100:0;$('officialProgressText').textContent=`${done} / ${total}`;$('officialProgressBar').style.width=`${pct}%`;$('officialProgressLabel').textContent=done===0?'Sorteggio non iniziato':done===total?'Sorteggio completato':'Sorteggio ufficiale in corso'}
function renderLiveHistory(){const wrap=$('liveHistory');$('historyCounter').textContent=state.assignments.length;if(!state.assignments.length){wrap.innerHTML='<div class="empty-state">Nessuna assegnazione confermata.</div>';return}wrap.innerHTML=state.assignments.slice(-6).reverse().map(a=>`<article class="history-item"><span>#${String(a.number).padStart(3,'0')}</span><strong>${escapeHtml(a.team)}</strong><b>${escapeHtml(a.division)}</b></article>`).join('')}
function setSyncStep(step,status){const el=document.querySelector(`#syncChecklist [data-step="${step}"]`);if(!el)return;el.dataset.status=status;const labels={local:'Salvataggio locale',cloud:'Salvataggio cloud',replay:'Replay aggiornato',nexus:'Nexus aggiornato'};el.textContent=`${status==='ok'?'✓':status==='error'?'✕':'○'} ${labels[step]}`}
function resetSyncChecklist(){const box=$('syncChecklist');box.classList.add('hidden');['local','cloud','replay','nexus'].forEach(s=>setSyncStep(s,'idle'))}
function playResultFeedback(){try{navigator.vibrate?.([80,40,120])}catch(e){}try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=new C(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.setValueAtTime(660,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(990,ctx.currentTime+.22);gain.gain.setValueAtTime(.001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.12,ctx.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.3);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.32)}catch(e){}}

function renderBoard(targetId,assignments,withEmpty){const c=divisionCounts(assignments),wrap=$(targetId);wrap.innerHTML='';DIVISIONS.forEach(d=>{const items=assignments.filter(a=>a.division===d),col=document.createElement('article');col.className='division-column';col.innerHTML=`<div class="division-header"><h4>${d}</h4><strong>${c[d]}/${CAPACITY}</strong></div>`;const ul=document.createElement('ol');ul.className='division-list';const max=withEmpty?CAPACITY:Math.max(items.length,1);for(let i=0;i<max;i++){const li=document.createElement('li');li.innerHTML=items[i]?`<span class="slot">${i+1}</span><strong>${escapeHtml(items[i].team)}</strong>`:`<span class="slot">${i+1}</span><span class="empty">Posto libero</span>`;ul.appendChild(li)}col.appendChild(ul);wrap.appendChild(col)})}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function normalizeAngle(a){const t=Math.PI*2;return((a%t)+t)%t}
function targetRotation(index,count,extraTurns){const arc=Math.PI*2/count,center=index*arc+arc/2,desired=-Math.PI/2-center;return extraTurns*Math.PI*2+normalizeAngle(desired)}
function animateSelection(teamIndex,divIndex,done){const speed=SPEEDS[$('ceremonySpeed')?.value||'standard'];const duration=autoRun.active?speed.spin:4800;const divs=availableDivisions(),teamRot=targetRotation(teamIndex,state.remaining.length,6+Math.floor(Math.random()*3)),divRot=targetRotation(divIndex,divs.length,6+Math.floor(Math.random()*3));if(pendingDraw){pendingDraw.teamRotation=teamRot;pendingDraw.divisionRotation=divRot;pendingDraw.animationDuration=duration;pendingDraw.pauseAfter=autoRun.active?speed.popup+speed.gap:900}teamCanvas.style.transition=`transform ${duration}ms cubic-bezier(.1,.7,.12,1)`;divisionCanvas.style.transition=`transform ${duration}ms cubic-bezier(.1,.7,.12,1)`;teamCanvas.style.transform=`rotate(${teamRot}rad)`;divisionCanvas.style.transform=`rotate(${divRot}rad)`;$('teamSelected').textContent='Estrazione…';$('divisionSelected').textContent='Estrazione…';setTimeout(()=>{teamCanvas.style.transition='none';divisionCanvas.style.transition='none';teamCanvas.style.transform='rotate(0rad)';divisionCanvas.style.transform='rotate(0rad)';void teamCanvas.offsetWidth;teamCanvas.style.transition=`transform ${duration}ms cubic-bezier(.1,.7,.12,1)`;divisionCanvas.style.transition=`transform ${duration}ms cubic-bezier(.1,.7,.12,1)`;done()},duration)}
function spin(){if(!viewerMode&&!state.cloudDrawId){alert('Crea prima l’evento LIVE e condividi il link.');return}if(spinning||pendingDraw||!state.remaining.length)return;const divs=availableDivisions();if(!divs.length)return;spinning=true;render();setCloudStatus(state.cloudDrawCode?`Cloud Nexus: ${state.cloudDrawCode}`:'Cloud Nexus: pronto',true);const teamIndex=Math.floor(Math.random()*state.remaining.length),divIndex=Math.floor(Math.random()*divs.length);pendingDraw={teamIndex,divIndex,team:state.remaining[teamIndex],division:divs[divIndex],generatedAt:new Date().toISOString()};animateSelection(teamIndex,divIndex,()=>{spinning=false;$('teamSelected').textContent=pendingDraw.team;$('divisionSelected').textContent=pendingDraw.division;showResultDialog();render()})}
function showResultDialog(){resetSyncChecklist();$('modalDrawNumber').textContent=`ASSEGNAZIONE #${String(state.assignments.length+1).padStart(3,'0')}`;$('modalTeam').textContent=pendingDraw.team;$('modalDivision').textContent=pendingDraw.division;$('modalProgress').textContent=`${state.assignments.length+1}/30 squadre assegnate`;$('resultDialog').showModal();playResultFeedback();const manual=$('drawMode')?.value==='manual'&&!autoRun.active;$('manualDialogActions').classList.toggle('hidden',!manual);if(!manual){setTimeout(()=>confirmPending(true),350)}}
async function confirmPending(fromAuto=false){if(!pendingDraw)return;const button=$('confirmDrawBtn');button.disabled=true;$('cancelDrawBtn').disabled=true;$('syncChecklist').classList.remove('hidden');const idx=state.remaining.indexOf(pendingDraw.team);if(idx<0)return;state.remaining.splice(idx,1);const record={number:state.assignments.length+1,team:pendingDraw.team,division:pendingDraw.division,time:new Date().toISOString(),teamRotation:pendingDraw.teamRotation||0,divisionRotation:pendingDraw.divisionRotation||0,animationDuration:pendingDraw.animationDuration||4800,pauseAfter:pendingDraw.pauseAfter||900};state.assignments.push(record);state.events.push({type:'confirmed',...record});$('resultTeam').textContent=record.team;$('resultDivision').textContent=record.division;$('resultCard').classList.remove('hidden');setSyncStep('local','ok');save();setSyncStep('replay','ok');const cloudOk=await syncCloudDraw(false);setSyncStep('cloud',cloudOk?'ok':'error');setSyncStep('nexus',cloudOk?'ok':'error');const popupDelay=autoRun.active?SPEEDS[$('ceremonySpeed').value].popup:650;await new Promise(r=>setTimeout(r,popupDelay));$('resultDialog').close();pendingDraw=null;$('teamSelected').textContent='Pronta';$('divisionSelected').textContent='Pronta';button.disabled=false;$('cancelDrawBtn').disabled=false;render();if(state.remaining.length===0){saveSession(true);stopAuto(false);return}if(autoRun.active&&!autoRun.paused&&!autoRun.stopped){autoRun.timer=setTimeout(()=>spin(),SPEEDS[$('ceremonySpeed').value].gap)}}
function cancelPending(){if(!pendingDraw)return;resetSyncChecklist();state.events.push({type:'cancelled',team:pendingDraw.team,division:pendingDraw.division,time:new Date().toISOString()});pendingDraw=null;$('resultDialog').close();$('teamSelected').textContent='Pronta';$('divisionSelected').textContent='Pronta';render()}
async function undo(){if(!state.assignments.length||spinning||pendingDraw)return;const last=state.assignments.pop();state.remaining.push(last.team);state.remaining.sort((a,b)=>state.teams.indexOf(a)-state.teams.indexOf(b));state.events.push({type:'undo',team:last.team,division:last.division,time:new Date().toISOString()});$('resultCard').classList.toggle('hidden',state.assignments.length===0);if(state.assignments.length){const x=state.assignments.at(-1);$('resultTeam').textContent=x.team;$('resultDivision').textContent=x.division}$('teamSelected').textContent='Pronta';$('divisionSelected').textContent='Pronta';render();await syncCloudDraw(false)}
function sessionObject(){return{format:'IMC_WHEEL_SESSION',version:'2.6.0',id:state.sessionId,title:'GW009 Division Draw',createdAt:state.startedAt,savedAt:new Date().toISOString(),teams:[...state.teams],divisions:[...DIVISIONS],capacity:CAPACITY,assignments:state.assignments.map(x=>({...x})),events:state.events.map(x=>({...x}))}}
function saveSession(auto=false){if(!state.assignments.length&&!auto){alert('Non ci sono estrazioni da salvare.');return}const obj=sessionObject(),i=archives.findIndex(x=>x.id===obj.id);if(i>=0)archives[i]=obj;else archives.unshift(obj);save();renderArchive();if(!auto)alert('Sorteggio salvato nell’archivio del dispositivo.')}
function downloadJson(obj,name){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportCSV(){const rows=[['N.','Squadra','Divisione','Data/Ora'],...state.assignments.map(a=>[a.number,a.team,a.division,a.time])],csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='imc-wheel-division-draw.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function renderArchive(){const wrap=$('archiveList');wrap.innerHTML='';if(!archives.length){wrap.innerHTML='<div class="empty-state">Nessun sorteggio salvato.</div>';return}archives.forEach(s=>{const item=document.createElement('article');item.className='archive-item';item.innerHTML=`<h4>${escapeHtml(s.title||'Sorteggio IMC')}</h4><div class="archive-meta">${s.assignments.length} estrazioni · ${new Date(s.savedAt||s.createdAt).toLocaleString('it-IT')}</div><div class="archive-actions"><button class="primary-btn" data-action="play" data-id="${s.id}">Riproduci</button><button class="secondary-btn" data-action="export" data-id="${s.id}">Esporta JSON</button><button class="danger-btn" data-action="delete" data-id="${s.id}">Elimina</button></div>`;wrap.appendChild(item)})}
function replaySpeedFactor(){const v=Number($('replaySpeed').value);return v===1800?.5:v===450?2:1}
function replayStateAt(index){const s=replay.session||{teams:DEFAULT_TEAMS,assignments:[]};const shown=s.assignments.slice(0,index);const remaining=(s.teams||DEFAULT_TEAMS).filter(t=>!shown.some(a=>a.team===t));const counts=Object.fromEntries(DIVISIONS.map(d=>[d,shown.filter(a=>a.division===d).length]));const divs=DIVISIONS.filter(d=>counts[d]<CAPACITY);return{shown,remaining,divs}}
function resetReplayWheelTransforms(){[replayTeamCanvas,replayDivisionCanvas].forEach(c=>{c.style.transition='none';c.style.transform='rotate(0rad)'});void replayTeamCanvas.offsetWidth}
function startReplay(session){stopReplay();replay={session,index:0,timer:null,playing:false,animating:false};$('archiveDialog').close();$('replayTitle').textContent=session.title||'Sorteggio';$('replayDialog').showModal();resetReplayWheelTransforms();renderReplay()}
function renderReplay(){const s=replay.session||{assignments:[]},ctx=replayStateAt(replay.index),total=s.assignments.length;$('replayStep').textContent=`${replay.index} / ${total}`;$('replayProgressBar').style.width=total?`${replay.index/total*100}%`:'0%';const current=ctx.shown.at(-1);$('replayTeam').textContent=current?current.team:'Pronto';$('replayDivision').textContent=current?current.division:'—';drawWheel(replayTeamCanvas,ctx.remaining.length?ctx.remaining:['Completato']);drawWheel(replayDivisionCanvas,ctx.divs.length?ctx.divs:['Completato']);renderBoard('replayBoard',ctx.shown,false);$('replayPrevBtn').disabled=replay.animating||replay.index<=0;$('replayNextBtn').disabled=replay.animating||replay.index>=total;$('replayPlayBtn').textContent=replay.playing?'Pausa':'Riproduci';if(!replay.animating)$('replayStatus').textContent=replay.index?`Assegnazione #${String(replay.index).padStart(3,'0')} riprodotta`:'Pronto alla riproduzione'}
function animateReplayStep(done){const a=replay.session.assignments[replay.index];if(!a){done();return}const ctx=replayStateAt(replay.index);drawWheel(replayTeamCanvas,ctx.remaining);drawWheel(replayDivisionCanvas,ctx.divs);resetReplayWheelTransforms();const factor=replaySpeedFactor(),duration=Math.max(450,(a.animationDuration||4800)/factor),teamRot=a.teamRotation||targetRotation(Math.max(0,ctx.remaining.indexOf(a.team)),Math.max(1,ctx.remaining.length),7),divRot=a.divisionRotation||targetRotation(Math.max(0,ctx.divs.indexOf(a.division)),Math.max(1,ctx.divs.length),7);replay.animating=true;$('replayStatus').textContent=`Ruote in movimento · estrazione #${String(a.number||replay.index+1).padStart(3,'0')}`;$('replayStatus').classList.add('spinning');replayTeamCanvas.style.transition=`transform ${duration}ms cubic-bezier(.1,.7,.12,1)`;replayDivisionCanvas.style.transition=`transform ${duration}ms cubic-bezier(.1,.7,.12,1)`;replayTeamCanvas.style.transform=`rotate(${teamRot}rad)`;replayDivisionCanvas.style.transform=`rotate(${divRot}rad)`;replay.timer=setTimeout(()=>{replay.index++;replay.animating=false;$('replayStatus').classList.remove('spinning');renderReplay();const hold=Math.max(250,(a.pauseAfter||900)/factor);replay.timer=setTimeout(done,hold)},duration)}
function toggleReplay(){if(!replay.session)return;if(replay.playing){stopReplay();renderReplay();return}if(replay.index>=replay.session.assignments.length){replay.index=0;resetReplayWheelTransforms();renderReplay()}replay.playing=true;renderReplay();scheduleReplay()}
function scheduleReplay(){clearTimeout(replay.timer);if(!replay.playing||replay.animating)return;const total=replay.session.assignments.length;if(replay.index>=total){replay.playing=false;renderReplay();return}animateReplayStep(()=>{if(replay.playing)scheduleReplay()})}
function stepReplay(direction){stopReplay();if(replay.animating)return;if(direction<0){replay.index=Math.max(0,replay.index-1);resetReplayWheelTransforms();renderReplay();return}if(replay.index<replay.session.assignments.length)animateReplayStep(()=>{})}
function stopReplay(){if(replay.timer)clearTimeout(replay.timer);replay.timer=null;replay.playing=false;if(replay.animating){replay.animating=false;$('replayStatus')?.classList.remove('spinning')}}

async function startAuto(){
  if(!state.cloudDrawId){alert('Crea prima l’evento LIVE e condividi il link.');return}
  if(autoRun.active){if(autoRun.paused){autoRun.paused=false;$('pauseAutoBtn').textContent='Pausa';spin()}return}
  if(!state.remaining.length)return;
  autoRun={active:true,paused:false,stopped:false,timer:null};
  $('pauseAutoBtn').classList.remove('hidden');$('stopAutoBtn').classList.remove('hidden');$('undoBtn').classList.add('hidden');
  $('spinBtn').textContent='SORTEGGIO AUTOMATICO IN CORSO';$('spinBtn').disabled=true;
  await ensureCloudDraw();updateLiveLink();syncCloudDraw(false);spin();
}
function pauseAuto(){if(!autoRun.active)return;autoRun.paused=!autoRun.paused;$('pauseAutoBtn').textContent=autoRun.paused?'Riprendi':'Pausa';if(!autoRun.paused&&!spinning&&!pendingDraw)spin()}
function stopAuto(user=true){clearTimeout(autoRun.timer);autoRun.active=false;autoRun.paused=false;autoRun.stopped=true;$('pauseAutoBtn').classList.add('hidden');$('stopAutoBtn').classList.add('hidden');$('undoBtn').classList.remove('hidden');$('spinBtn').textContent=state.remaining.length?'AVVIA SORTEGGIO':'SORTEGGIO COMPLETATO';$('spinBtn').disabled=!state.remaining.length;if(user)setCloudStatus('Sorteggio automatico interrotto',false)}
function updateLiveLink(){if(!state.cloudDrawId)return;const url=`${location.origin}${location.pathname}?live=${encodeURIComponent(state.cloudDrawId)}`;$('liveLinkInput').value=url;$('copyLiveLinkBtn').disabled=false;$('eventSetupTitle').textContent=`Evento ${state.cloudDrawCode||''} creato`;$('eventSetupStatus').textContent='Condividi il link. Gli spettatori vedranno la sala d’attesa fino all’avvio.';$('createLiveLinkBtn').textContent='EVENTO LIVE PRONTO';$('createLiveLinkBtn').disabled=true;$('spinBtn').disabled=!state.remaining.length;$('spinBtn').textContent=$('drawMode').value==='auto'?'AVVIA CERIMONIA':'GIRA LE RUOTE'}
async function createLiveLink(){const button=$('createLiveLinkBtn');button.disabled=true;button.textContent='CREAZIONE EVENTO…';try{await ensureCloudDraw();await syncCloudDraw(false);updateLiveLink();setCloudStatus(`Sala d’attesa pronta · ${state.cloudDrawCode}`,true)}catch(e){console.error(e);button.disabled=false;button.textContent='CREA EVENTO LIVE';alert('Impossibile creare l’evento LIVE. Controlla la connessione e riprova.')}}
async function copyLiveLink(){const v=$('liveLinkInput').value;if(!v)return;try{await navigator.clipboard.writeText(v);$('copyLiveLinkBtn').textContent='Copiato ✓';setTimeout(()=>$('copyLiveLinkBtn').textContent='Copia link',1500)}catch(e){$('liveLinkInput').select();document.execCommand('copy')}}
async function initViewer(drawId){viewerMode=true;viewerDrawId=drawId;document.body.classList.add('viewer-mode');$('liveBanner').classList.remove('hidden');$('officialProgressLabel').textContent='Collegamento alla diretta…';await pollViewer();viewerPoll=setInterval(pollViewer,2000)}
async function pollViewer(){try{const drawRows=await cloudRequest(`gw_division_draws?draw_id=eq.${encodeURIComponent(viewerDrawId)}&select=*`);const draw=drawRows?.[0];if(!draw)throw new Error('Sessione non trovata');const items=await cloudRequest(`gw_division_draw_items?draw_id=eq.${encodeURIComponent(viewerDrawId)}&select=*&order=draw_order.asc`);state.teams=draw.initial_teams||DEFAULT_TEAMS;state.assignments=(items||[]).map(x=>({number:x.draw_order,team:x.team_name,division:x.division_name,time:x.confirmed_at,teamRotation:Number(x.team_rotation)||0,divisionRotation:Number(x.division_rotation)||0,animationDuration:Number(x.animation_duration)||4800,pauseAfter:Number(x.pause_after)||900}));state.remaining=state.teams.filter(t=>!state.assignments.some(a=>a.team===t));state.cloudDrawId=draw.draw_id;state.cloudDrawCode=draw.draw_code;render();setCloudStatus(`LIVE · ${draw.draw_code}`,true);if(!state.assignments.length&&draw.draw_status==='draft'){$('officialProgressLabel').textContent='Sala d’attesa · il sorteggio inizierà tra poco'}if(state.assignments.length){const a=state.assignments.at(-1);$('resultTeam').textContent=a.team;$('resultDivision').textContent=a.division;$('resultCard').classList.remove('hidden')}if(draw.draw_status==='completed'){$('liveBanner').innerHTML='<span class="live-dot"></span> REPLAY DISPONIBILE · SORTEGGIO COMPLETATO';clearInterval(viewerPoll)}}catch(e){setCloudStatus('LIVE: connessione in attesa…',false)}}

function resetAll(teams=state.teams){pendingDraw=null;state=initialState(teams);$('liveLinkInput').value='';$('copyLiveLinkBtn').disabled=true;$('createLiveLinkBtn').disabled=false;$('createLiveLinkBtn').textContent='CREA EVENTO LIVE';$('eventSetupTitle').textContent='Crea l’evento LIVE';$('eventSetupStatus').textContent='Genera il link pubblico, condividilo e poi avvia la cerimonia.';$('spinBtn').disabled=true;$('spinBtn').textContent='CREA PRIMA L’EVENTO LIVE';$('resultCard').classList.add('hidden');$('teamSelected').textContent='Pronta';$('divisionSelected').textContent='Pronta';render()}
async function importJson(file){try{const x=JSON.parse(await file.text());if(x.format!=='IMC_WHEEL_SESSION'||!Array.isArray(x.assignments))throw new Error();if(!x.id)x.id=crypto.randomUUID?.()||String(Date.now());x.savedAt=new Date().toISOString();const i=archives.findIndex(a=>a.id===x.id);if(i>=0)archives[i]=x;else archives.unshift(x);save();renderArchive();alert('Sessione importata correttamente.')}catch(e){alert('File JSON non valido per IMC Wheel.')}}

spinBtn.addEventListener('click',()=>{$('drawMode').value==='auto'?startAuto():spin()});undoBtn.addEventListener('click',undo);$('confirmDrawBtn').addEventListener('click',confirmPending);$('cancelDrawBtn').addEventListener('click',cancelPending);$('exportBtn').addEventListener('click',exportCSV);$('saveSessionBtn').addEventListener('click',()=>saveSession(false));$('cloudSaveBtn').addEventListener('click',()=>syncCloudDraw(true));$('refreshCloudBtn').addEventListener('click',fetchCloudArchives);
$('settingsBtn').addEventListener('click',()=>{$('teamsInput').value=state.teams.join('\n');$('settingsDialog').showModal()});$('archiveBtn').addEventListener('click',()=>{renderArchive();$('archiveDialog').showModal();fetchCloudArchives()});document.querySelectorAll('.close-dialog').forEach(b=>b.addEventListener('click',()=>$(b.dataset.dialog).close()));
$('saveTeamsBtn').addEventListener('click',()=>{const teams=$('teamsInput').value.split('\n').map(x=>x.trim()).filter(Boolean);if(teams.length!==30){alert('Inserisci esattamente 30 squadre.');return}if(new Set(teams).size!==30){alert('Sono presenti nomi duplicati.');return}if(confirm('Salvare il nuovo elenco e azzerare il sorteggio?')){resetAll(teams);$('settingsDialog').close()}});$('resetBtn').addEventListener('click',()=>{if(confirm('Azzerare completamente il sorteggio corrente?')){resetAll();$('settingsDialog').close()}});
$('archiveList').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const s=archives.find(x=>x.id===b.dataset.id);if(!s)return;if(b.dataset.action==='play')startReplay(s);if(b.dataset.action==='export')downloadJson(s,`imc-wheel-${s.id}.json`);if(b.dataset.action==='delete'&&confirm('Eliminare questo sorteggio salvato?')){archives=archives.filter(x=>x.id!==s.id);save();renderArchive()}});$('exportCurrentJsonBtn').addEventListener('click',()=>downloadJson(sessionObject(),'imc-wheel-sessione-corrente.json'));$('importJsonInput').addEventListener('change',e=>{const f=e.target.files[0];if(f)importJson(f);e.target.value=''});
$('cloudArchiveList').addEventListener('click',async e=>{const b=e.target.closest('button[data-cloud-action]');if(!b)return;b.disabled=true;try{const session=await loadCloudSession(b.dataset.id);if(b.dataset.cloudAction==='play')startReplay(session);if(b.dataset.cloudAction==='json')downloadJson(session,`imc-wheel-cloud-${b.dataset.id}.json`)}catch(error){console.error(error);alert('Impossibile aprire il sorteggio cloud.')}finally{b.disabled=false}});
$('replayPlayBtn').addEventListener('click',toggleReplay);$('replayPrevBtn').addEventListener('click',()=>stepReplay(-1));$('replayNextBtn').addEventListener('click',()=>stepReplay(1));$('replaySpeed').addEventListener('change',()=>{if(replay.playing)scheduleReplay()});$('closeReplayBtn').addEventListener('click',()=>{stopReplay();$('replayDialog').close()});
$('pauseAutoBtn').addEventListener('click',pauseAuto);$('stopAutoBtn').addEventListener('click',()=>stopAuto(true));$('createLiveLinkBtn').addEventListener('click',createLiveLink);$('copyLiveLinkBtn').addEventListener('click',copyLiveLink);$('drawMode').addEventListener('change',()=>{spinBtn.textContent=state.cloudDrawId?($('drawMode').value==='auto'?'AVVIA CERIMONIA':'GIRA LE RUOTE'):'CREA PRIMA L’EVENTO LIVE'});
window.addEventListener('resize',()=>{drawWheel(teamCanvas,state.remaining);drawWheel(divisionCanvas,availableDivisions())});if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js?v=260').catch(()=>{}));const liveParam=new URLSearchParams(location.search).get('live');if(liveParam)initViewer(liveParam);else{if(state.cloudDrawId)updateLiveLink();render();}
