(function(){
"use strict";
if(window.IMC_CLUBHOUSE_FEED)return;
const VERSION="2.8.0";
let loading=false,loadedRoot=null;
const c=v=>String(v==null?"":v).trim();
const e=v=>c(v).replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[x]));
const upper=v=>c(v).toLocaleUpperCase("it-IT");
const nk=v=>c(v).toLocaleLowerCase("it-IT").replace(/\s+/g," ");
const ICONS={
 trophy:'<path d="M8 4h8v4.5a4 4 0 0 1-8 0V4Z"/><path d="M8 6H5v1.5A3.5 3.5 0 0 0 8.5 11"/><path d="M16 6h3v1.5A3.5 3.5 0 0 1 15.5 11"/><path d="M12 12.5V17"/><path d="M9 20h6"/><path d="M10 17h4"/>',
 qualified:'<path d="M5 16.5 12 9l7 7.5"/><path d="M12 9v10"/><path d="M7 5h10"/>',
 eliminated:'<circle cx="12" cy="12" r="8"/><path d="m9 9 6 6M15 9l-6 6"/>',
 derby:'<path d="M4 5.5 9 4l2 3-2 8-5-3V5.5Z"/><path d="m20 5.5-5-1.5-2 3 2 8 5-3V5.5Z"/><path d="m10 11 4 2M14 11l-4 2"/>',
 final:'<path d="m5 9 2 8h10l2-8-4 3-3-6-3 6-4-3Z"/><path d="M7 20h10"/>',
 penalties:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 4v3M20 12h-3M12 20v-3M4 12h3"/>',
 "first-leg":'<rect x="5" y="5" width="14" height="14" rx="3"/><path d="M12 8v8M10 10l2-2"/>',
 "second-leg":'<rect x="5" y="5" width="14" height="14" rx="3"/><path d="M9.5 10a2.5 2.5 0 0 1 5 0c0 2-5 2.5-5 6h5"/>',
 group:'<circle cx="7" cy="7" r="2"/><circle cx="17" cy="7" r="2"/><circle cx="7" cy="17" r="2"/><circle cx="17" cy="17" r="2"/><path d="M9 7h6M7 9v6M17 9v6M9 17h6"/>',
 "manager-imc":'<path d="m12 3 7 4v6c0 4-3 6.5-7 8-4-1.5-7-4-7-8V7l7-4Z"/><circle cx="12" cy="10" r="2.2"/><path d="M8.5 16c.7-2 2-3 3.5-3s2.8 1 3.5 3"/>',
 "external-manager":'<circle cx="10" cy="8" r="3"/><path d="M4.5 18c.8-3.2 2.7-5 5.5-5s4.7 1.8 5.5 5"/><path d="M17 8h3M18.5 6.5V9.5"/>'
};
function icon(name,cls="ch-nexus-icon"){const body=ICONS[name]||ICONS.trophy;return `<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`}
function ensureImageStyles(){if(document.getElementById("chFeedGeneratedImageStyles"))return;const s=document.createElement("style");s.id="chFeedGeneratedImageStyles";s.textContent='.ch-feed-editorial-image{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;z-index:0}.ch-feed-visual.ch-feed-has-image:before{z-index:1;background:linear-gradient(180deg,rgba(8,43,99,.04) 15%,rgba(5,24,48,.82) 100%)}.ch-feed-visual.ch-feed-has-image .ch-feed-visual-glow{display:none}.ch-feed-visual.ch-feed-has-image .ch-feed-feature-logo{width:54px;height:54px;filter:drop-shadow(0 5px 9px rgba(0,0,0,.34))}.ch-feed-visual.ch-feed-has-image .ch-feed-visual-kicker{color:#fff;text-shadow:0 2px 6px rgba(0,0,0,.55)}.ch-feed-visual.ch-feed-has-image>strong,.ch-feed-visual.ch-feed-has-image>small{color:#fff;text-shadow:0 2px 5px rgba(0,0,0,.5)}';document.head.appendChild(s)}
ensureImageStyles();
function surname(v){const p=c(v).split(/\s+/).filter(Boolean);return upper(p[p.length-1]||v||"IMC")}
function dateLabel(v){const s=c(v);if(!s)return"";const d=new Date(s+"T12:00:00");if(isNaN(d))return s;return d.toLocaleDateString("it-IT",{day:"2-digit",month:"short",year:"numeric"}).toUpperCase()}
function competitionName(row){let s=c(row.source_competition_name)||"Coppa";const patterns=[/\s+Quarter Final Leg [12]$/i,/\s+Quarti di Finalee(?: Andata| Ritorno)?$/i,/\s+Turno\s+\d+\s+Leg\s+[12]$/i,/\s+Turno\s+\d+(?: Andata| Ritorno)?$/i,/\s+Semifinale$/i,/\s+Girone\s+[^ ]+$/i,/\s+(?:Finale|Final)$/i];for(const r of patterns)s=s.replace(r,"");return c(s)||c(row.source_competition_name)||"Coppa"}
function sideData(row,side){const other=side==="home"?"away":"home";return{side,other,team:c(row[side+"_team"]),otherTeam:c(row[other+"_team"]),score:Number(row[side+"_score"]),otherScore:Number(row[other+"_score"]),pens:Number(row[side+"_penalties"]),otherPens:Number(row[other+"_penalties"]),agg:c(row[side+"_aggregate_score"]),otherAgg:c(row[other+"_aggregate_score"]),managerName:c(row[side+"_imc_manager_name"]||row[side+"_manager_name"]),otherManagerName:c(row[other+"_imc_manager_name"]||row[other+"_manager_name"]),otherType:c(row[other+"_manager_type"])}}
function imcSides(row){const out=[];if(c(row.home_manager_type)==="IMC")out.push("home");if(c(row.away_manager_type)==="IMC")out.push("away");return out}
function resultWord(row,side){const winner=c(row.match_winner_side);if(winner==="draw")return"pareggia";return winner===side?"vince":"perde"}
function scoreText(row){const base=`${c(row.home_team)} ${c(row.home_score)}-${c(row.away_score)} ${c(row.away_team)}`;if(row.decided_on_penalties)return `${base} · rigori ${c(row.home_penalties)}-${c(row.away_penalties)}`;return base}
function opponentDescriptor(d){if(d.otherType==="IMC")return `${d.otherTeam}, guidato dal manager IMC ${d.otherManagerName}`;if(d.otherType==="External")return d.otherManagerName?`${d.otherTeam}, guidato dal manager External ${d.otherManagerName}`:`${d.otherTeam}, guidato da un manager External`;if(d.otherType==="Unmanaged")return `${d.otherTeam}, squadra senza manager`;return d.otherTeam}
function qualifiedSide(row){const q=nk(row.qualified_team);if(!q)return"";if(q===nk(row.home_team))return"home";if(q===nk(row.away_team))return"away";return""}
function isSemi(row){return /semifinale/i.test(c(row.sm_round_label))||/semifinale/i.test(c(row.source_competition_name))}
function oneImcStory(row,side){const d=sideData(row,side),phase=c(row.phase_type),name=surname(d.managerName),verb=resultWord(row,side),win=c(row.match_winner_side)===side,draw=c(row.match_winner_side)==="draw",opp=opponentDescriptor(d),comp=competitionName(row),pens=!!row.decided_on_penalties,qSide=qualifiedSide(row),qualified=qSide===side;let headline="",body="";if(phase==="group"){headline=win?`${name} FA LA VOCE GROSSA!`:draw?`${name}, UN PUNTO NEL GIRONE!`:`SERATA STORTA PER ${name}`;body=`${d.team} ${verb} ${d.score}-${d.otherScore} contro ${opp} nel girone di ${comp}.`}else if(phase==="first_leg"){headline=win?`${name} PARTE FORTE!`:draw?`TUTTO APERTO PER ${name}!`:`${name} CADE NELL'ANDATA`;body=`${d.team} ${verb} l'andata ${d.score}-${d.otherScore} contro ${opp}. La sfida resta aperta in vista del ritorno.`}else if(phase==="second_leg"){headline=qualified?`${name} AVANTI!`:`${name} ELIMINATO`;const agg=d.agg!==""&&d.otherAgg!==""?`${d.agg}-${d.otherAgg}`:"—";body=`${d.team} ${verb} il ritorno ${d.score}-${d.otherScore} contro ${opp}. ${agg} il risultato complessivo: ${qualified?"qualificazione conquistata":"eliminazione dalla competizione"}.`}else if(phase==="final"){headline=win?`${name} È CAMPIONE!`:`FINALE AMARA PER ${name}`;body=pens?`Dopo il ${d.score}-${d.otherScore}, ${d.team} ${win?"vince":"perde"} ${d.pens}-${d.otherPens} ai rigori contro ${opp}. ${win?`Il trofeo di ${comp} è suo.`:`Il trofeo di ${comp} sfuma all'ultimo atto.`}`:`${d.team} ${verb} ${d.score}-${d.otherScore} contro ${opp} nella finale di ${comp}. ${win?"Trofeo conquistato.":"Il sogno si ferma all'ultimo atto."}`}else{headline=win?`${name} NON SI FERMA!`:`${name} FUORI DALLA COPPA`;const outcome=win?(isSemi(row)?"Finale conquistata.":"Passaggio al turno successivo conquistato."):"Eliminazione dalla competizione.";body=pens?`Dopo il ${d.score}-${d.otherScore}, ${d.team} ${win?"vince":"perde"} ${d.pens}-${d.otherPens} ai rigori contro ${opp}. ${outcome}`:`${d.team} ${verb} ${d.score}-${d.otherScore} contro ${opp}. ${outcome}`}return{headline,body,score:scoreText(row),opponentType:d.otherType}}
function twoImcStory(row){const phase=c(row.phase_type),winner=c(row.match_winner_side),q=qualifiedSide(row),home=sideData(row,"home"),away=sideData(row,"away"),comp=competitionName(row);let headline="",body="";if(phase==="group"){if(winner==="draw"){headline="DERBY IMC, EQUILIBRIO TOTALE!";body=`${home.team} e ${away.team} chiudono ${home.score}-${away.score}: un punto a testa per ${home.managerName} e ${away.managerName} nel girone di ${comp}.`}else{const w=winner==="home"?home:away,l=winner==="home"?away:home;headline=`IL DERBY È DI ${surname(w.managerName)}!`;body=`${w.team} supera ${l.team} ${w.score}-${w.otherScore}: ${w.managerName} vince il derby IMC contro ${l.managerName}.`}}else if(phase==="first_leg"){if(winner==="draw"){headline="DERBY IMC, TUTTO APERTO!";body=`${home.team}-${away.team} finisce ${home.score}-${away.score}: ${home.managerName} e ${away.managerName} rimandano ogni verdetto al ritorno.`}else{const w=winner==="home"?home:away,l=winner==="home"?away:home;headline=`PRIMO SANGUE: ${surname(w.managerName)} VINCE L'ANDATA!`;body=`${w.team} vince l'andata ${w.score}-${w.otherScore} contro ${l.team}: vantaggio per ${w.managerName}, ma il derby resta aperto.`}}else if(phase==="second_leg"){const qual=q==="home"?home:q==="away"?away:null,elim=q==="home"?away:q==="away"?home:null,matchSentence=winner==="draw"?`Il ritorno termina ${home.score}-${away.score}.`:`${winner==="home"?home.managerName:away.managerName} vince il ritorno ${home.score}-${away.score}.`,agg=home.agg!==""&&away.agg!==""?`${home.agg}-${away.agg}`:"—";headline=qual?`GAME OVER: PASSA ${surname(qual.managerName)}!`:"DERBY IMC, VERDETTO AL RITORNO!";body=qual&&elim?`${matchSentence} ${agg} il risultato complessivo: ${qual.managerName} conquista la qualificazione, ${elim.managerName} viene eliminato.`:`${matchSentence} Risultato complessivo ${agg}.`}else if(phase==="final"){const w=winner==="home"?home:winner==="away"?away:null,l=winner==="home"?away:winner==="away"?home:null;headline=w?`DERBY IMC, IL TROFEO È DI ${surname(w.managerName)}!`:"DERBY IMC, FINALE IN EQUILIBRIO!";body=w&&l?`${w.team} supera ${l.team} ${w.score}-${w.otherScore}${row.decided_on_penalties?` (${w.pens}-${w.otherPens} ai rigori)`:""}: ${w.managerName} conquista ${comp}, ${l.managerName} perde la finale.`:scoreText(row)}else{const w=winner==="home"?home:winner==="away"?away:null,l=winner==="home"?away:winner==="away"?home:null;if(w&&l){headline=`${surname(w.managerName)} FA FUORI ${surname(l.managerName)}!`;body=`${w.team} supera ${l.team} ${w.score}-${w.otherScore}${row.decided_on_penalties?` (${w.pens}-${w.otherPens} ai rigori)`:""}: ${w.managerName} ${isSemi(row)?"conquista la finale":"passa al turno successivo"}, ${l.managerName} saluta la competizione.`}else{headline="DERBY IMC, PARITÀ!";body=scoreText(row)}}return{headline,body,score:scoreText(row),opponentType:"IMC"}}
function story(row){const sides=imcSides(row);return sides.length>1?twoImcStory(row):oneImcStory(row,sides[0])}
function phaseLabel(v){return({group:"GIRONE",first_leg:"ANDATA",second_leg:"RITORNO",single_leg:"PARTITA SECCA",final:"FINALE"})[c(v)]||upper(v)}
function roundLabel(row){return upper(c(row.sm_round_label)||phaseLabel(row.phase_type))}
function phaseIcon(v){return({group:"group",first_leg:"first-leg",second_leg:"second-leg",final:"final"})[c(v)]||"trophy"}
function logoPath(v){const p=c(v);if(!p)return"";return p.startsWith("/")||/^https?:\/\//i.test(p)?p:`/nexus/${p.replace(/^\.\//,"")}`}
function teamLogo(logoMaps,row,side){const world=logoMaps.get(c(row.game_world_id));if(!world)return"";const byName=world.byName,byWorld=world.byWorld;const id=c(row[side+"_sm_club_id"]||row[side+"_sm_world_club_id"]);const name=nk(row[side+"_team"]);const t=(id&&byWorld.get(id))||byName.get(name);return logoPath(t&&t.logo_file)}
function initials(name){const p=c(name).split(/\s+/).filter(Boolean);return upper((p[0]?.[0]||"")+(p[1]?.[0]||p[0]?.[1]||""))||"IMC"}
function logoMarkup(src,name,cls){return src?`<img class="${cls}" src="${e(src)}" alt="${e(name)}">`:`<span class="${cls} ch-feed-logo-fallback">${e(initials(name))}</span>`}
function featuredSide(row){const sides=imcSides(row),q=qualifiedSide(row),winner=c(row.match_winner_side);if(sides.length===1)return sides[0];if(q&&sides.includes(q))return q;if(winner!=="draw"&&sides.includes(winner))return winner;return sides[0]||"home"}
function aggregateText(row){const h=c(row.home_aggregate_score),a=c(row.away_aggregate_score);return h!==""&&a!==""?`AGG. ${h}-${a}`:""}
function statusData(row){const sides=imcSides(row),phase=c(row.phase_type),q=qualifiedSide(row),winner=c(row.match_winner_side);if(sides.length>1)return{label:"DERBY IMC",tone:"blue",icon:"derby"};const side=sides[0]||"home",win=winner===side,qualified=q===side;if(phase==="final")return win?{label:"CAMPIONE",tone:"green",icon:"final"}:{label:"FINALISTA",tone:"red",icon:"final"};if(phase==="second_leg")return qualified?{label:"QUALIFICATO",tone:"green",icon:"qualified"}:{label:"ELIMINATO",tone:"red",icon:"eliminated"};if(phase==="single_leg")return win?{label:"QUALIFICATO",tone:"green",icon:"qualified"}:{label:"ELIMINATO",tone:"red",icon:"eliminated"};if(phase==="first_leg")return{label:"ANDATA",tone:"blue",icon:"first-leg"};if(phase==="group")return{label:"GIRONE",tone:"blue",icon:"group"};return{label:phaseLabel(phase),tone:"blue",icon:phaseIcon(phase)}}
function visualLabel(row){const side=featuredSide(row),name=c(row[side+"_imc_manager_name"]||row[side+"_manager_name"]);return name?surname(name):c(row.game_world_id)}
function headlineIcon(row,status,headline){if(imcSides(row).length>1)return"derby";const h=upper(headline);if(h.includes("CAMPIONE")||h.includes("TROFEO"))return"final";if(h.includes("ELIMINATO")||h.includes("FUORI DALLA COPPA")||h.includes("FINALE AMARA"))return"eliminated";if(row.decided_on_penalties)return"penalties";return status.icon||"trophy"}
function opponentIcon(type){if(type==="IMC")return"manager-imc";if(type==="External")return"external-manager";return""}
function derbyHero(row,homeLogo,awayLogo,media){const homeName=c(row.home_imc_manager_name||row.home_manager_name),awayName=c(row.away_imc_manager_name||row.away_manager_name);return `<div class="ch-feed-visual ch-feed-visual-derby${c(row.feed_image_url)?" ch-feed-has-image":""}">${media}<div class="ch-feed-derby-duel"><div class="ch-feed-derby-side ch-feed-derby-home">${logoMarkup(homeLogo,row.home_team,"ch-feed-derby-logo")}<span>${e(surname(homeName))}</span></div><b class="ch-feed-derby-vs">VS</b><div class="ch-feed-derby-side ch-feed-derby-away">${logoMarkup(awayLogo,row.away_team,"ch-feed-derby-logo")}<span>${e(surname(awayName))}</span></div></div><strong>${e(c(row.game_world_id))}</strong><small>${e(row.competition_type==="International"?"COPPA INTERNAZIONALE":"COPPA DOMESTICA")}</small></div>`}
function standardHero(row,featureLogo,featureTeam,media){return `<div class="ch-feed-visual${c(row.feed_image_url)?" ch-feed-has-image":""}">${media}${logoMarkup(featureLogo,featureTeam,"ch-feed-feature-logo")}<span class="ch-feed-visual-kicker">${e(visualLabel(row))}</span><strong>${e(c(row.game_world_id))}</strong><small>${e(row.competition_type==="International"?"COPPA INTERNAZIONALE":"COPPA DOMESTICA")}</small></div>`}
function article(row,logoMaps){const s=story(row),comp=competitionName(row),homeLogo=teamLogo(logoMaps,row,"home"),awayLogo=teamLogo(logoMaps,row,"away"),feature=featuredSide(row),featureLogo=feature==="home"?homeLogo:awayLogo,featureTeam=c(row[feature+"_team"]),agg=aggregateText(row),status=statusData(row),editorial=c(row.feed_image_url),oppIcon=opponentIcon(s.opponentType),derby=imcSides(row).length>1,pen=row.decided_on_penalties?`<small class="ch-feed-pen">${icon("penalties","ch-nexus-icon ch-nexus-icon-inline")}RIGORI ${e(row.home_penalties)}-${e(row.away_penalties)}</small>`:"",media=editorial?`<img class="ch-feed-editorial-image" src="${e(editorial)}" alt="" loading="lazy">`:`<div class="ch-feed-visual-glow"></div>`,hero=derby?derbyHero(row,homeLogo,awayLogo,media):standardHero(row,featureLogo,featureTeam,media);return `<article class="ch-feed-card${derby?" ch-feed-card-derby":""}" data-feed-status="${e(status.tone)}" data-fixture-id="${e(row.sm_fixture_id)}" data-game-world="${e(row.game_world_id)}">${hero}<div class="ch-feed-copy"><div class="ch-feed-copy-meta"><span>${icon("trophy","ch-nexus-icon ch-nexus-icon-meta ch-nexus-icon-gold")}${e(comp)}</span><span>${icon(phaseIcon(row.phase_type),"ch-nexus-icon ch-nexus-icon-meta")}${e(roundLabel(row))}</span><span>${e(dateLabel(row.match_date))}</span></div><h3>${icon(headlineIcon(row,status,s.headline),"ch-nexus-icon ch-nexus-icon-headline")}${e(s.headline)}</h3><p>${e(s.body)}</p><div class="ch-feed-copy-foot"><span>${e(c(row.game_world_id))}</span><span>${oppIcon?icon(oppIcon,"ch-nexus-icon ch-nexus-icon-inline"):""}AVVERSARIO ${e(s.opponentType==="Unmanaged"?"SENZA MANAGER":upper(s.opponentType))}</span></div></div><div class="ch-feed-scorebox"><div class="ch-feed-score-teams"><div>${logoMarkup(homeLogo,row.home_team,"ch-feed-score-logo")}<small>${e(row.home_team)}</small></div><strong>${e(row.home_score)}<i>-</i>${e(row.away_score)}</strong><div>${logoMarkup(awayLogo,row.away_team,"ch-feed-score-logo")}<small>${e(row.away_team)}</small></div></div>${pen}${agg?`<b class="ch-feed-agg">${e(agg)}</b>`:""}<span class="ch-feed-status ch-feed-status-${e(status.tone)}">${icon(status.icon,"ch-nexus-icon ch-nexus-icon-status")}${e(status.label)}</span></div></article>`}
function panel(root){const canvas=root.querySelector(".ch-clubhouse-canvas");if(!canvas)return null;let p=canvas.querySelector("[data-ch-feed-panel]");if(p)return p;p=document.createElement("section");p.className="ch-feed-panel";p.setAttribute("data-ch-feed-panel","");p.hidden=true;p.innerHTML=`<button type="button" class="ch-feed-back" data-ch-feed-home>← HOME</button><div class="ch-feed-head"><div><span>IMC NEXUS</span><h2>FEED <b>${icon("trophy","ch-nexus-icon ch-nexus-icon-title ch-nexus-icon-gold")}LE COPPE</b></h2><small>Le notti di Coppa dei manager IMC</small></div><div class="ch-feed-live"><i></i><span>LIVE FEED</span></div></div><div class="ch-feed-list" data-ch-feed-list><div class="ch-feed-loading">Caricamento news…</div></div>`;const nav=canvas.querySelector(".ch-bottom-nav"),group=canvas.querySelector("[data-ch-world-group]"),competition=canvas.querySelector(".ch-competition"),anchor=group||competition;if(anchor)anchor.insertAdjacentElement("afterend",p);else canvas.insertBefore(p,nav||null);return p}
function setActive(root,label){for(const b of root.querySelectorAll(".ch-bottom-nav button"))b.classList.toggle("active",upper(b.textContent)===label)}
function showClubhouse(root){const canvas=root.querySelector(".ch-clubhouse-canvas"),p=panel(root);if(!canvas||!p)return null;for(const child of [...canvas.children]){if(child===p||child.classList.contains("ch-bottom-nav"))continue;if(!child.hidden){child.hidden=true;child.setAttribute("data-ch-feed-hidden","")}}const welcome=root.querySelector(".ch-home-welcome");if(welcome)welcome.hidden=true;const nav=canvas.querySelector(".ch-bottom-nav");if(nav)nav.hidden=true;const subtitle=root.querySelector(".ch-hero-subtitle span");if(subtitle)subtitle.textContent="CLUB HOUSE";root.classList.add("ch-clubhouse-feed-view");p.hidden=false;return p}
function showHome(root){const canvas=root.querySelector(".ch-clubhouse-canvas"),p=panel(root);if(!canvas||!p)return;for(const child of canvas.querySelectorAll("[data-ch-feed-hidden]")){child.hidden=false;child.removeAttribute("data-ch-feed-hidden")}const welcome=root.querySelector(".ch-home-welcome");if(welcome)welcome.hidden=false;const nav=canvas.querySelector(".ch-bottom-nav");if(nav)nav.hidden=false;p.hidden=true;const subtitle=root.querySelector(".ch-hero-subtitle span");if(subtitle)subtitle.textContent="HOME";root.classList.remove("ch-clubhouse-feed-view");setActive(root,"HOME")}
async function loadLogoMaps(client,rows){const ids=[...new Set((rows||[]).map(x=>c(x.game_world_id)).filter(Boolean))],maps=new Map();await Promise.all(ids.map(async id=>{try{const r=await client.rpc("imc_nexus_gateway",{p_action:"gw_teams",p_args:{gameWorld:id}});if(r.error)throw r.error;const byName=new Map(),byWorld=new Map();for(const t of Array.isArray(r.data&&r.data.rows)?r.data.rows:[]){for(const name of [t.club_name,t.display_name])if(c(name))byName.set(nk(name),t);for(const raw of [t.sm_world_club_id,t.sm_club_id])if(c(raw))byWorld.set(c(raw),t)}maps.set(id,{byName,byWorld})}catch(_){maps.set(id,{byName:new Map(),byWorld:new Map()})}}));return maps}
async function load(root){if(loading||loadedRoot===root)return;const p=panel(root),list=p&&p.querySelector("[data-ch-feed-list]"),client=window.__IMC_NEXUS_CLIENT__;if(!list||!client)return;loading=true;list.innerHTML='<div class="ch-feed-loading">Caricamento news…</div>';try{const r=await client.rpc("imc_nexus_gateway",{p_action:"club_house_feed",p_args:{}});if(r.error)throw r.error;const rows=Array.isArray(r.data&&r.data.rows)?r.data.rows:[],logoMaps=await loadLogoMaps(client,rows);list.innerHTML=rows.length?rows.map(row=>article(row,logoMaps)).join(""):'<div class="ch-feed-empty">Nessuna news di Coppa disponibile.</div>';loadedRoot=root}catch(err){list.innerHTML=`<div class="ch-feed-empty">${e(err.message||"Feed non disponibile")}</div>`}finally{loading=false}}
function ensureInline(){const root=document.querySelector(".clubhouse");if(!root)return;const p=panel(root);if(!p)return;load(root)}
document.addEventListener("click",evt=>{const home=evt.target.closest&&evt.target.closest("[data-ch-feed-home]");if(home){document.dispatchEvent(new CustomEvent("nexus:navigate",{detail:{target:"clubhouse"}}));return}const b=evt.target.closest&&evt.target.closest(".clubhouse .ch-bottom-nav button");if(!b)return;const root=b.closest(".clubhouse"),label=upper(b.textContent);if(label==="FEED"){const p=showClubhouse(root);load(root);setActive(root,"FEED");if(p)p.scrollIntoView({behavior:"smooth",block:"start"})}else if(label==="HOME")showHome(root)});
new MutationObserver(()=>ensureInline()).observe(document.documentElement,{childList:true,subtree:true});
let bootTries=0;const boot=setInterval(()=>{bootTries++;ensureInline();const root=document.querySelector(".clubhouse");if((root&&loadedRoot===root)||bootTries>80)clearInterval(boot)},250);
window.IMC_CLUBHOUSE_FEED={version:VERSION,show:()=>{const root=document.querySelector(".clubhouse");if(root){showClubhouse(root);load(root)}},home:()=>{const root=document.querySelector(".clubhouse");if(root)showHome(root)}};
})();