(function(){
"use strict";
if(window.IMC_MANAGER_DETAIL)return;
const VERSION="2.0.0";
let s={container:null,client:null,worldId:"",managerId:"",smManagerId:null,name:"",tab:"results",manager:null};
const c=v=>String(v==null?"":v).trim();
const e=v=>c(v).replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[x]));
async function gateway(action,args){const r=await s.client.rpc("imc_nexus_gateway",{p_action:action,p_args:args});if(r.error)throw r.error;return r.data||{}}
async function loadManager(){const data=await gateway("managers",{gameWorld:s.worldId});const rows=Array.isArray(data.rows)?data.rows:[];s.manager=rows.find(x=>c(x.manager_id)===s.managerId)||null;if(s.manager){s.name=c(s.manager.full_name)||s.name||s.managerId;s.smManagerId=s.manager.sm_manager_id||s.smManagerId||null}}
function render(){if(!s.container)return;const sm=c(s.smManagerId);s.container.innerHTML=`<section class="md" data-manager-detail-version="${VERSION}"><header class="md-identity"><span>${e(s.worldId)}</span><h2>${e(s.name||s.managerId)}</h2><div class="md-ids"><small>${e(s.managerId)}</small>${sm?`<small>SM ${e(sm)}</small>`:""}</div></header><nav class="md-tabs" aria-label="Manager Detail"><button type="button" data-md-tab="results" class="${s.tab==="results"?"active":""}">RESULTS</button><button type="button" data-md-tab="stats" class="${s.tab==="stats"?"active":""}">STATS</button><button type="button" data-md-tab="h2h" class="${s.tab==="h2h"?"active":""}">H2H</button><button type="button" data-md-tab="timeline" class="${s.tab==="timeline"?"active":""}">MANAGER TIMELINE</button><button type="button" data-md-tab="trophies" class="${s.tab==="trophies"?"active":""}">TROPHY ROOM</button></nav><div class="md-content" data-md-content></div></section>`}
function unmountChild(){["IMC_RESULTS","IMC_STATS","IMC_H2H","IMC_MANAGER_TIMELINE","IMC_TROPHY_ROOM"].forEach(k=>{if(window[k]&&window[k].unmount)window[k].unmount()})}
async function openTab(tab){s.tab=tab;render();const host=s.container&&s.container.querySelector("[data-md-content]");if(!host)return;unmountChild();if(tab==="results"){await window.IMC_RESULTS.mount({container:host,client:s.client,worldId:s.worldId,managerSmId:s.smManagerId});return}if(tab==="stats"){await window.IMC_STATS.mount({container:host,client:s.client,worldId:s.worldId,managerSmId:s.smManagerId});return}if(tab==="h2h"){await window.IMC_H2H.mount({container:host,client:s.client,worldId:s.worldId,managerSmId:s.smManagerId});return}if(tab==="timeline"){await window.IMC_MANAGER_TIMELINE.mount({container:host,client:s.client,worldId:s.worldId,managerId:s.managerId});return}if(tab==="trophies"){await window.IMC_TROPHY_ROOM.mount({container:host,client:s.client,worldId:s.worldId,managerId:s.managerId})}}
async function mount(o){if(!o||!o.container||!o.client||!o.worldId||!o.managerId)throw Error("Manager Detail: parametri mancanti");s={...s,...o,container:o.container,client:o.client,worldId:c(o.worldId),managerId:c(o.managerId),smManagerId:o.smManagerId||null,name:c(o.name),tab:"results",manager:null};s.container.innerHTML='<div class="md-loading">Caricamento Manager…</div>';await loadManager();render();await openTab("results")}
function unmount(){unmountChild();if(s.container)s.container.innerHTML="";s.container=null}
document.addEventListener("click",ev=>{const b=ev.target.closest&&ev.target.closest("[data-md-tab]");if(b&&s.container&&s.container.contains(b)){const tab=c(b.getAttribute("data-md-tab"));openTab(tab).catch(err=>{const host=s.container&&s.container.querySelector("[data-md-content]");if(host)host.innerHTML=`<div class="md-empty">${e(err.message||err)}</div>`})}});
window.IMC_MANAGER_DETAIL={version:VERSION,mount,unmount};
})();