<?php
declare(strict_types=1);
const IMC_VERSION='2.1.0'; const IMC_MAX_ROWS=1000;
$GLOBALS['imc_started']=microtime(true);
function imc_out(array $x,int $s=200):never{http_response_code($s);$x['duration_ms']??=(int)round((microtime(true)-$GLOBALS['imc_started'])*1000);echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE);exit;}
function imc_ident(string $x):string{if(!preg_match('/^[A-Za-z_][A-Za-z0-9_]{0,63}$/',$x))throw new InvalidArgumentException('invalid_identifier');return'`'.$x.'`';}
function imc_cfg():array{$f=dirname(__DIR__).'/__imc_private_gateway/config.php';if(!is_file($f))throw new RuntimeException('gateway_configuration_not_found');return require$f;}
function imc_route(array$b,array$c):array{$g=strtoupper(trim((string)($b['game_world_id']??'')));if(strtolower((string)($b['source']??''))==='core'||$g==='CORE')return['source'=>'core','game_world_id'=>null,'database'=>$c['db']['core'],'family'=>'CORE'];if(!preg_match('/^GW00[1-9]$/',$g))throw new InvalidArgumentException('invalid_game_world');if(in_array($g,$c['gold_worlds'],true))return['source'=>'game_world','game_world_id'=>$g,'database'=>$c['db']['gold'],'family'=>'MULTI_LEAGUE'];if(in_array($g,$c['custom_worlds'],true))return['source'=>'game_world','game_world_id'=>$g,'database'=>$c['db']['custom'],'family'=>'SINGLE_LEAGUE'];throw new InvalidArgumentException('unsupported_game_world');}
function imc_db(array$c,string$d):PDO{return new PDO(sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4',$c['db']['host'],$c['db']['port'],$d),$c['db']['user'],$c['db']['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);}
function imc_table(array$b,array$r):?string{$t=trim((string)($b['table']??''));if($t!==''){imc_ident($t);return$t;}$q=trim((string)($b['repository']??''));if($q==='')return null;imc_ident($q);return$r['game_world_id']?$r['game_world_id'].'_'.$q:$q;}
function imc_exists(PDO$p,string$d,string$t):bool{$s=$p->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=? AND table_name=?');$s->execute([$d,$t]);return(int)$s->fetchColumn()>0;}
function imc_cols(PDO$p,string$t):array{$a=[];foreach($p->query('SHOW FULL COLUMNS FROM '.imc_ident($t)) as$r)$a[$r['Field']]=$r;return$a;}
function imc_where(array$w,array&$v):string{if(!$w)throw new InvalidArgumentException('where_required');$a=[];foreach($w as$k=>$x){imc_ident((string)$k);if($x===null)$a[]=imc_ident((string)$k).' IS NULL';else{$a[]=imc_ident((string)$k).'=?';$v[]=$x;}}return implode(' AND ',$a);}
function imc_count(PDO$p,string$t,array$w=[]):int{$v=[];$q='SELECT COUNT(*) FROM '.imc_ident($t).($w?' WHERE '.imc_where($w,$v):'');$s=$p->prepare($q);$s->execute($v);return(int)$s->fetchColumn();}
function imc_row(PDO$p,string$t,array$r):array{$c=imc_cols($p,$t);foreach($r as$k=>$v){if(!isset($c[$k]))throw new InvalidArgumentException('column_not_found:'.$k);if(str_starts_with(strtolower((string)$c[$k]['Type']),'json')){if(is_array($v))$r[$k]=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);elseif(is_string($v)&&json_decode($v,true)===null&&strtolower($v)!=='null')throw new InvalidArgumentException('invalid_json');}}return$r;}
function imc_type(string$x):string{$x=strtoupper(trim($x));if(!preg_match('/^(TINYINT|SMALLINT|MEDIUMINT|INT|BIGINT|FLOAT|DOUBLE|DECIMAL\([0-9]+,[0-9]+\)|CHAR\([0-9]+\)|VARCHAR\([0-9]+\)|TEXT|MEDIUMTEXT|LONGTEXT|DATE|DATETIME|TIMESTAMP|TIME|JSON|BOOLEAN)( UNSIGNED)?$/',$x))throw new InvalidArgumentException('invalid_column_type');return$x;}
function imc_peer():array{$f=dirname(__DIR__).'/imc-database-manager/index.php';if(!is_file($f))return['reachable'=>false,'status'=>'unavailable'];$j=json_decode((string)@file_get_contents($f),true);return is_array($j)?['reachable'=>true,'service'=>$j['service']??null,'status'=>$j['status']??null,'version'=>$j['version']??null,'role_version'=>$j['role_version']??null,'current_role'=>$j['current_role']??null,'capabilities'=>$j['capabilities']??[]]:['reachable'=>false,'status'=>'invalid_response'];}
function imc_log(array$r,string$a,?string$t,array$e=[]):void{$f=dirname(__DIR__).'/__imc_private_gateway/universal-gateway-audit.jsonl';@file_put_contents($f,json_encode(array_merge(['timestamp'=>gmdate('c'),'action'=>$a,'source'=>$r['source']??null,'game_world_id'=>$r['game_world_id']??null,'database'=>$r['database']??null,'table'=>$t],$e),JSON_UNESCAPED_SLASHES)."\n",FILE_APPEND|LOCK_EX);}
function imc_actions():array{return['health','probe','resolve_database','resolve_table','show_tables','read','read_one','sample','count','count_nulls','distinct','aggregate','show_columns','describe','schema','indexes','show_create_table','query','create_table','drop_table','rename_table','add_column','drop_column','rename_column','modify_column','add_index','drop_index','add_primary_key','drop_primary_key','insert','insert_many','upsert','upsert_many','update','delete_one','delete','clear_repository','clear_table','clone_table_structure','copy_rows','truncate_table','dry_run','validate','audit_repository','find_duplicates','foreign_keys','add_foreign_key','drop_foreign_key','table_status'];}
function imc_run():never{try{$c=imc_cfg();if(($_SERVER['REQUEST_METHOD']??'')!=='POST')imc_out(['ok'=>false,'error'=>'method_not_allowed'],405);$tok=(string)($_SERVER['HTTP_X_IMC_UNIVERSAL_TOKEN']??'');if($tok===''||!hash_equals((string)$c['token'],$tok))imc_out(['ok'=>false,'error'=>'unauthorized'],401);$b=json_decode(file_get_contents('php://input')?:'',true,64,JSON_THROW_ON_ERROR);if(!is_array($b))throw new InvalidArgumentException('invalid_payload');$a=strtolower(trim((string)($b['action']??'health')));$ch=strtoupper((string)($b['channel']??($_SERVER['HTTP_X_IMC_CHANNEL']??'CHATGPT')));if(!in_array($ch,['IMPORT','CHATGPT'],true))throw new InvalidArgumentException('invalid_channel');if($a==='health')imc_out(['ok'=>true,'action'=>'health','service'=>'IMC Universal Gateway','version'=>IMC_VERSION,'channels'=>['IMPORT','CHATGPT'],'capability_families'=>['ROUTING','READ','SCHEMA','QUERY','WRITE','DELETE','DDL','TRANSACTIONS','VALIDATION','AUDIT','LOG','RESPONSE'],'actions'=>imc_actions(),'database_manager'=>imc_peer()]);if(!in_array($a,imc_actions(),true))throw new InvalidArgumentException('unknown_action');$r=imc_route($b,$c);$t=imc_table($b,$r);if($a==='resolve_database')imc_out(['ok'=>true,'action'=>$a]+$r);if($a==='resolve_table')imc_out(['ok'=>true,'action'=>$a,'table'=>$t]+$r);$p=imc_db($c,$r['database']);$base=['ok'=>true,'action'=>$a,'channel'=>$ch,'source'=>$r['source'],'game_world_id'=>$r['game_world_id'],'database'=>$r['database'],'repository'=>$b['repository']??null,'table'=>$t];if($a==='probe')imc_out($base+['database_connection'=>(int)$p->query('SELECT 1')->fetchColumn()===1?'ok':'failed']);if(imc_read_action($a,$b,$r,$t,$p,$base))exit;if(imc_write_action($a,$b,$r,$t,$p,$base))exit;if(imc_ddl_action($a,$b,$r,$t,$p,$base))exit;throw new InvalidArgumentException('unknown_action');}catch(Throwable$e){$m=$e->getMessage();$known=['invalid_identifier','invalid_game_world','unsupported_game_world','table_required','table_not_found','column_not_found','column_already_exists','index_not_found','duplicate_entry','foreign_key_constraint','multiple_rows_matched','invalid_payload','required_field_missing','invalid_json','where_required','unknown_action','invalid_column_type'];$err='gateway_error';foreach($known as$k)if(str_starts_with($m,$k)){$err=$k;break;}imc_out(['ok'=>false,'error'=>$err,'message'=>$m],$e instanceof InvalidArgumentException?422:500);}}
