<?php
declare(strict_types=1);
function imc_ddl_action(string$a,array$b,array$r,?string$t,PDO$p,array$B):bool{
if($a==='create_table'){$t=(string)($b['table_name']??$t??'');imc_ident($t);if(imc_exists($p,$r['database'],$t))throw new RuntimeException('table_already_exists');$cc=$b['columns']??[];if(!is_array($cc)||!$cc)throw new InvalidArgumentException('required_field_missing');$defs=[];foreach($cc as$c){$n=(string)($c['name']??'');$d=imc_ident($n).' '.imc_type((string)($c['type']??''));$d.=($c['nullable']??true)?' NULL':' NOT NULL';if(array_key_exists('default',$c))$d.=$c['default']===null?' DEFAULT NULL':' DEFAULT '.$p->quote((string)$c['default']);if(!empty($c['auto_increment']))$d.=' AUTO_INCREMENT';$defs[]=$d;}$pk=$b['primary_key']??[];if($pk)$defs[]='PRIMARY KEY ('.implode(',',array_map(fn($x)=>imc_ident((string)$x),$pk)).')';foreach($b['unique_keys']??[] as$u)$defs[]='UNIQUE KEY '.imc_ident((string)$u['name']).' ('.implode(',',array_map(fn($x)=>imc_ident((string)$x),$u['columns'])).')';$engine=strtoupper((string)($b['engine']??'INNODB'));if(!in_array($engine,['INNODB'],true))throw new InvalidArgumentException('invalid_payload');$p->exec('CREATE TABLE '.imc_ident($t).' ('.implode(',',$defs).') ENGINE='.$engine.' DEFAULT CHARSET=utf8mb4');imc_log($r,$a,$t,['after_exists'=>true]);imc_out($B+['table'=>$t,'created'=>true,'after_exists'=>imc_exists($p,$r['database'],$t)]);}
if(!$t)return false;$E=imc_exists($p,$r['database'],$t);
if($a==='drop_table'){$before=$E;$cnt=$E?imc_count($p,$t):0;if($E)$p->exec('DROP TABLE '.imc_ident($t));imc_log($r,$a,$t,['before_count'=>$cnt,'after_exists'=>false]);imc_out($B+['before_exists'=>$before,'before_count'=>$cnt,'dropped'=>$before,'after_exists'=>imc_exists($p,$r['database'],$t)]);}
if($a==='rename_table'){$new=(string)($b['new_name']??'');imc_ident($new);if(!$E)throw new RuntimeException('table_not_found');if(imc_exists($p,$r['database'],$new))throw new RuntimeException('table_already_exists');$p->exec('RENAME TABLE '.imc_ident($t).' TO '.imc_ident($new));imc_out($B+['old_name'=>$t,'new_name'=>$new,'renamed'=>imc_exists($p,$r['database'],$new)]);}
if($a==='clone_table_structure'){$src=(string)($b['source_table']??$t);$dst=(string)($b['destination_table']??'');imc_ident($src);imc_ident($dst);$p->exec('CREATE TABLE '.imc_ident($dst).' LIKE '.imc_ident($src));imc_out($B+['source_table'=>$src,'destination_table'=>$dst,'created'=>imc_exists($p,$r['database'],$dst)]);}
if(!$E)throw new RuntimeException('table_not_found');$backup=$p->query('SHOW CREATE TABLE '.imc_ident($t))->fetch()['Create Table']??null;
if($a==='add_column'){$n=(string)($b['column_name']??'');if(isset(imc_cols($p,$t)[$n]))throw new RuntimeException('column_already_exists');$q='ALTER TABLE '.imc_ident($t).' ADD COLUMN '.imc_ident($n).' '.imc_type((string)($b['column_type']??''));$q.=($b['nullable']??true)?' NULL':' NOT NULL';if(array_key_exists('default',$b))$q.=$b['default']===null?' DEFAULT NULL':' DEFAULT '.$p->quote((string)$b['default']);if(($b['position']??'')==='FIRST')$q.=' FIRST';elseif(!empty($b['after']))$q.=' AFTER '.imc_ident((string)$b['after']);$p->exec($q);imc_out($B+['column'=>$n,'created'=>isset(imc_cols($p,$t)[$n]),'backup_ddl'=>$backup]);}
if($a==='drop_column'){$n=(string)($b['column_name']??'');if(!isset(imc_cols($p,$t)[$n]))throw new RuntimeException('column_not_found');$ix=$p->query('SHOW INDEX FROM '.imc_ident($t))->fetchAll();$deps=array_values(array_filter($ix,fn($x)=>$x['Column_name']===$n));$p->exec('ALTER TABLE '.imc_ident($t).' DROP COLUMN '.imc_ident($n));imc_out($B+['column'=>$n,'dependencies'=>$deps,'dropped'=>!isset(imc_cols($p,$t)[$n]),'backup_ddl'=>$backup]);}
if($a==='rename_column'){$old=(string)($b['old_name']??'');$new=(string)($b['new_name']??'');imc_ident($old);imc_ident($new);$p->exec('ALTER TABLE '.imc_ident($t).' RENAME COLUMN '.imc_ident($old).' TO '.imc_ident($new));$c=imc_cols($p,$t);imc_out($B+['old_name'=>$old,'new_name'=>$new,'renamed'=>isset($c[$new])&&!isset($c[$old]),'backup_ddl'=>$backup]);}
if($a==='modify_column'){$n=(string)($b['column_name']??'');$cur=imc_cols($p,$t)[$n]??null;if(!$cur)throw new RuntimeException('column_not_found');$type=isset($b['column_type'])?imc_type((string)$b['column_type']):strtoupper((string)$cur['Type']);$nullable=array_key_exists('nullable',$b)?(bool)$b['nullable']:$cur['Null']==='YES';$q='ALTER TABLE '.imc_ident($t).' MODIFY COLUMN '.imc_ident($n).' '.$type.($nullable?' NULL':' NOT NULL');if(array_key_exists('default',$b))$q.=$b['default']===null?' DEFAULT NULL':' DEFAULT '.$p->quote((string)$b['default']);if(($b['position']??'')==='FIRST')$q.=' FIRST';elseif(!empty($b['after']))$q.=' AFTER '.imc_ident((string)$b['after']);$p->exec($q);imc_out($B+['column'=>$n,'definition'=>imc_cols($p,$t)[$n]??null,'backup_ddl'=>$backup]);}
if($a==='add_index'){$n=(string)($b['index_name']??'');$cc=$b['columns']??[];$q='ALTER TABLE '.imc_ident($t).' ADD '.(($b['unique']??false)?'UNIQUE ':'').'INDEX '.imc_ident($n).' ('.implode(',',array_map(fn($x)=>imc_ident((string)$x),$cc)).')';$p->exec($q);imc_out($B+['index'=>$n,'created'=>true,'backup_ddl'=>$backup]);}
if($a==='drop_index'){$n=(string)($b['index_name']??'');$p->exec('ALTER TABLE '.imc_ident($t).' DROP INDEX '.imc_ident($n));imc_out($B+['index'=>$n,'dropped'=>true,'backup_ddl'=>$backup]);}
if($a==='add_primary_key'){$cc=$b['columns']??[];$p->exec('ALTER TABLE '.imc_ident($t).' ADD PRIMARY KEY ('.implode(',',array_map(fn($x)=>imc_ident((string)$x),$cc)).')');imc_out($B+['primary_key'=>$cc,'created'=>true,'backup_ddl'=>$backup]);}
if($a==='drop_primary_key'){$p->exec('ALTER TABLE '.imc_ident($t).' DROP PRIMARY KEY');imc_out($B+['dropped'=>true,'backup_ddl'=>$backup]);}
if($a==='add_foreign_key'){$n=(string)($b['constraint_name']??'');$c=(string)($b['column']??'');$pt=(string)($b['parent_table']??'');$pc=(string)($b['parent_column']??'');$p->exec('ALTER TABLE '.imc_ident($t).' ADD CONSTRAINT '.imc_ident($n).' FOREIGN KEY ('.imc_ident($c).') REFERENCES '.imc_ident($pt).' ('.imc_ident($pc).')');imc_out($B+['constraint'=>$n,'created'=>true,'backup_ddl'=>$backup]);}
if($a==='drop_foreign_key'){$n=(string)($b['constraint_name']??'');$p->exec('ALTER TABLE '.imc_ident($t).' DROP FOREIGN KEY '.imc_ident($n));imc_out($B+['constraint'=>$n,'dropped'=>true,'backup_ddl'=>$backup]);}return false;}
