<?php
declare(strict_types=1);
function imc_read_action(string$a,array$b,array$r,?string$t,PDO$p,array$B):bool{
if($a==='show_tables'){$x=$p->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);imc_out($B+['rows'=>$x,'returned_rows'=>count($x)]);}if(!$t)return false;$E=imc_exists($p,$r['database'],$t);
if(in_array($a,['show_columns','describe','schema'],true)){if(!$E)throw new RuntimeException('table_not_found');$x=array_values(imc_cols($p,$t));imc_out($B+['rows'=>$x,'returned_rows'=>count($x)]);}
if($a==='indexes'){$x=$p->query('SHOW INDEX FROM '.imc_ident($t))->fetchAll();imc_out($B+['rows'=>$x,'returned_rows'=>count($x)]);}
if($a==='show_create_table'){$x=$p->query('SHOW CREATE TABLE '.imc_ident($t))->fetch();imc_out($B+['create_table'=>$x['Create Table']??null]);}
if($a==='table_status'){$s=$p->prepare('SHOW TABLE STATUS LIKE ?');$s->execute([$t]);imc_out($B+['status'=>$s->fetch()]);}
if($a==='foreign_keys'){$s=$p->prepare('SELECT constraint_name,column_name,referenced_table_name,referenced_column_name FROM information_schema.key_column_usage WHERE table_schema=? AND table_name=? AND referenced_table_name IS NOT NULL');$s->execute([$r['database'],$t]);$x=$s->fetchAll();imc_out($B+['rows'=>$x,'returned_rows'=>count($x)]);}
if(in_array($a,['read','read_one','sample'],true)){if(!$E)throw new RuntimeException('table_not_found');$v=[];$q='SELECT * FROM '.imc_ident($t);if(!empty($b['where']))$q.=' WHERE '.imc_where($b['where'],$v);if($a==='sample')$q.=' ORDER BY RAND()';elseif(!empty($b['order_by'])){$ob=(string)$b['order_by'];$dir=strtoupper((string)($b['order']??'ASC'));if(!in_array($dir,['ASC','DESC'],true))throw new InvalidArgumentException('invalid_identifier');$q.=' ORDER BY '.imc_ident($ob).' '.$dir;}$l=$a==='read_one'?1:max(1,min(IMC_MAX_ROWS,(int)($b['limit']??100)));$o=max(0,(int)($b['offset']??0));$fetchLimit=$a==='read_one'?1:$l+1;$q.=" LIMIT $fetchLimit OFFSET $o";$s=$p->prepare($q);$s->execute($v);$x=$s->fetchAll();$hasMore=$a==='read_one'?false:count($x)>$l;if($hasMore)array_pop($x);$rowCount=count($x);imc_out($B+['rows'=>$x,'row'=>$a==='read_one'?($x[0]??null):null,'row_count'=>$rowCount,'returned_rows'=>$rowCount,'limit'=>$l,'offset'=>$o,'has_more'=>$hasMore,'next_offset'=>$hasMore?$o+$rowCount:null]);}
if($a==='count')imc_out($B+['count'=>imc_count($p,$t,$b['where']??[])]);
if($a==='count_nulls'){$c=(string)($b['column']??'');$x=$p->query('SELECT SUM('.imc_ident($c).' IS NULL) null_count,SUM('.imc_ident($c).' IS NOT NULL) not_null_count FROM '.imc_ident($t))->fetch();imc_out($B+$x);}
if($a==='distinct'){$c=(string)($b['column']??'');$x=$p->query('SELECT DISTINCT '.imc_ident($c).' FROM '.imc_ident($t).' LIMIT '.max(1,min(IMC_MAX_ROWS,(int)($b['limit']??500))))->fetchAll();imc_out($B+['rows'=>$x,'returned_rows'=>count($x)]);}
if($a==='aggregate'){$f=strtoupper((string)($b['function']??'COUNT'));if(!in_array($f,['COUNT','SUM','AVG','MIN','MAX'],true))throw new InvalidArgumentException('invalid_payload');$c=(string)($b['column']??'*');$e=$c==='*'?'*':imc_ident($c);$g=$b['group_by']??null;$q="SELECT $f($e) value".($g?', '.imc_ident((string)$g):'').' FROM '.imc_ident($t).($g?' GROUP BY '.imc_ident((string)$g):'');$x=$p->query($q)->fetchAll();imc_out($B+['rows'=>$x,'returned_rows'=>count($x)]);}
if($a==='query'){$q=trim((string)($b['sql']??''));if(!preg_match('/^(SELECT|SHOW|DESCRIBE|DESC|EXPLAIN)\b/i',$q)||preg_match('/;\s*\S/',$q)||preg_match('/\b(INTO\s+OUTFILE|INTO\s+DUMPFILE|FOR\s+UPDATE|LOAD_FILE\s*\()\b/i',$q))throw new InvalidArgumentException('invalid_payload');$x=$p->query($q)->fetchAll();imc_out($B+['rows'=>$x,'returned_rows'=>count($x)]);}
if($a==='validate')imc_out($B+['valid'=>$E,'table_exists'=>$E,'columns'=>$E?array_keys(imc_cols($p,$t)):[]]);
if($a==='find_duplicates'){$cc=$b['columns']??[];if(!is_array($cc)||!$cc)throw new InvalidArgumentException('required_field_missing');$z=array_map(fn($x)=>imc_ident((string)$x),$cc);$x=$p->query('SELECT '.implode(',',$z).',COUNT(*) duplicate_count FROM '.imc_ident($t).' GROUP BY '.implode(',',$z).' HAVING COUNT(*)>1')->fetchAll();imc_out($B+['rows'=>$x,'returned_rows'=>count($x)]);}
if($a==='audit_repository'){$co=array_values(imc_cols($p,$t));$ix=$p->query('SHOW INDEX FROM '.imc_ident($t))->fetchAll();$nu=[];foreach($co as$c)$nu[$c['Field']]=(int)$p->query('SELECT SUM('.imc_ident($c['Field']).' IS NULL) FROM '.imc_ident($t))->fetchColumn();imc_out($B+['row_count'=>imc_count($p,$t),'columns'=>$co,'indexes'=>$ix,'null_counts'=>$nu]);}
if($a==='dry_run')imc_out($B+['valid'=>true,'planned_sql'=>'generated server-side after validation','affected_estimate'=>$E?imc_count($p,$t,$b['where']??[]):0,'errors'=>[]]);return false;}
