<?php
header('Content-Type: application/json; charset=utf-8');header('Cache-Control:no-store');
$file=__DIR__.'/state.json';
$players=json_decode(<<<'P'
[["K. Coman",90,30,"10.7M","Al Nassr FC"],["I. Toney",90,30,"9.8M","Al Ahli SFC"],["M. Asensio",90,30,"9.5M","Fenerbahçe SK"],["J. Andersen",90,30,"10.5M","Fulham"],["A. Golovin",90,30,"10.5M","AS Monaco"],["C. Joelinton",90,30,"11.0M","Newcastle United"],["L. Pellegrini",90,30,"10.7M","AS Roma"],["N. Aguerd",90,30,"10.3M","Olympique Marseille"],["B. Pavard",90,30,"10.3M","Internazionale"],["G. Lo Celso",90,30,"10.4M","Real Betis"],["G. Mancini",90,30,"10.4M","AS Roma"],["W. Anton",90,30,"10.8M","Svincolato"],["P. Fornals",90,30,"10.2M","Real Betis"],["D. Undav",90,30,"10.4M","VfB Stuttgart"],["F. Aursnes",89,30,"6.6M","Manchester United"],["J. Bednarek",89,30,"6.9M","Svincolato"],["J. Brandt",89,30,"7.0M","Borussia Dortmund"],["D. Sánchez",89,30,"7.1M","Galatasaray SK"],["D. Ceballos",89,30,"7.3M","Real Betis"],["S. Amrabat",89,30,"7.3M","Svincolato"],["T. Kehrer",89,30,"7.4M","AS Monaco"],["P. Lienhart",89,30,"7.2M","SC Freiburg"],["A. Iwobi",89,30,"7.0M","Fulham"],["Y. Wissa",89,30,"7.1M","Newcastle United"],["R. Koch",89,30,"7.2M","Eintracht Frankfurt"],["G. Guruzeta",89,30,"7.1M","Athletic Club"],["L. Shaw",90,31,"7.9M","Arsenal"],["P. Højbjerg",90,31,"8.0M","Olympique Marseille"],["M. Škriniar",90,31,"7.4M","Fenerbahçe SK"],["A. Romagnoli",90,31,"7.3M","Al Sadd SC"],["N. Aké",90,31,"7.4M","Fenerbahçe SK"],["M. Pašalić",90,31,"7.4M","Atalanta BC"],["B. Cristante",90,31,"7.5M","AS Roma"],["M. Zaccagni",90,31,"7.3M","SS Lazio"],["J. Palhinha",90,31,"7.9M","Svincolato"],["O. Monteiro",89,31,"4.9M","Al Qadsiah FC"],["J. Gayà",89,31,"5.1M","Atlético Madrid"],["T. Minamino",89,31,"4.5M","Ajax"],["Á. Correa",89,31,"4.7M","Bayern München"],["T. Kleindienst",89,31,"5.0M","Borussia Mönchengladbach"],["C. Lenglet",89,31,"5.2M","Svincolato"],["R. Bensebaini",89,31,"5.0M","SSC Napoli"],["Á. Berenguer",89,31,"4.9M","Athletic Club"],["M. Hermoso",89,31,"5.2M","AS Roma"],["F. Mendy",89,31,"5.2M","SL Benfica"],["L. Milla",89,31,"4.7M","Como 1907"],["N. Pépé",89,31,"4.8M","Villarreal CF"],["L. Paredes",90,32,"5.7M","Svincolato"],["M. Kovačić",90,32,"5.6M","Manchester City"],["M. Sabitzer",90,32,"5.5M","Svincolato"],["P. Dybala",90,32,"4.7M","AS Roma"],["T. Fabinho",90,32,"5.1M","Rangers"],["R. Guerreiro",90,32,"5.2M","Svincolato"],["A. Robertson",90,32,"5.5M","Tottenham Hotspur"],["R. Andrich",90,32,"7.9M","Bayer Leverkusen"],["V. Muriqi",90,32,"5.1M","Celtic"],["R. Mandava",89,32,"3.5M","Juventus"],["R. Lukaku",90,33,"3.7M","Bayern München"],["H. Maguire",90,33,"4.0M","Svincolato"],["W. Orban",90,33,"3.8M","Celtic"],["F. Thauvin",90,33,"3.5M","Atlético Madrid"],["M. Politano",90,33,"3.9M","Svincolato"],["V. Grifo",90,33,"3.6M","SSC Napoli"],["A. Pérez",90,33,"3.8M","Villarreal CF"]]
P
,true);
$orders=json_decode(<<<'O'
[["Prisco","Nudo","Buitre","Simone","Iodice","Tana","Cabrioli","Grugni","Palace","Minasyan","Mello","Errico","Catalano","Gattuso","Martorano","Trovato"],["Trovato","Martorano","Gattuso","Catalano","Errico","Mello","Minasyan","Palace","Grugni","Cabrioli","Tana","Iodice","Simone","Buitre","Nudo","Prisco"],["Grugni","Palace","Minasyan","Mello","Errico","Catalano","Gattuso","Martorano","Trovato","Prisco","Nudo","Buitre","Simone","Iodice","Tana","Cabrioli"],["Cabrioli","Tana","Iodice","Simone","Buitre","Nudo","Prisco","Trovato","Martorano","Gattuso","Catalano","Errico","Mello","Minasyan","Palace","Grugni"]]
O
,true);
function fresh(){return ['started'=>false,'draws'=>[]];}
$fp=fopen($file,'c+');if(!$fp){http_response_code(500);echo json_encode(['ok'=>false,'error'=>'state']);exit;}flock($fp,LOCK_EX);rewind($fp);$raw=stream_get_contents($fp);$s=$raw?json_decode($raw,true):fresh();if(!is_array($s)||!isset($s['draws']))$s=fresh();
if($_SERVER['REQUEST_METHOD']==='POST'){$in=json_decode(file_get_contents('php://input'),true)?:[];$a=$in['action']??'';
if($a==='start'){$s=fresh();$s['started']=true;}elseif($a==='reset'){$s=fresh();}elseif($a==='draw'){$n=count($s['draws']);if(!$s['started']||$n>=64){http_response_code(409);echo json_encode(['ok'=>false,'error'=>'not_ready']);flock($fp,LOCK_UN);fclose($fp);exit;}$used=array_column($s['draws'],'player');$avail=array_values(array_filter($players,fn($p)=>!in_array($p[0],$used,true)));$p=$avail[random_int(0,count($avail)-1)];$r=intdiv($n,16);$k=$n%16;$s['draws'][]=['call'=>$n+1,'round'=>$r+1,'pick'=>$k+1,'manager'=>$orders[$r][$k],'player'=>$p[0],'rating'=>$p[1],'age'=>$p[2],'value'=>$p[3],'club'=>$p[4]];}else{http_response_code(400);echo json_encode(['ok'=>false,'error'=>'action']);flock($fp,LOCK_UN);fclose($fp);exit;}rewind($fp);ftruncate($fp,0);fwrite($fp,json_encode($s,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT));fflush($fp);}
$n=count($s['draws']);$r=intdiv($n,16);$k=$n%16;$used=array_column($s['draws'],'player');$remaining=array_values(array_filter($players,fn($p)=>!in_array($p[0],$used,true)));$manager=$n<64?$orders[$r][$k]:null;echo json_encode(array_merge(['ok'=>true,'manager'=>$manager,'round'=>$n<64?$r+1:4,'pick'=>$n<64?$k+1:16,'call'=>$n+1,'remaining'=>$remaining,'completed'=>$n>=64],$s),JSON_UNESCAPED_UNICODE);flock($fp,LOCK_UN);fclose($fp);