<?php
header('Content-Type: application/json; charset=utf-8');header('Cache-Control:no-store');
$f=__DIR__.'/draft_state.json';$players=json_decode('["K. COMAN","I. TONEY","M. ASENSIO","J. ANDERSEN","A. GOLOVIN","C. JOELINTON","L. PELLEGRINI","N. AGUERD","B. PAVARD","G. LO CELSO","G. MANCINI","W. ANTON","P. FORNALS","D. UNDAV","L. SHAW","P. HOJBJERG","M. SKRINIAR","A. ROMAGNOLI","N. AKÉ","J. GIMÉNEZ","M. PAŠALIĆ","B. CRISTANTE","M. ZACCAGNI","J. PALHINHA","L. PAREDES","M. KOVAČIĆ","M. SABITZER","P. DYBALA","R. GUERREIRO","A. ROBERTSON","R. ANDRICH","H. MAGUIRE","M. POLITANO","A. PÉREZ","F. AURSNES","J. BEDNAREK","J. BRANDT","D. SÁNCHEZ","D. CEBALLOS","S. AMRABAT","T. KEHRER","P. LIENHART","L. TORREIRA","A. IWOBI","Y. WISSA","R. KOCH","G. GURUZETA","O. MONTEIRO","T. KLEINDIENST","J. MURPHY","C. LENGLET","Á. BERENGUER","N. PÉPÉ","M. HERMOSO","F. MENDY","L. MILLA","C. TOLISSO","G. GÓMEZ","M. ICARDI","B. IGLESIAS","S. EL SHAARAWY","M. ARNOLD","L. TORRÓ","A. BARDAKCI"]',true);$orders=json_decode('[["Prisco","Nudo","Buitre","Simone","Iodice","Tana","Cabrioli","Grugni","Palace","Minasyan","Mello","Errico","Catalano","Gattuso","Martorano","Trovato"],["Trovato","Martorano","Gattuso","Catalano","Errico","Mello","Minasyan","Palace","Grugni","Cabrioli","Tana","Iodice","Simone","Buitre","Nudo","Prisco"],["Grugni","Palace","Minasyan","Mello","Errico","Catalano","Gattuso","Martorano","Trovato","Prisco","Nudo","Buitre","Simone","Iodice","Tana","Cabrioli"],["Cabrioli","Tana","Iodice","Simone","Buitre","Nudo","Prisco","Trovato","Martorano","Gattuso","Catalano","Errico","Mello","Minasyan","Palace","Grugni"]]',true);
function emptyState(){return ['running'=>false,'revealed'=>0,'draft'=>[],'started_at'=>null];}
$s=file_exists($f)?json_decode(file_get_contents($f),true):emptyState();if(!is_array($s))$s=emptyState();
$VERSION='CLEAN_AUTO64_V3';if(($s['version']??'')!==$VERSION){$s=emptyState();$s['version']=$VERSION;file_put_contents($f,json_encode($s,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX);}
if($_SERVER['REQUEST_METHOD']==='POST'){$in=json_decode(file_get_contents('php://input'),true)?:[];$a=$in['action']??'';
 if($a==='reset'){$s=emptyState();$s['version']=$VERSION;}
 if($a==='start'){$pool=$players;shuffle($pool);$draft=[];for($i=0;$i<64;$i++){$r=intdiv($i,16);$k=$i%16;$draft[]=['call'=>$i+1,'round'=>$r+1,'pick'=>$k+1,'manager'=>$orders[$r][$k],'player'=>$pool[$i]];}$s=['running'=>true,'revealed'=>0,'draft'=>$draft,'started_at'=>microtime(true),'version'=>$VERSION];}

 file_put_contents($f,json_encode($s,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX);}
if($s['running']&&!empty($s['started_at'])){$elapsed=microtime(true)-(float)$s['started_at'];$s['revealed']=min(64,(int)floor($elapsed/1.6));if($s['revealed']>=64){$s['revealed']=64;$s['running']=false;}file_put_contents($f,json_encode($s,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX);}echo json_encode(['ok'=>true]+$s,JSON_UNESCAPED_UNICODE);