(() => {
'use strict';
const GW='GW001',root=document.getElementById('app'); if(!root)return;
const S={world:null,clubs:[],clubCodex:new Map(),competitions:[],managers:[],managerCodex:new Map(),results:[],schedule:[],transfers:[],stats:[],reports:[],playerCodex:new Map(),loading:true,error:null};
const NAV=[['home','HOME'],['competitions','COMPETITIONS'],['clubs','CLUBS'],['managers','MANAGERS'],['scores','SCORES'],['fixtures','FIXTURES'],['players','PLAYERS'],['transfers','TRANSFERS'],['reports','REPORTS']];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rows=x=>Array.isArray(x)?x:Array.isArray(x?.rows)?x.rows:Array.isArray(x?.data)?x.data:[];
const get=(o,ks,f='')=>{for(const k of ks)if(o&&o[k]!=null&&o[k]!=='')return o[k];return f};
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const read=(api,res,opt={})=>api.read(res,{game_world_id:GW,...opt});
const dateVal=o=>{const n=Date.parse(get(o,['match_date','transfer_date','imported_at','created_at'],''));return Number.isFinite(n)?n:0};
const fmt=n=>n?new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(n)):'—';
const waitApi=ms=>new Promise(resolve=>{const t=Date.now();(function f(){if(window.IMC_MINISITE_DATA?.read)return resolve(window.IMC_MINISITE_DATA);if(Date.now()-t>ms)return resolve(null);setTimeout(f,50)})()});
function slug(s){return encodeURIComponent(String(s??''))} function unslug(s){try{return decodeURIComponent(s||'')}catch{return s||''}}
function route(){const raw=(location.hash||'#home').slice(1);const [name,arg]=raw.split('/');return {name:NAV.some(x=>x[0]===name)||['competition','club','manager'].includes(name)?name:'home',arg:unslug(arg)}}
window.addEventListener('hashchange',render);
boot();
async function boot(){shell();const api=await waitApi(3000);if(!api){S.error='Data service unavailable';S.loading=false;render();return}try{const [w,c,co,m,r,sc,t,st,rp]=await Promise.all([read(api,'game_world_codex'),read(api,'game_world_club_mapping'),read(api,'competition_codex'),read(api,'manager_assignments'),read(api,'results',{limit:1000}),read(api,'schedule',{limit:1000}),read(api,'transfers',{limit:1000}),read(api,'sm_player_stats',{limit:1000}),read(api,'match_report',{limit:1000})]);S.world=rows(w)[0]||null;S.clubs=rows(c);S.competitions=rows(co);S.managers=rows(m);S.results=rows(r);S.schedule=rows(sc);S.transfers=rows(t);S.stats=rows(st);S.reports=rows(rp);await Promise.all([hydrateClubs(api),hydrateManagers(api),hydratePlayers(api)])}catch(e){console.error(e);S.error=e?.message||'Unable to load data'}S.loading=false;render()}
async function hydrateClubs(api){await Promise.all(S.clubs.slice(0,120).map(async c=>{if(!c.club_id)return;try{const x=rows(await read(api,'club_codex',{club_id:c.club_id}))[0];if(x)S.clubCodex.set(String(c.club_id),x)}catch{}}))}
async function hydrateManagers(api){await Promise.all([...new Set(S.managers.map(x=>x.manager_id).filter(Boolean))].slice(0,120).map(async id=>{try{const x=rows(await read(api,'manager_codex',{manager_id:id}))[0];if(x)S.managerCodex.set(String(id),x)}catch{}}))}
async function hydratePlayers(api){await Promise.all(topStats(60).map(async p=>{const id=p.sm_player_id||p.player_id;if(!id)return;try{const x=rows(await read(api,'player_codex',{player_id:id}))[0];if(x)S.playerCodex.set(String(id),x)}catch{}}))}
function shell(){root.innerHTML=`<div class="broadcast-shell"><header class="topline"><a href="#home" class="brand"><b>IMC</b><span>SPORT</span><i>001</i></a><nav>${NAV.map(([r,l])=>`<a href="#${r}" data-nav="${r}">${l}</a>`).join('')}</nav><button id="menuBtn">MENU</button></header><main id="stage"></main><div class="breaking"><b>LIVE</b><span id="ticker">ROAD TO HISTORY</span></div><dialog id="menu"><button id="menuClose">×</button>${NAV.map(([r,l])=>`<a href="#${r}">${l}</a>`).join('')}</dialog></div>`;document.getElementById('menuBtn').onclick=()=>document.getElementById('menu').showModal();document.getElementById('menuClose').onclick=()=>document.getElementById('menu').close();document.querySelectorAll('#menu a').forEach(a=>a.onclick=()=>document.getElementById('menu').close());render()}
function render(){const st=document.getElementById('stage');if(!st)return;const r=route();document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===r.name));if(S.loading){st.innerHTML='<section class="loading"><strong>IMC SPORT</strong><span>Loading GW001 data...</span></section>';return}if(S.error){st.innerHTML=`<section class="loading"><strong>DATA LINK OFFLINE</strong><span>${esc(S.error)}</span></section>`;return}document.getElementById('ticker').textContent=tickerText();const views={home,competitions,competition,clubs,club,managers,manager,scores,fixtures,players,transfers,reports};st.innerHTML=views[r.name](r.arg);bind()}
function bind(){document.querySelectorAll('[data-open-club]').forEach(b=>b.onclick=()=>location.hash=`#club/${slug(b.dataset.openClub)}`);document.querySelectorAll('[data-open-manager]').forEach(b=>b.onclick=()=>location.hash=`#manager/${slug(b.dataset.openManager)}`)}
function home(){const w=S.world||{},lead=topStats(1)[0],latest=recent(1)[0],next=upcoming(1)[0],img=lead?playerImage(lead):'';return `<section class="home"><article class="hero ${img?'photo':''}" style="${img?`--hero:url('${esc(img)}')`:''}"><div class="hero-copy"><span>IMC SPORT NETWORK · GW001</span><h1>${esc(get(w,['game_world_name','IMC GW Name'],'ROAD TO HISTORY'))}</h1><p>${S.clubs.length} clubs · ${S.competitions.length} competitions · ${S.results.length} results</p><div><a href="#competitions">ENTER COMPETITION HUB</a><a href="#clubs">CLUB NETWORK</a></div></div></article><section class="headline-grid">${latest?story('FINAL',matchText(latest,true),compLabel(latest),'#scores'):''}${next?story('NEXT',matchText(next,false),fmt(dateVal(next)),'#fixtures'):''}${story('MARKET',`${S.transfers.length} transfers tracked`,'Transfer desk','#transfers')}</section><section class="home-comp"><header><div><span>CORE OF THE WORLD</span><h2>Competition Hub</h2></div><a href="#competitions">VIEW ALL</a></header>${competitionGroups(true)}</section><section class="home-clubs"><header><div><span>THE CLUBS</span><h2>Club Network</h2></div><a href="#clubs">EXPLORE</a></header><div class="club-ribbon">${S.clubs.slice(0,18).map(clubMini).join('')}</div></section><section class="home-managers"><header><div><span>THE DUGOUT</span><h2>Managers</h2></div><a href="#managers">OPEN HUB</a></header><div class="manager-ribbon">${S.managers.slice(0,8).map(managerMini).join('')}</div></section></section>`}
function story(k,t,s,h){return `<a class="headline" href="${h}"><span>${k}</span><strong>${esc(t)}</strong><small>${esc(s)}</small></a>`}
function competitions(){return pageHead('COMPETITIONS','Competition Hub','Domestic, international and national-team competitions, each with live results, fixtures and match reports.')+competitionGroups(false)}
function competitionGroups(compact){const groups=['DOMESTIC','INTERNATIONAL','NATIONS'];return `<div class="competition-groups">${groups.map(g=>{const arr=S.competitions.filter(c=>group(c)===g);return `<section class="comp-group ${g.toLowerCase()}"><header><span>${g}</span><b>${arr.length}</b></header><div>${arr.map(c=>competitionCard(c,compact)).join('')||'<p class="empty">No competitions</p>'}</div></section>`}).join('')}</div>`}
function competitionCard(c,compact){const key=compKey(c),rr=filterComp(S.results,c),ss=filterComp(S.schedule,c),rp=filterComp(S.reports,c);return `<a class="competition-card" href="#competition/${slug(key)}"><span>${esc(group(c))}</span><h3>${esc(compName(c))}</h3><p>${esc(c.sm_country||'Global')}${c.sm_division?` · Division ${esc(c.sm_division)}`:''}</p><div><b>${rr.length}<small>RESULTS</small></b><b>${ss.length}<small>FIXTURES</small></b><b>${rp.length}<small>REPORTS</small></b></div>${compact?'':'<i>OPEN HUB →</i>'}</a>`}
function competition(arg){const c=S.competitions.find(x=>compKey(x)===arg);if(!c)return notFound('Competition');const rr=filterComp(S.results,c).sort((a,b)=>dateVal(b)-dateVal(a)),ss=filterComp(S.schedule,c).sort((a,b)=>dateVal(a)-dateVal(b)),rp=filterComp(S.reports,c).sort((a,b)=>dateVal(b)-dateVal(a));return `<section class="detail competition-detail"><a class="back" href="#competitions">← ALL COMPETITIONS</a><header class="detail-hero"><span>${esc(group(c))}</span><h1>${esc(compName(c))}</h1><p>${esc(c.sm_country||'Global')}${c.sm_division?` · Division ${esc(c.sm_division)}`:''} · ${esc(c.teams_count||'—')} teams</p><div><b>${rr.length}<small>RESULTS</small></b><b>${ss.length}<small>FIXTURES</small></b><b>${rp.length}<small>REPORTS</small></b><b>${esc(c.expected_match||'—')}<small>EXPECTED</small></b></div></header><div class="detail-columns"><section><h2>Latest Results</h2>${rr.slice(0,20).map(scoreCard).join('')||empty('No results')}</section><section><h2>Schedule</h2>${ss.slice(0,20).map(fixtureCard).join('')||empty('No fixtures')}</section><section><h2>Match Reports</h2>${rp.slice(0,20).map(reportCard).join('')||empty('No reports')}</section></div></section>`}
function clubs(){return pageHead('CLUBS','Club Hub','Every club becomes its own mini-world: results, schedule, manager, players and transfers.')+`<div class="club-grid">${S.clubs.map(clubCard).join('')}</div>`}
function clubCard(c){const id=clubKey(c),x=S.clubCodex.get(String(c.club_id)),m=managerForClub(c),form=clubForm(c);return `<button class="club-card" data-open-club="${esc(id)}">${logo(x?.image_url,c.club_name)}<div><span>${esc(form)}</span><h3>${esc(c.club_name||x?.name||'Club')}</h3><p>${esc(managerName(m)||'IMC Club')}</p></div><b>OPEN</b></button>`}
function club(arg){const c=S.clubs.find(x=>clubKey(x)===arg);if(!c)return notFound('Club');const x=S.clubCodex.get(String(c.club_id)),m=managerForClub(c),rr=clubRows(S.results,c).sort((a,b)=>dateVal(b)-dateVal(a)),ss=clubRows(S.schedule,c).sort((a,b)=>dateVal(a)-dateVal(b)),tt=transferRows(c),pp=S.stats.filter(p=>sameClub(p,c)).sort((a,b)=>num(b.avg_rating)-num(a.avg_rating));return `<section class="detail club-detail"><a class="back" href="#clubs">← ALL CLUBS</a><header class="club-hero">${logo(x?.image_url,c.club_name)}<div><span>GW001 CLUB</span><h1>${esc(c.club_name||x?.name||'Club')}</h1><p>${m?`Manager · ${esc(managerName(m))}`:'Manager assignment unavailable'}</p>${m?`<button data-open-manager="${esc(m.manager_id)}">OPEN MANAGER PROFILE</button>`:''}</div></header><div class="club-kpis"><b>${rr.length}<small>RESULTS</small></b><b>${ss.length}<small>FIXTURES</small></b><b>${pp.length}<small>PLAYERS</small></b><b>${tt.length}<small>TRANSFERS</small></b></div><div class="detail-columns club-cols"><section><h2>Recent Results</h2>${rr.slice(0,12).map(scoreCard).join('')||empty('No results')}</section><section><h2>Next Fixtures</h2>${ss.slice(0,12).map(fixtureCard).join('')||empty('No fixtures')}</section><section><h2>Top Players</h2>${pp.slice(0,12).map(playerLine).join('')||empty('No player stats')}</section><section><h2>Transfer Activity</h2>${tt.slice(0,12).map(transferCard).join('')||empty('No transfers')}</section></div></section>`}
function managers(){return pageHead('MANAGERS','Manager Hub','Assignments, clubs and the sporting record attached to each manager.')+`<div class="manager-grid">${S.managers.map(managerCard).join('')}</div>`}
function managerCard(m){const n=managerName(m);return `<button class="manager-card" data-open-manager="${esc(m.manager_id)}"><div>${initials(n)}</div><section><span>IMC MANAGER</span><h3>${esc(n)}</h3><p>${esc(m.club_name||'Assignment')}</p></section><b>PROFILE</b></button>`}
function manager(arg){const m=S.managers.find(x=>String(x.manager_id)===String(arg));if(!m)return notFound('Manager');const n=managerName(m),c=S.clubs.find(x=>sameClubName(x.club_name,m.club_name)||String(x.club_id||'')===String(m.club_id||'')),rr=c?clubRows(S.results,c):[],ss=c?clubRows(S.schedule,c):[];return `<section class="detail manager-detail"><a class="back" href="#managers">← ALL MANAGERS</a><header class="manager-hero"><div>${initials(n)}</div><section><span>IMC MANAGER</span><h1>${esc(n)}</h1><p>${esc(m.club_name||'Current assignment')}</p>${c?`<button data-open-club="${esc(clubKey(c))}">OPEN CLUB HUB</button>`:''}</section></header><div class="manager-kpis"><b>${rr.length}<small>CLUB RESULTS</small></b><b>${ss.length}<small>FIXTURES</small></b><b>${esc(m.manager_id||'—')}<small>MANAGER ID</small></b></div><div class="detail-columns"><section><h2>Latest Club Results</h2>${rr.sort((a,b)=>dateVal(b)-dateVal(a)).slice(0,15).map(scoreCard).join('')||empty('No linked results')}</section><section><h2>Upcoming Club Fixtures</h2>${ss.sort((a,b)=>dateVal(a)-dateVal(b)).slice(0,15).map(fixtureCard).join('')||empty('No linked fixtures')}</section></div></section>`}
function scores(){return pageHead('SCORES','Match Centre',`${S.results.length} recorded matches`)+`<div class="list">${recent(S.results.length).map(scoreCard).join('')||empty('No results')}</div>`}
function fixtures(){return pageHead('FIXTURES','Schedule',`${S.schedule.length} scheduled fixtures`)+`<div class="list">${upcoming(S.schedule.length).map(fixtureCard).join('')||empty('No fixtures')}</div>`}
function players(){return pageHead('PLAYERS','Player Performance','Live SM player statistics')+`<div class="player-grid">${topStats(100).map(playerPoster).join('')||empty('No player stats')}</div>`}
function transfers(){return pageHead('TRANSFERS','Transfer Desk',`${S.transfers.length} tracked moves`)+`<div class="list">${S.transfers.map(transferCard).join('')||empty('No transfers')}</div>`}
function reports(){return pageHead('REPORTS','Match Report Archive',`${S.reports.length} reports`)+`<div class="list">${S.reports.map(reportCard).join('')||empty('No reports')}</div>`}
function pageHead(k,t,p){return `<section class="page-head"><span>${k}</span><h1>${t}</h1><p>${p}</p></section>`}
function scoreCard(r){return `<article class="score-card"><span>${esc(compLabel(r))} · ${fmt(dateVal(r))}</span><div><strong>${esc(get(r,['home_name','home_team','home_club_name'],'Home'))}</strong><b>${esc(get(r,['home_score'],'–'))}:${esc(get(r,['away_score'],'–'))}</b><strong>${esc(get(r,['away_name','away_team','away_club_name'],'Away'))}</strong></div></article>`}
function fixtureCard(r){return `<article class="fixture-card"><time>${fmt(dateVal(r))}</time><div><span>${esc(compLabel(r))}</span><strong>${esc(matchText(r,false))}</strong></div></article>`}
function reportCard(r){return `<article class="report-card"><span>${fmt(dateVal(r))} · ${esc(compLabel(r))}</span><strong>${esc(matchText(r,true))}</strong><p>${esc(get(r,['result_status','status'],'Match report'))}</p></article>`}
function transferCard(t){return `<article class="transfer-card"><time>${fmt(dateVal(t))}</time><div><strong>${esc(get(t,['player_name','name'],'Player'))}</strong><span>${esc(get(t,['from_club_name','old_club_name'],'—'))} → ${esc(get(t,['to_club_name','new_club_name'],'—'))}</span></div></article>`}
function playerLine(p){return `<article class="player-line"><strong>${esc(get(p,['player_name','full_name'],'Player'))}</strong><span>${esc(get(p,['avg_rating'],'—'))} AVG · ${num(p.goals)}G · ${num(p.assists)}A</span></article>`}
function playerPoster(p){const n=get(p,['player_name','full_name'],'Player'),img=playerImage(p);return `<article class="player-poster">${img?`<img src="${esc(img)}" alt="${esc(n)}">`:`<div>${initials(n)}</div>`}<section><span>${esc(get(p,['club_name'],'Club'))}</span><h3>${esc(n)}</h3><b>${esc(get(p,['avg_rating'],'—'))} AVG · ${num(p.goals)} G</b></section></article>`}
function competitionGroupName(v){v=String(v||'').toUpperCase();if(v.includes('NATION'))return'NATIONS';if(v.includes('INTER'))return'INTERNATIONAL';return'DOMESTIC'}
function group(c){return competitionGroupName(c.sm_action_group||c.competition_group||'DOMESTIC')}
function compName(c){return c.custom_competition||c.competition_name||c.sm_action||c.competition_key||'Competition'}
function compKey(c){return String(c.competition_key||[c.sm_action,c.sm_country,c.sm_division,c.custom_competition].filter(Boolean).join('|')||compName(c))}
function compLabel(r){return get(r,['competition_group_name','competition_name','competition_key','sm_action'],'Competition')}
function filterComp(list,c){const ck=String(c.competition_key||''),sa=String(c.sm_action||'').toLowerCase(),ct=String(c.sm_country||'').toLowerCase(),dv=String(c.sm_division||'');return list.filter(r=>{const rk=String(r.competition_key||'');if(ck&&rk)return rk===ck;const ra=String(r.sm_action||'').toLowerCase(),rc=String(r.sm_country||r.country||'').toLowerCase(),rd=String(r.sm_division||r.division||'');return (!sa||ra===sa)&&(!ct||!rc||rc===ct)&&(!dv||!rd||rd===dv)})}
function clubKey(c){return String(c.club_gw_id||c.sm_club_id||c.world_club_id||c.club_id||c.club_name)}
function sameClub(row,c){const id=clubKey(c),vals=['sm_club_id','home_sm_club_id','away_sm_club_id','home_sm_team_id','away_sm_team_id','from_sm_world_club_id','to_sm_world_club_id'].map(k=>String(row?.[k]??''));return vals.includes(id)||sameClubName(get(row,['club_name','home_name','away_name','from_club_name','to_club_name'],''),c.club_name)}
function clubRows(list,c){const id=clubKey(c),name=String(c.club_name||'').toLowerCase();return list.filter(r=>[r.home_sm_club_id,r.away_sm_club_id,r.home_sm_team_id,r.away_sm_team_id].map(x=>String(x??'')).includes(id)||[r.home_name,r.away_name,r.home_team,r.away_team,r.home_club_name,r.away_club_name].some(x=>String(x||'').toLowerCase()===name))}
function transferRows(c){const id=clubKey(c),name=String(c.club_name||'').toLowerCase();return S.transfers.filter(t=>[t.from_sm_world_club_id,t.to_sm_world_club_id,t.sm_club_id].map(x=>String(x??'')).includes(id)||[t.from_club_name,t.to_club_name,t.old_club_name,t.new_club_name].some(x=>String(x||'').toLowerCase()===name))}
function managerForClub(c){return S.managers.find(m=>String(m.club_id||'')===String(c.club_id||'')||sameClubName(m.club_name,c.club_name))}
function managerName(m){if(!m)return'';const x=S.managerCodex.get(String(m.manager_id));return x?.full_name||m.manager_name||m.full_name||`Manager ${m.manager_id||''}`}
function sameClubName(a,b){return String(a||'').trim().toLowerCase()===String(b||'').trim().toLowerCase()&&String(a||'').trim()!==''}
function clubForm(c){const rr=clubRows(S.results,c).sort((a,b)=>dateVal(b)-dateVal(a)).slice(0,5);return rr.map(r=>{const h=sameClubName(r.home_name,c.club_name)||String(r.home_sm_club_id??'')===clubKey(c),hs=num(r.home_score),as=num(r.away_score);return hs===as?'D':(h?hs>as:as>hs)?'W':'L'}).join(' ')||'NO FORM'}
function clubMini(c){const x=S.clubCodex.get(String(c.club_id));return `<button data-open-club="${esc(clubKey(c))}">${logo(x?.image_url,c.club_name)}<span>${esc(c.club_name||'Club')}</span></button>`}
function managerMini(m){const n=managerName(m);return `<button data-open-manager="${esc(m.manager_id)}"><div>${initials(n)}</div><strong>${esc(n)}</strong><span>${esc(m.club_name||'Assignment')}</span></button>`}
function logo(url,name){return url?`<img class="club-logo" src="${esc(url)}" alt="${esc(name||'Club')}">`:`<div class="club-logo fallback">${initials(name)}</div>`}
function initials(n){return String(n||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function playerImage(p){const id=p.sm_player_id||p.player_id,x=S.playerCodex.get(String(id));return x?.image_url||p.player_image_url||p.image_url||''}
function matchText(r,score){const h=get(r,['home_name','home_team','home_club_name'],'Home'),a=get(r,['away_name','away_team','away_club_name'],'Away');return score?`${h} ${get(r,['home_score'],'–')}–${get(r,['away_score'],'–')} ${a}`:`${h} vs ${a}`}
function recent(n){return [...S.results].sort((a,b)=>dateVal(b)-dateVal(a)).slice(0,n)}
function upcoming(n){return [...S.schedule].sort((a,b)=>dateVal(a)-dateVal(b)).slice(0,n)}
function topStats(n){return [...S.stats].sort((a,b)=>num(b.avg_rating)-num(a.avg_rating)||num(b.goals)-num(a.goals)).slice(0,n)}
function tickerText(){const r=recent(1)[0],n=upcoming(1)[0];return [r&&`FINAL ${matchText(r,true)}`,n&&`NEXT ${matchText(n,false)}`,`${S.competitions.length} COMPETITIONS`].filter(Boolean).join('  •  ')}
function empty(t){return `<p class="empty">${esc(t)}</p>`}function notFound(t){return `<section class="loading"><strong>${esc(t)} not found</strong><a href="#home">Back home</a></section>`}
})();