(()=>{
'use strict';
const GW='GW001',root=document.getElementById('app'); if(!root)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rows=x=>Array.isArray(x)?x:Array.isArray(x?.rows)?x.rows:Array.isArray(x?.data)?x.data:[];
const get=(o,ks,f='')=>{for(const k of ks){if(o&&o[k]!=null&&o[k]!=='')return o[k]}return f};
const read=(api,res,opt={})=>api.read(res,{game_world_id:GW,...opt});
const dateVal=o=>{const n=Date.parse(get(o,['match_date','date','fixture_date'],''));return Number.isFinite(n)?n:0};
const fmtDate=n=>n?new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short'}).format(new Date(n)):'—';
const waitApi=ms=>new Promise(resolve=>{const t=Date.now();(function f(){if(window.IMC_MINISITE_DATA?.read)return resolve(window.IMC_MINISITE_DATA);if(Date.now()-t>ms)return resolve(null);setTimeout(f,50)})()});
const S={world:null,competitions:[],clubs:[],managers:[],results:[],schedule:[],clubCodex:new Map()};
root.innerHTML='<section class="loading"><b>IMC · GW001</b><span>Loading Road To History…</span></section>';
boot();
async function boot(){const api=await waitApi(3000);if(!api){root.innerHTML='<section class="loading"><b>GW001</b><span>Data service unavailable</span></section>';return}try{const [w,c,cl,m,r,s]=await Promise.all([read(api,'game_world_codex'),read(api,'competition_codex'),read(api,'game_world_club_mapping'),read(api,'manager_assignments'),read(api,'results',{limit:2000}),read(api,'schedule',{limit:2000})]);S.world=rows(w)[0]||null;S.competitions=rows(c);S.clubs=rows(cl);S.managers=rows(m);S.results=rows(r);S.schedule=rows(s);const next=nextFixture();for(const id of [get(next,['home_sm_club_id','home_club_id']),get(next,['away_sm_club_id','away_club_id'])].filter(Boolean)){try{const x=rows(await read(api,'club_codex',{club_id:id}))[0];if(x)S.clubCodex.set(String(id),x)}catch{}}render()}catch(e){console.error(e);root.innerHTML='<section class="loading"><b>GW001</b><span>Unable to load world data</span></section>'}}
function activeManagers(){return S.managers.filter(m=>{const end=get(m,['end_date','date_end'],'');const active=get(m,['active','is_active','status'],'');if(active!==''&&String(active).toLowerCase()!=='active'&&String(active)!=='1'&&active!==true)return false;return !end})}
function expectedTotal(){const vals=S.competitions.map(c=>Number(get(c,['expected_match','expected_matches'],0))).filter(Number.isFinite);const sum=vals.reduce((a,b)=>a+b,0);return sum>0?sum:S.results.length+S.schedule.length}
function nextFixture(){const now=Date.now();const future=[...S.schedule].filter(x=>dateVal(x)>=now).sort((a,b)=>dateVal(a)-dateVal(b));return future[0]||[...S.schedule].sort((a,b)=>dateVal(a)-dateVal(b))[0]||null}
function logo(id,name){const x=S.clubCodex.get(String(id));const u=get(x,['image_url','ImageURL'],'');return u?`<img class="club-logo" src="${esc(u)}" alt="${esc(name)}">`:`<div class="logo-fallback">${esc(String(name||'GW').slice(0,2).toUpperCase())}</div>`}
function render(){const played=S.results.length,expected=expectedTotal(),pct=expected?Math.min(100,Math.round(played/expected*100)):0,next=nextFixture();const worldName=get(S.world,['game_world_name','IMC GW Name'],window.IMC_GAME_WORLD?.name||'Road To History');const home=get(next,['home_name','home_team','home_club_name'],'Home'),away=get(next,['away_name','away_team','away_club_name'],'Away');const hid=get(next,['home_sm_club_id','home_club_id'],'');const when=dateVal(next);root.innerHTML=`<div class="gw-home"><header class="top"><button class="menu" id="menuBtn">☰</button><div class="brandline"><div class="imc-mark"><span class="crown">♛</span><b>IMC</b><small>ITALIAN MASTERS CLUB</small></div><i class="vline"></i><div class="world-title"><strong>GW001</strong><span>${esc(worldName.toUpperCase())}</span></div></div><span></span></header><section class="hero"><div class="hero-script">Road to History</div><div class="hero-crown">♛</div></section><main class="content"><section class="panel progress-panel"><div class="eyebrow">SEASON PROGRESS</div><div class="progress-row"><div class="ring" style="--p:${pct}"><strong>${pct}%</strong></div><div class="progress-copy"><b>${played} / ${expected}</b><span>MATCHES PLAYED</span></div></div></section><section class="kpis"><article class="kpi"><b>${S.competitions.length}</b><span>COMPETITIONS</span></article><article class="kpi"><b>${S.clubs.length}</b><span>CLUBS</span></article><article class="kpi"><b>${activeManagers().length}</b><span>MANAGERS<br>(ACTIVE)</span></article></section><a class="panel next" href="./legacy.html#fixtures"><div>${next?logo(hid,home):'<div class="logo-fallback">GW</div>'}</div><div><small>NEXT MATCH</small><strong>${next?`${esc(home)}<br>vs ${esc(away)}`:'No fixture available'}</strong><span>${next?fmtDate(when):'—'}${next?' · '+esc(get(next,['competition_group_name','competition_name','competition_key'],'Fixture')):''}</span></div><div class="chev">›</div></a></main><nav class="bottom"><a class="active" href="./"><b>◉</b><span>World</span></a><a href="./legacy.html#competitions"><b>♕</b><span>Competitions</span></a><a href="./legacy.html#clubs"><b>◇</b><span>Clubs</span></a><a href="./legacy.html#managers"><b>♙</b><span>People</span></a><a href="./legacy.html#players"><b>▥</b><span>Data</span></a></nav><dialog id="menu"><button id="close">×</button><a href="./legacy.html#competitions">Competitions</a><a href="./legacy.html#clubs">Clubs</a><a href="./legacy.html#managers">Managers</a><a href="./legacy.html#scores">Scores</a><a href="./legacy.html#fixtures">Fixtures</a><a href="./legacy.html#players">Players</a><a href="./legacy.html#transfers">Transfers</a><a href="./legacy.html#reports">Reports</a></dialog></div>`;const d=document.getElementById('menu');document.getElementById('menuBtn').onclick=()=>d.showModal();document.getElementById('close').onclick=()=>d.close()}
})();
