(function(){
"use strict";
const BUILD="1.0";
const SUPABASE_URL="https://toanuzojdkfjgucztpze.supabase.co";
const SUPABASE_KEY="sb_publishable_DYmVU7yEavK_ddsdNMUjcg_a7HesB-l";
const WORLDS={GW001:"Road To History",GW002:"Gold 558",GW003:"Gold 557",GW004:"World League",GW005:"Hall Of Famers",GW006:"Master League World",GW007:"The Four Kingdoms",GW008:"Gold 1",GW009:"Kick Off"};
const REMEMBER_KEY="imc_nexus_remember_access",USERNAME_KEY="imc_nexus_username";
let db=null,identity=null,currentView="clubhouse",selectedWorld=null,selectedSeason=null,lastWorldRoute=null,adminAssetsPromise=null;
function el(id){return document.getElementById(id)}
function technicalEmail(username){return username.trim().toLowerCase()+"@users.imcnexus.local"}
function setStatus(msg,isError){const n=el("status");if(!n)return;n.textContent=msg||"";n.classList.toggle("error",!!isError)}
function show(id){["loginView","appView"].forEach(x=>{const n=el(x);if(n)n.hidden=x!==id})}
function worldContent(){return el("worldArea")&&el("worldArea").querySelector("[data-gw-content]")}
function isAdmin(){return String(identity&&identity.role||"").trim().toLowerCase()==="admin"}
function syncAdminLauncher(){const b=el("adminLauncher");if(b)b.hidden=!identity||!isAdmin()||currentView==="admin"}
function loadAdminAssets(){if(window.IMC_ADMIN)return Promise.resolve();if(adminAssetsPromise)return adminAssetsPromise;adminAssetsPromise=new Promise((resolve,reject)=>{if(!document.querySelector('link[data-nexus-admin-css]')){const l=document.createElement("link");l.rel="stylesheet";l.href="v1/modules/admin/admin.css?v=1.0.0";l.dataset.nexusAdminCss="1";document.head.appendChild(l)}const existing=document.querySelector('script[data-nexus-admin-js]');if(existing){existing.addEventListener("load",()=>resolve());existing.addEventListener("error",reject);return}const s=document.createElement("script");s.src="v1/modules/admin/admin.js?v=1.0.1";s.dataset.nexusAdminJs="1";s.onload=()=>resolve();s.onerror=reject;document.body.appendChild(s)});return adminAssetsPromise}
function unmountWorldModules(){["IMC_TEAM_HUB","IMC_MANAGERS","IMC_COMPETITIONS","IMC_TROPHY_ROOM","IMC_GAME_WORLD_NEWS_FEED","IMC_RESULTS","IMC_MATCH_REPORT","IMC_MANAGER_DETAIL","IMC_COMPETITION_DETAIL","IMC_TEAM_DETAIL","IMC_SYNTEX","IMC_TRANSFERS","IMC_TRANSFER_DETAIL","IMC_ROAD_CHRONICLE_ISSUES","IMC_ADMIN"].forEach(k=>{if(window[k]&&window[k].unmount)window[k].unmount()})}
async function loadIdentity(user){const nx=await db.from("nexus_users").select("user_id,manager_id,app_role,is_active,must_change_password").eq("user_id",user.id).maybeSingle();if(nx.error)throw nx.error;if(!nx.data||!nx.data.manager_id)throw new Error("Account Nexus non associato a un manager IMC");const r=await db.from("imc_users").select("manager_id,username,role,must_change_password").eq("manager_id",nx.data.manager_id).maybeSingle();if(r.error)throw r.error;return{manager_id:nx.data.manager_id,username:r.data?.username||nx.data.manager_id,role:r.data?.role||nx.data.app_role,must_change_password:r.data?.must_change_password??nx.data.must_change_password};}
function renderAccount(){el("userName").textContent=identity.username||"Nexus User";el("managerId").textContent=identity.manager_id||""}
function mountNavigation(){if(!window.IMC_NAVIGATION)throw new Error("Modulo Navigation non disponibile");window.IMC_NAVIGATION.mount({host:el("navigationHost"),current:"clubhouse"})}
function nexusVisitorId(){const key="imc_nexus_visitor_id";let value="";try{value=localStorage.getItem(key)||""}catch(_){value=""}if(value&&value.length>=8)return value;if(window.crypto&&typeof window.crypto.randomUUID==="function")value=window.crypto.randomUUID();else value="nx-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2);try{localStorage.setItem(key,value)}catch(_){}return value}
async function registerAnalyticsAccess(){const sessionKey="imc_nexus_access_registered";try{if(sessionStorage.getItem(sessionKey)==="1")return}catch(_){}try{const r=await db.rpc("imc_nexus_gateway",{p_action:"analytics_track",p_args:{visitorId:nexusVisitorId()}});if(!r.error){try{sessionStorage.setItem(sessionKey,"1")}catch(_){}}}catch(_){} }
async function openClubHouse(){const previousWorld=selectedWorld;currentView="clubhouse";selectedWorld=null;selectedSeason=null;lastWorldRoute=null;if(window.IMC_SEASON_CONTEXT&&previousWorld)window.IMC_SEASON_CONTEXT.clear(previousWorld);unmountWorldModules();if(window.IMC_GAME_WORLD_SHELL)window.IMC_GAME_WORLD_SHELL.unmount();const navHost=el("navigationHost");if(navHost)navHost.hidden=true;if(window.IMC_NAVIGATION)window.IMC_NAVIGATION.setContext({current:"clubhouse",worldId:null,worldName:null});const host=el("moduleHost");host.hidden=false;const area=el("worldArea");area.hidden=true;area.innerHTML="";syncAdminLauncher();await window.IMC_CLUBHOUSE.mount({container:host,client:db,user:identity,managerId:identity.manager_id,username:identity.username})}
async function openClubHouseFeed(){if(currentView!=="clubhouse")await openClubHouse();currentView="clubhouse-feed";syncAdminLauncher();if(!window.IMC_CLUBHOUSE_FEED)throw new Error("Club House Feed non disponibile");window.IMC_CLUBHOUSE_FEED.show()}
async function openWorld(worldId){currentView="game-world";selectedWorld=worldId;selectedSeason=null;lastWorldRoute={target:"game-world",worldId};if(window.IMC_SEASON_CONTEXT)window.IMC_SEASON_CONTEXT.clear(worldId);const name=WORLDS[worldId]||worldId;const navHost=el("navigationHost");if(navHost)navHost.hidden=true;if(window.IMC_NAVIGATION)window.IMC_NAVIGATION.setContext({current:"game-world",worldId,worldName:name});if(window.IMC_CLUBHOUSE)window.IMC_CLUBHOUSE.unmount();unmountWorldModules();el("moduleHost").hidden=true;const area=el("worldArea");area.hidden=false;syncAdminLauncher();const active=await window.IMC_GAME_WORLD_SHELL.mount({container:area,client:db,managerId:identity.manager_id,worldId,worldName:name});selectedSeason=Number(active)||null;if(window.IMC_SEASON_CONTEXT&&selectedSeason)window.IMC_SEASON_CONTEXT.set(worldId,selectedSeason)}
async function openAdmin(){const previousWorld=selectedWorld;if(!isAdmin())return;await loadAdminAssets();currentView="admin";selectedWorld=null;selectedSeason=null;lastWorldRoute=null;if(window.IMC_SEASON_CONTEXT&&previousWorld)window.IMC_SEASON_CONTEXT.clear(previousWorld);if(window.IMC_CLUBHOUSE)window.IMC_CLUBHOUSE.unmount();if(window.IMC_GAME_WORLD_SHELL)window.IMC_GAME_WORLD_SHELL.unmount();unmountWorldModules();const navHost=el("navigationHost");if(navHost)navHost.hidden=true;const area=el("worldArea");area.hidden=true;area.innerHTML="";const host=el("moduleHost");host.hidden=false;host.innerHTML="";syncAdminLauncher();if(!window.IMC_ADMIN)throw new Error("Modulo Admin non disponibile");await window.IMC_ADMIN.mount({container:host,client:db,user:identity})}
async function openWorldSection(worldId,section){if(worldId!==selectedWorld)await openWorld(worldId);lastWorldRoute={target:"game-world-section",worldId,section};const content=worldContent();if(!content)return;unmountWorldModules();if(section==="home"){const active=await window.IMC_GAME_WORLD_SHELL.setWorld({worldId,worldName:WORLDS[worldId]||worldId,season:selectedSeason});selectedSeason=Number(active)||selectedSeason;if(window.IMC_SEASON_CONTEXT&&selectedSeason)window.IMC_SEASON_CONTEXT.set(worldId,selectedSeason);return}if(section==="teams"){await window.IMC_TEAM_HUB.mount({container:content,client:db,worldId});return}if(section==="managers"){await window.IMC_MANAGERS.mount({container:content,client:db,worldId});return}if(section==="competitions"){await window.IMC_COMPETITIONS.mount({container:content,client:db,worldId,worldName:WORLDS[worldId]||worldId});return}if(section==="transfers"){await window.IMC_TRANSFERS.mount({container:content,client:db,worldId});return}if(section==="trophy-room"){await window.IMC_TROPHY_ROOM.mount({container:content,client:db,worldId});return}if(section==="news-feed"){await window.IMC_GAME_WORLD_NEWS_FEED.mount({container:content,client:db,worldId,worldName:WORLDS[worldId]||worldId});return}if(section==="road-chronicle-issues"){if(!window.IMC_ROAD_CHRONICLE_ISSUES)throw new Error("Modulo Road Chronicle Issues non disponibile");window.IMC_ROAD_CHRONICLE_ISSUES.mount({container:content,worldId});return}content.innerHTML='<div class="gw-shell-empty">Sezione pronta per il relativo modulo autonomo.</div>'}
async function openManagerDetail(d){lastWorldRoute={...d,target:"manager-detail"};const content=worldContent();if(!content)return;unmountWorldModules();await window.IMC_MANAGER_DETAIL.mount({container:content,client:db,worldId:d.worldId,managerId:d.managerId,smManagerId:d.smManagerId||null,name:d.name||d.managerId})}
async function openCompetitionDetail(d){lastWorldRoute={...d,target:"competition-detail"};const content=worldContent();if(!content)return;unmountWorldModules();await window.IMC_COMPETITION_DETAIL.mount({container:content,client:db,worldId:d.worldId,competitionKey:d.competitionKey,name:d.name||d.competitionKey})}
async function openTeamDetail(d){lastWorldRoute={...d,target:"team-detail"};const content=worldContent();if(!content)return;unmountWorldModules();await window.IMC_TEAM_DETAIL.mount({container:content,client:db,worldId:d.worldId,teamType:d.teamType,teamId:d.teamId||null,teamName:d.teamName||"",teamNames:d.teamNames||[],nationId:d.nationId||null})}
async function openTransferDetail(d){lastWorldRoute={...d,target:"transfer-detail"};const content=worldContent();if(!content)return;unmountWorldModules();await window.IMC_TRANSFER_DETAIL.mount({container:content,client:db,worldId:d.worldId,transferId:d.transferId||"",transfer:d.transfer||null})}
async function openMatchReport(d){lastWorldRoute={...d,target:"match-report"};const content=worldContent();if(!content)return;unmountWorldModules();await window.IMC_MATCH_REPORT.mount({container:content,client:db,worldId:d.worldId,fixtureId:d.fixtureId})}
async function refreshSeasonRoute(){const r=lastWorldRoute;if(!r)return;if(r.target==="competition-detail"){await openCompetitionDetail(r);return}if(r.target==="game-world-section"&&(r.section==="competitions"||r.section==="trophy-room")){await openWorldSection(r.worldId,r.section);return}if(r.target==="match-report"){await openMatchReport(r)}}
async function enter(user){identity=await loadIdentity(user);renderAccount();show("appView");mountNavigation();syncAdminLauncher();await registerAnalyticsAccess();await openClubHouse()}
async function boot(){document.title="IMC Nexus · Build 1.0";db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});if(window.IMC_SEASON_CONTEXT)window.IMC_SEASON_CONTEXT.attach(db);window.__IMC_NEXUS_CLIENT__=db;const remember=localStorage.getItem(REMEMBER_KEY)!=="0";const cb=el("rememberAccess");if(cb)cb.checked=remember;const saved=localStorage.getItem(USERNAME_KEY);if(saved&&el("username"))el("username").value=saved;const r=await db.auth.getSession();if(r.error)throw r.error;if(remember&&r.data.session&&r.data.session.user){try{await enter(r.data.session.user);return}catch(e){await db.auth.signOut()}}show("loginView")}
document.addEventListener("submit",async e=>{if(e.target.id!=="loginForm")return;e.preventDefault();setStatus("Accesso in corso…");const username=el("username").value.trim(),password=el("password").value,remember=!!el("rememberAccess")?.checked;if(!username||!password){setStatus("Inserisci username e password",true);return}try{localStorage.setItem(REMEMBER_KEY,remember?"1":"0");if(remember)localStorage.setItem(USERNAME_KEY,username);else localStorage.removeItem(USERNAME_KEY);const auth=await db.auth.signInWithPassword({email:technicalEmail(username),password});if(auth.error)throw auth.error;await enter(auth.data.user);setStatus("")}catch(err){setStatus(err.message||"Accesso non riuscito",true)}});
document.addEventListener("nexus:season-change",async e=>{const d=e.detail||{},worldId=String(d.worldId||"");const season=Number(d.season);if(!worldId||worldId!==selectedWorld||!Number.isInteger(season)||season<1)return;selectedSeason=season;if(window.IMC_SEASON_CONTEXT)window.IMC_SEASON_CONTEXT.set(worldId,season);try{await refreshSeasonRoute()}catch(err){const content=worldContent();if(content)content.innerHTML='<div class="gw-shell-empty">'+String(err.message||err)+'</div>'}});
document.addEventListener("nexus:navigate",async e=>{const d=e.detail||{};try{if(d.target==="clubhouse"){await openClubHouse();return}if(d.target==="clubhouse-feed"){await openClubHouseFeed();return}if(d.target==="game-world"&&d.worldId){await openWorld(String(d.worldId));return}if(d.target==="game-world-section"&&d.worldId&&d.section){await openWorldSection(String(d.worldId),String(d.section));return}if(d.target==="manager-detail"){await openManagerDetail(d);return}if(d.target==="competition-detail"){await openCompetitionDetail(d);return}if(d.target==="team-detail"){await openTeamDetail(d);return}if(d.target==="transfer-detail"){await openTransferDetail(d);return}if(d.target==="match-report"){await openMatchReport(d);return}}catch(err){const content=worldContent();if(content)content.innerHTML='<div class="gw-shell-empty">'+String(err.message||err)+'</div>'}});
document.addEventListener("click",async e=>{if(e.target.closest("#adminLauncher")){try{await openAdmin()}catch(err){console.error(err)}return}if(e.target.closest("#logout")){unmountWorldModules();if(window.IMC_CLUBHOUSE)window.IMC_CLUBHOUSE.unmount();if(window.IMC_GAME_WORLD_SHELL)window.IMC_GAME_WORLD_SHELL.unmount();if(window.IMC_NAVIGATION)window.IMC_NAVIGATION.unmount();if(window.IMC_SEASON_CONTEXT)window.IMC_SEASON_CONTEXT.clear();await db.auth.signOut();identity=null;selectedWorld=null;selectedSeason=null;lastWorldRoute=null;currentView="clubhouse";syncAdminLauncher();show("loginView");setStatus("")}});
boot().catch(e=>{show("loginView");setStatus(e.message||String(e),true)});
})();
