(function(){
"use strict";
const SUPABASE_URL="https://toanuzojdkfjgucztpze.supabase.co";
const SUPABASE_KEY="sb_publishable_DYmVU7yEavK_ddsdNMUjcg_a7HesB-l";
const WORLDS={GW001:"Road To History",GW002:"Gold 558",GW003:"Gold 557",GW004:"World League",GW005:"Hall Of Famers",GW006:"Master League World",GW007:"The Four Kingdoms",GW008:"Gold 1",GW009:"Kick Off",GW010:"GW010"};
let db=null,identity={manager_id:"",username:"Nexus",role:"public"},currentView="clubhouse",selectedWorld=null,selectedSeason=null,lastWorldRoute=null;
const el=id=>document.getElementById(id);
function showApp(){const login=el("loginView"),app=el("appView");if(login)login.hidden=true;if(app)app.hidden=false}
function worldContent(){return el("worldArea")&&el("worldArea").querySelector("[data-gw-content]")}
function unmountWorldModules(){["IMC_TEAM_HUB","IMC_MANAGERS","IMC_COMPETITIONS","IMC_TROPHY_ROOM","IMC_GAME_WORLD_NEWS_FEED","IMC_RESULTS","IMC_MATCH_REPORT","IMC_MANAGER_DETAIL","IMC_COMPETITION_DETAIL","IMC_TEAM_DETAIL","IMC_SYNTEX","IMC_TRANSFERS","IMC_TRANSFER_DETAIL","IMC_ROAD_CHRONICLE_ISSUES"].forEach(k=>{if(window[k]&&window[k].unmount)window[k].unmount()})}
function mountNavigation(){if(window.IMC_NAVIGATION)window.IMC_NAVIGATION.mount({host:el("navigationHost"),current:"clubhouse"})}
async function openClubHouse(){const previousWorld=selectedWorld;currentView="clubhouse";selectedWorld=null;selectedSeason=null;lastWorldRoute=null;if(window.IMC_SEASON_CONTEXT&&previousWorld)window.IMC_SEASON_CONTEXT.clear(previousWorld);unmountWorldModules();if(window.IMC_GAME_WORLD_SHELL)window.IMC_GAME_WORLD_SHELL.unmount();const navHost=el("navigationHost");if(navHost)navHost.hidden=true;if(window.IMC_NAVIGATION)window.IMC_NAVIGATION.setContext({current:"clubhouse",worldId:null,worldName:null});const host=el("moduleHost");host.hidden=false;const area=el("worldArea");area.hidden=true;area.innerHTML="";await window.IMC_CLUBHOUSE.mount({container:host,client:db,user:identity,managerId:"",username:"Nexus"})}
async function openClubHouseFeed(){if(currentView!=="clubhouse")await openClubHouse();currentView="clubhouse-feed";if(!window.IMC_CLUBHOUSE_FEED)throw new Error("Club House Feed non disponibile");window.IMC_CLUBHOUSE_FEED.show()}
async function openWorld(worldId){currentView="game-world";selectedWorld=worldId;selectedSeason=null;lastWorldRoute={target:"game-world",worldId};if(window.IMC_SEASON_CONTEXT)window.IMC_SEASON_CONTEXT.clear(worldId);const name=WORLDS[worldId]||worldId;const navHost=el("navigationHost");if(navHost)navHost.hidden=true;if(window.IMC_NAVIGATION)window.IMC_NAVIGATION.setContext({current:"game-world",worldId,worldName:name});if(window.IMC_CLUBHOUSE)window.IMC_CLUBHOUSE.unmount();unmountWorldModules();el("moduleHost").hidden=true;const area=el("worldArea");area.hidden=false;const active=await window.IMC_GAME_WORLD_SHELL.mount({container:area,client:db,managerId:"",worldId,worldName:name});selectedSeason=Number(active)||null;if(window.IMC_SEASON_CONTEXT&&selectedSeason)window.IMC_SEASON_CONTEXT.set(worldId,selectedSeason)}
async function openWorldSection(worldId,section){if(worldId!==selectedWorld)await openWorld(worldId);lastWorldRoute={target:"game-world-section",worldId,section};const content=worldContent();if(!content)return;unmountWorldModules();if(section==="home"){const active=await window.IMC_GAME_WORLD_SHELL.setWorld({worldId,worldName:WORLDS[worldId]||worldId,season:selectedSeason});selectedSeason=Number(active)||selectedSeason;return}if(section==="teams"){await window.IMC_TEAM_HUB.mount({container:content,client:db,worldId});return}if(section==="managers"){await window.IMC_MANAGERS.mount({container:content,client:db,worldId});return}if(section==="competitions"){await window.IMC_COMPETITIONS.mount({container:content,client:db,worldId,worldName:WORLDS[worldId]||worldId});return}if(section==="transfers"){await window.IMC_TRANSFERS.mount({container:content,client:db,worldId});return}if(section==="trophy-room"){await window.IMC_TROPHY_ROOM.mount({container:content,client:db,worldId});return}if(section==="news-feed"){await window.IMC_GAME_WORLD_NEWS_FEED.mount({container:content,client:db,worldId,worldName:WORLDS[worldId]||worldId});return}if(section==="road-chronicle-issues"&&window.IMC_ROAD_CHRONICLE_ISSUES){window.IMC_ROAD_CHRONICLE_ISSUES.mount({container:content,worldId});return}content.innerHTML='<div class="gw-shell-empty">Sezione pronta per il relativo modulo autonomo.</div>'}
async function openManagerDetail(d){lastWorldRoute={...d,target:"manager-detail"};const content=worldContent();if(content)await window.IMC_MANAGER_DETAIL.mount({container:content,client:db,worldId:d.worldId,managerId:d.managerId,smManagerId:d.smManagerId||null,name:d.name||d.managerId})}
async function openCompetitionDetail(d){lastWorldRoute={...d,target:"competition-detail"};const content=worldContent();if(content)await window.IMC_COMPETITION_DETAIL.mount({container:content,client:db,worldId:d.worldId,competitionKey:d.competitionKey,name:d.name||d.competitionKey})}
async function openTeamDetail(d){lastWorldRoute={...d,target:"team-detail"};const content=worldContent();if(content)await window.IMC_TEAM_DETAIL.mount({container:content,client:db,worldId:d.worldId,teamType:d.teamType,teamId:d.teamId||null,teamName:d.teamName||"",teamNames:d.teamNames||[],nationId:d.nationId||null})}
async function openTransferDetail(d){lastWorldRoute={...d,target:"transfer-detail"};const content=worldContent();if(content)await window.IMC_TRANSFER_DETAIL.mount({container:content,client:db,worldId:d.worldId,transferId:d.transferId||"",transfer:d.transfer||null})}
async function openMatchReport(d){lastWorldRoute={...d,target:"match-report"};const content=worldContent();if(content)await window.IMC_MATCH_REPORT.mount({container:content,client:db,worldId:d.worldId,fixtureId:d.fixtureId})}
async function boot(){document.title="IMC Nexus · Public";db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});window.__IMC_NEXUS_CLIENT__=db;if(window.IMC_SEASON_CONTEXT)window.IMC_SEASON_CONTEXT.attach(db);showApp();mountNavigation();await openClubHouse()}
document.addEventListener("nexus:navigate",async e=>{const d=e.detail||{};try{if(d.target==="clubhouse")return await openClubHouse();if(d.target==="clubhouse-feed")return await openClubHouseFeed();if(d.target==="game-world"&&d.worldId)return await openWorld(String(d.worldId));if(d.target==="game-world-section"&&d.worldId&&d.section)return await openWorldSection(String(d.worldId),String(d.section));if(d.target==="manager-detail")return await openManagerDetail(d);if(d.target==="competition-detail")return await openCompetitionDetail(d);if(d.target==="team-detail")return await openTeamDetail(d);if(d.target==="transfer-detail")return await openTransferDetail(d);if(d.target==="match-report")return await openMatchReport(d)}catch(err){const content=worldContent();if(content)content.innerHTML='<div class="gw-shell-empty">'+String(err.message||err)+'</div>'}});
document.addEventListener("nexus:season-change",async e=>{const d=e.detail||{},worldId=String(d.worldId||""),season=Number(d.season);if(worldId!==selectedWorld||!Number.isInteger(season)||season<1)return;selectedSeason=season;if(window.IMC_SEASON_CONTEXT)window.IMC_SEASON_CONTEXT.set(worldId,season);if(lastWorldRoute&&lastWorldRoute.target==="competition-detail")await openCompetitionDetail(lastWorldRoute)});
boot().catch(err=>{showApp();const host=el("moduleHost");if(host)host.innerHTML='<div class="gw-shell-empty">Nexus non disponibile: '+String(err.message||err)+'</div>'});
})();
