<?php
declare(strict_types=1);
require __DIR__.'/../nexus/core/bootstrap.php';
require __DIR__.'/../nexus/club-house/engine.php';
require __DIR__.'/../nexus/club-house/national-results.php';
function ensure(bool $v,string $message): void {if(!$v)throw new RuntimeException($message);}
$people=[['manager_id'=>'A','full_name'=>'One','sm_manager_id'=>100],['manager_id'=>'B','full_name'=>'Two','sm_manager_id'=>200],['manager_id'=>'C','full_name'=>'Three','sm_manager_id'=>null]];
$assignment=['game_world_id'=>'GW001','assignment_type'=>'national_team','manager_id'=>'A','national_team_id'=>73,'start_date'=>'2026-07-01','end_date'=>'2026-07-10'];
$assignments=[$assignment,array_replace($assignment,['manager_id'=>'B','national_team_id'=>75,'end_date'=>null]),array_replace($assignment,['manager_id'=>'C','start_date'=>'2026-07-11','end_date'=>null])];
$mapping=[['world_id'=>73,'sm_id'=>73,'entity_id'=>30],['world_id'=>75,'sm_id'=>75,'entity_id'=>32],['world_id'=>30,'sm_id'=>30,'entity_id'=>69]];
ensure(ch_nation_team(30,ch_nation_aliases($mapping))===30,'Never confuse core national ID with world national ID');
$row=['game_world_id'=>'GW001','sm_fixture_id'=>1,'match_date'=>'2026-07-01','imc_season'=>1,'competition_group'=>'NATIONS','sm_action'=>'worldcup','competition_key'=>'GW001|NATIONS|worldcup','home_sm_club_id'=>73,'away_sm_club_id'=>75,'home_name'=>'Nation A','away_name'=>'Nation B','home_score'=>2,'away_score'=>1,'home_sm_manager_id'=>200,'away_sm_manager_id'=>100];
$rows=[$row,array_replace($row,['sm_fixture_id'=>2,'match_date'=>'2026-06-30']),array_replace($row,['sm_fixture_id'=>3,'match_date'=>'2026-07-10','imc_season'=>2]),array_replace($row,['sm_fixture_id'=>4,'match_date'=>'2026-07-11']),array_replace($row,['sm_fixture_id'=>5,'game_world_id'=>'GW002']),array_replace($row,['sm_fixture_id'=>6,'competition_group'=>'DOMESTIC','sm_action'=>'league','competition_key'=>'league'])];
$d=ch_national_rows($rows,'GW001',$people,'A',$assignments,$mapping);
ensure($d['managers']['A']['stats']['played']===2,'Inclusive start/end and all seasons');
ensure($d['managers']['C']['stats']['played']===1,'Successor without SM ID counts by assignment');
ensure($d['managers']['B']['stats']['played']===3,'Opponent uses own tenure dates');
ensure(count($d['matches'])===2&&$d['matches'][0]['opponent_id']==='B','H2H assignment identity');
ensure($d['managers']['A']['stats']['matched_by_id']===0&&$d['managers']['A']['stats']['matched_by_assignment']===2,'Never use Results manager ID');
$duplicate=ch_national_rows([$row,array_replace($row,['home_sm_manager_id'=>999])],'GW001',$people,'A',$assignments,$mapping);
ensure(count($duplicate['matches'])===1,'Deduplicate fixture; stale Result manager IDs ignored');
$conflict=ch_national_rows([$row,array_replace($row,['home_score'=>9])],'GW001',$people,'A',$assignments,$mapping);
ensure(count($conflict['matches'])===0&&$conflict['national_coverage']['excluded_fixtures']===1,'Conflicting Results excluded');
$overlap=ch_national_rows([$row],'GW001',$people,'A',array_merge($assignments,[array_replace($assignment,['manager_id'=>'C'])]),$mapping);
ensure($overlap['managers']['A']['stats']['played']===0&&$overlap['managers']['B']['stats']['played']===1,'Ambiguous side excluded; opposite side valid');
ensure($overlap['national_coverage']['ambiguous_sides']===1&&$overlap['managers']['A']['excluded']===1,'Overlaps flagged');
$wrong=ch_national_rows([$row],'GW001',$people,'A',[array_replace($assignment,['game_world_id'=>'GW002']),array_replace($assignment,['assignment_type'=>'club']),array_replace($assignment,['start_date'=>null])],$mapping);
ensure($wrong['managers']['A']['stats']['played']===0,'No cross-world, club tenure or missing date fallback');
$gap=ch_national_rows([array_replace($row,['match_date'=>'2026-07-15'])],'GW001',$people,'A',[$assignment,array_replace($assignment,['start_date'=>'2026-07-20','end_date'=>null])],$mapping);
ensure($gap['managers']['A']['stats']['played']===0,'Gap between tenures excluded');
$same=ch_national_rows([$row],'GW001',$people,'A',[$assignment,$assignment],$mapping);
ensure($same['managers']['A']['stats']['played']===1,'Duplicate same-manager assignments do not duplicate fixture');
$club=ch_init($people);$club['managers']['A']['stats']['played']=3;$merged=ch_scope_merge($club,$d);
ensure($merged['managers']['A']['stats']['played']===5&&count($merged['matches'])===2,'Global sums club and national without report duplication');
$db=new PDO('mysql:host=127.0.0.1;port=3306;charset=utf8mb4','root',getenv('MYSQL_TEST_PASSWORD'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$db->exec('CREATE DATABASE IF NOT EXISTS nexus_national_assignments_test');$db->exec('USE nexus_national_assignments_test');
$db->exec('CREATE TEMPORARY TABLE GW001_IMC_Results (game_world_id VARCHAR(16),sm_fixture_id BIGINT,match_date DATE,imc_season INT,competition_group VARCHAR(32),sm_action VARCHAR(32),competition_key VARCHAR(255),home_sm_club_id BIGINT,away_sm_club_id BIGINT,home_name VARCHAR(255),away_name VARCHAR(255),home_score INT,away_score INT,home_sm_manager_id BIGINT,away_sm_manager_id BIGINT)');
$stmt=$db->prepare('INSERT INTO GW001_IMC_Results VALUES ('.implode(',',array_fill(0,count($row),'?')).')');foreach($rows as $r)$stmt->execute(array_values($r));
$sql=ch_national_read($db,'GW001',$people,'A',$assignments,$mapping);
ensure($sql['managers']['A']['stats']['played']===2,'SQL reads Results only, no Match Report table required');
echo "PASS: national Results, world/team/date attribution, inclusive boundaries, transfers, gaps, overlapping tenures, duplicates, absent and misleading SM IDs, all seasons, Global sum\n";
