(()=>{
const API='/sensible-soccer-academy/live/api.php',TAU=Math.PI*2,P=-Math.PI/2,$=id=>document.getElementById(id);
const E=[['Max Palace','EU'],['Luciano Catalano','EU'],['Tommaso Mello','SA'],['Sir Simone','EU'],['Ringhio Gattuso','EU'],['Vincenzo Martorano','SA'],['Andrea Meneghini','EU'],['Davide Rapisarda','EU'],['Vardan Minasyan','SA'],['Francesco Senesi','EU'],['Oleksandr Medvid','EU'],['Giuseppe Trovato','SA'],['Luciano Tana','EU'],['Carlo Colombo','EU'],['Nick Pepe','SA'],['Chicco Belin','EU'],['Marco Aloisi','EU'],['Cosimo Lonoce','SA'],['Nessun manager 1','SA'],['Nessun manager 2','SA'],['Nessun manager 3','SA'],['Nessun manager 4','SA'],['Nessun manager 5','SA'],['Nessun manager 6','SA']].map(x=>({name:x[0],region:x[1]}));
const T={SA:['Peñarol','Colo-Colo','Millonarios','Bolívar','Olimpia','Alianza Lima','Santos','São Paulo','Grêmio','Argentinos Juniors',"Newell's Old Boys",'Vélez Sarsfield'],EU:['Atalanta','Ferencváros','IFK Göteborg','Aberdeen','Siviglia','West Ham United','Stoccarda','Anderlecht','Ajax','Olympique Lyonnais','Dinamo Zagreb','Benfica']};
const ids={'Peñarol':376,'Colo-Colo':362,'Millonarios':618,'Bolívar':1238,'Olimpia':613,'Alianza Lima':621,'Santos':304,'São Paulo':306,'Grêmio':602,'Argentinos Juniors':267,"Newell's Old Boys":278,'Vélez Sarsfield':285,'Atalanta':96,'Ferencváros':1416,'IFK Göteborg':471,'Aberdeen':420,'Siviglia':168,'West Ham United':85,'Stoccarda':417,'Anderlecht':353,'Ajax':180,'Olympique Lyonnais':329,'Dinamo Zagreb':365,'Benfica':218};
const mw=$('mw'),tw=$('tw'),mc=mw?.getContext('2d'),tc=tw?.getContext('2d');if(!mw||!tw)return;
let M=E.map((_,i)=>i),teams={EU:[...T.EU],SA:[...T.SA]},ma=0,ta=0,phase='',lastSeq=0,lastAssignmentShown=0,lastTs=0,reg='EU';const imgs={};Object.entries(ids).forEach(([n,id])=>{const im=new Image();im.onload=()=>drawAll();im.src='../draw/crest.php?id='+id;imgs[n]=im});
const start=$('start');if(start){start.disabled=true;start.style.display='none'}const status=$('status');if(status)status.innerHTML='<strong>LIVE SPECTATOR</strong><br>Il sorteggio è controllato dall’host.';
function norm(a){return((a%TAU)+TAU)%TAU}function label(n){return n.replace(/ \d+$/,'')}function man(c,x,y,s,rr,empty){c.save();c.translate(x,y);if(empty){c.strokeStyle='#fff';c.lineWidth=2;c.strokeRect(-9*s,-17*s,18*s,31*s);c.fillStyle='#fff';c.font='900 '+12*s+'px Courier New';c.textAlign='center';c.fillText('?',0,2*s)}else{c.fillStyle='#d99d68';c.fillRect(-5*s,-17*s,10*s,8*s);c.fillStyle=rr==='SA'?'#d94a3f':'#367fd5';c.fillRect(-9*s,-8*s,18*s,15*s);c.fillStyle='#fff';c.fillRect(-7*s,7*s,14*s,7*s);c.fillStyle='#111';c.fillRect(-8*s,14*s,6*s,4*s);c.fillRect(2*s,14*s,6*s,4*s)}c.restore()}
function crest(c,n,size){const im=imgs[n];if(!im||!im.complete||!im.naturalWidth)return;c.save();const k=Math.min((size-4)/im.naturalWidth,(size-4)/im.naturalHeight),w=im.naturalWidth*k,h=im.naturalHeight*k;c.fillStyle='#fff';c.fillRect(-size/2,-size/2,size,size);c.drawImage(im,-w/2,-h/2,w,h);c.restore()}
function wheel(c,v,it,a,type,r){const W=v.width,C=W/2,R=W*.43,n=Math.max(1,it.length),s=TAU/n;c.clearRect(0,0,W,W);for(let i=0;i<n;i++){const rr=type==='m'?E[it[i]].region:r,a0=a+i*s,a1=a0+s,mid=a0+s/2;c.beginPath();c.moveTo(C,C);c.arc(C,C,R,a0,a1);c.closePath();c.fillStyle=rr==='SA'?(i%2?'#9b3b34':'#b45143'):(i%2?'#1d5fa7':'#2879c7');c.fill();c.lineWidth=3;c.strokeStyle='#f0e6b4';c.stroke();const x=C+Math.cos(mid)*R*.68,y=C+Math.sin(mid)*R*.68;c.save();c.translate(x,y);c.rotate(mid+Math.PI/2);c.textAlign='center';c.fillStyle='#fff';if(type==='m'){const e=E[it[i]],empty=e.name.startsWith('Nessun manager');man(c,0,-16,n>18?.82:1,rr,empty);c.font='900 '+(n>18?11:13)+'px Courier New';let l=label(e.name);if(l.length>18)l=l.slice(0,17)+'…';c.fillText(l,0,25)}else{const name=it[i];crest(c,name,n>10?32:42);c.font='900 '+(n>10?11:14)+'px Courier New';let l=name;if(l.length>18)l=l.slice(0,17)+'…';c.fillText(l,0,n>10?22:29)}c.restore()}c.beginPath();c.arc(C,C,R,0,TAU);c.lineWidth=12;c.strokeStyle='#07152c';c.stroke()}
function drawAll(){wheel(mc,mw,M,ma,'m','EU');if(teams[reg]?.length)wheel(tc,tw,teams[reg],ta,'t',reg)}
function targetAngle(list,name,type,current){const ix=list.findIndex(v=>(type==='m'?E[v].name:v)===name);if(ix<0)return current;const s=TAU/list.length,desired=P-(ix+.5)*s;return current+4*TAU+norm(desired-current)}
function ease(which,to,dur=850){const from=which==='m'?ma:ta,t0=performance.now();function f(t){const p=Math.min(1,(t-t0)/dur),v=from+(to-from)*(1-Math.pow(1-p,4));if(which==='m'){ma=v;wheel(mc,mw,M,ma,'m','EU')}else{ta=v;wheel(tc,tw,teams[reg],ta,'t',reg)}if(p<1)requestAnimationFrame(f)}requestAnimationFrame(f)}
function apply(arr){if(!Array.isArray(arr))return;for(const a of arr){if(a.seq<=lastSeq)continue;const mi=M.findIndex(i=>E[i].name===a.manager);if(mi>=0)M.splice(mi,1);const ti=teams[a.region]?.indexOf(a.team);if(ti>=0)teams[a.region].splice(ti,1);lastSeq=a.seq}const h=$('history');if(h)h.innerHTML=arr.map(a=>'<div class="hrow"><span>#'+a.seq+'</span><b>'+label(a.manager)+'</b><div class="clubcell"><img class="mini" src="../draw/crest.php?id='+ids[a.team]+'"><b>'+a.team+'</b></div><span>'+(a.region==='SA'?'S. AMERICA':'EUROPE')+'</span></div>').join('');drawAll()}
function popup(a){if(!a||a.seq===lastAssignmentShown)return;lastAssignmentShown=a.seq;if($('pm'))$('pm').textContent=label(a.manager);if($('pr'))$('pr').textContent=a.region==='SA'?'SOUTH AMERICA':'EUROPE';if($('pt'))$('pt').textContent=a.team;if($('pcrest'))$('pcrest').src='../draw/crest.php?id='+ids[a.team];$('popup')?.classList.add('show');setTimeout(()=>$('popup')?.classList.remove('show'),4500)}
function loop(ts){if(!lastTs)lastTs=ts;const dt=(ts-lastTs)/1000;lastTs=ts;if(phase==='manager_spinning'){ma+=dt*7;wheel(mc,mw,M,ma,'m','EU')}if(phase==='team_spinning'){ta+=dt*7;wheel(tc,tw,teams[reg],ta,'t',reg)}requestAnimationFrame(loop)}requestAnimationFrame(loop);
async function poll(){try{const r=await fetch(API+'?t='+Date.now(),{cache:'no-store'}),s=await r.json();if(!s.ok)return;const prev=phase;phase=s.phase||'idle';if(phase==='manager_spinning'&&prev!==phase){$('teamstage')?.classList.remove('show');if($('mwinner'))$('mwinner').textContent='SPINNING...'}if(phase==='manager_selected'&&s.current_manager){const to=targetAngle(M,s.current_manager,'m',ma);ease('m',to);if($('mwinner'))$('mwinner').textContent=label(s.current_manager);reg=s.current_region||'EU';$('teamstage')?.classList.add('show');ta=0;wheel(tc,tw,teams[reg],ta,'t',reg)}if(phase==='team_spinning'){reg=s.current_region||reg;$('teamstage')?.classList.add('show');if($('twinner'))$('twinner').textContent='SPINNING...'}if(Array.isArray(s.assignments)&&s.assignments.length>lastSeq){const a=s.assignments[s.assignments.length-1];reg=a.region;const to=targetAngle(teams[reg],a.team,'t',ta);ease('t',to);if($('mwinner'))$('mwinner').textContent=label(a.manager);if($('twinner'))$('twinner').textContent=a.team;popup(a);apply(s.assignments)}if(s.event==='completed'){phase='idle';if($('status'))$('status').innerHTML='<strong>DRAW COMPLETE · 24/24</strong><br>Replay ufficiale disponibile.'}if($('counter'))$('counter').innerHTML=Math.max(0,24-lastSeq)+' SLOT<br>'+Math.max(0,24-lastSeq)+' CLUB'}catch(e){}}
setInterval(poll,400);poll();drawAll();
})();