<?php
declare(strict_types=1);require dirname(__DIR__).'/core/bootstrap.php';
try{$c=nexus_config();$gw=nexus_world($_GET['world']??'');$season=nexus_season($_GET['season']??null);$id=(int)($_GET['id']??0);if($id<1)throw new InvalidArgumentException('invalid_club');$core=nexus_db($c,'core');$m=nexus_rows($core,'SELECT `SM Club ID` sm_club_id,`SM World Club ID` world_id,`Club Name` name FROM `IMC Game World Club Mapping` WHERE `Game World`=? AND `Club ID`=? LIMIT 1',[$gw,$id]);if(!$m)throw new InvalidArgumentException('club_not_found');$sm=(int)$m[0]['world_id'];$db=nexus_db($c,nexus_target($c,$gw));$table=nexus_table($gw,'Match_Report');$w='(home_sm_club_id=? OR away_sm_club_id=?)';$p=[$sm,$sm];if($season!==null){$w.=' AND imc_season=?';$p[]=$season;}$rows=nexus_rows($db,'SELECT sm_fixture_id,competition_key,match_date,home_sm_club_id,home_name,away_sm_club_id,away_name,home_score,away_score,stadium_name,attendance,team_stats_json,players_json,events_json,home_manager_name,away_manager_name FROM `'.$table.'` WHERE '.$w.' ORDER BY match_date DESC,sm_fixture_id DESC',$p);
$transfers=[];try{$tt=nexus_table($gw,'Transfers');$transfers=nexus_rows($db,'SELECT player_id,player_name,player_image,club_from,from_sm_world_club_id,club_to,to_sm_world_club_id,normalized_transfer_date,normalized_season,imc_season,amount_text FROM `'.$tt.'` WHERE (from_sm_world_club_id=? OR to_sm_world_club_id=?) ORDER BY (normalized_transfer_date IS NULL),normalized_transfer_date DESC,imc_transfer_number DESC LIMIT 500',[$sm,$sm]);}catch(Throwable $e){$transfers=[];}
$sum=['played'=>0,'won'=>0,'drawn'=>0,'lost'=>0,'gf'=>0,'ga'=>0,'attendance_total'=>0,'attendance_matches'=>0,'attendance_max'=>0];$players=[];$opponents=[];
foreach($rows as $r){$home=(int)$r['home_sm_club_id']===$sm;$side=$home?'home':'away';$gf=(int)($home?$r['home_score']:$r['away_score']);$ga=(int)($home?$r['away_score']:$r['home_score']);$sum['played']++;$sum['gf']+=$gf;$sum['ga']+=$ga;if($gf>$ga)$sum['won']++;elseif($gf===$ga)$sum['drawn']++;else$sum['lost']++;if($r['attendance']!==null){$a=(int)$r['attendance'];$sum['attendance_total']+=$a;$sum['attendance_matches']++;$sum['attendance_max']=max($sum['attendance_max'],$a);}$opp=$home?$r['away_name']:$r['home_name'];if(!isset($opponents[$opp]))$opponents[$opp]=['opponent'=>$opp,'played'=>0,'won'=>0,'drawn'=>0,'lost'=>0,'gf'=>0,'ga'=>0];$o=&$opponents[$opp];$o['played']++;$o['gf']+=$gf;$o['ga']+=$ga;if($gf>$ga)$o['won']++;elseif($gf===$ga)$o['drawn']++;else$o['lost']++;unset($o);
$pj=json_decode((string)($r['players_json']??''),true);if(is_array($pj))foreach($pj as $pl){if(!is_array($pl)||strtolower((string)($pl['team_side']??''))!==$side)continue;$pid=(string)($pl['sm_player_id']??'');if($pid==='')continue;if(!isset($players[$pid]))$players[$pid]=['player_id'=>(int)$pid,'name'=>$pl['player_name']??'Player','appearances'=>0,'starts'=>0,'subs'=>0,'minutes'=>0,'goals'=>0,'assists'=>0,'rating_sum'=>0,'rating_count'=>0,'mom'=>0,'yellow'=>0,'red'=>0,'own_goals'=>0,'captain'=>0];$x=&$players[$pid];$starter=(int)($pl['starter']??0)===1;$sub=(int)($pl['substitute']??0)===1;$on=$pl['sub_on_minute']??null;$off=$pl['sub_off_minute']??null;$played=$starter||$on!==null;if($played)$x['appearances']++;if($starter)$x['starts']++;if($sub)$x['subs']++;if($played){if($starter)$mins=$off!==null?(int)$off:90;else$mins=$on!==null?max(0,90-(int)$on):0;$x['minutes']+=$mins;}$x['goals']+=(int)($pl['goals']??0);$x['assists']+=(int)($pl['assists']??0);if(isset($pl['rating'])&&is_numeric($pl['rating'])){$x['rating_sum']+=(float)$pl['rating'];$x['rating_count']++;}$x['mom']+=(int)($pl['man_of_match']??0);$x['yellow']+=(int)($pl['yellow_card']??0);$x['red']+=(int)($pl['red_card']??0);$x['own_goals']+=(int)($pl['own_goals']??0);$x['captain']+=(int)($pl['captain']??0);unset($x);}}
$sum['gd']=$sum['gf']-$sum['ga'];$sum['win_pct']=$sum['played']?round($sum['won']*100/$sum['played'],1):0;$sum['attendance_avg']=$sum['attendance_matches']?round($sum['attendance_total']/$sum['attendance_matches']):0;
$ids=array_map('intval',array_keys($players));$codex=[];if($ids){$pt=nexus_table($gw,'Player_Codex');$ph=implode(',',array_fill(0,count($ids),'?'));foreach(nexus_rows($db,'SELECT player_id,position,image_url FROM `'.$pt.'` WHERE player_id IN ('.$ph.')',$ids) as $pc)$codex[(string)$pc['player_id']]=$pc;}
foreach($players as $pid=>&$x){$x['rating']=$x['rating_count']?round($x['rating_sum']/$x['rating_count'],2):null;$x['position']=$codex[$pid]['position']??null;$x['image_url']=$codex[$pid]['image_url']??null;unset($x['rating_sum'],$x['rating_count']);}unset($x);usort($players,fn($a,$b)=>$b['appearances']<=>$a['appearances']);usort($opponents,fn($a,$b)=>$b['played']<=>$a['played']);nexus_out(['ok'=>true,'summary'=>$sum,'matches'=>$rows,'players'=>array_values($players),'h2h'=>array_values($opponents),'transfers'=>$transfers]);}
catch(InvalidArgumentException $e){nexus_out(['ok'=>false,'error'=>$e->getMessage()],422);}catch(Throwable $e){nexus_out(['ok'=>false,'error'=>'club_data_error'],500);}
