function metric(label,A,B,idx){let av=+A[idx],bv=+B[idx],sum=Math.max(av+bv,1),home=av/sum*100,fmt=v=>idx===8?`${v}%`:String(v);return `<div class="metric"><div class="metric-label"><span>${A[1]}</span><span>${B[1]}</span></div><div class="metric-values"><b>${fmt(av)}</b><b>${fmt(bv)}</b></div><div class="rail" style="background:linear-gradient(90deg,#d8ad4f 0%,#d8ad4f ${home}%,#2f80ff ${home}%,#2f80ff 100%)"></div><div class="metric-label metric-foot"><span>${label}</span><span>${label}</span></div></div>`}
function formScore(s){return [...s].reduce((n,c)=>n+(c==='W'?3:c==='D'?1:0),0)}
function market(A,B){let tableA=(11-A[4])/10,tableB=(11-B[4])/10,ptsMax=Math.max(A[5],B[5],1),ptsA=A[5]/ptsMax,ptsB=B[5]/ptsMax,formA=formScore(A[11])/15,formB=formScore(B[11])/15,attMax=Math.max(A[6],B[6],1),attA=A[6]/attMax,attB=B[6]/attMax,defMax=Math.max(A[7],B[7],1),defA=1-A[7]/(defMax*1.35),defB=1-B[7]/(defMax*1.35),posMax=Math.max(A[8],B[8],1),posA=A[8]/posMax,posB=B[8]/posMax,shotMax=Math.max(A[9],B[9],1),shotA=A[9]/shotMax,shotB=B[9]/shotMax;let sa=.26*tableA+.25*ptsA+.18*formA+.11*attA+.08*defA+.06*posA+.06*shotA,sb=.26*tableB+.25*ptsB+.18*formB+.11*attB+.08*defB+.06*posB+.06*shotB;sa*=1.055;let diff=sa-sb,draw=Math.max(.19,.31-Math.abs(diff)*.28),remain=1-draw,pa=remain/(1+Math.exp(-diff*4.2)),pb=remain-pa,margin=.06;return {pa,draw,pb,qa:(1/(pa*(1-margin))).toFixed(2),qx:(1/(draw*(1-margin))).toFixed(2),qb:(1/(pb*(1-margin))).toFixed(2),dir:diff>0.025?'home':diff<-.025?'away':'even'}}
function injectOdds(){if(!(view==='match'&&F[d]&&F[d][mi]))return;let f=F[d][mi],A=T[f[0]],B=T[f[1]],m=market(A,B),battle=document.querySelector('.battle');if(!battle)return;let old=battle.querySelector('.odds');if(old)old.remove();let odds=document.createElement('div');odds.className='odds';odds.innerHTML=`<div class="odds-title"><span>GAME QUOTES</span><small>modello Nexus · non bookmaker</small></div><div class="odds-grid"><div class="odd home"><small>1 · ${A[1]}</small><b>${m.qa}</b><span>${Math.round(m.pa*100)}%</span></div><div class="odd draw"><small>X · PAREGGIO</small><b>${m.qx}</b><span>${Math.round(m.draw*100)}%</span></div><div class="odd away"><small>2 · ${B[1]}</small><b>${m.qb}</b><span>${Math.round(m.pb*100)}%</span></div></div>`;battle.insertBefore(odds,battle.querySelector('.battle-head'));let arrow=battle.querySelector('.flow-arrow');if(arrow){arrow.classList.remove('to-home','to-away','even');arrow.classList.add(m.dir==='home'?'to-home':m.dir==='away'?'to-away':'even')}}
function removeDugout(){let x=document.querySelector('.dugout');if(x){let s=x.closest('.section');if(s&&s.querySelectorAll('.dugout').length===1)s.remove();else x.remove()}}
const DQ={
'84-82':['REVENGE HAS A MEMORY.','All’andata Reggina ha tolto tre punti a Dresden. Oggi la Dynamo è seconda a un solo punto dalla vetta: una vendetta qui vale molto più di un risultato.'],
'83-89':['THE HUNT STAYS ALIVE.','AEK è ancora dentro la corsa alta, Parma invece cerca aria nella zona più dura della classifica. Per una è pressione, per l’altra è sopravvivenza.'],
'86-88':['SOMEBODY HAS TO BLINK.','Palermo arriva con tre vittorie nelle ultime cinque, Torino è terzo e continua a segnare. Due squadre che non hanno nessuna intenzione di abbassare il ritmo.'],
'87-85':['CHAOS, ROUND TWO?','Il 3-3 dell’andata ha lasciato tutto aperto. Il 1860 tiene più palla, Académica non può più permettersi serate senza punti: il copione perfetto per un’altra partita fuori controllo.'],
'90-81':['THE GIANT KILLER TEST.','Partizan è ultimo, Atalanta è prima. Sulla carta non dovrebbe esserci storia. Ed è esattamente per questo che una notte così può diventare pericolosa per la capolista.'],
'129-126':['NO MORE SAFE PLACES.','Palmeiras e Genoa hanno bisogno di punti per ragioni diverse, ma con la stessa urgenza. Qui non si difende l’estetica: si difende la stagione.'],
'127-123':['CAN BOCA STOP THE STREAK?','Eintracht arriva da quattro vittorie consecutive e ha agganciato il secondo posto. Boca deve spezzare quella corsa prima che diventi una fuga vera.'],
'124-91':['FIVE GOALS WEREN’T ENOUGH.','All’andata finì 3-2 e nessuno riuscì davvero a controllarla. Oggi Fenerbahçe ha più classifica, Feyenoord più bisogno: miscela perfetta per un’altra notte sporca.'],
'128-125':['SURVIVAL DOESN’T WAIT.','Sunderland è penultimo e il tempo comincia a diventare un avversario. Kaiserslautern può guardare verso l’alto, ma prima deve passare da una squadra che gioca con l’acqua alla gola.'],
'122-121':['CAN BOLOGNA TOUCH THE THRONE?','Sampdoria è prima con sette punti di vantaggio, Bologna ha il miglior volume offensivo del gruppo. Se c’è una partita capace di scuotere la vetta, è questa.'],
'135-131':['THERE’S NO ROOM IN THE MIDDLE.','Celtic, Napoli e il resto del gruppo sono compressi in pochi punti. Qui una vittoria non migliora soltanto la classifica: cambia completamente la prospettiva della stagione.'],
'136-134':['WHO ESCAPES THE PRESSURE?','Guangzhou prova a uscire dalla zona bassa, Tottenham è a un passo dal gruppo europeo. Entrambe vedono una porta aperta, ma soltanto una può attraversarla.'],
'137-133':['CAN SÃO PAULO BREAK THE SCRIPT?','São Paulo è ultimo, Atlético è secondo e arriva con una serie che profuma di rincorsa. Il pronostico è chiaro. La domanda è se il campo avrà voglia di rispettarlo.'],
'101-130':['THE ONE TEAM THAT KNOWS HOW.','Valencia ha vinto le ultime cinque ed è in fuga. Ma Schalke è l’unica squadra che l’ha già battuta in questo incrocio. A volte il passato è un dato, altre volte diventa una minaccia.'],
'138-132':['SEVEN GOALS LATER…','Shakhtar e Marseille ne fecero sette all’andata. Entrambe producono occasioni, entrambe concedono. Qui la prudenza sembra quasi un insulto alla storia della sfida.'],
'148-139':['THIRD. FOURTH. SAME POINTS.','Roma e Legia sono appaiate a 26. Non c’è bisogno di costruire la tensione: è già tutta nella classifica. Una vittoria qui cambia il peso specifico di entrambe.'],
'149-143':['CAN THE LEADERS SURVIVE THE MADNESS?','Lazio guida la divisione, ma all’andata Campobasso la trascinò in un 4-3 folle. La capolista ha i numeri, gli altri hanno già dimostrato di poterle fare male.'],
'146-142':['FIVE NIL DOESN’T DISAPPEAR.','Il 5-0 dell’andata è ancora lì, impossibile da ignorare. Club América oggi ha un volto diverso in panchina, Dynamo Kyiv la miglior difesa del gruppo: questa è una prova di carattere prima ancora che di classifica.'],
'150-145':['CAN FLAMENGO STOP THE REPEAT?','Hertha vinse 4-1 all’andata e arriva con più ritmo, più punti e più produzione. Flamengo deve impedire che il precedente diventi una profezia.'],
'111-144':['THE WARNING WAS FOUR GOALS.','Dortmund è secondo a pari punti con la Lazio e all’andata ne fece quattro a River. Per gli argentini questa non è solo una trasferta: è il tentativo di cancellare un ricordo pesante.']};
function rewriteQuestion(){if(!(view==='match'&&F[d]&&F[d][mi]))return;let f=F[d][mi],q=DQ[`${f[0]}-${f[1]}`],box=document.querySelector('.question');if(!box||!q)return;let h=box.querySelector('h2'),p=box.querySelector('p');if(h)h.textContent=q[0];if(p)p.textContent=q[1]}
function rebuildContext(){if(!(view==='match'&&F[d]&&F[d][mi]))return;let f=F[d][mi],A=T[f[0]],B=T[f[1]],duo=document.querySelector('.duo');if(!duo)return;let gap=Math.abs(A[5]-B[5]);duo.className='context-bands';duo.innerHTML=`<div class="context-band first"><div class="context-copy"><div class="ey">LAST TIME OUT · THE FIRST LEG</div><strong>${f[2]}</strong><p>Il ritorno arriva dopo quattordici giornate: stessi club, ma una pressione completamente diversa.</p></div><div class="context-mark">↻</div></div><div class="context-band pressure"><div class="rank-side"><img src="${A[2]}"><b>#${A[4]}</b><span>${A[5]} PT</span></div><div class="gap-core"><div class="ey">TABLE PRESSURE</div><strong>${gap}</strong><span>PUNTI DI DISTANZA</span></div><div class="rank-side right"><img src="${B[2]}"><b>#${B[4]}</b><span>${B[5]} PT</span></div></div>`}
function patch15(){document.querySelectorAll('.date').forEach(el=>el.innerHTML='30 AUG 2026<small>MATCHDAY 15 · 20:00</small>');let landing=document.querySelector('.landing h1');if(landing)landing.innerHTML='MATCHDAY<br><span>15.</span>';document.querySelectorAll('.landing p').forEach(p=>p.textContent='20 partite. 40 club. Quattro divisioni. Il Matchday 15 porta nuove pressioni, nuovi incroci e le GAME QUOTES del modello Nexus.');}
if(view==='match'&&F[d]&&F[d][mi]){match(d,mi);injectOdds();removeDugout();rebuildContext();rewriteQuestion();patch15()}else{patch15()}