'use strict';
const routes={index:'Home',world:'World',competitions:'Competizioni',results:'Risultati',schedule:'Calendario',match:'Match Center',standings:'Classifiche',managers:'Manager',manager:'Profilo manager',players:'Player',player:'Profilo player',clubs:'Club',club:'Profilo club',transfers:'Trasferimenti',data:'Data / Ranking',moodboard:'System Moodboard'};
const key=location.pathname.split('/').pop().replace('.html','')||'index';
const page=routes[key]?key:'index';
const params=new URLSearchParams(location.search);const selected=Math.max(0,Math.min(5,Number(params.get('id'))||0));
const clubs=['Northbridge FC','Riverside Athletic','Portside United','Kingsfield FC','Westhaven City','Eastborough'];
const names=['Manager A','Manager B','Manager C','Manager D','Manager E','Manager F'];
const players=['Player A','Player B','Player C','Player D','Player E','Player F'];
const pts=[38,35,33,29,26,24],gf=[32,29,27,24,21,19],ga=[12,14,16,18,19,21],wins=[12,11,10,9,8,7],draws=[2,2,3,2,2,3],goals=[14,12,10,9,8,7],forms=['VVNVV','VVPVV','NVVNV','PVVNP','VPNVP','NVPVN'];
const link=(p,t,id)=>`<a href="${p}.html${id===undefined?'':'?id='+id}">${t}</a>`;
const form=(s)=>`<div class="form" aria-label="Ultime cinque partite: ${s.split('').map(c=>({V:'vittoria',N:'pareggio',P:'sconfitta'}[c])).join(', ')}">${[...s].map(c=>`<span class="${c==='P'?'loss':c==='N'?'draw':''}">${c}</span>`).join('')}</div>`;
const title=(over,t,sub='')=>`<div class="heading"><div><span class="eyebrow">${over}</span><h1>${t}</h1>${sub?`<p class="muted pageintro">${sub}</p>`:''}</div></div>`;
const section=(t,content,p)=>`<section class="section"><div class="heading"><h2>${t}</h2>${p?link(p,'Esplora →'):''}</div>${content}</section>`;
const rows=(type='club',limit=6)=>`<div class="board">${clubs.slice(0,limit).map((c,i)=>`<div class="row ${i===0?'leader':''}" data-search="${c.toLowerCase()} ${names[i].toLowerCase()} ${players[i].toLowerCase()}"><span class="ranknum ${i===0?'gold':''}">${String(i+1).padStart(2,'0')}</span><div><strong>${link(type,type==='manager'?names[i]:type==='player'?players[i]:c,i)}</strong><small>${type==='club'?names[i]:c} · Campione A / D1</small></div>${form(forms[i])}<span class="value">${type==='player'?goals[i]:pts[i]}<small>${type==='player'?'gol':'punti club'}</small></span></div>`).join('')}</div>`;
const score=(i=0,fixture=false)=>`<div class="scoreline"><div><span class="clubname">${link('club',clubs[i],i)}</span><small>${names[i]}</small></div><div><div class="score">${fixture?'— : —':'2 : 1'}</div><small>${fixture?'DA GIOCARE':'FT · DEMO'}</small></div><div><span class="clubname">${link('club',clubs[(i+1)%6],(i+1)%6)}</span><small>${names[(i+1)%6]}</small></div></div>`;
const matches=(fixture=false)=>`<div class="board">${[0,2,4].map((i,j)=>`<div class="matchrow"><small>${fixture?'G17 · 20:00':'G16 · FT'}</small><div class="home">${link('club',clubs[i],i)}</div><div class="score">${link('match',fixture?'vs':j===0?'2 : 1':j===1?'0 : 0':'1 : 3',i)}${fixture?'<small>DEMO</small>':''}</div><div class="away">${link('club',clubs[i+1],i+1)}</div>${link('match','↗',i)}</div>`).join('')}</div>`;
const metrics=(items)=>`<div class="metrics">${items.map(([l,v])=>`<div class="metric"><small>${l}</small><strong>${v}</strong></div>`).join('')}</div>`;
const rail=()=>`<aside class="rail"><section><span class="eyebrow">Leader · campione A</span><div class="goldlock"><h3>${link('club',clubs[0],0)}</h3><p>38 punti · +3 sulla seconda</p>${form(forms[0])}</div></section><section><span class="eyebrow">Prossimo incontro · demo</span><h3>${clubs[0]}<br>vs ${clubs[1]}</h3><p>Giornata 17 · orario dimostrativo 20:00</p>${link('schedule','Calendario →')}</section><section><span class="eyebrow">Criterio di lettura</span><p>Una competizione alla volta. I punti del club non sono un ranking personale del manager.</p>${link('data','Leggi i confronti →')}</section></aside>`;
const filters=(search=false)=>`<div class="filters"><label>Campione<select id="scope"><option value="a">Campione A · DEMO</option><option value="b">Campione B · vuoto</option></select></label><label>Divisione<select id="division"><option value="1">Divisione 1</option><option value="2">Divisione 2 · vuota</option></select></label>${search?'<label>Cerca<input id="search" type="search" placeholder="Nome o club"></label>':''}</div><div id="empty" class="empty hidden" role="status">Nessun elemento in questa selezione dimostrativa. Prova Campione A / Divisione 1.</div>`;
const bars=(labels,values,unit)=>`<div class="chart"><span class="eyebrow">Campione A · D1 · dopo G16 · DEMO</span>${labels.map((n,i)=>`<div class="barrow"><span>${n}</span><div class="bar"><i class="${i===0?'top':''}" style="width:${values[i]/Math.max(...values)*100}%"></i></div><strong>${values[i]}</strong></div>`).join('')}<p class="legend">${unit} · scala comune, origine zero.</p></div>`;
const directory=(kind)=>`<div class="directory">${clubs.map((c,i)=>`<article class="entry" data-search="${c.toLowerCase()} ${names[i].toLowerCase()} ${players[i].toLowerCase()}"><span class="monogram" aria-hidden="true">${kind==='club'?c.split(' ').map(w=>w[0]).slice(0,2).join(''):String(i+1).padStart(2,'0')}</span><div><h3>${link(kind,kind==='manager'?names[i]:kind==='player'?players[i]:c,i)}</h3><small>${kind==='club'?names[i]:c}</small><small>Campione A · Divisione 1</small></div></article>`).join('')}</div>`;
const profile=(kind)=>{let i=selected;let name=kind==='manager'?names[i]:kind==='player'?players[i]:clubs[i];return `<section class="stage"><span class="eyebrow">${kind==='club'?'Team status board':kind==='manager'?'Elite profile':'Player performance'} · DEMO</span><div class="profile"><div class="portrait"><b>${kind==='club'?'FC':String(i+1).padStart(2,'0')}</b><span>${kind==='club'?'STEMMA NON DISPONIBILE':'RITRATTO NON DISPONIBILE'}</span></div><div><h1>${name}</h1><p>${kind==='club'?names[i]:clubs[i]} · Campione A / Divisione 1</p><div class="${i===0?'goldlock':'statusblock'}"><span class="eyebrow">${kind==='player'?'Gol nel campione':'Posizione del club'}</span><span class="bigstat">${kind==='player'?goals[i]:String(i+1).padStart(2,'0')}</span></div><div class="profilelinks">${link('club','Club',i)}${link('manager','Manager',i)}${link('player','Player',i)}</div></div></div></section>${metrics(kind==='player'?[['Presenze',16],['Gol',goals[i]],['Assist',6-i],['MOTM',Math.max(1,5-i)]]:[['Punti club',pts[i]],['Partite',16],['Vittorie',wins[i]],['Differenza reti','+'+(gf[i]-ga[i])]])}`;};
let body='';
switch(page){
case 'index':body=`<div class="herogrid"><section class="stage"><span class="eyebrow">GW008 · Gold 1</span><h1>The Elite<br>Football Board.</h1><p>Ogni posizione conta.</p>${link('standings','Apri la classifica →')}</section><aside class="heroaside"><span class="goldlabel">Top of the board · DEMO</span><div class="goldlock" style="margin-top:22px"><span class="bigstat">01</span><h2 style="margin-top:15px">${link('club',clubs[0],0)}</h2><p>38 punti <small>/ +3 sulla seconda</small></p>${form(forms[0])}</div></aside></div><div class="split section"><div>${section('The board',rows('club',4),'standings')}${section('Ultimi risultati',matches(),'results')}</div>${rail()}</div>${section('Manager sul board',directory('manager'),'managers')}`;break;
case 'world':body=title('World / overview','Gold 1. In prospettiva.','Una vista ordinata su competizioni, protagonisti e prestazioni. Questa esplorazione usa un campione fittizio, non descrive la struttura reale del GW.')+metrics([['Club nel campione',6],['Manager demo',6],['Player demo',6],['Divisione campione',1]])+section('Percorsi nel mondo',`<div class="three">${[['competitions','01','Competizioni','Dal torneo alla sua classifica.'],['managers','02','Protagonisti','Manager, club e player nel loro contesto.'],['data','03','Prestazioni','Confronti con periodo e criteri espliciti.']].map(([p,n,t,d])=>`<article class="competition"><span class="ranknum">${n}</span><h2>${link(p,t)}</h2><p>${d}</p></article>`).join('')}</div>`)+section('Top of the board',rows('club',3));break;
case 'competitions':body=title('Competition status','La competizione, prima.','Seleziona il contesto sportivo prima di confrontare le posizioni.')+filters()+`<div id="dataset" class="three"><article class="competition"><span class="eyebrow">League · Campione A</span><h2>Divisione 1</h2><p>G16 · scenario dimostrativo</p><span class="goldlabel">Leader del campione</span><h3 style="margin:15px 0">${clubs[0]}</h3>${link('standings','Classifica →')}</article><article class="competition"><span class="eyebrow">Cup · demo</span><h2>Fase da verificare</h2><p>Tabellone e qualificazioni non disponibili nel campione.</p>${link('schedule','Calendario →')}</article><article class="competition"><span class="eyebrow">International · demo</span><h2>Stato non disponibile</h2><p>Nessun vincitore o leader attribuito senza dati.</p>${link('world','World overview →')}</article></div>`;break;
case 'results':body=title('Results / sports broadcast','Il risultato resta.','Campione dimostrativo · Giornata 16')+filters()+`<div id="dataset">${matches()}${section('Match in evidenza',`<div class="stage"><span class="eyebrow">Campione A · D1 · G16</span>${score()}${link('match','Apri il Match Center →',0)}</div>`)}</div>`;break;
case 'schedule':body=title('Fixtures / next match','La prossima posizione.','Giornata 17 · incontri e orari dimostrativi, nessuna data reale annunciata.')+filters()+`<div id="dataset">${matches(true)}${section('Focus sul prossimo turno',`<div class="stage"><span class="eyebrow">Primo contro secondo · DEMO</span><h2>${clubs[0]} / ${clubs[1]}</h2><p>Tre punti separano i due club nella classifica campione.</p>${link('standings','Confronta le posizioni →')}</div>`)}</div>`;break;
case 'match':{let i=selected-selected%2;const scores=i===0?'2 : 1':i===2?'0 : 0':'1 : 3';body=title('Match center','Dentro il risultato.')+`<div class="stage"><span class="eyebrow">Campione A / Divisione 1 / G16 · FT · DEMO</span>${score(i).replace('2 : 1',scores)}</div>`+metrics([['Casa · posizione',i+1],['Ospiti · posizione',i+2],['Stato','FT'],['Dati','DEMO']])+section('Contesto dell’incontro',`<div class="split"><div><div class="board"><div class="row"><span class="ranknum">H</span><div><strong>${link('manager',names[i],i)}</strong><small>${clubs[i]}</small></div>${form(forms[i])}<span>${pts[i]} pt</span></div><div class="row"><span class="ranknum">A</span><div><strong>${link('manager',names[i+1],i+1)}</strong><small>${clubs[i+1]}</small></div>${form(forms[i+1])}<span>${pts[i+1]} pt</span></div></div><p class="legend">Forma e posizione riferite alla classifica campione dopo G16.</p><div class="empty"><h3>Report dettagliato non disponibile</h3><p>Marcatori, eventi, formazioni e statistiche partita non sono inclusi nel campione.</p></div></div>${rail()}</div>`);break;}
case 'standings':body=title('Status at a glance','Ogni posizione conta.','Campione A / Divisione 1 · classifica parziale dimostrativa dopo G16.')+filters()+`<div id="dataset" class="split"><div><div class="tablewrap"><table><thead><tr><th>Pos</th><th>Club</th><th>G</th><th class="optional">V</th><th class="optional">N</th><th class="optional">P</th><th>DR</th><th>Pt</th></tr></thead><tbody>${clubs.map((c,i)=>`<tr><td>${String(i+1).padStart(2,'0')}</td><td>${link('club',c,i)}</td><td>16</td><td class="optional">${wins[i]}</td><td class="optional">${draws[i]}</td><td class="optional">${16-wins[i]-draws[i]}</td><td>${gf[i]-ga[i]}</td><td><strong>${pts[i]}</strong></td></tr>`).join('')}</tbody></table></div><p class="legend">Estratto di sei club. Pt = 3 × V + N. L’oro segnala esclusivamente il primo posto nel campione. Nessuna zona promozione ipotizzata.</p></div>${rail()}</div>`;break;
case 'managers':body=title('Manager directory','Il volto del club.','Identità dimostrative · ordinamento alfabetico.')+filters(true)+`<div id="dataset">${directory('manager')}${section('Forma dei club gestiti',rows('manager'))}</div>`;break;
case 'manager':body=profile('manager')+section('Manager status strip',`<div class="board"><div class="row"><span class="ranknum">${selected+1}</span><div><strong>${clubs[selected]}</strong><small>Forma del club · ultime cinque partite</small></div>${form(forms[selected])}<span>${pts[selected]} pt</span></div></div>`)+section('Il club e la competizione',`<div class="three"><div class="competition"><h3>Club attuale</h3><p>${link('club',clubs[selected],selected)}</p></div><div class="competition"><h3>Contesto</h3><p>${link('standings','Campione A · Divisione 1')}</p></div><div class="competition"><h3>Record personali</h3><p>Non disponibili nel campione.</p></div></div>`);break;
case 'players':body=title('Performance listing','La prestazione emerge.','Player dimostrativi · gol nel campione dopo G16.')+filters(true)+`<div id="dataset">${rows('player')}${section('Directory player',directory('player'))}</div>`;break;
case 'player':body=profile('player')+section('Signature performance',bars([players[selected]],[goals[selected]],'Gol nel campione'))+section('Lettura delle metriche',`<div class="empty"><h3>Rating del gioco e voto medio partita</h3><p>Non disponibili nel campione. Nessun trend viene dedotto dal totale dei gol.</p>${link('club','Vai al club →',selected)}</div>`);break;
case 'clubs':body=title('Club directory','Un posto sul board.','Club fittizi creati esclusivamente per questa esplorazione.')+filters(true)+`<div id="dataset">${directory('club')}</div>`+section('Classifica del campione',rows('club',3),'standings');break;
case 'club':body=profile('club')+section('Forma del club',`<div class="competition">${form(forms[selected])}<p>Ultime cinque partite · dalla meno recente alla più recente.</p></div>`)+section('Player in evidenza',`<div class="board"><div class="row"><span class="ranknum">P</span><div><strong>${link('player',players[selected],selected)}</strong><small>16 presenze · Campione A / D1</small></div><span>Gol</span><span class="value">${goals[selected]}</span></div></div>`)+section('Percorsi club',`<div class="navall">${link('results','Risultati')}${link('schedule','Calendario')}${link('transfers','Trasferimenti')}${link('manager','Manager',selected)}</div>`);break;
case 'transfers':body=title('Elite movement','Un nuovo contesto.','Movimenti fittizi di esempio. Valori economici e date non disponibili.')+`<div class="board">${[0,1,2].map((i)=>`<article class="transfer"><div><h3>${link('player',players[i],i)}</h3><small>Trasferimento dimostrativo</small></div><div>${clubs[(i+3)%6]}<small>Provenienza</small></div><span>→</span><div>${link('club',clubs[i],i)}<small>Nuovo club</small></div><small>Valore<br>—</small></article>`).join('')}</div>`+section('La prestazione nel nuovo club',`<div class="stage"><span class="eyebrow">Player board</span><h2>Il movimento apre il confronto.</h2><p>I totali disponibili non consentono di isolare la prestazione prima e dopo il trasferimento.</p>${link('players','Esplora i player →')}</div>`);break;
case 'data':body=title('Premium clarity','Chi occupa il vertice.','Confronti dentro la stessa divisione campione, dopo G16.')+`<div class="filters"><label>Metrica club<select id="metric"><option value="points">Punti</option><option value="goals">Gol segnati</option><option value="difference">Differenza reti</option></select></label></div><div id="chart">${bars(clubs,pts,'Punti')}</div>`+section('Forma a confronto',rows('club'))+section('Metodo e limiti',`<div class="empty"><h3>Un contesto, una scala.</h3><p>Dati statici, fittizi e dichiarati. Sei club nella stessa divisione campione. Nessuna classifica reale o confronto globale fra paesi. La forma è una sequenza dimostrativa; delta, trend temporali e distribuzioni complete richiedono uno storico e qui non sono mostrati.</p></div>`);break;
case 'moodboard':body=title('System Moodboard / Proposal 01','The Elite Football Board.','Top-tier football, clearly ordered.')+`<div class="swatches"><span style="background:#081527;color:white">Deep navy</span><span style="background:#102847;color:white">Royal navy</span><span style="background:white">Porcelain</span><span style="background:#d8dce2">Silver</span><span style="background:#c5a35a;flex:.3">Gold</span></div><div class="sample"><section class="stage"><span class="eyebrow">Refined sports grotesk</span><div class="moodtype">Position.<br>Precision.<br>Performance.</div><div class="moodnumbers">01 / 38 / 2:1</div></section><section class="competition"><span class="eyebrow">White board surface</span><h2>Calm authority.</h2><p>Elite · clarity · position · composure · precision · stature · sporting · selection · confidence · performance.</p><p>Il dato determina lo status. Il gold identifica il vertice. Navy e bianco distinguono focus e consultazione.</p></section></div>`+section('Elite rank object',rows('club',3))+section('Elite score',`<div class="stage">${score()}</div>`)+section('Material / light / photography',`<div class="three"><article class="competition"><h3>Porcelain / silver</h3><p>Superfici continue, bordi sottili, ombre solo sui livelli sovrapposti.</p></article><article class="competition"><h3>Navy / satin gold</h3><p>Profondità controllata. Oro solo per un primato leggibile, mai come fondo diffuso.</p></article><article class="competition"><h3>Clean sports portraiture</h3><p>Ritratti nitidi e kit leggibili. Nessun volto sintetico attribuito a una persona reale. Fotografie da integrare dopo verifica degli asset.</p></article></div>`)+section('Motion / responsive',`<div class="competition"><h3>Board Shift · Gold Lock · Status Rise</h3><p>Esplorazioni di sistema, non animazioni continue. Interazioni 160 ms; rispetto del movimento ridotto. Sul mobile restano posizione, identità e valore, mentre la status rail passa sotto il board.</p><h3>White → Navy → White</h3><p>Consultazione, focus, ritorno al confronto. Nessun neon, podio, vetro pesante o cornice dorata.</p></div>`);break;
}
document.title=`${routes[page]} · GOLD 1 / GW008`;
document.getElementById('app').innerHTML=`<a class="skip" href="#main">Vai al contenuto</a><header><div class="mast"><a href="/" class="brand"><img src="/site-assets/images/imc-logo.png" alt="IMC">ITALIAN MASTERS CLUB</a><span>ONE CLUB. MANY WORLDS.</span><small>THE WORLD IS OUR PLAYGROUND</small></div><div class="identity"><a href="index.html" class="worldmark"><img src="/site-assets/images/game-worlds/gw008.webp" alt="Logo ufficiale GW008 Gold 1"><div><span class="eyebrow">GW008 / THE ELITE FOOTBALL BOARD</span><strong>GOLD 1</strong></div></a><span class="eyebrow">TOP-TIER FOOTBALL, CLEARLY ORDERED.</span></div></header><nav aria-label="Navigazione Gold 1"><button class="menubutton" aria-expanded="false" aria-controls="navlinks">${routes[page]} <span style="float:right">Menu +</span></button><div class="navinner" id="navlinks">${['index','world','competitions','results','schedule','standings','managers','players','clubs','transfers','data'].map(p=>`<a href="${p}.html" ${p===page?'aria-current="page"':''}>${routes[p]}</a>`).join('')}</div></nav><div class="notice">VISUAL DESIGN EXPLORATION 01 · Tutti i dati sportivi, nomi e club del campione sono DEMO / FITTIZI.</div><main id="main">${body}</main><footer><div><strong>GOLD 1 / GW008</strong><br>Italian Masters Club · Visual Design Exploration 01</div><div>${link('moodboard','System Moodboard')} · ${link('world','World overview')}</div></footer>`;
document.querySelector('.menubutton').addEventListener('click',e=>{const b=e.currentTarget;const open=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(open));document.getElementById('navlinks').classList.toggle('open',open);});
function applyFilters(){let visible=true;const scope=document.getElementById('scope'),division=document.getElementById('division'),search=document.getElementById('search');if(scope)visible=scope.value==='a'&&division.value==='1';const dataset=document.getElementById('dataset');if(dataset)dataset.classList.toggle('hidden',!visible);let count=0;document.querySelectorAll('[data-search]').forEach(el=>{const match=!search||el.dataset.search.includes(search.value.toLowerCase().trim());el.classList.toggle('hidden',!match);if(match)count++;});const empty=document.getElementById('empty');if(empty)empty.classList.toggle('hidden',visible&&(!search||count>0));}
['scope','division'].forEach(id=>document.getElementById(id)?.addEventListener('change',applyFilters));document.getElementById('search')?.addEventListener('input',applyFilters);
document.getElementById('metric')?.addEventListener('change',e=>{const [v,u]=e.target.value==='goals'?[gf,'Gol segnati']:e.target.value==='difference'?[gf.map((n,i)=>n-ga[i]),'Differenza reti']:[pts,'Punti'];document.getElementById('chart').innerHTML=bars(clubs,v,u);});
