'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let csrf='',data=null,editing=null,mode='save',editingWorld='',serial=0,busy=false;
for(let i=1;i<=10;i++){const gw='GW'+String(i).padStart(3,'0');$('world').add(new Option(gw,gw));}
const requested=new URLSearchParams(location.search).get('world');if(/^GW00[1-9]$|^GW010$/.test(requested||''))$('world').value=requested;
async function api(body,query=''){
 const response=await fetch('api.php'+query,{credentials:'same-origin',cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(body)}:{})});
 const result=await response.json();
 if(!response.ok||!result.ok){if(response.status===401){$('workspace').hidden=true;$('login').hidden=false;$('logout').hidden=true;if($('editor').open)$('editor').close();csrf='';data=null;}throw Error(result.error||'Operazione non riuscita.');}return result;
}
function message(text){$('message').textContent=text;}
function status(row){return row.start_date>data.today?'future':row.end_date&&row.end_date<data.today?'closed':'active';}
function teamName(row){const group=data.teams[row.assignment_type]||[];const id=row.assignment_type==='club'?row.team_id:row.national_team_id;const match=group.find(t=>[t.id,t.codex_id,t.sm_id,t.world_id].some(v=>v!=null&&String(v)===String(id)));return row.team_name||match?.name||'Squadra senza mapping';}
function render(){if(!data)return;const query=$('search').value.toLocaleLowerCase('it');const rows=data.rows.filter(r=>($('kind').value==='all'||r.assignment_type===$('kind').value)&&($('status').value==='all'||status(r)===$('status').value)&&[r.full_name,teamName(r),r.manager_id,r.team_id,r.national_team_id].join(' ').toLocaleLowerCase('it').includes(query));
 $('count').textContent=rows.length+' incarichi · '+$('world').value;
 $('assignments').innerHTML=rows.length?rows.map(r=>`<article><div><strong>${esc(r.full_name)}</strong><small>${esc(r.manager_id)} · #${r.id}</small></div><div><strong>${esc(teamName(r))}</strong><small>${r.assignment_type==='club'?'Club':'Nazionale'} · ID ${esc(r.assignment_type==='club'?r.team_id:r.national_team_id)}</small></div><div><span class="badge ${status(r)}">${{active:'In carica',closed:'Concluso',future:'Futuro'}[status(r)]}</span><small>${esc(r.start_date)} → ${esc(r.end_date||'in corso')}</small></div><div class="row-actions"><button data-id="${r.id}" data-action="save">Correggi</button><button data-id="${r.id}" data-action="close">Chiudi</button><button data-id="${r.id}" data-action="replace">Subentro</button></div></article>`).join(''):'<p class="panel">Nessun incarico per questi filtri.</p>';
}
async function load(){const seq=++serial;data=null;$('assignments').innerHTML='';$('count').textContent='Caricamento…';$('add').disabled=true;try{const result=await api(null,'?world='+encodeURIComponent($('world').value));if(seq!==serial)return;data=result;render();$('add').disabled=false;}catch(e){if(seq===serial){message(e.message);$('count').textContent='Dati non caricati';}}}
function teams(selected){const entries=data.teams[$('type').value]||[];$('team').innerHTML='<option value="">Seleziona squadra</option>'+entries.map(t=>`<option value="${esc(t.id)}">${esc(t.name)} · ${esc(t.id)}</option>`).join('');if(selected){const t=entries.find(t=>[t.id,t.codex_id,t.sm_id,t.world_id].some(v=>v!=null&&String(v)===String(selected)));if(t)$('team').value=String(t.id);}}
function openEditor(action,row=null){if(!data||busy)return;mode=action;editing=row;editingWorld=$('world').value;$('edit-form').reset();$('edit-error').textContent='';$('edit-title').textContent=action==='replace'?'Subentro / cambio squadra':action==='close'?'Chiudi incarico':row?'Correggi incarico':'Nuova assegnazione';$('edit-context').textContent=editingWorld+(row?' · '+row.full_name+' · '+teamName(row):'');
 $('manager').innerHTML='<option value="">Seleziona manager</option>'+data.managers.map(m=>`<option value="${esc(m.manager_id)}">${esc(m.full_name)} · ${esc(m.manager_id)}</option>`).join('');
 $('manager').value=row?.manager_id||'';$('type').value=row?.assignment_type||($('kind').value==='national_team'?'national_team':'club');$('type').disabled=action==='replace';teams(row&&(row.assignment_type==='club'?row.team_id:row.national_team_id));
 $('identity-fields').hidden=action==='close';$('manager').required=action!=='close';$('team').required=action!=='close';$('start-label').hidden=action==='close';$('start').required=action!=='close';$('end-label').hidden=action==='replace';$('close-label').hidden=action!=='replace';$('close-date').required=action==='replace';$('end').required=action==='close';
 $('start').value=action==='replace'?data.today:(row?.start_date||data.today);$('end').value=action==='close'?(row?.end_date||data.today):action==='replace'?'':(row?.end_date||'');
 if(action==='replace')previousDate();
 $('edit-note').textContent=action==='replace'?'Il vecchio incarico verrà chiuso e il nuovo creato in un unico salvataggio. Per cambiare allenatore scegli il nuovo manager; per cambiare squadra mantieni il manager.':action==='close'?'La data fine è l’ultimo giorno in carica. L’incarico rimane nello storico.':'Usa Correggi per rettificare dati errati. Per un cambio effettivo usa Subentro: le date determinano anche i trofei del manager.';
 $('save').textContent=action==='replace'?'Chiudi precedente e crea nuovo':action==='close'?'Conferma chiusura':'Salva assegnazione';$('editor').showModal();}
function previousDate(){const d=new Date($('start').value+'T12:00:00Z');if(!Number.isNaN(d.valueOf())){d.setUTCDate(d.getUTCDate()-1);$('close-date').value=d.toISOString().slice(0,10);}}
$('start').addEventListener('change',()=>{if(mode==='replace')previousDate();});
$('type').addEventListener('change',()=>teams());
$('assignments').addEventListener('click',event=>{const b=event.target.closest('button[data-id]');if(b)openEditor(b.dataset.action,data.rows.find(r=>String(r.id)===b.dataset.id));});
$('add').addEventListener('click',()=>openEditor('save'));$('cancel').addEventListener('click',()=>{if(!busy)$('editor').close();});$('editor').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
$('edit-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;$('save').disabled=true;$('cancel').disabled=true;$('edit-error').textContent='';const body={action:mode,world:editingWorld,id:editing?.id||0,version:editing?.version||'',manager_id:$('manager').value,assignment_type:$('type').value,team:$('team').value,start_date:$('start').value,end_date:mode==='replace'?'':$('end').value,close_date:$('close-date').value};try{await api(body);$('editor').close();message('Assegnazione salvata.');await load();}catch(err){$('edit-error').textContent=err.message;message(err.message);}finally{busy=false;$('save').disabled=false;$('cancel').disabled=false;}});
$('login').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const result=await api({action:'login',key:$('key').value});$('key').value='';csrf=result.csrf;$('login').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;message('');await load();}catch(err){message(err.message);}finally{button.disabled=false;}});
$('logout').addEventListener('click',async()=>{try{await api({action:'logout'});location.reload();}catch(e){message(e.message);}});
$('world').addEventListener('change',()=>{message('');load();});$('reload').addEventListener('click',load);for(const id of ['kind','status','search'])$(id).addEventListener(id==='search'?'input':'change',render);
(async()=>{try{const result=await api(null,'?action=session');csrf=result.csrf;$('login').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;await load();}catch(e){if(e.message!=='Accedi come amministratore.')message(e.message);}})();
