(function(){var x=new XMLHttpRequest();x.open('GET','data.js?raw=1',false);x.send(null);if(x.status>=200&&x.status<300){(0,eval)(x.responseText);if(window.RTH14&&RTH14.T&&RTH14.T[85])RTH14.T[85][2]='tsv-1860.svg';}else{throw new Error('RTH Matchday data unavailable');}
var s=document.createElement('style');s.textContent=`
/* MATCHDAY 14 PREMIUM MATCH CENTRE OVERRIDE */
@media(max-width:720px){
  body{background:#071426!important}
  .match-hero{min-height:430px!important;background:radial-gradient(circle at 50% 45%,rgba(43,126,255,.24),transparent 34%),linear-gradient(155deg,#03101f 0%,#0a294c 58%,#061426 100%)!important}
  .match-hero:after{bottom:-52%!important;height:58%!important;opacity:.55}
  .match-hero .top{height:62px!important;padding-top:2px}
  .match-hero .brand img{width:36px!important;height:36px!important}.match-hero .brand b{font-size:9px!important}.match-hero .brand small{font-size:7px!important}.match-hero .date{font-size:9px!important}.match-hero .date small{font-size:7px!important}
  .match-hero-content{padding:14px 0 38px!important}
  .match-meta{font-size:7px!important;letter-spacing:.14em!important;margin-bottom:13px!important}
  .duel{grid-template-columns:1fr 46px 1fr!important;margin:0 auto!important;gap:4px!important}
  .duel-team img{width:96px!important;height:96px!important;filter:drop-shadow(0 12px 18px rgba(0,0,0,.34))!important}
  .duel-team h1{font-size:22px!important;line-height:1!important;margin:10px 0 5px!important;min-height:44px;display:flex;align-items:center;justify-content:center}
  .duel-team small{font-size:8px!important}.duel-vs{font-size:14px!important}
  .headline-strip{margin-top:-24px!important}.headline-box{border-radius:20px!important;padding:19px 20px!important;box-shadow:0 14px 32px rgba(3,16,31,.18)!important}.headline-box h2{font-size:30px!important;line-height:.96!important;margin:7px 0 8px!important}.headline-box .ey{font-size:8px!important}.headline-box>div:last-child{font-size:8px!important}
  .section{padding:32px 0!important}.section.ice{background:#eaf1fa!important}.section.white{background:#061426!important;color:#fff!important}
  .match-grid{grid-template-columns:1fr!important;gap:12px!important}.panel{border-radius:18px!important;padding:18px!important;box-shadow:0 10px 24px rgba(4,25,48,.09)!important}.panel h3{font-size:24px!important;margin:5px 0 13px!important}
  .form-duel{display:grid!important;grid-template-columns:1fr 1fr!important;gap:10px!important}.formteam{background:#f2f6fb!important;border:1px solid #dce6f1!important;border-radius:14px!important;padding:14px 12px!important}.formteam b{font-size:11px!important;color:#091629!important;display:block!important;margin-bottom:10px!important}.formteam span{width:30px!important;height:30px!important;font-size:8px!important;border-radius:9px!important;margin-right:3px!important}
  .darkpanel{background:linear-gradient(145deg,#061426,#0a2748)!important;border:1px solid rgba(111,164,255,.18)!important}.darkpanel h3{color:#fff!important}.dugout{display:grid!important;grid-template-columns:1fr 38px 1fr!important;align-items:stretch!important;gap:8px!important}.boss{background:#102a49!important;border:1px solid rgba(255,255,255,.12)!important;border-radius:14px!important;padding:15px 8px!important;text-align:center!important;min-height:92px!important;display:flex!important;flex-direction:column!important;justify-content:center!important}.boss b{display:block!important;color:#fff!important;font-size:14px!important;line-height:1.12!important;text-shadow:none!important}.boss small{display:block!important;color:#9fb4cc!important;font-size:8px!important;margin-top:7px!important}.dugout .vs{align-self:center!important;color:#d8ad4f!important}
  .section-head{display:block!important;margin-bottom:17px!important}.section-head[style]{margin-top:31px!important}.section h2{font-size:38px!important;line-height:.88!important}.section-copy{font-size:10px!important;line-height:1.45!important;margin-top:12px!important}
  .metrics{display:grid!important;gap:8px!important}.metric{border-radius:15px!important;padding:12px 13px!important;background:#fff!important;box-shadow:0 7px 18px rgba(7,26,51,.05)!important}.metric-top{font-size:7px!important}.metric-values{grid-template-columns:28px 34px 1fr 34px 28px!important;gap:7px!important;margin-top:9px!important}.metric-values img{width:25px!important;height:25px!important}.metric-values b{font-size:15px!important}.bar{height:8px!important}
  .player-duel{grid-template-columns:1fr 1fr!important;gap:10px!important}.player-card{border-radius:17px!important;overflow:hidden!important;box-shadow:0 10px 24px rgba(7,26,51,.12)!important}.player-card .pic{height:155px!important;background:linear-gradient(155deg,#102b4a,#071426)!important}.player-card .pic img{height:100%!important;width:100%!important;object-fit:contain!important;filter:drop-shadow(0 10px 18px rgba(0,0,0,.25))!important}.pcopy{padding:13px!important}.pcopy .ey{font-size:6px!important}.pcopy h3{font-size:16px!important;margin:5px 0 9px!important}.player-numbers{grid-template-columns:repeat(4,1fr)!important;gap:4px!important}.player-numbers b{font-size:13px!important}.player-numbers small{font-size:5px!important}
  .question{background:linear-gradient(135deg,#0b2647,#061426)!important;border:1px solid rgba(87,147,234,.24)!important;border-radius:18px!important;padding:20px!important;box-shadow:none!important}.question .ey{color:#75aaff!important}.question h2{font-size:28px!important;line-height:.98!important;color:#fff!important;margin:8px 0!important}
  .h2h{display:grid!important;grid-template-columns:1fr 1fr!important;gap:10px!important;margin-top:12px!important}.prior{background:#0b203b!important;border:1px solid rgba(255,255,255,.1)!important;border-radius:16px!important;padding:16px!important;color:#fff!important}.prior .ey{font-size:7px!important;color:#75aaff!important}.prior h3{font-size:18px!important;line-height:1!important;color:#fff!important}.prior strong{font-size:9px!important;color:#d8ad4f!important}.prior p{color:#9aafc7!important;font-size:7px!important}
  .nav-match{margin-top:14px!important;display:grid!important;grid-template-columns:1fr auto 1fr!important;gap:8px!important;align-items:center!important}.nav-match .btn{padding:12px 9px!important;font-size:7px!important}.counter{font-size:8px!important;color:#9fb2c9!important}
}
@media(min-width:721px){.boss b{color:#fff!important}.boss small{color:#a8b9cc!important}}
`;
document.head.appendChild(s);
})();