function metric(label,A,B,idx){let av=+A[idx],bv=+B[idx],sum=Math.max(av+bv,1),home=av/sum*100,fmt=v=>idx===8?`${v}%`:String(v);return `<div class="metric"><div class="metric-label"><span>${A[1]}</span><span>${B[1]}</span></div><div class="metric-values"><b>${fmt(av)}</b><b>${fmt(bv)}</b></div><div class="rail" style="background:linear-gradient(90deg,#d8ad4f 0%,#d8ad4f ${home}%,#2f80ff ${home}%,#2f80ff 100%)"></div><div class="metric-label metric-foot"><span>${label}</span><span>${label}</span></div></div>`}
function formScore(s){return [...s].reduce((n,c)=>n+(c==='W'?3:c==='D'?1:0),0)}
function market(A,B){let tableA=(11-A[4])/10,tableB=(11-B[4])/10,ptsMax=Math.max(A[5],B[5],1),ptsA=A[5]/ptsMax,ptsB=B[5]/ptsMax,formA=formScore(A[11])/15,formB=formScore(B[11])/15,attMax=Math.max(A[6],B[6],1),attA=A[6]/attMax,attB=B[6]/attMax,defMax=Math.max(A[7],B[7],1),defA=1-A[7]/(defMax*1.35),defB=1-B[7]/(defMax*1.35),posMax=Math.max(A[8],B[8],1),posA=A[8]/posMax,posB=B[8]/posMax,shotMax=Math.max(A[9],B[9],1),shotA=A[9]/shotMax,shotB=B[9]/shotMax;let sa=.26*tableA+.25*ptsA+.18*formA+.11*attA+.08*defA+.06*posA+.06*shotA,sb=.26*tableB+.25*ptsB+.18*formB+.11*attB+.08*defB+.06*posB+.06*shotB;sa*=1.055;let diff=sa-sb,draw=Math.max(.19,.31-Math.abs(diff)*.28),remain=1-draw,pa=remain/(1+Math.exp(-diff*4.2)),pb=remain-pa,margin=.06;return {pa,draw,pb,qa:(1/(pa*(1-margin))).toFixed(2),qx:(1/(draw*(1-margin))).toFixed(2),qb:(1/(pb*(1-margin))).toFixed(2),dir:diff>0.025?'home':diff<-.025?'away':'even'}}
function injectMarket(){if(!(view==='match'&&F[d]&&F[d][mi]))return;let f=F[d][mi],A=T[f[0]],B=T[f[1]],m=market(A,B),battle=document.querySelector('.battle');if(!battle)return;let odds=document.createElement('div');odds.className='odds';odds.innerHTML=`<div class="odds-title"><span>RTH MATCH ODDS</span><small>quote modello Nexus · non bookmaker</small></div><div class="odds-grid"><div class="odd home"><small>1 · ${A[1]}</small><b>${m.qa}</b><span>${Math.round(m.pa*100)}%</span></div><div class="odd draw"><small>X · PAREGGIO</small><b>${m.qx}</b><span>${Math.round(m.draw*100)}%</span></div><div class="odd away"><small>2 · ${B[1]}</small><b>${m.qb}</b><span>${Math.round(m.pb*100)}%</span></div></div>`;battle.insertBefore(odds,battle.querySelector('.battle-head'));let arrow=battle.querySelector('.flow-arrow');if(arrow)arrow.classList.add(m.dir==='home'?'to-home':m.dir==='away'?'to-away':'even')}
function removeDugout(){let x=document.querySelector('.dugout');if(x){let s=x.closest('.section');if(s&&s.querySelectorAll('.dugout').length===1)s.remove();else x.remove()}}
const DQ={
'89-84':['WHO OWNS THE NIGHT?','Parma ha ritrovato un battito, Dresden vede il podio a portata di mano. Una delle due dovrà trasformare il momento in qualcosa di più grande.'],
'88-83':['NO PLACE TO HIDE.','Due contender separate da dettagli. Torino arriva lanciato, AEK sa come spegnere le partite: stasera il margine può stare in un solo episodio.'],
'85-86':['CHAOS OR CONTROL?','Palermo vuole trasformare ogni possesso in pericolo, il 1860 vuole comandare il pallone. Quando due idee così diverse si scontrano, qualcuno finisce fuori copione.'],
'81-87':['CAN THE LEADERS BE TOUCHED?','Atalanta porta addosso il peso del primo posto. Académica porta qualcosa di più pericoloso: niente da perdere. È così che nascono le notti storte delle grandi.'],
'82-90':['WHO ESCAPES FIRST?','Qui non si gioca per il glamour. Si gioca per respirare. Reggina e Partizan hanno bisogno di punti veri, e ogni errore stasera peserà il doppio.'],
'121-122':['CAN BOLOGNA SHAKE THE THRONE?','La Sampdoria guarda tutti dall’alto e ha costruito margine. Bologna arriva per scoprire se quella distanza è davvero sicurezza o soltanto pressione accumulata.'],
'91-123':['WHO BLINKS FIRST?','Punti pesanti e una classifica che non concede pause. Fenerbahçe ed Eintracht entrano nella stessa notte sapendo che un passo falso può cambiare il panorama.'],
'127-125':['ONE WIN FROM A DIFFERENT STORY.','Boca e Kaiserslautern sono abbastanza vicine da potersi rubare prospettive, fiducia e posizione con una sola vittoria. Tre punti qui valgono più della somma.'],
'126-124':['CAN SOMEONE BREAK THE PATTERN?','Genoa e Feyenoord hanno vissuto troppe serate senza continuità. Questa può essere l’ennesima occasione mancata oppure la partita che cambia finalmente il ritmo.'],
'128-129':['HOW BADLY DO YOU WANT OUT?','In fondo alla classifica non esistono partite piccole. Sunderland e Palmeiras giocano contro l’avversario, ma soprattutto contro il tempo che comincia a stringere.'],
'101-133':['THE SUMMIT IS CALLING.','Valencia difende la vetta, Atlético arriva con quattro vittorie consecutive. Non è solo uno scontro d’alta classifica: è una candidatura al controllo della divisione.'],
'135-132':['FIREPOWER OR MOMENTUM?','Shakhtar produce occasioni come pochi, Celtic arriva con una forma che continua a crescere. Stasera volume e fiducia si guardano negli occhi.'],
'131-134':['WHO TURNS THE SEASON?','Napoli e Tottenham sono ancora abbastanza vicine al gruppo per cambiare il proprio destino. Ma le giornate passano: questa è una di quelle che separano il recupero dal rimpianto.'],
'138-130':['CAN SCHALKE STOP THE FALL?','Cinque sconfitte consecutive sono un peso che entra in campo prima dei giocatori. Marseille proverà a spingere proprio lì, dove la fiducia dello Schalke è più fragile.'],
'136-137':['WHO FINDS AIR FIRST?','Guangzhou e São Paulo vivono nella zona in cui ogni punto sembra ossigeno. Non serve bellezza: serve una notte capace di cambiare l’umore di una stagione.'],
'142-149':['REVENGE OR REPEAT?','Kyiv ha già lasciato un segno pesantissimo all’andata. Lazio arriva più in alto e con una forma feroce. Ora resta da capire se il passato comanda ancora il presente.'],
'111-148':['CAN ROMA SILENCE THE LEADERS?','Dortmund ha la vetta, i numeri e l’autorità. Roma ha abbastanza qualità per trasformare una trasferta proibitiva nella partita che tutti ricorderanno.'],
'139-150':['WHO TAKES THE NEXT STEP?','Legia ed Hertha sono separate da una zona di classifica in cui basta una vittoria per cambiare prospettiva. Qui non si difende una posizione: si prova a conquistarne una nuova.'],
'146-144':['NEW VOICE, FIRST STATEMENT?','Club América entra in una nuova era dalla panchina. River Plate arriva ferito e affamato di punti: il primo messaggio del nuovo corso dovrà essere immediato.'],
'143-145':['WHEN LOSING HAS TO END.','Campobasso e Flamengo conoscono fin troppo bene il peso delle sconfitte. Stasera una delle due può finalmente interrompere il rumore e ricominciare a respirare.']};
function rewriteQuestion(){if(!(view==='match'&&F[d]&&F[d][mi]))return;let f=F[d][mi],q=DQ[`${f[0]}-${f[1]}`],box=document.querySelector('.question');if(!box||!q)return;let h=box.querySelector('h2'),p=box.querySelector('p');if(h)h.textContent=q[0];if(p)p.textContent=q[1]}
function rebuildContext(){if(!(view==='match'&&F[d]&&F[d][mi]))return;let f=F[d][mi],A=T[f[0]],B=T[f[1]],duo=document.querySelector('.duo');if(!duo)return;let gap=Math.abs(A[5]-B[5]);duo.className='context-bands';duo.innerHTML=`<div class="context-band first"><div class="context-copy"><div class="ey">LAST TIME OUT · THE FIRST LEG</div><strong>${f[2]}</strong><p>Il ritorno arriva dopo tredici giornate: stessi club, ma una pressione completamente diversa.</p></div><div class="context-mark">↻</div></div><div class="context-band pressure"><div class="rank-side"><img src="${A[2]}"><b>#${A[4]}</b><span>${A[5]} PT</span></div><div class="gap-core"><div class="ey">TABLE PRESSURE</div><strong>${gap}</strong><span>PUNTI DI DISTANZA</span></div><div class="rank-side right"><img src="${B[2]}"><b>#${B[4]}</b><span>${B[5]} PT</span></div></div>`}
if(view==='match'&&F[d]&&F[d][mi]){match(d,mi);injectMarket();removeDugout();rebuildContext();rewriteQuestion()}