<?php
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
$f=__DIR__.'/state.json';
$players=json_decode(<<<'P'
[["K. COMAN",90,30,"Al Nassr FC"],["I. TONEY",90,30,"Al Ahli SFC"],["M. ASENSIO",90,30,"Fenerbahçe SK"],["J. ANDERSEN",90,30,"Fulham"],["A. GOLOVIN",90,30,"AS Monaco"],["C. JOELINTON",90,30,"Newcastle United"],["L. PELLEGRINI",90,30,"AS Roma"],["N. AGUERD",90,30,"Olympique Marseille"],["B. PAVARD",90,30,"Internazionale"],["G. LO CELSO",90,30,"Real Betis"],["G. MANCINI",90,30,"AS Roma"],["W. ANTON",90,30,"Svincolato"],["P. FORNALS",90,30,"Real Betis"],["D. UNDAV",90,30,"VfB Stuttgart"],["L. SHAW",90,31,"Arsenal"],["P. HOJBJERG",90,31,"Olympique Marseille"],["M. SKRINIAR",90,31,"Fenerbahçe SK"],["A. ROMAGNOLI",90,31,"Al Sadd SC"],["N. AKÉ",90,31,"Fenerbahçe SK"],["J. GIMÉNEZ",90,31,"Svincolato"],["M. PAŠALIĆ",90,31,"Atalanta BC"],["B. CRISTANTE",90,31,"AS Roma"],["M. ZACCAGNI",90,31,"SS Lazio"],["J. PALHINHA",90,31,"Svincolato"],["L. PAREDES",90,32,"Svincolato"],["M. KOVAČIĆ",90,32,"Manchester City"],["M. SABITZER",90,32,"Svincolato"],["P. DYBALA",90,32,"AS Roma"],["R. GUERREIRO",90,32,"Svincolato"],["A. ROBERTSON",90,32,"Tottenham Hotspur"],["R. ANDRICH",90,32,"Bayer Leverkusen"],["H. MAGUIRE",90,33,"Svincolato"],["M. POLITANO",90,33,"Svincolato"],["A. PÉREZ",90,33,"Villarreal CF"],["F. AURSNES",89,30,"Manchester United"],["J. BEDNAREK",89,30,"Svincolato"],["J. BRANDT",89,30,"Borussia Dortmund"],["D. SÁNCHEZ",89,30,"Galatasaray SK"],["D. CEBALLOS",89,30,"Real Betis"],["S. AMRABAT",89,30,"Svincolato"],["T. KEHRER",89,30,"AS Monaco"],["P. LIENHART",89,30,"SC Freiburg"],["L. TORREIRA",89,30,"Galatasaray SK"],["A. IWOBI",89,30,"Fulham"],["Y. WISSA",89,30,"Newcastle United"],["R. KOCH",89,30,"Eintracht Frankfurt"],["G. GURUZETA",89,30,"Athletic Club"],["O. MONTEIRO",89,31,"Al Qadsiah FC"],["T. KLEINDIENST",89,31,"Borussia Mönchengladbach"],["J. MURPHY",89,31,"Newcastle United"],["C. LENGLET",89,31,"Svincolato"],["Á. BERENGUER",89,31,"Athletic Club"],["N. PÉPÉ",89,31,"Villarreal CF"],["M. HERMOSO",89,31,"AS Roma"],["F. MENDY",89,31,"SL Benfica"],["L. MILLA",89,31,"Como 1907"],["C. TOLISSO",89,32,"Olympique Lyonnais"],["G. GÓMEZ",89,33,"Svincolato"],["M. ICARDI",89,33,"Svincolato"],["B. IGLESIAS",89,33,"Celta Vigo"],["S. EL SHAARAWY",89,33,"Genoa CFC"],["M. ARNOLD",88,32,"VfL Wolfsburg"],["L. TORRÓ",88,32,"CA Osasuna"],["A. BARDAKCI",88,32,"Galatasaray SK"]]
P
,true);
$picks=json_decode(<<<'K'
[["Prisco","Nudo","Buitre","Simone","Iodice","Tana","Cabrioli","Grugni","Palace","Minasyan","Mello","Errico","Catalano","Gattuso","Martorano","Trovato"],["Trovato","Martorano","Gattuso","Catalano","Errico","Mello","Minasyan","Palace","Grugni","Cabrioli","Tana","Iodice","Simone","Buitre","Nudo","Prisco"],["Grugni","Palace","Minasyan","Mello","Errico","Catalano","Gattuso","Martorano","Trovato","Prisco","Nudo","Buitre","Simone","Iodice","Tana","Cabrioli"],["Cabrioli","Tana","Iodice","Simone","Buitre","Nudo","Prisco","Trovato","Martorano","Gattuso","Catalano","Errico","Mello","Minasyan","Palace","Grugni"]]
K
,true);
function blank(){return ['running'=>false,'started_at'=>null,'draft'=>[]];}
$s=file_exists($f)?json_decode(file_get_contents($f),true):blank();if(!is_array($s))$s=blank();
$resetTag='FINAL_RESET_20260923_1';if(($s['reset_tag']??'')!==$resetTag){$s=blank();$s['reset_tag']=$resetTag;file_put_contents($f,json_encode($s,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX);}
if($_SERVER['REQUEST_METHOD']==='POST'){$in=json_decode(file_get_contents('php://input'),true)?:[];if(($in['action']??'')==='start'){$pool=$players;shuffle($pool);$draft=[];for($i=0;$i<64;$i++){$r=intdiv($i,16);$k=$i%16;$p=$pool[$i];$draft[]=['call'=>$i+1,'round'=>$r+1,'pick'=>$k+1,'manager'=>$picks[$r][$k],'player'=>$p[0],'rating'=>$p[1],'age'=>$p[2],'club'=>$p[3]];}$s=['running'=>true,'started_at'=>microtime(true),'draft'=>$draft,'reset_tag'=>$resetTag];file_put_contents($f,json_encode($s,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX);}}
$revealed=0;if(!empty($s['started_at'])&&count($s['draft'])===64){$revealed=min(64,(int)floor((microtime(true)-(float)$s['started_at'])/1.8)+1);if($revealed>=64){$revealed=64;$s['running']=false;}else{$s['running']=true;}}
echo json_encode(['ok'=>true,'running'=>$s['running'],'revealed'=>$revealed,'draft'=>$s['draft']],JSON_UNESCAPED_UNICODE);