'use strict';
const D=window.GW007_DATA;
const K=[{id:'ENG',name:'Inghilterra',title:'ENGLAND',color:'#B64959',word:'BELONGING',desc:'Ogni campo, un’appartenenza.'},{id:'ESP',name:'Spagna',title:'ESPAÑA',color:'#C77648',word:'EXPRESSION',desc:'Il territorio prende forma nel gioco.'},{id:'GER',name:'Germania',title:'DEUTSCHLAND',color:'#328E95',word:'INTENSITY',desc:'La forza è un movimento collettivo.'},{id:'ITA',name:'Italia',title:'ITALIA',color:'#557ED1',word:'IDENTITY',desc:'Una città. Una maglia. Un’identità.'}];
const P=new URLSearchParams(location.search), page=document.body.dataset.page, active=K.find(k=>k.id===P.get('k'))||K[0];
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=(p,q={})=>p+'.html'+(Object.keys(q).length?'?'+new URLSearchParams(q):'');
const link=(p,text,q={},cls='')=>`<a class="${cls}" href="${url(p,q)}">${text}</a>`;
const label=t=>`<span class="eyebrow">${t}</span>`;
const tag=t=>`<span class="tag">${t}</span>`;
const date=s=>s?new Date(s+'T12:00:00').toLocaleDateString('it-IT',{day:'2-digit',month:'short',year:'numeric'}):'Data non disponibile';
const rows=k=>D.results.filter(r=>r.sm_country===k);
const goals=k=>rows(k).reduce((n,r)=>n+Number(r.home_score)+Number(r.away_score),0);
const names=k=>[...new Set(rows(k).flatMap(r=>[r.home_name,r.away_name]))];
const source=(t='Risultati del 09.09.2026 · League D1')=>`<p class="source">${t} · Snapshot verificato 10.09.2026 · ${D.source}</p>`;
const empty=t=>`<div class="empty">${t}</div>`;
const demo=t=>`<p class="demo">DEMO · ${t}</p>`;
const heading=(small,title,sub='')=>`<header class="page-heading">${label(small)}<h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</header>`;
const flag=k=>k==='ENG'?'<span class="eng-flag" role="img" aria-label="Bandiera dell’Inghilterra: croce di San Giorgio"></span>':'';
const kingdomLinks=(target='kingdom')=>K.map(k=>link(target,`${flag(k.id)}<b>${k.id}</b><span>${k.name}</span>`,{k:k.id},`kingdom-link ${active.id===k.id&&page==='kingdom'?'selected':''}`)).join('');
const nav=[['index','Home'],['world','Four Kingdoms'],['map','Territory Map'],['competitions','Competizioni'],['results','Risultati'],['schedule','Calendario'],['standings','Power Rankings'],['manager','Manager'],['player','Giocatori'],['club','Club'],['transfers','Trasferimenti'],['rivalries','Rivalità']];
const score=(r,big=false)=>`<a href="${url('match',{id:r.sm_fixture_id})}" class="score ${big?'score-big':''}" style="--territory:${K.find(k=>k.id===r.sm_country)?.color||'#586A7D'}"><div class="score-meta">${r.sm_country} / LEAGUE D${r.sm_division} <span>${date(r.match_date)} · ${r.home_score!=null?'FINALE':'IN PROGRAMMA'}</span></div><div class="score-line"><span>${esc(r.home_name)}</span><strong>${r.home_score!=null?`${r.home_score}<i>:</i>${r.away_score}`:'VS'}</strong><span>${esc(r.away_name)}</span></div><div class="score-foot">${big?'Apri Match Center':'Match Center'} <span>↗</span></div></a>`;
const stats=()=>`<div class="four-stats">${K.map(k=>`<a href="${url('kingdom',{k:k.id})}" style="--territory:${k.color}">${label(k.id+' / '+k.name)}<strong>${goals(k.id)}</strong><span>gol · ${rows(k.id).length} partite</span></a>`).join('')}</div>`;
const balance=()=>`<div class="balance">${K.map(k=>`<a href="${url('kingdom',{k:k.id})}" style="--territory:${k.color}"><span>${k.id}</span><div class="bar-track"><i style="width:${goals(k.id)/Math.max(...K.map(j=>goals(j.id)))*100}%"></i></div><b>${goals(k.id)}</b></a>`).join('')}</div>`;
function map(){return `<div class="territory-map">${K.map((k,i)=>`<section class="map-region region-${i}" style="--territory:${k.color}">${link('kingdom',`<span class="eyebrow">TERRITORY 0${i+1}</span><h3>${k.title}</h3>`,{k:k.id})}<div class="nodes">${names(k.id).slice(0,3).map(n=>link('club',`<i></i>${esc(n)}`,{name:n,k:k.id},'club-node')).join('')}</div>${link('kingdom',`${rows(k.id).length} confronti / ${goals(k.id)} gol ↗`,{k:k.id},'map-caption')}</section>`).join('')}<div class="map-axis" aria-hidden="true">FOUR / ONE</div></div><p class="source">Mappa relazionale astratta · aree di uguale dimensione · nessuna scala geografica. Nodi: selezione di club dai risultati letti.</p>`;}
function filters(){return `<div class="filters"><label>Territorio<select id="filter"><option value="ALL">Tutti i Kingdom</option>${K.map(k=>`<option value="${k.id}" ${P.get('k')===k.id?'selected':''}>${k.name}</option>`).join('')}</select></label><span>LEAGUE / DIVISIONE 1</span></div>`;}
function home(){const feature=D.results.find(r=>r.home_name==='Real Madrid');return `${heading('IMC / GW007 · FOOTBALL TERRITORIES','THE FOUR<br>KINGDOMS','FOUR NATIONS. ONE CROWN.')}<section class="home-stage"><div class="hero-image"><img src="assets/stadium.webp" alt="Atmosfera sintetica: uno stadio anonimo nella città notturna"><div class="hero-copy">${label('THE PITCH IS A TERRITORY')}<h2>Il calcio ha<br>un luogo.<br><em>Il potere, quattro.</em></h2>${link('world','Esplora i quattro territori ↗',{},'button')}</div><span class="image-note">IMMAGINE ATMOSFERICA AI · STADIO IMMAGINARIO</span></div><aside class="intelligence">${label('TERRITORIAL INTELLIGENCE')}<h2>L’equilibrio <br>del turno.</h2><p>Gol nei quattro campionati<br>09 settembre · Divisione 1</p>${balance()}${link('world','Leggi il confronto ↗',{},'text-link')}</aside></section><section class="section"><div class="section-title"><h2>Quattro appartenenze.</h2>${label('SELECT YOUR TERRITORY')}</div>${stats()}</section><section class="split section"><div>${label('CONFRONTATION / ESP')}${score(feature,true)}</div><article class="paper">${label('MANIFESTO / 01')}<h2>The pitch<br>is a territory.</h2><p>Le città diventano club. I club diventano appartenenza. Il campo è il luogo in cui queste identità si incontrano.</p>${link('map','Entra nella mappa ↗',{},'text-link')}</article></section>${source()}`;}
function world(){return `${heading('GLOBAL VIEW / 01','QUATTRO TERRITORI.<br>UN EQUILIBRIO.','La stessa giornata, quattro prospettive sul gioco.')}${stats()}<section class="split section"><div><h2>Volume offensivo</h2>${balance()}<p>Gol complessivi per campionato. Germania: 9 partite; altri territori: 10. Il volume non misura la superiorità di un Kingdom.</p></div><div class="paper"><h2>Confrontare<br>senza confondere.</h2><p>Per un confronto omogeneo, osserva anche i gol per partita.</p>${K.map(k=>`<div class="data-row"><span>${k.name}</span><b>${(goals(k.id)/rows(k.id).length).toFixed(2)}</b></div>`).join('')}</div></section>${map()}${source()}`;}
function kingdom(){const rr=rows(active.id),best=[...rr].sort((a,b)=>Math.abs(b.home_score-b.away_score)-Math.abs(a.home_score-a.away_score))[0];return `<section class="kingdom-hero" style="--territory:${active.color}">${label('KINGDOM / '+active.id)}<h1>${active.title}</h1><div class="territory-word">${active.word}</div><p>${active.desc}</p><div class="kingdom-numbers"><strong>${goals(active.id)}<small>GOL NEL TURNO</small></strong><strong>${rr.length}<small>PARTITE OSSERVATE</small></strong><strong>${names(active.id).length}<small>CLUB NEL CAMPIONE</small></strong></div></section><section class="split section"><div><h2>Il confronto in evidenza</h2>${score(best,true)}</div><div><h2>I nodi del territorio</h2><div class="club-list">${names(active.id).slice(0,8).map(n=>link('club',`${esc(n)} <span>↗</span>`,{name:n,k:active.id})).join('')}</div></div></section>${link('results','Tutti i risultati del territorio ↗',{k:active.id},'button')}${source()}`;}
function results(){return `${heading('BORDER SCORES / 04','IL CAMPO<br>HA RISPOSTO.','09 settembre 2026 · Risultati verificati dei quattro territori')}${filters()}<div id="match-list" class="match-grid"></div>${source()}`;}
function schedule(){return `${heading('NEXT CONFRONTATIONS / 05','IL PROSSIMO<br>PUNTO DI CONTATTO.','Calendario letto dalla fonte · orari riportati come registrati, fuso non specificato')}${filters()}<div id="match-list" class="match-grid"></div>${source('Calendario · estratto dal 12.09.2026 · League D1')}`;}
function match(){const r=[...D.results,...D.schedule].find(r=>r.sm_fixture_id===P.get('id'))||D.results.find(r=>r.home_name==='Real Madrid');return `${heading('MATCH CENTER / '+r.sm_country,'IL CONFINE<br>È IL CAMPO.')}${score(r,true)}<section class="split section"><div><h2>Il confronto</h2><div class="club-list">${link('club',esc(r.home_name)+' ↗',{name:r.home_name,k:r.sm_country})}${link('club',esc(r.away_name)+' ↗',{name:r.away_name,k:r.sm_country})}</div><div class="data-row"><span>Competizione</span><b>League · D${r.sm_division}</b></div><div class="data-row"><span>Data</span><b>${date(r.match_date)}</b></div><div class="data-row"><span>Fixture ID</span><b>${r.sm_fixture_id}</b></div></div><article class="paper">${label('MATCH REPORT')}<h2>Il risultato.<br>Poi, la storia.</h2><p>Il punteggio è disponibile. Cronaca, marcatori, possesso e formazioni non sono inclusi in questo snapshot.</p><p>Nessuna statistica del report viene ricostruita dal solo risultato.</p></article></section>${source(r.home_score!=null?'GW007_IMC Results':'GW007_IMC Schedule')}`;}
function competitions(){return `${heading('COMPETITIONS / 03','PERCORSI<br>CHE CONVERGONO.','Dal campionato territoriale all’incontro fra identità.')}<section class="league-paths">${K.map(k=>`<article style="--territory:${k.color}">${label(k.id+' / DOMESTIC')}<h2>${k.name}</h2><div class="path-node">League · Divisione 1</div><div class="path-line"></div><div class="path-node">09 SET · ${rows(k.id).length} partite</div>${link('results','Risultati ↗',{k:k.id},'text-link')}${link('schedule','Calendario ↗',{k:k.id},'text-link')}</article>`).join('')}</section><article class="paper section">${label('CONVERGING PATHS / STUDIO DI COMPONENTE')}<h2>Quattro percorsi.<br>Un punto d’incontro.</h2>${demo('Progressione coppa puramente visuale. Partecipanti e turni non sono dati ufficiali.')}<div class="cup-path"><span>Territorio A<br>Territorio B</span><b>SEMIFINALE</b><span class="crown">FINALE</span><b>SEMIFINALE</b><span>Territorio C<br>Territorio D</span></div></article>${source()}`;}
function standings(){const ranking=D.results.flatMap(r=>[{name:r.home_name,k:r.sm_country,gf:+r.home_score,ga:+r.away_score},{name:r.away_name,k:r.sm_country,gf:+r.away_score,ga:+r.home_score}]).sort((a,b)=>(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf||a.name.localeCompare(b.name));return `${heading('POWER HIERARCHY / 07','L’IMPATTO<br>DI UNA GIORNATA.','Graduatoria derivata dal turno del 9 settembre. Non è la classifica del campionato.')}<div class="ranking-intro"><strong class="huge">+${ranking[0].gf-ranking[0].ga}</strong><div>${label('MASSIMA DIFFERENZA RETI DEL TURNO')}<h2>La forza si legge<br>nel confronto.</h2><p>Ordine: differenza reti, gol segnati, nome. I pari merito numerici hanno lo stesso impatto sportivo.</p></div></div><div class="table-wrap"><table><caption>Impatto del turno · primi 20 club · D1</caption><thead><tr><th>Club</th><th>Kingdom</th><th>GF</th><th>GS</th><th>DR</th></tr></thead><tbody>${ranking.slice(0,20).map(r=>`<tr><td>${link('club',esc(r.name),{name:r.name,k:r.k})}</td><td>${r.k}</td><td>${r.gf}</td><td>${r.ga}</td><td><b>${r.gf-r.ga>0?'+':''}${r.gf-r.ga}</b></td></tr>`).join('')}</tbody></table></div><p class="source">Power Index ufficiale non definito: nessun punteggio composito o crown holder viene attribuito.</p>${source()}`;}
function manager(){return `${heading('DIPLOMATIC DOSSIER / 08','CHI RAPPRESENTA<br>IL TERRITORIO.')}<section class="dossier"><div class="identity-placeholder">${label('PORTRAIT / NON DISPONIBILE')}<span>IMC<br>REP.</span><p>Ritratto da collegare<br>a un’identità verificata.</p></div><article class="paper">${label('TERRITORY REPRESENTATIVE')}<h2>Manager<br>da verificare.</h2><p>La tabella manager consultata non restituisce righe. Il dossier mostra la struttura prevista, senza attribuire club, nazionalità o risultati a una persona.</p><div class="data-row"><span>Club</span><b>—</b></div><div class="data-row"><span>Kingdom del club</span><b>—</b></div><div class="data-row"><span>Record</span><b>—</b></div><div class="data-row"><span>Ranking</span><b>—</b></div></article></section><section class="section"><h2>Le quattro appartenenze</h2><div class="territory-switch">${kingdomLinks()}</div></section>${source('GW007_managers · nessuna riga restituita')}`;}
function player(){const p=D.players.find(x=>x.sm_player_id===P.get('id'))||D.players[0];return `${heading('PLAYER / SPORTING IDENTITY',esc(p.player_name),'Identità sportiva letta dallo snapshot')}<section class="player-layout"><div class="player-type"><span>${esc(p.player_name.split('.')[0])}</span><strong>${esc(p.player_name.split('.').slice(1).join('.'))}</strong>${label('ESP / LEAGUE D1')}</div><div><h2>${esc(p.club_name||'Club non disponibile')}</h2><p>Il dato identifica il giocatore e il contesto competitivo. Le prestazioni non sono valorizzate nella fonte letta.</p><div class="metric-grid">${[['Presenze',p.appearances],['Gol',p.goals],['Assist',p.assists],['Voto medio',p.avg_rating]].map(([l,v])=>`<div>${label(l)}<strong>${v??'—'}</strong></div>`).join('')}</div>${p.club_name?link('club','Apri il club ↗',{name:p.club_name,k:'ESP'},'button'):''}</div></section><section class="section"><h2>Altri profili nello snapshot</h2><div class="club-list">${D.players.map(p=>link('player',`${esc(p.player_name)} <span>${esc(p.club_name||'Club —')} ↗</span>`,{id:p.sm_player_id})).join('')}</div></section>${source('GW007_IMC SM Player Stats · valori null mostrati con —')}`;}
function club(){const n=P.get('name')||'AS Roma',rr=D.results.filter(r=>r.home_name===n||r.away_name===n),ss=D.schedule.filter(r=>r.home_name===n||r.away_name===n),k=K.find(k=>k.id===(rr[0]?.sm_country||P.get('k')))||K[3];return `${heading('CLUB NODE / '+k.id,esc(n),'Un club è il punto in cui territorio e appartenenza si incontrano.')}<section class="club-hero" style="--territory:${k.color}"><span class="club-monogram">${esc(n.split(' ').map(x=>x[0]).slice(0,3).join(''))}</span><div>${label('NODO DEL TERRITORIO')}<h2>${k.name}</h2><p>Monogramma tipografico provvisorio · stemma non collegato.</p>${link('kingdom','Esplora il Kingdom ↗',{k:k.id},'button')}</div></section><section class="split section"><div><h2>Ultimo confronto nello snapshot</h2>${rr.length?rr.map(r=>score(r)).join(''):empty('Nessun risultato incluso per questo club.')}</div><div><h2>Prossimo incontro nello snapshot</h2>${ss.length?score(ss[0]):empty('Nessuna partita inclusa per questo club.')}</div></section>${source()}`;}
function transfers(){return `${heading('MOVEMENT / 11','CAMBIA MAGLIA.<br>CAMBIA TERRITORIO.','Tre trasferimenti reali dal repository · estratto, non cronologia completa.')}<section class="transfer-list">${D.transfers.map((t,i)=>`<article>${label('MOVIMENTO / 0'+(i+1))}<div class="transfer-title"><h2>${esc(t.player_name)}</h2><strong>${esc(t.amount_text)}</strong></div><div class="transfer-route"><span>${esc(t.club_from)}<small>ORIGINE</small></span><div class="route-track"><i></i><b>→</b></div><span>${esc(t.club_to)}<small>DESTINAZIONE</small></span></div><p class="source">Data trasferimento non disponibile · import ${esc(t.imported_at)}</p></article>`).join('')}</section><article class="paper section"><h2>Il movimento<br>prima della distanza.</h2><p>Le linee collegano club di origine e destinazione. Non rappresentano itinerari geografici né implicano che ogni trasferimento attraversi un confine nazionale.</p></article>${source('GW007_IMC Transfers · campione di 3 righe')}`;}
function rivalries(){const games=D.results.filter(r=>['Real Madrid','AC Milan','Manchester City'].includes(r.home_name));return `${heading('RIVALRY EDITORIAL / 12','STESSO CAMPO.<br>DIVERSE APPARTENENZE.','Una selezione editoriale di confronti presenti nei risultati verificati.')}<div class="rivalry-stack">${games.map((r,i)=>`<article>${label('CONFRONTO / 0'+(i+1))}<h2>${esc(r.home_name)}<br><em>${esc(r.away_name)}</em></h2>${score(r,true)}</article>`).join('')}</div>${source()}`;}
const views={index:home,world,kingdom,competitions,results,schedule,match,standings,manager,player,club,transfers,map:()=>heading('TERRITORY MAP / 02','IL CALCIO<br>PRENDE SPAZIO.','Seleziona un territorio o un club. I collegamenti descrivono appartenenze, non coordinate.')+map()+source(),rivalries};
document.getElementById('app').innerHTML=`<a class="skip" href="#main">Salta al contenuto</a><header class="topbar">${link('index','<b class="imc">IMC</b><span>THE FOUR KINGDOMS<small>GW007 / FOOTBALL TERRITORIES</small></span>',{},'brand')}<span class="exploration-label">VISUAL DESIGN EXPLORATION · 01</span><button id="menu-button" aria-expanded="false" aria-controls="navigation">Menu</button></header><div class="shell"><aside id="navigation" class="sidebar"><p class="eyebrow">WORLD NAVIGATION</p><nav aria-label="Navigazione principale">${nav.map(([p,n],i)=>link(p,`<span>${String(i+1).padStart(2,'0')}</span>${n}`,{},p===page?'current':'')).join('')}</nav><div class="sidebar-territories">${label('YOUR TERRITORY')}${kingdomLinks()}</div><p class="rail-claim">FOUR NATIONS.<br>ONE CROWN.</p></aside><div class="main-wrap"><div class="territory-switch" aria-label="Seleziona Kingdom">${kingdomLinks()}</div><main id="main">${(views[page]||home)()}</main><footer><b>IMC / GW007</b><span>The World is our Playground.</span><p>Visual Design Exploration 01 · Dati reali: snapshot 10.09.2026. Esempi segnalati DEMO. Immagine dello stadio generata, non documentaria.</p></footer></div></div>`;
document.getElementById('menu-button').addEventListener('click',e=>{const open=e.currentTarget.getAttribute('aria-expanded')!=='true';e.currentTarget.setAttribute('aria-expanded',String(open));document.getElementById('navigation').classList.toggle('open',open);});
const f=document.getElementById('filter');if(f){const draw=()=>{const records=(page==='results'?D.results:D.schedule).filter(r=>f.value==='ALL'||r.sm_country===f.value);document.getElementById('match-list').innerHTML=records.map(r=>score(r)).join('')||empty('Nessuna partita per questo filtro.');};f.addEventListener('change',draw);draw();}
