(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const menu=$('menu'),open=document.querySelector('.menu-toggle'),close=document.querySelector('.menu-close');
function setMenu(on){menu.inert=!on;menu.classList.toggle('open',on);menu.setAttribute('aria-hidden',String(!on));open.setAttribute('aria-expanded',String(on));document.body.style.overflow=on?'hidden':'';(on?close:open).focus()}
open.addEventListener('click',()=>setMenu(true));close.addEventListener('click',()=>setMenu(false));menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));
menu.addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false);if(e.key==='Tab'){const items=[...menu.querySelectorAll('button,a')],first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
const consent=$('consent');function saved(){try{return localStorage.getItem('imc_analytics_consent')}catch{return null}}function applyConsent(value){window.gtag?.('consent','update',{analytics_storage:value,ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'});try{localStorage.setItem('imc_analytics_consent',value)}catch{}consent.hidden=true}
const preference=saved();if(['granted','denied'].includes(preference))applyConsent(preference);else consent.hidden=false;consent.querySelectorAll('[data-consent]').forEach(b=>b.addEventListener('click',()=>applyConsent(b.dataset.consent)));$('cookie-settings').onclick=()=>{consent.hidden=false;consent.querySelector('button').focus()};
let data=null,expanded=false,busy=false,lastSignature='';
function renderManagers(){if(!data)return;const q=$('manager-search').value.trim().toLocaleLowerCase('it'),world=$('manager-world').value;const list=data.managers.filter(m=>(!q||m.full_name.toLocaleLowerCase('it').includes(q))&&(!world||m.worlds.includes(world)));const visible=expanded?list:list.slice(0,8);$('managerWall').innerHTML=visible.map(m=>'<a class="manager-chip" href="/nexus/club-house/?manager='+encodeURIComponent(m.manager_id)+'"><small>'+esc(m.manager_id)+'</small><strong>'+esc(m.full_name)+'</strong><span class="manager-worlds">'+m.worlds.map(esc).join(' · ')+'</span></a>').join('')||'<p class="loading">Nessun manager trovato.</p>';$('manager-summary').textContent=list.length+' manager'+(world?' in '+world:' con un incarico attivo')+' · '+visible.length+' visualizzati';$('more-managers').hidden=list.length<=8;$('more-managers').textContent=expanded?'Mostra meno':'Mostra tutti i '+list.length+' manager';$('more-managers').setAttribute('aria-expanded',String(expanded))}
$('manager-search').addEventListener('input',()=>{expanded=false;renderManagers()});$('manager-world').addEventListener('change',()=>{expanded=false;renderManagers()});$('more-managers').onclick=()=>{expanded=!expanded;renderManagers()};
function render(d){data=d;document.querySelector('[data-count="managers"]').textContent=d.managers.length;document.querySelector('[data-count="worlds"]').textContent=d.worlds.length;$('world-list').innerHTML=d.worlds.map(w=>'<a class="world-card is-live" href="'+esc(w.href)+'" aria-label="Apri il Gameboard di '+esc(w.name)+' in Nexus"><span class="world-number" aria-hidden="true">'+esc(w.game_world_id.replace('GW',''))+'</span><div><small>'+esc(w.game_world_id)+'</small><h3>'+esc(w.name)+'</h3><p>ID Soccer Manager '+esc(w.sm_game_world_id)+'</p></div><div class="world-foot"><span><i aria-hidden="true"></i>'+w.manager_count+' manager IMC</span><b>GAMEBOARD ↗</b></div></a>').join('');const chosen=$('manager-world').value;$('manager-world').innerHTML='<option value="">Tutti i mondi</option>'+d.worlds.map(w=>'<option value="'+esc(w.game_world_id)+'">'+esc(w.game_world_id+' · '+w.name)+'</option>').join('');$('manager-world').value=d.worlds.some(w=>w.game_world_id===chosen)?chosen:'';renderManagers()}
async function refresh(){if(busy)return;busy=true;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch('/site-assets/master/homepage.php',{cache:'no-store',signal:controller.signal});const d=await r.json();if(!r.ok||!d.ok||!Array.isArray(d.worlds)||!Array.isArray(d.managers))throw Error('directory');const signature=JSON.stringify([d.worlds,d.managers]);if(signature!==lastSignature){render(d);lastSignature=signature}$('data-status').textContent='Community aggiornata · '+new Date(d.updated_at).toLocaleTimeString('it-IT',{timeZone:'Europe/Rome',hour:'2-digit',minute:'2-digit'})+' · Incarichi attivi di club e nazionali';$('retry-data').hidden=true}catch{if(!data){$('world-list').innerHTML='<p class="loading">I mondi non sono disponibili in questo momento. <a href="/nexus/club-house/">Apri Nexus →</a></p>';$('managerWall').innerHTML='<p class="loading">I manager non sono disponibili in questo momento.</p>'}$('data-status').textContent=data?'Aggiornamento non riuscito. Sono mostrati gli ultimi dati caricati; riproveremo automaticamente.':'Non è stato possibile caricare la community. Riprova tra poco.';$('retry-data').hidden=false}finally{clearTimeout(timer);busy=false}}
$('retry-data').onclick=refresh;refresh();setInterval(()=>{if(!document.hidden)refresh()},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});window.addEventListener('online',refresh);
document.addEventListener('click',e=>{const a=e.target.closest('a');if(a)window.gtag?.('event','cta_click',{cta_text:a.textContent.trim().slice(0,80),destination:a.getAttribute('href')})});
})();
