(function(){
"use strict";
if(window.IMC_COMPETITIONS)return;
const VERSION="3.1.0";
let state={container:null,client:null,worldId:"",worldName:"",items:[],seasons:[],view:"hub",activeType:"domestic",activeCountry:"",schedule:[],previews:new Map(),scheduleLoaded:false};
function clean(v){return String(v==null?"":v).trim()}
function esc(v){return clean(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function typeOf(x){return clean(x&&x.IMC_competition_type).toLowerCase()}
function actionOf(x){return clean(x&&x.sm_action).toLowerCase()}
function keyOf(x){return clean(x&&x.competition_key)}
function nameOf(x){return clean(x&&x["Nexus View"]||x&&x.sm_competition_name||keyOf(x)||"Competition")}
function countType(v){return state.items.filter(x=>typeOf(x)===v).length}
function countAction(v){return state.items.filter(x=>actionOf(x)===v).length}
function countries(){return [...new Set(state.items.filter(x=>typeOf(x)==="domestic").map(x=>clean(x["Country Nexus View"]||x.sm_country)).filter(Boolean))].sort()}
function countryCount(){return countries().length}
function formatDate(v){const s=clean(v);if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return "—";const [y,m,d]=s.split("-").map(Number),months=["GEN","FEB","MAR","APR","MAG","GIU","LUG","AGO","SET","OTT","NOV","DIC"];return `${String(d).padStart(2,"0")} ${months[m-1]||""} ${y}`}
function compactDate(v){const s=clean(v);if(!s)return "—";const d=new Date(s.length===10?s+"T12:00:00":s);if(isNaN(d))return "—";return d.toLocaleDateString("it-IT",{day:"2-digit",month:"short"}).toUpperCase()}
function trophyIcon(){return `<svg viewBox="0 0 120 120" aria-hidden="true"><defs><linearGradient id="cpCup" x1="0" x2="1"><stop offset="0" stop-color="#d8e0ea"/><stop offset=".45" stop-color="#fff"/><stop offset=".7" stop-color="#9aaabc"/><stop offset="1" stop-color="#f8fbff"/></linearGradient><linearGradient id="cpGold" x1="0" x2="1"><stop offset="0" stop-color="#c99a35"/><stop offset=".5" stop-color="#f2d47a"/><stop offset="1" stop-color="#b98320"/></linearGradient></defs><path d="M35 18h50v23c0 25-10 40-25 48-15-8-25-23-25-48Z" fill="url(#cpCup)" stroke="#7e8da0" stroke-width="2"/><path d="M35 27H22c0 24 7 34 24 36M85 27h13c0 24-7 34-24 36" fill="none" stroke="url(#cpGold)" stroke-width="5" stroke-linecap="round"/><path d="M55 88h10v11h16v8H39v-8h16Z" fill="url(#cpCup)" stroke="#8b99aa" stroke-width="1.5"/></svg>`}
function globeIcon(){return `<svg viewBox="0 0 120 120" aria-hidden="true"><defs><radialGradient id="cpGlobe" cx="35%" cy="30%"><stop offset="0" stop-color="#5aa2ff"/><stop offset=".5" stop-color="#0d4d9b"/><stop offset="1" stop-color="#082b63"/></radialGradient></defs><circle cx="60" cy="60" r="39" fill="url(#cpGlobe)" stroke="#d7ad48" stroke-width="2"/><path d="M22 60h76M60 21c14 15 20 27 20 39S74 84 60 99M60 21C46 36 40 48 40 60s6 24 20 39M32 38c17 9 39 9 56 0M32 82c17-9 39-9 56 0" fill="none" stroke="#dbe9fb" stroke-width="2" opacity=".9"/></svg>`}
function flagIcon(){return `<svg viewBox="0 0 120 120" aria-hidden="true"><defs><linearGradient id="cpFlag" x1="0" x2="1"><stop offset="0" stop-color="#f6f8fb"/><stop offset=".55" stop-color="#fff"/><stop offset="1" stop-color="#dbe3ee"/></linearGradient></defs><path d="M29 15v91" stroke="#a97722" stroke-width="4"/><path d="M33 21c20-12 37 8 58-2v45c-21 10-38-10-58 2Z" fill="url(#cpFlag)" stroke="#9ba9b9" stroke-width="2"/><circle cx="62" cy="43" r="12" fill="#0d4d9b" opacity=".92"/><path d="M55 43h14M62 36v14" stroke="#d7ad48" stroke-width="2"/></svg>`}
function statIcon(type){const map={countries:'<circle cx="12" cy="12" r="8"/><path d="M4 12h16M12 4c3 3 4 5 4 8s-1 5-4 8M12 4c-3-3-4-5-4-8s1-5 4-8"/>',leagues:'<path d="M5 5h14v4c0 5-3 8-7 10-4-2-7-5-7-10Z"/><path d="M8 5V3h8v2"/>',cup:'<path d="M7 4h10v4c0 5-2 8-5 9-3-1-5-4-5-9V4Z"/><path d="M9 17v3h6v-3M4 6H2c0 4 2 6 5 6M20 6h2c0 4-2 6-5 6"/>',shield:'<path d="M12 3 20 6v6c0 5-3 8-8 10-5-2-8-5-8-10V6Z"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${map[type]||""}</svg>`}
function cardIcon(x){const a=actionOf(x);if(a==="league")return `<div class="cp-menu-emblem"><strong>${esc(clean(x.IMC_league_divisions||"L").replace(/[^0-9]/g,"")||"L")}</strong><small>${esc(clean(x.sm_country||""))}</small></div>`;if(a==="worldcup"||a==="interqualifier")return `<div class="cp-menu-art cp-menu-art-flag">${flagIcon()}</div>`;if(a==="smfacup"||a==="smfashield"||a==="supercup")return `<div class="cp-menu-art">${globeIcon()}</div>`;return `<div class="cp-menu-art">${trophyIcon()}</div>`}
async function load(){const [c,s]=await Promise.all([state.client.rpc("imc_nexus_gateway",{p_action:"gw_competitions",p_args:{gameWorld:state.worldId}}),state.client.rpc("imc_nexus_gateway",{p_action:"imc_seasons",p_args:{gameWorld:state.worldId}})]);if(c.error)throw c.error;if(s.error)throw s.error;state.items=(c.data&&c.data.rows)||[];state.seasons=(s.data&&s.data.rows)||[];if(!state.activeCountry)state.activeCountry=countries()[0]||""}
async function ensureSchedule(){if(state.scheduleLoaded)return;const r=await state.client.rpc("imc_nexus_gateway",{p_action:"schedule",p_args:{gameWorld:state.worldId}});if(!r.error)state.schedule=(r.data&&r.data.rows)||[];state.scheduleLoaded=true}
function standings(rows){const t=new Map();for(const r of rows){const h=clean(r.home_name),a=clean(r.away_name),hs=Number(r.home_score),as=Number(r.away_score);if(!h||!a||Number.isNaN(hs)||Number.isNaN(as))continue;if(!t.has(h))t.set(h,{name:h,p:0,pts:0,gd:0});if(!t.has(a))t.set(a,{name:a,p:0,pts:0,gd:0});const H=t.get(h),A=t.get(a);H.p++;A.p++;H.gd+=hs-as;A.gd+=as-hs;if(hs>as)H.pts+=3;else if(as>hs)A.pts+=3;else{H.pts++;A.pts++}}return [...t.values()].sort((x,y)=>y.pts-x.pts||y.gd-x.gd||x.name.localeCompare(y.name)).slice(0,3)}
async function ensurePreviews(items){await ensureSchedule();const missing=items.filter(x=>keyOf(x)&&!state.previews.has(keyOf(x)));await Promise.all(missing.map(async x=>{const k=keyOf(x);const r=await state.client.rpc("imc_nexus_gateway",{p_action:"results",p_args:{gameWorld:state.worldId,competitionKey:k,limit:1000}});const rows=!r.error&&r.data&&r.data.rows?r.data.rows:[];const scheduled=state.schedule.filter(s=>clean(s.competition_key)===k);const future=scheduled.map(s=>({...s,_d:new Date(clean(s.match_date)+"T12:00:00")})).filter(s=>!isNaN(s._d)&&s._d>=new Date(new Date().setHours(0,0,0,0))).sort((a,b)=>a._d-b._d);state.previews.set(k,{rows,last:rows[0]||null,next:future[0]||null,top:actionOf(x)==="league"?standings(rows):[],scheduleRows:scheduled,future})}))}
function renderHub(){const domestic=countType("domestic"),international=countType("international"),nations=countType("nations"),countriesN=countryCount(),leagues=countAction("league"),nationalCups=countAction("leaguecup"),leagueCups=countAction("leagueshield"),charity=countAction("charityshield"),season=state.seasons[0]||{},seasonLabel=clean(season.imc_season||season.soccer_manager_season||"—"),start=formatDate(season.imc_season_start_date),end=formatDate(season.imc_season_end_date);return `<section class="cp-hub" data-competitions-version="${VERSION}"><section class="cp-world-strip"><div class="cp-world-mark"><span>${esc(state.worldId)}</span><strong>${esc(state.worldName||state.worldId)}</strong></div><div class="cp-world-season"><b>SEASON ${esc(seasonLabel)}</b><small>${start} — ${end}</small></div></section><div class="cp-hub-title"><span>COMPETITIONS HUB</span></div><button type="button" class="cp-domestic" data-cp-open="domestic"><div class="cp-domestic-copy"><span class="cp-kicker">DOMESTIC</span><div class="cp-count"><strong>${domestic}</strong><b>COMPETITIONS</b></div><div class="cp-ecosystem"><div>${statIcon("countries")}<strong>${countriesN}</strong><span>COUNTRIES</span></div><div>${statIcon("leagues")}<strong>${leagues}</strong><span>LEAGUES</span></div><div>${statIcon("cup")}<strong>${nationalCups}</strong><span>NATIONAL<br>CUPS</span></div><div>${statIcon("cup")}<strong>${leagueCups}</strong><span>LEAGUE<br>CUPS</span></div><div>${statIcon("shield")}<strong>${charity}</strong><span>CHARITY<br>SHIELDS</span></div></div></div><div class="cp-domestic-art">${trophyIcon()}</div></button><section class="cp-secondary-grid"><button type="button" class="cp-secondary cp-international" data-cp-open="international"><div><span>INTERNATIONAL</span><strong>${international}</strong><small>COMPETITIONS</small></div><div class="cp-secondary-art">${globeIcon()}</div></button><button type="button" class="cp-secondary cp-nations" data-cp-open="nations"><div><span>NATIONS</span><strong>${nations}</strong><small>COMPETITIONS</small></div><div class="cp-secondary-art">${flagIcon()}</div></button></section></section>`}
function visibleItems(){let a=state.items.filter(x=>typeOf(x)===state.activeType);if(state.activeType==="domestic")a=a.filter(x=>clean(x["Country Nexus View"]||x.sm_country)===state.activeCountry);const order={league:1,leaguecup:2,leagueshield:3,charityshield:4,smfacup:1,smfashield:2,supercup:3,worldcup:1,interqualifier:2};return a.sort((x,y)=>(order[actionOf(x)]||9)-(order[actionOf(y)]||9)||nameOf(x).localeCompare(nameOf(y)))}
function lastBlock(p){const r=p&&p.last;if(!r)return `<div class="cp-mini"><span>LAST RESULT</span><strong>—</strong><small>Nessun risultato</small></div>`;return `<div class="cp-mini"><span>LAST RESULT</span><strong>${esc(r.home_score)} - ${esc(r.away_score)}</strong><small>${esc(r.home_name)} · ${esc(r.away_name)}</small></div>`}
function nextBlock(p){const n=p&&p.next;if(!n)return `<div class="cp-mini"><span>NEXT MATCH</span><strong>—</strong><small>Nessun match</small></div>`;return `<div class="cp-mini"><span>NEXT MATCH</span><strong>${esc(n.home_name)} vs ${esc(n.away_name)}</strong><small>${compactDate(n.match_date)}</small></div>`}
function topBlock(p,x){if(actionOf(x)!=="league")return `<div class="cp-mini cp-mini-stage"><span>FORMAT</span><strong>${esc(actionOf(x)==="charityshield"?"ONE-OFF":"KNOCKOUT")}</strong><small>${esc(clean(x.sm_round_label||""))}</small></div>`;const top=p&&p.top||[];return `<div class="cp-top3"><span>TOP 3</span>${top.length?top.map((t,i)=>`<div><b>${i+1}</b><strong>${esc(t.name)}</strong><em>${t.pts} PT</em></div>`).join(""):'<small>Classifica non disponibile</small>'}</div>`}
function actionLabel(x){const a=actionOf(x);if(a==="league")return `LEAGUE · ${clean(x.IMC_league_teams_count||"—")} TEAMS`;if(a==="leaguecup")return"NATIONAL CUP";if(a==="leagueshield")return"LEAGUE CUP";if(a==="charityshield")return"CHARITY SHIELD";if(a==="smfacup"||a==="smfashield")return"INTERNATIONAL";if(a==="supercup")return"SUPER CUP";if(a==="worldcup")return"WORLD CUP";if(a==="interqualifier")return"WORLD CUP QUALIFIER";return a.toUpperCase()}
function groupCount(rows){return new Set((rows||[]).map(r=>clean(r.group_label)).filter(Boolean)).size}
function teamsInRows(rows){const set=new Set();for(const r of rows||[]){if(clean(r.home_name))set.add(clean(r.home_name));if(clean(r.away_name))set.add(clean(r.away_name))}return set.size}
function latestRound(rows){for(const r of rows||[]){const q=clean(r.sm_round_label);if(q)return q}return""}
function winnerOf(r){if(!r)return"";const pw=clean(r.penalty_winner_name);if(pw)return pw;const hs=Number(r.home_score),as=Number(r.away_score);if(Number.isNaN(hs)||Number.isNaN(as)||hs===as)return"";return hs>as?clean(r.home_name):clean(r.away_name)}
function metric(label,value){return `<div><span>${esc(label)}</span><strong>${esc(value||"—")}</strong></div>`}
function gw002Facts(x,p){
  if(!p)return{status:"LOADING",metrics:[["STATUS","LOADING"],["DATA","—"],["NEXT","—"]]};
  const a=actionOf(x),rows=p.rows||[],next=p.next||null;
  if(a==="league"){
    const teams=Number(x.IMC_league_teams_count)||0,perTurn=teams?teams/2:0,played=perTurn?Math.floor(rows.length/perTurn):0,total=perTurn&&Number(x.expected_total_matches)?Math.round(Number(x.expected_total_matches)/perTurn):0,leader=(p.top||[])[0];
    return{status:total&&played>=total?"COMPLETED":"LEAGUE",metrics:[["MATCH",total?`${played}/${total}`:String(played||"—")],["LEADER",leader?`${leader.name} · ${leader.pts} PT`:"—"],["NEXT TURN",next?compactDate(next.match_date):"—"]]};
  }
  if(a==="charityshield"||a==="supercup"){
    const w=winnerOf(p.last);
    return{status:rows.length&&!next?"COMPLETED":"ONE-OFF",metrics:[["STATUS",rows.length&&!next?"COMPLETED":"UPCOMING"],["WINNER",w||"—"],["DATE",next?compactDate(next.match_date):p.last?compactDate(p.last.source_page_date||p.last.match_date):"—"]]};
  }
  if(a==="smfacup"||a==="smfashield"){
    const groups=groupCount(rows),ko=rows.filter(r=>!clean(r.group_label)),stage=ko.length?(latestRound(ko)||"KNOCKOUT"):(groups?"GROUP STAGE":"NOT STARTED");
    return{status:stage,metrics:[["STAGE",stage],[groups?"GROUPS":"MATCHES",groups?String(groups):String(rows.length)],["NEXT DATE",next?compactDate(next.match_date):"—"]]};
  }
  if(a==="worldcup"||a==="interqualifier"){
    const groups=groupCount(rows),stage=rows.length?(groups?"GROUP STAGE":latestRound(rows)||"KNOCKOUT"):(next?"UPCOMING":"NOT STARTED");
    return{status:stage,metrics:[["STATUS",stage],[groups?"GROUPS":"MATCHES",groups?String(groups):String(rows.length)],["NEXT DATE",next?compactDate(next.match_date):"—"]]};
  }
  const round=clean(next&&next.sm_round_label)||latestRound(rows)||(!rows.length&&!next?"NOT STARTED":"KNOCKOUT"),nextDate=next?clean(next.match_date):"",sameDate=nextDate?(p.future||[]).filter(r=>clean(r.match_date)===nextDate):[],remaining=teamsInRows(sameDate);
  return{status:round,metrics:[["ROUND",round],[remaining?"TEAMS":"MATCHES",remaining?String(remaining):String(rows.length)],["NEXT",next?compactDate(next.match_date):"—"]]};
}
function renderMenuGW002(){const list=visibleItems(),typeLabel=state.activeType.toUpperCase(),chips=state.activeType==="domestic"?`<div class="cp-country-filter">${countries().map(c=>`<button type="button" data-cp-country="${esc(c)}" class="${c===state.activeCountry?"is-active":""}">${esc(c)}</button>`).join("")}</div>`:"";return `<section class="cp-menu cp-gw002-lab" data-competitions-version="${VERSION}"><section class="cp-menu-world"><button type="button" class="cp-menu-back" data-cp-back aria-label="Torna al Competition Hub">‹</button><div><span>${esc(state.worldId)}</span><strong>${esc(state.worldName||state.worldId)}</strong></div><small>COMPETITIONS</small></section><nav class="cp-type-tabs" aria-label="Competition type"><button type="button" data-cp-type="domestic" class="${state.activeType==="domestic"?"is-active":""}">DOMESTIC</button><button type="button" data-cp-type="international" class="${state.activeType==="international"?"is-active":""}">INTERNATIONAL</button><button type="button" data-cp-type="nations" class="${state.activeType==="nations"?"is-active":""}">NATIONS</button></nav>${chips}<div class="cp-menu-label"><span>${typeLabel}</span><b>${list.length}</b></div><div class="cp-menu-grid cp-lab-grid">${list.map(x=>{const p=state.previews.get(keyOf(x)),facts=gw002Facts(x,p);return `<article class="cp-preview-card cp-lab-card">${cardIcon(x)}<div class="cp-lab-copy"><header><div><h3>${esc(nameOf(x))}</h3><p>${esc(actionLabel(x))}</p></div><span class="cp-lab-status">${esc(facts.status)}</span></header><div class="cp-lab-metrics">${facts.metrics.map(m=>metric(m[0],m[1])).join("")}</div></div><span class="cp-preview-arrow">›</span></article>`}).join("")||`<div class="cp-menu-empty">Nessuna competition disponibile.</div>`}</div></section>`}
function renderMenu(){if(state.worldId==="GW002")return renderMenuGW002();const list=visibleItems();const typeLabel=state.activeType.toUpperCase();const chips=state.activeType==="domestic"?`<div class="cp-country-filter">${countries().map(c=>`<button type="button" data-cp-country="${esc(c)}" class="${c===state.activeCountry?"is-active":""}">${esc(c)}</button>`).join("")}</div>`:"";return `<section class="cp-menu" data-competitions-version="${VERSION}"><section class="cp-menu-world"><button type="button" class="cp-menu-back" data-cp-back aria-label="Torna al Competition Hub">‹</button><div><span>${esc(state.worldId)}</span><strong>${esc(state.worldName||state.worldId)}</strong></div><small>COMPETITIONS</small></section><nav class="cp-type-tabs" aria-label="Competition type"><button type="button" data-cp-type="domestic" class="${state.activeType==="domestic"?"is-active":""}">DOMESTIC</button><button type="button" data-cp-type="international" class="${state.activeType==="international"?"is-active":""}">INTERNATIONAL</button><button type="button" data-cp-type="nations" class="${state.activeType==="nations"?"is-active":""}">NATIONS</button></nav>${chips}<div class="cp-menu-label"><span>${typeLabel}</span><b>${list.length}</b></div><div class="cp-menu-grid">${list.map(x=>{const p=state.previews.get(keyOf(x));return `<article class="cp-preview-card">${cardIcon(x)}<div class="cp-preview-main"><header><div><h3>${esc(nameOf(x))}</h3><p>${esc(actionOf(x)==="league"?`LEAGUE · ${clean(x.IMC_league_teams_count||"—")} TEAMS`:actionOf(x).replace(/([a-z])([A-Z])/g,"$1 $2").toUpperCase())}</p></div><span class="cp-preview-arrow">›</span></header><div class="cp-preview-data">${lastBlock(p)}${nextBlock(p)}${topBlock(p,x)}</div></div></article>`}).join("")||`<div class="cp-menu-empty">Nessuna competition disponibile.</div>`}</div></section>`}
function render(){if(!state.container)return;state.container.innerHTML=state.view==="hub"?renderHub():renderMenu()}
async function openMenu(type){state.activeType=type;state.view="menu";if(type==="domestic"&&!state.activeCountry)state.activeCountry=countries()[0]||"";render();const list=visibleItems();await ensurePreviews(list);if(state.view==="menu"&&state.activeType===type)render()}
async function mount(opts){if(!opts||!opts.container||!opts.client||!opts.worldId)throw new Error("Competitions: parametri mancanti");state={...state,...opts,worldId:clean(opts.worldId),worldName:clean(opts.worldName),items:[],seasons:[],view:"hub",activeType:"domestic",activeCountry:"",schedule:[],previews:new Map(),scheduleLoaded:false};state.container.innerHTML='<div class="cp-loading">Caricamento Competition Hub…</div>';await load();render()}
function unmount(){if(state.container)state.container.innerHTML="";state.container=null}
document.addEventListener("click",async e=>{if(!state.container)return;const open=e.target.closest&&e.target.closest("[data-cp-open]");if(open&&state.container.contains(open)){await openMenu(clean(open.getAttribute("data-cp-open")));return}const back=e.target.closest&&e.target.closest("[data-cp-back]");if(back&&state.container.contains(back)){state.view="hub";render();return}const type=e.target.closest&&e.target.closest("[data-cp-type]");if(type&&state.container.contains(type)){await openMenu(clean(type.getAttribute("data-cp-type")));return}const country=e.target.closest&&e.target.closest("[data-cp-country]");if(country&&state.container.contains(country)){state.activeCountry=clean(country.getAttribute("data-cp-country"));render();await ensurePreviews(visibleItems());if(state.view==="menu"&&state.activeType==="domestic")render()}});
window.IMC_COMPETITIONS={version:VERSION,mount,unmount};
})();