(() => {
'use strict';
const GW='GW003',root=document.getElementById('app'); if(!root)return;
const S={world:null,clubs:[],clubCodex:new Map(),competitions:[],managers:[],managerCodex:new Map(),results:[],schedule:[],transfers:[],stats:[],reports:[],players:new Map(),loading:true,error:null};
const MAIN=[['home','Home'],['competitions','Competitions'],['clubs','Clubs'],['managers','Managers'],['matches','Matches'],['players','Players'],['market','Market'],['reports','Reports']];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rows=x=>Array.isArray(x)?x:Array.isArray(x?.rows)?x.rows:Array.isArray(x?.data)?x.data:[];
const get=(o,ks,f='')=>{for(const k of ks)if(o&&o[k]!=null&&o[k]!=='')return o[k];return f};
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const read=(api,res,opt={})=>api.read(res,{game_world_id:GW,...opt});
const dateVal=o=>{const n=Date.parse(get(o,['match_date','transfer_date','imported_at','created_at'],''));return Number.isFinite(n)?n:0};
const fmt=n=>n?new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short'}).format(new Date(n)):'—';
const slug=s=>encodeURIComponent(String(s??'')); const unslug=s=>{try{return decodeURIComponent(s||'')}catch{return s||''}};
const waitApi=ms=>new Promise(resolve=>{const t=Date.now();(function f(){if(window.IMC_MINISITE_DATA?.read)return resolve(window.IMC_MINISITE_DATA);if(Date.now()-t>ms)return resolve(null);setTimeout(f,50)})()});
const initials=n=>String(n||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
function route(){const raw=(location.hash||'#home').slice(1),[name,arg,tab]=raw.split('/');return {name:[...MAIN.map(x=>x[0]),'competition','club','manager'].includes(name)?name:'home',arg:unslug(arg),tab:tab||'overview'}}
window.addEventListener('hashchange',render);
boot();
async function boot(){shell();const api=await waitApi(3000);if(!api){S.error='Data service unavailable';S.loading=false;render();return}try{const [w,c,co,m,r,sc,t,st,rp]=await Promise.all([read(api,'game_world_codex'),read(api,'game_world_club_mapping'),read(api,'competition_codex'),read(api,'manager_assignments'),read(api,'results',{limit:1000}),read(api,'schedule',{limit:1000}),read(api,'transfers',{limit:1000}),read(api,'sm_player_stats',{limit:1000}),read(api,'match_report',{limit:1000})]);S.world=rows(w)[0]||null;S.clubs=rows(c);S.competitions=rows(co);S.managers=rows(m);S.results=rows(r);S.schedule=rows(sc);S.transfers=rows(t);S.stats=rows(st);S.reports=rows(rp);await Promise.all([hydrateClubs(api),hydrateManagers(api),hydratePlayers(api)])}catch(e){S.error=e?.message||'Unable to load data'}S.loading=false;render()}
async function hydrateClubs(api){await Promise.all(S.clubs.slice(0,140).map(async c=>{if(!c.club_id)return;try{const x=rows(await read(api,'club_codex',{club_id:c.club_id}))[0];if(x)S.clubCodex.set(String(c.club_id),x)}catch{}}))}
async function hydrateManagers(api){await Promise.all([...new Set(S.managers.map(x=>x.manager_id).filter(Boolean))].slice(0,140).map(async id=>{try{const x=rows(await read(api,'manager_codex',{manager_id:id}))[0];if(x)S.managerCodex.set(String(id),x)}catch{}}))}
async function hydratePlayers(api){await Promise.all(topStats(80).map(async p=>{const id=p.sm_player_id||p.player_id;if(!id)return;try{const x=rows(await read(api,'player_codex',{player_id:id}))[0];if(x)S.players.set(String(id),x)}catch{}}))}
function shell(){root.innerHTML=`<div class="app-shell"><header class="app-top"><a href="#home" class="app-brand"><span>IMC</span><b>MANAGER</b><i>GW003</i></a><button id="openMenu">☰</button></header><main id="view"></main><nav class="app-dock">${MAIN.slice(0,5).map(([r,l])=>`<a href="#${r}" data-nav="${r}"><b>${l[0]}</b><span>${l}</span></a>`).join('')}</nav><dialog id="menu"><button id="closeMenu">×</button><h3>GW003</h3>${MAIN.map(([r,l])=>`<a href="#${r}">${l}</a>`).join('')}</dialog></div>`;document.getElementById('openMenu').onclick=()=>document.getElementById('menu').showModal();document.getElementById('closeMenu').onclick=()=>document.getElementById('menu').close();document.querySelectorAll('#menu a').forEach(a=>a.onclick=()=>document.getElementById('menu').close());render()}
function render(){const v=document.getElementById('view');if(!v)return;const r=route();document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===r.name));if(S.loading){v.innerHTML='<section class="boot"><div class="pulse"></div><b>SYNCING GW003</b><span>Loading live Game World data</span></section>';return}if(S.error){v.innerHTML=`<section class="boot"><b>DATA OFFLINE</b><span>${esc(S.error)}</span></section>`;return}const map={home,competitions,competition,clubs,club,managers,manager,matches,players,market,reports};v.innerHTML=map[r.name](r.arg,r.tab);bind()}
function bind(){document.querySelectorAll('[data-open-club]').forEach(b=>b.onclick=()=>location.hash=`#club/${slug(b.dataset.openClub)}`);document.querySelectorAll('[data-open-manager]').forEach(b=>b.onclick=()=>location.hash=`#manager/${slug(b.dataset.openManager)}`)}
function home(){const w=S.world||{},lead=topStats(1)[0],last=recent(1)[0],next=upcoming(1)[0];return `<section class="home-screen"><div class="hero-app"><span>LIVE GAME WORLD</span><h1>${esc(get(w,['game_world_name','IMC GW Name'],window.IMC_GAME_WORLD?.name||'Gold 557'))}</h1><p>${S.clubs.length} clubs · ${S.competitions.length} competitions · ${S.results.length} results</p><div class="hero-actions"><a href="#competitions">Competition Hub</a><a href="#matches">Match Centre</a></div></div><div class="metric-carousel">${metric('RESULTS',S.results.length,'#matches')}${metric('FIXTURES',S.schedule.length,'#matches')}${metric('TRANSFERS',S.transfers.length,'#market')}${metric('PLAYERS',S.stats.length,'#players')}</div><section class="home-grid"><article class="feature player-feature">${lead?playerFeature(lead):empty('No player stats')}</article><article class="feature timeline-feature"><header><span>NOW</span><h2>Match Timeline</h2></header>${last?matchRow(last,true):''}${next?matchRow(next,false):''}<a href="#matches">Open full timeline →</a></article><article class="feature comp-feature"><header><span>CORE MODE</span><h2>Competition Hub</h2></header>${['DOMESTIC','INTERNATIONAL','NATIONS'].map(g=>groupButton(g)).join('')}</article><article class="feature clubs-feature"><header><span>CLUB WORLD</span><h2>Club Network</h2></header><div class="club-strip">${S.clubs.slice(0,12).map(clubChip).join('')}</div><a href="#clubs">Explore all clubs →</a></article></section></section>`}
const metric=(l,v,h)=>`<a href="${h}"><span>${l}</span><b>${v}</b></a>`;
function playerFeature(p){const n=get(p,['player_name','full_name','name'],'Player'),img=playerImage(p);return `<div class="player-visual">${img?`<img src="${esc(img)}" alt="${esc(n)}">`:`<div>${initials(n)}</div>`}</div><div class="player-copy"><span>FORM LEADER</span><h2>${esc(n)}</h2><p>${esc(get(p,['club_name'],'Club'))}</p><div class="ring"><b>${esc(get(p,['avg_rating','rating'],'—'))}</b><small>AVG</small></div><div class="mini-stats"><b>${num(p.appearances)}<small>APP</small></b><b>${num(p.goals)}<small>G</small></b><b>${num(p.assists)}<small>A</small></b></div><a href="#players">Player Deck →</a></div>`}
function groupButton(g){const arr=S.competitions.filter(c=>group(c)===g);return `<a class="group-btn ${g.toLowerCase()}" href="#competitions"><span>${g}</span><b>${arr.length}</b><i>›</i></a>`}
function competitions(){return screenHead('COMPETITION HUB','Choose a world, then drill into results, fixtures and reports')+`<div class="segmented">${['DOMESTIC','INTERNATIONAL','NATIONS'].map(g=>`<a href="#competitions">${g}</a>`).join('')}</div><div class="competition-sections">${['DOMESTIC','INTERNATIONAL','NATIONS'].map(g=>`<section><header><span>${g}</span><b>${S.competitions.filter(c=>group(c)===g).length}</b></header><div class="comp-carousel">${S.competitions.filter(c=>group(c)===g).map(compCard).join('')||empty('No competitions')}</div></section>`).join('')}</div>`}
function compCard(c){const r=filterComp(S.results,c),s=filterComp(S.schedule,c),rp=filterComp(S.reports,c);return `<a class="comp-card" href="#competition/${slug(compKey(c))}"><span>${esc(group(c))}</span><h3>${esc(compName(c))}</h3><p>${esc(c.sm_country||'Global')}${c.sm_division?` · D${esc(c.sm_division)}`:''}</p><div class="comp-kpis"><b>${r.length}<small>RES</small></b><b>${s.length}<small>FIX</small></b><b>${rp.length}<small>REP</small></b></div><i>OPEN HUB</i></a>`}
function competition(arg,tab){const c=S.competitions.find(x=>compKey(x)===arg);if(!c)return notFound('Competition');const r=filterComp(S.results,c).sort((a,b)=>dateVal(b)-dateVal(a)),s=filterComp(S.schedule,c).sort((a,b)=>dateVal(a)-dateVal(b)),rp=filterComp(S.reports,c).sort((a,b)=>dateVal(b)-dateVal(a));const tabs=['overview','results','fixtures','reports'];const active=tabs.includes(tab)?tab:'overview';return `<section class="detail-screen"><a class="back" href="#competitions">← Competitions</a><div class="comp-hero"><span>${esc(group(c))}</span><h1>${esc(compName(c))}</h1><p>${esc(c.sm_country||'Global')}${c.sm_division?` · Division ${esc(c.sm_division)}`:''}</p><div class="progress-card"><div style="--p:${Math.min(100,Math.round((r.length/Math.max(num(c.expected_match),r.length||1))*100))}%"><span></span></div><b>${r.length}<small>played</small></b><b>${esc(c.expected_match||'—')}<small>expected</small></b></div></div><nav class="tabs">${tabs.map(t=>`<a class="${active===t?'active':''}" href="#competition/${slug(arg)}/${t}">${t}</a>`).join('')}</nav>${active==='overview'?competitionOverview(c,r,s,rp):active==='results'?listWrap(r.map(x=>matchRow(x,true)).join('')):active==='fixtures'?listWrap(s.map(x=>matchRow(x,false)).join('')):listWrap(rp.map(reportRow).join(''))}</section>`}
function competitionOverview(c,r,s,rp){return `<div class="detail-grid"><article><span>LAST RESULT</span>${r[0]?matchRow(r[0],true):empty('No results')}</article><article><span>NEXT FIXTURE</span>${s[0]?matchRow(s[0],false):empty('No fixtures')}</article><article class="wide"><span>MATCH REPORTS</span>${rp.slice(0,4).map(reportRow).join('')||empty('No reports')}</article></div>`}
function clubs(){return screenHead('CLUB HUB','Tap a club to open its live profile')+`<div class="club-wall">${S.clubs.map(clubCard).join('')}</div>`}
function clubCard(c){const x=S.clubCodex.get(String(c.club_id)),m=managerForClub(c);return `<button data-open-club="${esc(clubKey(c))}" class="club-tile">${logo(x?.image_url,c.club_name)}<div><span>${esc(clubForm(c))}</span><h3>${esc(c.club_name||'Club')}</h3><p>${esc(managerName(m)||'IMC Club')}</p></div><i>›</i></button>`}
function club(arg){const c=S.clubs.find(x=>clubKey(x)===arg);if(!c)return notFound('Club');const x=S.clubCodex.get(String(c.club_id)),m=managerForClub(c),r=clubRows(S.results,c).sort((a,b)=>dateVal(b)-dateVal(a)),s=clubRows(S.schedule,c).sort((a,b)=>dateVal(a)-dateVal(b)),p=S.stats.filter(v=>sameClub(v,c)).sort((a,b)=>num(b.avg_rating)-num(a.avg_rating)),t=transferRows(c);return `<section class="detail-screen"><a class="back" href="#clubs">← Clubs</a><div class="club-profile">${logo(x?.image_url,c.club_name)}<div><span>CLUB PROFILE</span><h1>${esc(c.club_name||'Club')}</h1><p>${esc(managerName(m)||'Manager unavailable')}</p>${m?`<button data-open-manager="${esc(m.manager_id)}">Manager profile</button>`:''}</div></div><div class="metric-carousel">${metric('RESULTS',r.length,'#matches')}${metric('FIXTURES',s.length,'#matches')}${metric('PLAYERS',p.length,'#players')}${metric('MOVES',t.length,'#market')}</div><div class="detail-grid"><article><span>FORM</span>${r.slice(0,5).map(x=>matchRow(x,true)).join('')||empty('No results')}</article><article><span>NEXT</span>${s.slice(0,5).map(x=>matchRow(x,false)).join('')||empty('No fixtures')}</article><article class="wide"><span>TOP PLAYERS</span>${p.slice(0,8).map(playerLine).join('')||empty('No player stats')}</article></div></section>`}
function managers(){return screenHead('MANAGER HUB','Profiles, assignments and club performance')+`<div class="manager-stack">${S.managers.map(managerCard).join('')}</div>`}
function managerCard(m){const n=managerName(m);return `<button data-open-manager="${esc(m.manager_id)}" class="manager-card"><div>${initials(n)}</div><section><span>IMC MANAGER</span><h3>${esc(n)}</h3><p>${esc(m.club_name||'Assignment')}</p></section><i>›</i></button>`}
function manager(arg){const m=S.managers.find(x=>String(x.manager_id)===String(arg));if(!m)return notFound('Manager');const n=managerName(m),c=S.clubs.find(x=>String(x.club_id||'')===String(m.club_id||'')||sameName(x.club_name,m.club_name)),r=c?clubRows(S.results,c):[],s=c?clubRows(S.schedule,c):[];return `<section class="detail-screen"><a class="back" href="#managers">← Managers</a><div class="manager-profile"><div>${initials(n)}</div><section><span>CAREER PROFILE</span><h1>${esc(n)}</h1><p>${esc(m.club_name||'Current assignment')}</p>${c?`<button data-open-club="${esc(clubKey(c))}">Open Club Hub</button>`:''}</section></div><div class="detail-grid"><article><span>RECENT RESULTS</span>${r.slice(0,8).map(x=>matchRow(x,true)).join('')||empty('No linked results')}</article><article><span>UPCOMING</span>${s.slice(0,8).map(x=>matchRow(x,false)).join('')||empty('No linked fixtures')}</article></div></section>`}
function matches(){const merged=[...S.results.map(x=>({...x,_done:true})),...S.schedule.map(x=>({...x,_done:false}))].sort((a,b)=>dateVal(b)-dateVal(a));return screenHead('MATCH CENTRE','A single live timeline for results and fixtures')+`<div class="timeline">${merged.slice(0,80).map(x=>matchRow(x,x._done)).join('')||empty('No matches')}</div>`}
function players(){return screenHead('PLAYER DECK','Swipe-style cards built from live player stats')+`<div class="player-deck">${topStats(60).map(playerCard).join('')||empty('No player stats')}</div>`}
function playerCard(p){const n=get(p,['player_name','full_name','name'],'Player'),img=playerImage(p);return `<article class="player-card">${img?`<img src="${esc(img)}" alt="${esc(n)}">`:`<div class="player-fallback">${initials(n)}</div>`}<div class="player-overlay"><span>${esc(get(p,['club_name'],'Club'))}</span><h2>${esc(n)}</h2><div><b>${esc(get(p,['avg_rating'],'—'))}<small>AVG</small></b><b>${num(p.goals)}<small>G</small></b><b>${num(p.assists)}<small>A</small></b><b>${num(p.appearances)}<small>APP</small></b></div></div></article>`}
function market(){return screenHead('TRANSFER FEED','Live market intelligence')+`<div class="market-feed">${S.transfers.map(transferRow).join('')||empty('No transfers')}</div>`}
function reports(){return screenHead('MATCH STORIES','Match report archive')+`<div class="report-feed">${S.reports.map(reportRow).join('')||empty('No reports')}</div>`}
function screenHead(k,t){return `<header class="screen-head"><span>${esc(k)}</span><h1>${esc(t)}</h1></header>`}
function listWrap(x){return `<div class="timeline">${x||empty('Nothing here')}</div>`}
function matchRow(r,done){return `<article class="match-row"><time>${fmt(dateVal(r))}</time><div><span>${esc(compNameFromRow(r))}</span><strong>${esc(done?matchText(r):fixtureText(r))}</strong></div><b>${done?`${esc(get(r,['home_score'],'–'))}:${esc(get(r,['away_score'],'–'))}`:'›'}</b></article>`}
function reportRow(r){return `<article class="report-row"><span>${fmt(dateVal(r))} · ${esc(compNameFromRow(r))}</span><strong>${esc(matchText(r))}</strong><p>${esc(get(r,['result_status','status'],'Match report'))}</p></article>`}
function transferRow(t){return `<article class="transfer-row"><time>${fmt(dateVal(t))}</time><div><strong>${esc(get(t,['player_name','name'],'Player'))}</strong><span>${esc(get(t,['from_club_name','old_club_name'],'—'))} → ${esc(get(t,['to_club_name','new_club_name'],'—'))}</span></div><b>${esc(get(t,['transfer_fee','fee'],'LIVE'))}</b></article>`}
function playerLine(p){return `<div class="player-line"><strong>${esc(get(p,['player_name','full_name'],'Player'))}</strong><span>${esc(get(p,['club_name'],'Club'))}</span><b>${esc(get(p,['avg_rating'],'—'))}</b></div>`}
function clubChip(c){const x=S.clubCodex.get(String(c.club_id));return `<button data-open-club="${esc(clubKey(c))}">${logo(x?.image_url,c.club_name)}<span>${esc(c.club_name)}</span></button>`}
function recent(n){return [...S.results].sort((a,b)=>dateVal(b)-dateVal(a)).slice(0,n)} function upcoming(n){return [...S.schedule].sort((a,b)=>dateVal(a)-dateVal(b)).slice(0,n)} function topStats(n){return [...S.stats].sort((a,b)=>num(b.avg_rating)-num(a.avg_rating)||num(b.goals)-num(a.goals)).slice(0,n)}
function compName(c){return get(c,['custom_competition','competition_name','sm_action'],'Competition')} function compKey(c){return String(get(c,['competition_key','custom_competition','sm_action'],'Competition'))} function group(c){const g=String(get(c,['sm_action_group','competition_group'],'')).toUpperCase();return g.includes('NATION')?'NATIONS':g.includes('INTERN')?'INTERNATIONAL':'DOMESTIC'} function compNameFromRow(r){return get(r,['competition_group_name','competition_name','competition_key','sm_action'],'Competition')}
function filterComp(arr,c){const key=compKey(c).toLowerCase(),name=compName(c).toLowerCase();return arr.filter(r=>{const vals=[r.competition_key,r.competition_group_name,r.competition_name,r.sm_action].filter(Boolean).map(v=>String(v).toLowerCase());return vals.some(v=>v===key||v===name||v.includes(name)||key.includes(v))})}
function managerForClub(c){return S.managers.find(m=>String(m.club_id||'')===String(c.club_id||'')||sameName(m.club_name,c.club_name))} function managerName(m){if(!m)return'';const x=S.managerCodex.get(String(m.manager_id));return x?.full_name||m.manager_name||`Manager ${m.manager_id||''}`} function clubKey(c){return String(c.club_id||c.club_name||'')} function sameName(a,b){return String(a||'').trim().toLowerCase()===String(b||'').trim().toLowerCase()} function sameClub(p,c){return String(p.sm_club_id||p.club_id||'')===String(c.club_id||'')||sameName(p.club_name,c.club_name)} function clubRows(arr,c){return arr.filter(r=>sameName(get(r,['home_name','home_team','home_club_name'],''),c.club_name)||sameName(get(r,['away_name','away_team','away_club_name'],''),c.club_name)||String(r.home_sm_club_id||'')===String(c.club_id||'')||String(r.away_sm_club_id||'')===String(c.club_id||''))} function transferRows(c){return S.transfers.filter(t=>sameName(get(t,['from_club_name','old_club_name'],''),c.club_name)||sameName(get(t,['to_club_name','new_club_name'],''),c.club_name)||String(t.from_sm_club_id||'')===String(c.club_id||'')||String(t.to_sm_club_id||'')===String(c.club_id||''))}
function clubForm(c){return clubRows(S.results,c).sort((a,b)=>dateVal(b)-dateVal(a)).slice(0,5).map(r=>{const hn=get(r,['home_name','home_team'],'');const home=sameName(hn,c.club_name)||String(r.home_sm_club_id||'')===String(c.club_id||'');const gf=num(home?r.home_score:r.away_score),ga=num(home?r.away_score:r.home_score);return gf>ga?'W':gf<ga?'L':'D'}).join(' ')||'—'}
function playerImage(p){const id=p?.sm_player_id||p?.player_id;const x=S.players.get(String(id));return x?.image_url||p?.player_image_url||p?.image_url||''} function logo(u,n){return u?`<img src="${esc(u)}" alt="${esc(n||'Club')}">`:`<span class="logo-fallback">${initials(n)}</span>`}
function matchText(r){return `${get(r,['home_name','home_team','home_club_name'],'Home')} ${get(r,['home_score'],'–')}–${get(r,['away_score'],'–')} ${get(r,['away_name','away_team','away_club_name'],'Away')}`} function fixtureText(r){return `${get(r,['home_name','home_team','home_club_name'],'Home')} vs ${get(r,['away_name','away_team','away_club_name'],'Away')}`}
function empty(t){return `<p class="empty">${esc(t)}</p>`} function notFound(t){return `<section class="boot"><b>${esc(t)} not found</b><a href="#home">Back home</a></section>`}
})();