(() => {
'use strict';
// Exploration 01 is deliberately isolated from production reads. The shared
// adapter remains available for the subsequent, separately verified data handoff.
const productionAdapter = window.IMC_MINISITE_DATA;
const mode = 'DEMO';
const root = document.getElementById('app');
if (!root) return;
const countries = [
 {id:'it',name:'Italia',code:'ITA',levels:3,base:['Milano','Torino','Roma','Napoli','Genova','Parma','Bologna','Firenze']},
 {id:'en',name:'Inghilterra',code:'ENG',levels:4,base:['London','Manchester','Liverpool','Leeds','Bristol','York','Derby','Oxford']},
 {id:'de',name:'Germania',code:'GER',levels:3,base:['Berlin','Hamburg','Bremen','Mainz','Bonn','Essen','Kiel','Ulm']},
 {id:'es',name:'Spagna',code:'ESP',levels:2,base:['Madrid','Sevilla','Bilbao','Valencia','Vigo','Cadiz','Malaga','Girona']},
 {id:'fr',name:'Francia',code:'FRA',levels:2,base:['Paris','Lyon','Lille','Nantes','Nice','Lens','Metz','Reims']},
 {id:'br',name:'Brasile',code:'BRA',levels:2,base:['Rio','Santos','Recife','Bahia','Natal','Palmas','Manaus','Belem']}
];
// These city-based labels are fictional demonstration clubs, not SM club records.
const clubs = countries.flatMap(c=>Array.from({length:c.levels},(_,j)=>c.base.map((n,k)=>({id:`${c.id}-${j+1}-${k}`,name:`${n} ${j?'Academy':'Demo'}`,country:c.id,division:j+1,position:k+1,played:8,w:[6,5,4,4,3,2,1,0][k],d:[1,2,2,1,2,2,2,2][k],gd:[12,9,5,2,0,-4,-9,-15][k],form:['WWDWW','DWWDW','WDWLW','WLWDW','LDWWD','LLDWD','DLLWL','LLDLL'][k]})))).flat();
clubs.forEach(c=>{c.points=c.w*3+c.d;c.loss=c.played-c.w-c.d});
const nav=[['home','Home'],['world','World Grid'],['countries','Countries'],['country','Country'],['division','Division'],['competitions','Competitions'],['results','Results'],['schedule','Schedule'],['match','Match Center'],['standings','Standings'],['manager','Manager'],['player','Player'],['club','Club'],['transfers','Transfers'],['data','Data / Comparison'],['report','World Report'],['moodboard','System Moodboard'],['responsive','Responsive Lab']];
const S={page:'home',country:'it',division:1,club:'it-1-0',tab:'events',sort:'structure',search:'',metric:'clubs',scope:'all',other:'en'};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const C=()=>countries.find(c=>c.id===S.country)||countries[0];
const group=()=>clubs.filter(c=>c.country===S.country&&c.division===S.division);
const currentClub=()=>clubs.find(c=>c.id===S.club)||group()[0];
const fmt=n=>String(n).padStart(2,'0');
function href(page,opts={}){const q=new URLSearchParams({country:S.country,division:String(S.division),...(['manager','player','club'].includes(page)?{club:S.club}:{}),...opts});return `#${page}?${q}`}
const A=(p,t,cl='',opts={})=>`<a class="${cl}" href="${href(p,opts)}">${t}</a>`;
const section=(title,p='',label='Esplora →')=>`<div class="section-title"><h2>${title}</h2>${p?A(p,label):''}</div>`;
const head=(eyebrow,title,desc='')=>`<header class="pagehead"><div class="eyebrow">${eyebrow}</div><h1 tabindex="-1">${title}</h1>${desc?`<p>${desc}</p>`:''}</header>`;
const metrics=items=>`<div class="metrics">${items.map(([n,l])=>`<div><b>${n}</b><small>${l}</small></div>`).join('')}</div>`;
const form=c=>`<span class="form" aria-label="Forma: ${c.form.split('').map(x=>({W:'vittoria',D:'pareggio',L:'sconfitta'}[x])).join(', ')}">${c.form.split('').map(x=>`<span class="${x}">${x}</span>`).join('')}</span>`;
const facts=items=>`<dl class="fact-list">${items.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>`;
const placeholder=(label,letters)=>`<div class="identity-placeholder"><b>${letters}</b><small>${label} DEMO</small></div>`;
function route(){const [p,q='']=(location.hash.slice(1)||'home').split('?');const z=new URLSearchParams(q);S.page=nav.some(x=>x[0]===p)?p:'notfound';const cc=countries.find(c=>c.id===z.get('country'));if(cc)S.country=cc.id;const d=Number(z.get('division')||S.division);S.division=Math.max(1,Math.min(C().levels,Number.isFinite(d)?d:1));S.club=z.get('club')||`${S.country}-${S.division}-0`;const club=clubs.find(c=>c.id===S.club);if(club&&['club','manager','player'].includes(S.page)){S.country=club.country;S.division=club.division}S.tab='events';S.search='';S.scope='all';render();}
function options(){return countries.map(c=>`<option value="${c.id}" ${c.id===S.country?'selected':''}>${c.name}</option>`).join('')}
function navlinks(){return nav.map(([p,l],i)=>A(p,`<span>${fmt(i+1)}</span>${l}`,`navlink ${p===S.page?'active':''}`)).join('')}
function shell(){root.innerHTML=`<header class="topbar"><a class="brand" href="#home"><img src="/minisite/GW002/imc-logo.png" alt="Italian Masters Club"><div><strong>GOLD 557</strong><small>IMC / GW003</small></div></a><span class="top-title">THE GLOBAL FOOTBALL GRID</span><span class="edition">VISUAL EXPLORATION<br>PROPOSAL 01</span><button data-menu>Indice completo</button></header><div class="layout"><aside class="index"><div class="eyebrow">Structure Index</div><nav aria-label="Navigazione principale">${navlinks()}</nav><div class="rail-note">EVERY CLUB<br>HAS A PLACE<br>IN THE GRID.<br><br>IMC · ONE CLUB.<br>MANY WORLDS.</div></aside><div class="center"><div class="context"><div class="crumb">${A('world','WORLD')} / ${A('country',C().code)} / ${A('division',`D${S.division}`)}</div><div class="context-controls"><label>Country <select id="country-switch" aria-label="Country">${options()}</select></label><label>Division <select id="division-switch" aria-label="Division">${Array.from({length:C().levels},(_,i)=>`<option value="${i+1}" ${i+1===S.division?'selected':''}>D${i+1}</option>`).join('')}</select></label></div></div><div class="demo"><b>DEMO</b>Campione illustrativo. Club, persone e numeri non sono dati reali di GW003.</div><main class="content" id="content" tabindex="-1"></main></div><aside class="context-rail">${contextRail()}</aside></div><footer class="footer"><span>ITALIAN MASTERS CLUB / GW003 · GOLD 557</span><span>VISUAL DESIGN EXPLORATION 01 · DATI DEMO</span></footer><nav class="mobile-nav" aria-label="Navigazione mobile">${[['home','Home'],['world','Grid'],['results','Results'],['standings','Table']].map(([p,l])=>A(p,l,p===S.page?'active':'')).join('')}<button data-menu>Indice</button></nav><dialog id="menu"><header><h2>Structure Index</h2><button id="close-menu" aria-label="Chiudi indice">Chiudi ×</button></header><nav aria-label="Indice completo">${navlinks()}</nav></dialog>`;}
function contextRail(){const c=currentClub();return `<div class="eyebrow">Selected context</div><h2>${C().name}<br>Division ${S.division}</h2><div class="rail-item"><span class="eyebrow">Prima posizione · demo</span><strong>${group()[0].name}</strong><p>${group()[0].points} punti / 8 partite</p>${A('standings','Classifica →')}</div><div class="rail-item"><span class="eyebrow">Club node</span><strong>${c.name}</strong>${A('club','Apri profilo →','',{club:c.id})}</div><div class="rail-item"><span class="eyebrow">Prossima finestra · demo</span><strong>12 SET / 20:00</strong><p>Calendario dimostrativo · UTC</p>${A('schedule','Tutte le partite →')}</div><div class="coordinate"><span>POSITION IN THE GRID</span><b>003<br>${C().code}<br>D${S.division}</b></div><div class="rail-note">Campione sintetico per valutare ordine, confronto e scala. Nessun collegamento ai dati di produzione in questa esplorazione.</div>`}
function render(){shell();const views={home,world,countries:countryIndex,country:countryPage,division,competitions,results,schedule,match,standings,manager,player,club,transfers,data,report,moodboard,responsive,notfound};document.getElementById('content').innerHTML=views[S.page]();document.title=`${nav.find(n=>n[0]===S.page)?.[1]||'Pagina non trovata'} · Gold 557 · GW003`;bind();}
function bind(){document.querySelector('.skip').onclick=e=>{e.preventDefault();document.getElementById('content').focus()};document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>document.getElementById('menu').showModal());document.getElementById('close-menu').onclick=()=>document.getElementById('menu').close();document.getElementById('country-switch').onchange=e=>location.hash=href('country',{country:e.target.value,division:'1'});document.getElementById('division-switch').onchange=e=>location.hash=href('division',{division:e.target.value});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;document.getElementById('match-detail').innerHTML=matchDetail();document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.tab===S.tab)))});const search=document.getElementById('country-search');if(search)search.oninput=e=>{S.search=e.target.value;document.getElementById('country-grid').innerHTML=countryCells(filteredCountries());document.getElementById('search-count').textContent=`${filteredCountries().length} country nel campione`};const sort=document.getElementById('grid-sort');if(sort)sort.onchange=e=>{S.sort=e.target.value;document.getElementById('world-matrix').innerHTML=matrix(sortedCountries())};const metric=document.getElementById('metric');if(metric)metric.onchange=e=>{S.metric=e.target.value;document.getElementById('bars').innerHTML=bars()};const other=document.getElementById('compare-country');if(other)other.onchange=e=>{S.other=e.target.value;document.getElementById('country-comparison').innerHTML=countryCompare()};const scope=document.getElementById('competition-scope');if(scope)scope.onchange=e=>{S.scope=e.target.value;document.getElementById('competition-list').innerHTML=competitionList()};const day=document.getElementById('result-day');if(day)day.onchange=e=>{document.getElementById('result-list').innerHTML=scoreList(Number(e.target.value))};const reset=document.getElementById('reset-search');if(reset)reset.onclick=()=>{S.search='';search.value='';search.dispatchEvent(new Event('input'))};}
function countryCells(arr=countries){return arr.map((c,i)=>A('country',`<div class="cell-meta"><span>${c.code} / WORLD NODE</span><span>${fmt(countries.indexOf(c)+1)}</span></div><h3>${c.name}</h3><div class="levels">${Array.from({length:c.levels},(_,j)=>`<i>D${j+1}</i>`).join('')}</div><div class="cell-foot"><span><b>${c.levels*8}</b> club demo</span><span class="arrow">↗</span></div>`,`country-cell ${c.id===S.country?'selected':''}`,{country:c.id,division:'1'})).join('')||'<div class="empty"><h2>Nessun country trovato</h2><p>Prova un altro nome o azzera la ricerca.</p></div>'}
function photo(){return `<figure><img src="https://images.unsplash.com/photo-1511204579483-e5c2b1d69acd?auto=format&fit=crop&w=1000&q=80" width="1000" height="700" alt="Vista aerea di uno stadio e della sua struttura urbana, riferimento fotografico" loading="lazy"><figcaption>Riferimento fotografico, non un impianto attribuito a GW003. <a href="https://unsplash.com/photos/aerial-view-photography-of-soccer-stadium-K4IVAFtu9GA" target="_blank" rel="noreferrer">Willian Justen de Vasconcellos / Unsplash</a></figcaption></figure>`}
function editorial(){return `<section class="editorial"><div class="editorial-copy"><span class="eyebrow">World report / design study</span><h2>Il sistema.<br>Dentro, il calcio.</h2><p>Paesi, divisioni, club. Una struttura leggibile per ritrovare ogni storia nel suo contesto.</p>${A('report','Apri il world report →','textlink')}</div>${photo()}</section>`}
function home(){return `${head('GW003 / THE GLOBAL FOOTBALL GRID','<span class="home-title"><span>EVERY CLUB.<br><em>ONE GRID.</em></span><span class="side-caption">Ogni club occupa una posizione.<br>Esplora il mondo, livello dopo livello.</span></span>')}${metrics([[6,'COUNTRY DEMO'],[16,'DIVISIONI DEMO'],[128,'CLUB DEMO'],['01','EXPLORATION']])}${section('World Grid','world','Apri la matrice →')}<div class="world-grid">${countryCells()}</div>${section('Dentro la competizione','results','Tutti i risultati →')}<div class="two">${score(0)}${score(1)}</div>${editorial()}${section('Il contesto prima del confronto','data','Confronta →')}${matrix(countries.slice(0,3))}`}
function sortedCountries(){return [...countries].sort(S.sort==='name'?(a,b)=>a.name.localeCompare(b.name):S.sort==='clubs'?(a,b)=>b.levels-a.levels:()=>0)}
function matrix(arr=countries){return `<table class="matrix"><caption>Division Matrix · numero di club per divisione, campione DEMO</caption><thead><tr><th scope="col">Country</th>${[1,2,3,4].map(d=>`<th scope="col">D${d}</th>`).join('')}</tr></thead><tbody>${arr.map(c=>`<tr><th scope="row">${A('country',c.name,'',{country:c.id,division:'1'})}</th>${[1,2,3,4].map(d=>`<td data-level="D${d}">${d<=c.levels?A('division','08','',{country:c.id,division:String(d)}):'<span class="absent">Non prevista</span>'}</td>`).join('')}</tr>`).join('')}</tbody></table><p class="legend">08 = club nel campione · “Non prevista” descrive soltanto la struttura demo.</p>`}
function world(){return `${head('WORLD / STRUCTURE INDEX','La scala.<br>In ordine.','Una lettura simultanea del campione, dai country alle divisioni.')}${metrics([[6,'COUNTRY DEMO'],[16,'LIVELLI TOTALI'],[128,'CLUB DEMO'],[8,'CLUB / LIVELLO']])}<div class="toolbar"><label>Ordina la matrice<select id="grid-sort"><option value="structure" ${S.sort==='structure'?'selected':''}>Ordine strutturale</option><option value="name" ${S.sort==='name'?'selected':''}>Country A–Z</option><option value="clubs" ${S.sort==='clubs'?'selected':''}>Numero di club</option></select></label></div><div id="world-matrix">${matrix(sortedCountries())}</div><div class="ice"><span class="eyebrow">Reading the grid</span><h2>Dimensione e forza<br>sono misure diverse.</h2><p>Qui confronti la struttura del campione. Il numero di divisioni non misura la qualità calcistica di un country.</p></div>${editorial()}`}
function filteredCountries(){return countries.filter(c=>`${c.name} ${c.code}`.toLowerCase().includes(S.search.toLowerCase().trim()))}
function countryIndex(){return `${head('COUNTRIES / COMPETITIVE UNITS','Scegli il<br>tuo contesto.','Ogni country apre il proprio indice competitivo.')}<div class="toolbar"><label>Cerca country<input id="country-search" type="search" placeholder="Nome o codice country" autocomplete="off"></label><button id="reset-search">Azzera</button></div><p class="legend" id="search-count" aria-live="polite">6 country nel campione</p><div id="country-grid" class="world-grid">${countryCells()}</div>`}
function countryPage(){return `${head(`${C().code} / COUNTRY BLOCK`,C().name,'Un’unità competitiva. Più livelli da esplorare.')}${metrics([[fmt(C().levels),'DIVISIONI DEMO'],[C().levels*8,'CLUB DEMO'],['D1','PRIMO LIVELLO'],['08','CLUB / DIVISIONE']])}${section('Struttura interna')}${Array.from({length:C().levels},(_,i)=>`<div class="division-row"><b>D${i+1}</b><div><h3>Division ${i+1}</h3><p>8 club demo · League<br>Prima posizione: ${clubs.find(c=>c.country===S.country&&c.division===i+1).name}</p></div>${A('division','Apri ↗','btn',{division:String(i+1)})}</div>`).join('')}${section('Ultimo turno dimostrativo','results')}${score(0)}${section('Confronto tra country','data')}${bars()}`}
function table(limit=8){const g=group().slice(0,limit);return `<table class="standings"><caption>${C().name} / D${S.division} · Classifica dimostrativa dopo 8 partite</caption><thead><tr><th class="position" scope="col">Pos.</th><th class="club-col" scope="col">Club</th><th scope="col">PT</th><th scope="col">DG</th><th class="optional" scope="col">G</th><th class="optional" scope="col">Forma</th></tr></thead><tbody>${g.map(c=>`<tr><td class="position">${fmt(c.position)}</td><td class="club-col">${A('club',c.name,'',{club:c.id})}</td><td class="points">${c.points}</td><td>${c.gd>0?'+':''}${c.gd}</td><td class="optional">${c.played}</td><td class="optional">${form(c)}</td></tr>`).join('')}</tbody></table>`}
function division(){return `${head(`${C().code} / DIVISION ${S.division}`,'Division '+S.division,'Posizioni, risultati e prossime partite nello stesso contesto.')}<div class="tabbar">${A('standings','Classifica','btn')}${A('results','Risultati','btn')}${A('schedule','Calendario','btn')}</div>${table(4)}${A('standings','Tutti gli 8 club →','textlink')}${section('Grid score / ultimo turno','results')}<div class="two">${score(0)}${score(1)}</div><div class="ice"><span class="eyebrow">Division status / demo</span><h2>${group()[0].points-group()[1].points} punti.<br>Tra prima e seconda.</h2><p>Il distacco mette a confronto due posizioni della stessa classifica, nello stesso momento.</p></div>`}
function matchData(i=0,day=10){const g=group(),pair=i%4;return {home:g[pair*2],away:g[pair*2+1],hs:[2,1,0,2][pair],as:[1,1,0,3][pair],day}}
function score(i=0,fixture=false,day=10){const m=matchData(i,day);return `<article class="score"><header><span>${C().code} / D${S.division} / LEAGUE</span><span>${fixture?'12':day} SET · DEMO</span></header>${A('match',`<span class="team">${m.home.name}</span><strong>${fixture?'20:00':`${m.hs} : ${m.as}`}</strong><span class="team">${m.away.name}</span>`,'scoreline',{match:String(i),day:String(day),...(fixture?{fixture:'1'}:{})})}<footer><span>${fixture?'PROGRAMMATA · UTC':'TERMINATA'} · ${day===9?'TURNO 7':'TURNO 8'}</span><span>Match Center ↗</span></footer></article>`}
function scoreList(day=10){return Array.from({length:4},(_,i)=>score(i,false,day)).join('')}
function results(){return `${head(`${C().code} / D${S.division} / RESULTS`,'Il turno.<br>Cella per cella.','Quattro incontri dimostrativi nel contesto selezionato.')}<div class="toolbar"><label>Turno demo<select id="result-day"><option value="10">Turno 8 · 10 settembre 2026</option><option value="9">Turno 7 · 9 settembre 2026</option></select></label></div><div id="result-list">${scoreList()}</div><p class="legend">I punteggi sono specimen grafici; non costituiscono lo storico completo della classifica demo.</p>`}
function schedule(){return `${head(`${C().code} / D${S.division} / SCHEDULE`,'Il prossimo<br>livello di gioco.','Programmazione dimostrativa · orari UTC.')}<section class="date-block"><header><b>12</b><span>SETTEMBRE 2026<br>TURNO DEMO</span></header><div>${[0,1,2,3].map(i=>score(i,true)).join('')}</div></section><div class="ice"><span class="eyebrow">Contesto persistente</span><h2>${C().name} / D${S.division}</h2><p>Cambia country o divisione dal selettore per esplorare un’altra parte del campione.</p></div>`}
function selectedMatch(){const z=new URLSearchParams(location.hash.split('?')[1]||'');return {m:matchData(Math.max(0,Math.min(3,Number(z.get('match'))||0)),Number(z.get('day'))||10),fixture:z.get('fixture')==='1'}}
function match(){const {m,fixture}=selectedMatch();return `${head(`${C().code} / D${S.division} / MATCH CENTER`,'Dentro il match.')}<article class="match-hero"><header><span>LEAGUE · ${C().name} · D${S.division}</span><span>DEMO / ${fixture?'12':m.day} SET 2026</span></header><div class="scoreline"><div class="team">${A('club',m.home.name,'',{club:m.home.id})}</div><strong>${fixture?'20:00':`${m.hs} : ${m.as}`}</strong><div class="team">${A('club',m.away.name,'',{club:m.away.id})}</div></div><footer>${fixture?'PROGRAMMATA · UTC · Statistiche disponibili solo dopo il match':'TERMINATA · Punteggio e report dimostrativi'}</footer></article>${fixture?`<div class="two"><section>${section('Casa')}${facts([['Club',m.home.name],['Posizione demo',m.home.position],['Punti demo',m.home.points]])}</section><section>${section('Ospiti')}${facts([['Club',m.away.name],['Posizione demo',m.away.position],['Punti demo',m.away.points]])}</section></div>`:`<div class="tabbar"><button data-tab="events" aria-pressed="true">Eventi</button><button data-tab="stats" aria-pressed="false">Statistiche</button><button data-tab="lineups" aria-pressed="false">Formazioni</button></div><div id="match-detail">${matchDetail()}</div>`}`}
function compareRow(label,a,b,unit=''){return `<div class="comparison-row"><div><b>${a}${unit}</b><span>${label}</span><b>${b}${unit}</b></div><div class="track"><i style="width:${a+b?a/(a+b)*100:50}%"></i></div></div>`}
function matchDetail(){const {m}=selectedMatch();if(S.tab==='stats')return `<p class="legend">Statistiche illustrative del report · casa a sinistra, ospiti a destra</p>${compareRow('Possesso',54,46,'%')}${compareRow('Tiri',12,8)}${compareRow('Tiri in porta',5,3)}${compareRow('Corner',6,4)}`;if(S.tab==='lineups')return `<div class="two">${[m.home,m.away].map(c=>`<section>${section(c.name)}<p class="legend">Schema demo · 4–3–3</p>${facts([['Portiere','Giocatore demo 01'],['Difesa','Demo 02 / 03 / 04 / 05'],['Centrocampo','Demo 06 / 07 / 08'],['Attacco','Demo 09 / 10 / 11']])}</section>`).join('')}</div>`;const events=[{min:0,title:'Calcio d’inizio',detail:'Inizio della partita dimostrativa'}];for(let i=0;i<m.hs+m.as;i++)events.push({min:Math.round((i+1)*85/(m.hs+m.as+1)),title:'Gol',detail:i<m.hs?m.home.name:m.away.name});events.push({min:90,title:'Fine partita',detail:`${m.hs} : ${m.as}`});return `<p class="legend">Eventi dimostrativi, coerenti con il punteggio selezionato.</p><div class="events">${events.map(e=>`<article class="event"><b>${e.min}′</b><div><h3>${e.title}</h3><p>${e.detail}</p></div></article>`).join('')}</div>`}
function standings(){return `${head(`${C().code} / D${S.division} / STANDINGS`,'Ogni posizione<br>conta.','Una classifica, un perimetro, un confronto leggibile.')}${table()}<p class="legend">PT = punti · DG = differenza reti · G = partite. W vittoria / D pareggio / L sconfitta. Nessuna zona di promozione attribuita senza regolamento.</p><div class="two"><section>${section('Confronto al vertice')}${compareRow('Punti demo',group()[0].points,group()[1].points)}<p>${group()[0].name} / ${group()[1].name}</p></section><section>${section('Dettaglio della prima posizione')}${facts([['Vittorie',6],['Pareggi',1],['Sconfitte',1],['Partite',8]])}</section></div>`}
function manager(){const c=currentClub();return `${head('MANAGER / SYSTEM ACTOR','Una guida.<br>Una posizione.')}<div class="profile-head">${placeholder('Ritratto','M01')}<div><span class="eyebrow">Manager dimostrativo</span><h2>Manager Demo ${fmt(c.position)}</h2><p>${c.name} / ${C().name} / D${S.division}</p>${A('club','Apri il club →','textlink',{club:c.id})}</div></div><div class="profile-grid"><section><span class="eyebrow">Posizione in divisione · demo</span><div class="rating">${fmt(c.position)}</div>${form(c)}</section><section>${facts([['Club',c.name],['Country',C().name],['Divisione',`D${S.division}`],['Vittorie',c.w],['Pareggi',c.d],['Sconfitte',c.loss]])}</section></div><div class="ice"><span class="eyebrow">Manager Grid Profile</span><h2>Identità e contesto,<br>nello stesso campo.</h2><p>Il ritratto è un segnaposto dichiarato. Il profilo non rappresenta un manager IMC reale.</p></div>`}
function player(){const c=currentClub();return `${head('PLAYER / PERFORMANCE PROFILE','La prestazione.<br>Nel suo contesto.')}<div class="profile-head">${placeholder('Ritratto','P09')}<div><span class="eyebrow">Player dimostrativo</span><h2>Player Demo 09</h2><p>${c.name} / ${C().code} / D${S.division}</p>${A('club','Club node →','textlink',{club:c.id})}</div></div><div class="profile-grid"><section><span class="eyebrow">Media voto demo</span><div class="rating">7.42</div><p>8 presenze · League<br>Profilo dimostrativo, nessuna identità reale.</p></section><section>${metrics([[8,'PRESENZE'],[5,'GOL'],[3,'ASSIST'],[2,'MOM']])}${facts([['Rating rosa demo',88],['Posizione demo','Attaccante'],['Competizione','League'],['Trend','Non disponibile']])}</section></div>${section('Lettura della prestazione')}${compareRow('Gol / assist demo',5,3)}<p class="legend">Gol a sinistra, assist a destra. Valori assoluti; nessun confronto con medie di altre divisioni.</p>`}
function club(){const c=currentClub();return `${head(`${C().code} / D${S.division} / CLUB NODE`,c.name)}<div class="profile-head">${placeholder('Stemma',c.name.slice(0,2).toUpperCase())}<div><span class="eyebrow">Club dimostrativo / ${c.id.toUpperCase()}</span><h2>Una cella.<br>Una squadra.</h2><p>${C().name} / Division ${S.division}</p></div></div>${metrics([[fmt(c.position),'POSIZIONE'],[c.points,'PUNTI DEMO'],[c.played,'PARTITE'],[c.gd,'DIFF. RETI']])}<div class="two"><section>${section('System actors')}${facts([['Manager',A('manager',`Manager Demo ${fmt(c.position)} →`,'',{club:c.id})],['Player',A('player','Player Demo 09 →','',{club:c.id})],['Competizione',A('competitions','League →')]])}</section><section>${section('Forma recente')}${form(c)}<p class="legend">Cinque esiti dimostrativi. Per il confronto completo, apri la classifica della divisione.</p>${A('standings','Apri classifica →','textlink')}</section></div>${section('Posizione nel sistema')}${matrix([C()])}`}
function competitionList(){let s='';if(S.scope==='all'||S.scope==='domestic')s+=`<section class="comp-block"><strong>01</strong><div><span class="eyebrow">DOMESTIC / ${C().code} / D${S.division}</span><h2>League</h2><p>Campione demo · 8 club · classifica dopo 8 partite</p>${A('standings','Apri la classifica →','textlink')}</div></section><section class="comp-block"><strong>02</strong><div><span class="eyebrow">DOMESTIC / ${C().code} / SENZA DIVISIONE</span><h2>League Cup</h2><p>Specimen di progressione a eliminazione diretta.</p><div class="bracket"><div><article><span class="eyebrow">Semifinale demo</span><p>${C().base[0]} Demo <b>2</b></p><p>${C().base[1]} Demo <b>1</b></p></article><article><span class="eyebrow">Semifinale demo</span><p>${C().base[2]} Demo <b>0</b></p><p>${C().base[3]} Demo <b>1</b></p></article></div><div><article><span class="eyebrow">Finale demo / da giocare</span><p>${C().base[0]} Demo</p><p>${C().base[3]} Demo</p></article></div></div></div></section>`;if(S.scope==='all'||S.scope==='international')s+=`<section class="comp-block"><strong>03</strong><div><span class="eyebrow">INTERNATIONAL / CROSS-COUNTRY</span><h2>SMFA Cup</h2><p>Lo scope supera il country. Nessuna divisione assegnata alla competizione.</p><div class="world-grid">${countryCells(countries.slice(0,3))}</div></div></section>`;return s}
function competitions(){return `${head('COMPETITIONS / STAGE & HIERARCHY','Strutture diverse.<br>Un ordine comune.','League, coppe e intersezioni internazionali.')}<div class="toolbar"><label>Scope della competizione<select id="competition-scope"><option value="all">Tutti gli scope</option><option value="domestic">Domestic</option><option value="international">International</option></select></label></div><div id="competition-list">${competitionList()}</div>`}
function transfers(){return `${head('TRANSFERS / NODE CHANGE','Cambia club.<br>Cambia posizione.','Il trasferimento come passaggio tra due contesti competitivi.')}<article class="node-change"><div><span class="eyebrow">Origine / demo</span><h3>Reims Academy</h3><p>Francia / D2</p></div><div class="arrow" aria-label="verso">→</div><div><span class="eyebrow">Destinazione / demo</span><h3>${group()[0].name}</h3><p>${C().name} / D${S.division}</p></div><footer><b>Player Demo 09</b><span>10 SET 2026 · TRASFERITO · DEMO</span></footer></article>${facts([['Valore','Non disponibile'],['Tipo','Trasferimento demo'],['Club di destinazione',A('club',group()[0].name+' →')],['Profilo player',A('player','Player Demo 09 →')]])}<div class="ice"><span class="eyebrow">Node shift</span><h2>Il percorso è il dato.</h2><p>Origine, destinazione e nuovo contesto restano leggibili insieme. Il valore non viene stimato se manca.</p></div>`}
function bars(){const max=S.metric==='clubs'?32:4;return countries.map(c=>{const v=S.metric==='clubs'?c.levels*8:c.levels;return `<div class="bar-row">${A('country',c.name,'',{country:c.id,division:'1'})}<div><i style="width:${v/max*100}%"></i></div><b>${v}</b></div>`}).join('')}
function countryCompare(){const b=countries.find(c=>c.id===S.other)||countries[1];return `<p class="legend">${C().name} a sinistra / ${b.name} a destra · dimensioni del campione</p>${compareRow('Divisioni demo',C().levels,b.levels)}${compareRow('Club demo',C().levels*8,b.levels*8)}<p class="legend">La dimensione del campione non esprime forza competitiva.</p>`}
function data(){return `${head('DATA / STRUCTURED COMPARISON','Confrontare.<br>Con criterio.','Stesso perimetro, stessa unità, differenze leggibili.')}<div class="two"><section>${section('Distribuzione del campione')}<div class="toolbar"><label>Metrica<select id="metric"><option value="clubs" ${S.metric==='clubs'?'selected':''}>Numero di club demo</option><option value="divisions" ${S.metric==='divisions'?'selected':''}>Numero di divisioni demo</option></select></label></div><div id="bars">${bars()}</div></section><section>${section('Country / country')}<div class="toolbar"><label>Confronta ${C().name} con<select id="compare-country">${countries.map(c=>`<option value="${c.id}" ${c.id===S.other?'selected':''}>${c.name}</option>`).join('')}</select></label></div><div id="country-comparison">${countryCompare()}</div></section></div>${section('Matrix / distribuzione per livello')}${matrix()}<div class="ice"><span class="eyebrow">Data contract / exploration</span><h2>Un dato mancante<br>non è uno zero.</h2><p>“Non prevista” indica una cella assente dal campione. I valori mostrati sono sintetici; questa pagina non misura attività o performance reali di GW003.</p></div>`}
function report(){return `${head('WORLD REPORT / EDITORIAL STUDY','Il calcio ha<br>una struttura.','Studio editoriale della proposta visuale, non cronaca di eventi reali.')}${editorial()}<div class="ice"><span class="eyebrow">01 / Il mondo</span><h2>La scala diventa leggibile<br>quando trovi il contesto.</h2><p>Il country introduce un’unità competitiva. La divisione restringe il campo. Il club porta la lettura a una posizione precisa. Il sistema mantiene questi riferimenti durante il passaggio tra risultati, profili e confronto.</p></div>${section('02 / Dal racconto alla struttura','world')}${matrix(countries.slice(0,2))}<div class="mood-area"><h2>03 / La presenza umana</h2><p>Fotografia documentaria e profili interrompono la densità dei dati. Le identità autentiche e i ritratti ufficiali entreranno nel popolamento del minisito; qui i profili sono specimen dichiarati.</p>${A('manager','Esplora il Manager Grid Profile →','textlink')}</div>`}
const moods=[
 ['Concept statement','THE GLOBAL FOOTBALL GRID. Un atlante competitivo abitabile: ogni elemento conserva la propria posizione e il proprio contesto. La grid segue country, divisioni e club; evitare reticoli decorativi.'],
 ['Mood keywords','Structure · Scale · Position · Order · Precision · Competition · Depth · Balance · Clarity · Connection · Documentary · Authority. Precisione con presenza umana; evitare sterilità.'],
 ['Color world','Ink dominante, midnight per profondità, cobalt per selezione, ice per lettura editoriale. Sky evidenzia focus, silver separa; amber e red richiedono etichette. Gold soltanto per titoli verificati. Evitare emerald e grandi superfici blu aziendali.'],
 ['Typographic world','Barlow per display strutturale e interfaccia; Barlow Condensed per score e numeri. Fallback di sistema, numeri tabulari, corpo 16 px. Country ampi e dati compatti rendono leggibile la gerarchia. Evitare monospace diffuso e microtesti.'],
 ['Material world','Ink opaco, pannelli midnight, giunti silver e pause ice. Superfici continue legano i contenuti; evitare vetro, chrome e card isolate ripetute.'],
 ['Grid / structure world','Country come blocco, divisione come livello, club come posizione. Ogni cella deve aprire un contesto coerente. Celle assenti e valori mancanti restano distinti; evitare densità senza gerarchia.'],
 ['Lighting world','Luce naturale diffusa nelle fotografie. Nell’interfaccia la luminosità indica gerarchia e il cobalt indica focus. Evitare aloni neon e incarnati virati in blu.'],
 ['Photographic world','Documentario calcistico: stadi, tribune, geometrie del campo, allenamento e ritratti ambientati. Le immagini restituiscono scala umana. Mai attribuire una fotografia generica a un club o evento specifico.'],
 ['Generative image world','Territorio eventuale: architetture calcistiche modulari e astratte, dichiarate concettuali. Atmosfera senza dati, mappe o stemmi inventati. Nessuna immagine AI generata per questa proposta.'],
 ['Broadcast object world','Grid Score: due club e centro numerico stabile, contesto sopra e stato sotto. Linee steel, accento cobalt, numeri bianchi. Evitare ticker, bagliori e stati live privi di fonte.'],
 ['UI object world','World, country, division, club, manager, player, match e competition hanno un dato dominante e una forma propria. Il contesto comune li rende confrontabili. Evitare variazioni cosmetiche della stessa card.'],
 ['Country / division world','Country come unità competitiva, divisione come livello navigabile. Breadcrumb e selettori mantengono orientamento. Le coppe internazionali non ereditano divisioni inesistenti. Evitare bandiere decorative.'],
 ['Data visualization world','Matrix per struttura, barre per quantità, confronti per valori omogenei e tabelle per precisione. Ogni visual dichiara unità e perimetro. Evitare confronti tra forza calcistica e volume dei dati.'],
 ['Editorial world','World Report e Country Report su ice, titoli strutturali e fotografia. Collegamenti dal racconto al dato creano profondità. Evitare cronache inventate e hero ripetute.'],
 ['Motion world','120–200 ms. Cell Focus e Context Expand guidano il cambio di contesto; Matrix Reorder cambia ordinamento senza animazioni continue. Node Shift descrive il percorso. Rispetto di reduced motion. Evitare pulse, glitch e movimento ornamentale.'],
 ['Mobile world','Country e divisione prima del dettaglio. Matrix trasformata in sequenza di righe; classifica compatta con club, punti e differenza reti. Contesto sticky e indice a dialogo. Evitare desktop compresso e overflow della pagina.'],
 ['Desktop world','Indice sinistro, superficie centrale, rail contestuale destro quando c’è spazio. La simultaneità aiuta il confronto. Evitare pannelli tutti equivalenti e dashboard aziendale.'],
 ['Signature element exploration','World Grid / Country Block / Division Matrix / Grid Score / Node Shift / Cell Focus / Matrix Reorder / Cobalt System Line / Structure Index / World → Country → Division Expansion. Forme sperimentali, non standard definitivi.'],
 ['Visual rhythm','Grid → Photo → Data → Space → Comparison → Story. Results usa scansione; Player identità e numeri; Data confronto. Evitare uniformità di impaginazione fra funzioni diverse.'],
 ['Do / Don’t','DO: superfici contigue, contesto persistente, dati allineati, fotografia pertinente, selezione cobalt. DON’T: emerald, trading, globi, bandiere giganti, HUD, neon, glassmorphism e grafici decorativi.'],
 ['Rischi visivi','Blu corporate: correggere con scala sportiva e score. Freddezza: introdurre reportage e persone. Densità: priorità e dettaglio progressivo. Somiglianza con GW002: cambiare composizione e comportamento, non soltanto colore.'],
 ['Sintesi del sistema','GW003 si riconosce da superfici strutturali continue, gerarchia leggibile, score modulari e confronti allineati. L’identità IMC resta negli asset ufficiali e nel codice GW003. EVERY CLUB HAS A PLACE IN THE GRID.']
];
function moodboard(){const palette=[['DEEP INK','#0B0F16'],['MIDNIGHT','#121B2B'],['COBALT','#2F62D0'],['SKY','#5EA0F5'],['ICE','#DDE7F2'],['OFF-WHITE','#F4F5F2'],['GRAPHITE','#59616C'],['AMBER','#D79A3B'],['RED','#C84A50'],['SILVER','#BAC3CF'],['GOLD','#C6A45A']];return `${head('SYSTEM MOODBOARD / PROPOSAL 01','GOLD 557.<br>THE GRID.','Struttura, ordine e confronto. Sistema in esplorazione.')}<div class="swatches">${palette.map(([n,c])=>`<div><i style="background:${c}"></i><b>${n}</b><small>${c}</small></div>`).join('')}</div><div class="specimen">STRUCTURE.<br>POSITION.<br><span class="num">557 / 02 : 01</span></div>${section('Materiali / superficie e giunto')}<div class="world-grid">${['INK MATTE','FROSTED BLUE','SATIN RAIL'].map((x,i)=>`<div class="country-cell ${i===1?'selected':''}"><span class="eyebrow">Material ${i+1}</span><h3>${x}</h3><p>Superficie strutturale</p></div>`).join('')}</div>${editorial()}${moods.map(([t,p],i)=>`<section class="mood-area"><h2>${fmt(i+1)} / ${t}</h2><p>${p}</p></section>`).join('')}`}
function responsive(){return `${head('SYSTEM / RESPONSIVE LAB','La grid cambia.<br>Il contesto resta.','Anteprima navigabile del minisito in una composizione mobile di 390 px.')}<p class="legend">Usa l’indice dentro l’anteprima per visitare tutte le viste. La larghezza si adatta su schermi più piccoli.</p><iframe title="GW003 composizione mobile" src="./index.html#home" width="390" height="844" style="display:block;width:390px;max-width:100%;height:844px;border:1px solid var(--line);background:var(--ink)"></iframe>`}
function notfound(){return `${head('GW003 / NAVIGATION','Pagina non trovata.','Questo percorso non appartiene all’esplorazione.')} ${A('home','Torna alla Home','btn')}`}
window.addEventListener('hashchange',()=>{route();window.scrollTo(0,0);document.querySelector('h1')?.focus({preventScroll:true})});
route();
})();
