<?php
declare(strict_types=1);

function smm_ingestion_reply(string $action,int $inserted,int $updated,int $skipped,array $errors,array $extra=[],int $status=200):never{
    smm_json(array_merge(['ok'=>$status<300&&!$errors,'action'=>$action,'inserted'=>$inserted,'updated'=>$updated,'skipped'=>$skipped,'errors'=>$errors],$extra),$status);
}
function smm_ingestion_auth():void{
    $https=strtolower((string)($_SERVER['HTTPS']??''));$forwarded=strtolower(trim(explode(',',(string)($_SERVER['HTTP_X_FORWARDED_PROTO']??''))[0]));
    if($https!=='on'&&$https!=='1'&&$forwarded!=='https')throw new RuntimeException('HTTPS required.');
    $header=trim((string)($_SERVER['HTTP_AUTHORIZATION']??''));if($header===''&&function_exists('getallheaders')){$h=getallheaders();$header=trim((string)($h['Authorization']??$h['authorization']??''));}
    if(!preg_match('/^Bearer\s+(.+)$/i',$header,$m)||!hash_equals((string)smm_config()['admin_token'],trim($m[1]))){http_response_code(401);throw new RuntimeException('Unauthorized.');}
}
function smm_ingestion_payload():array{
    if(($_SERVER['REQUEST_METHOD']??'')!=='POST'){http_response_code(405);header('Allow: POST');throw new RuntimeException('POST required.');}
    if(strtolower(trim(explode(';',(string)($_SERVER['CONTENT_TYPE']??''))[0]))!=='application/json'){http_response_code(415);throw new RuntimeException('Content-Type application/json required.');}
    if((int)($_SERVER['CONTENT_LENGTH']??0)>524288){http_response_code(413);throw new RuntimeException('Payload too large.');}
    $raw=file_get_contents('php://input',false,null,0,524289);if($raw===false||$raw==='')throw new InvalidArgumentException('Empty JSON payload.');if(strlen($raw)>524288){http_response_code(413);throw new RuntimeException('Payload too large.');}
    $payload=json_decode($raw,true,32,JSON_THROW_ON_ERROR);if(!is_array($payload))throw new InvalidArgumentException('JSON object required.');return $payload;
}
function smm_ingestion_tables(mysqli $db):void{
    $db->query("CREATE TABLE IF NOT EXISTS ingestion_runs(run_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,request_id VARCHAR(80) NOT NULL,action VARCHAR(64) NOT NULL,status ENUM('running','success','failed') NOT NULL,received_count INT UNSIGNED NOT NULL DEFAULT 0,inserted_count INT UNSIGNED NOT NULL DEFAULT 0,updated_count INT UNSIGNED NOT NULL DEFAULT 0,skipped_count INT UNSIGNED NOT NULL DEFAULT 0,error_count INT UNSIGNED NOT NULL DEFAULT 0,started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,finished_at DATETIME NULL,PRIMARY KEY(run_id),UNIQUE KEY uq_ingestion_request(request_id,action),KEY idx_ingestion_action_started(action,started_at))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $db->query("CREATE TABLE IF NOT EXISTS ingestion_errors(error_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,run_id BIGINT UNSIGNED NULL,action VARCHAR(64) NOT NULL,record_key VARCHAR(160) NULL,error_message VARCHAR(1000) NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(error_id),KEY idx_ingestion_error_run(run_id),CONSTRAINT fk_ingestion_error_run FOREIGN KEY(run_id) REFERENCES ingestion_runs(run_id) ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $db->query("CREATE TABLE IF NOT EXISTS imc_managers(manager_id VARCHAR(16) NOT NULL,full_name VARCHAR(160) NOT NULL,imc_join_date DATE NULL,sm_manager_id BIGINT UNSIGNED NULL,sm_username VARCHAR(160) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(manager_id),UNIQUE KEY uq_imc_managers_sm_manager_id(sm_manager_id),KEY idx_imc_managers_name(full_name))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
}
function smm_manager_row(array $row,int $i):array{
    $unknown=array_diff(array_keys($row),['manager_id','full_name','imc_join_date','sm_manager_id','sm_username']);if($unknown)throw new InvalidArgumentException("records[$i]: unknown field ".reset($unknown));
    $id=trim((string)($row['manager_id']??''));$name=trim((string)($row['full_name']??''));if(!preg_match('/^MNG\d{3,12}$/',$id))throw new InvalidArgumentException("records[$i].manager_id is invalid");if($name===''||mb_strlen($name)>160)throw new InvalidArgumentException("records[$i].full_name is invalid");
    $date=$row['imc_join_date']??null;if($date!==null){$date=trim((string)$date);$d=DateTimeImmutable::createFromFormat('!Y-m-d',$date);if(!$d||$d->format('Y-m-d')!==$date)throw new InvalidArgumentException("records[$i].imc_join_date is invalid");}
    $sm=$row['sm_manager_id']??null;if($sm!==null&&(!is_int($sm)&&!(is_string($sm)&&ctype_digit($sm))))throw new InvalidArgumentException("records[$i].sm_manager_id is invalid");if($sm!==null&&((int)$sm<1||(int)$sm>4294967295))throw new InvalidArgumentException("records[$i].sm_manager_id is out of range");
    $user=$row['sm_username']??null;if($user!==null){$user=trim((string)$user);if($user===''||mb_strlen($user)>160)throw new InvalidArgumentException("records[$i].sm_username is invalid");}return[$id,$name,$date,$sm===null?null:(int)$sm,$user];
}
function smm_upsert_managers(array $payload):never{
    $action='upsert_imc_managers';$request=trim((string)($payload['request_id']??''));if(!preg_match('/^[A-Za-z0-9][A-Za-z0-9._:-]{7,79}$/',$request))throw new InvalidArgumentException('request_id is invalid.');
    $records=$payload['records']??null;if(!is_array($records)||!array_is_list($records)||count($records)<1||count($records)>1000)throw new InvalidArgumentException('records must be a non-empty JSON array with at most 1000 items.');
    $db=smm_db();smm_ingestion_tables($db);$check=$db->prepare('SELECT run_id,status FROM ingestion_runs WHERE request_id=? AND action=? LIMIT 1');$check->bind_param('ss',$request,$action);$check->execute();$previous=$check->get_result()->fetch_assoc();$check->close();
    if($previous&&$previous['status']==='success')smm_ingestion_reply($action,0,0,count($records),[],['request_id'=>$request,'run_id'=>(int)$previous['run_id'],'idempotent_replay'=>true]);if($previous)throw new RuntimeException('request_id already exists with non-success status.');
    $received=count($records);$start=$db->prepare("INSERT INTO ingestion_runs(request_id,action,status,received_count)VALUES(?,?,'running',?)");$start->bind_param('ssi',$request,$action,$received);$start->execute();$run=(int)$db->insert_id;$start->close();$errors=[];$valid=[];$ids=[];$smIds=[];
    foreach($records as $i=>$row){try{if(!is_array($row))throw new InvalidArgumentException("records[$i] must be an object");$v=smm_manager_row($row,$i);if(isset($ids[$v[0]]))throw new InvalidArgumentException("records[$i].manager_id is duplicated");if($v[3]!==null&&isset($smIds[$v[3]]))throw new InvalidArgumentException("records[$i].sm_manager_id is duplicated");$ids[$v[0]]=1;if($v[3]!==null)$smIds[$v[3]]=1;$valid[]=$v;}catch(Throwable $e){$errors[]=['index'=>$i,'manager_id'=>$row['manager_id']??null,'error'=>$e->getMessage()];}}
    if($errors){smm_fail_ingestion($db,$run,$action,$errors);smm_ingestion_reply($action,0,0,0,$errors,['request_id'=>$request,'run_id'=>$run],422);}
    $inserted=$updated=$skipped=0;
    try{$select=$db->prepare('SELECT full_name,imc_join_date,sm_manager_id,sm_username FROM imc_managers WHERE manager_id=? LIMIT 1');$upsert=$db->prepare('INSERT INTO imc_managers(manager_id,full_name,imc_join_date,sm_manager_id,sm_username)VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE full_name=VALUES(full_name),imc_join_date=VALUES(imc_join_date),sm_manager_id=VALUES(sm_manager_id),sm_username=VALUES(sm_username)');$db->begin_transaction();
        foreach($valid as[$id,$name,$date,$sm,$user]){$select->bind_param('s',$id);$select->execute();$old=$select->get_result()->fetch_assoc();$same=$old&&$old['full_name']===$name&&$old['imc_join_date']===$date&&($old['sm_manager_id']===null?null:(int)$old['sm_manager_id'])===$sm&&$old['sm_username']===$user;if($same){$skipped++;continue;}$upsert->bind_param('sssis',$id,$name,$date,$sm,$user);$upsert->execute();$old?$updated++:$inserted++;}$db->commit();$select->close();$upsert->close();
        $finish=$db->prepare("UPDATE ingestion_runs SET status='success',inserted_count=?,updated_count=?,skipped_count=?,finished_at=NOW() WHERE run_id=?");$finish->bind_param('iiii',$inserted,$updated,$skipped,$run);$finish->execute();$finish->close();$counts=$db->query('SELECT COUNT(*) total,COUNT(DISTINCT manager_id) distinct_ids FROM imc_managers')->fetch_assoc();smm_ingestion_reply($action,$inserted,$updated,$skipped,[],['request_id'=>$request,'run_id'=>$run,'table_count'=>(int)$counts['total'],'distinct_manager_ids'=>(int)$counts['distinct_ids']]);
    }catch(Throwable $e){try{$db->rollback();}catch(Throwable){}$errors=[['error'=>$e->getMessage()]];smm_fail_ingestion($db,$run,$action,$errors);smm_ingestion_reply($action,0,0,0,$errors,['request_id'=>$request,'run_id'=>$run],422);}
}
function smm_fail_ingestion(mysqli $db,int $run,string $action,array $errors):void{$log=$db->prepare('INSERT INTO ingestion_errors(run_id,action,record_key,error_message)VALUES(?,?,?,?)');foreach($errors as $e){$key=isset($e['manager_id'])?(string)$e['manager_id']:null;$message=(string)$e['error'];$log->bind_param('isss',$run,$action,$key,$message);$log->execute();}$log->close();$n=count($errors);$finish=$db->prepare("UPDATE ingestion_runs SET status='failed',error_count=?,finished_at=NOW() WHERE run_id=?");$finish->bind_param('ii',$n,$run);$finish->execute();$finish->close();}
function smm_handle_ingestion():never{smm_ingestion_auth();$payload=smm_ingestion_payload();$action=(string)($payload['action']??'');if($action==='upsert_imc_managers')smm_upsert_managers($payload);throw new InvalidArgumentException('Unknown action.');}
