(() => {
'use strict';
const pages=[['index','Home'],['competitions','Competitions'],['league','League'],['results','Results'],['schedule','Schedule'],['match','Match Center'],['standings','Standings'],['managers','Managers'],['manager','Manager Profile'],['players','Players'],['player','Player Profile'],['club','Club'],['transfers','Transfers'],['playoffs','Playoffs'],['data','Data'],['archive','Archive'],['moodboard','System Moodboard'],['sources','Dati e fonti']];
const file=location.pathname.split('/').pop()||'index.html';
const page=pages.some(([id])=>id+'.html'===file)?file.replace('.html',''):'index';
const params=new URLSearchParams(location.search);
const div=['D1','D2','D3','D4','D5'].includes(params.get('division'))?params.get('division'):'D2';
const clubs=['Club A','Club B','Club C','Club D','Club E','Club F'];
const pts=[34,31,29,27,23,20], forms=['WWDWW','WDWWL','DWWLD','WLWDW','LDWDW','LLWWD'];
const A=(id,text,cls='')=>`<a class="${cls}" href="${id}.html">${text}</a>`;
const form=(s)=>`<span class="form" aria-label="Forma: ${s.split('').map(x=>({W:'vittoria',D:'pareggio',L:'sconfitta'}[x])).join(', ')}">${s.split('').map(x=>`<i class="${x.toLowerCase()}">${x}</i>`).join('')}</span>`;
const intro=(ey,title,description='')=>`<header class="intro"><div class="eyebrow">${ey}</div><h1>${title}</h1>${description?`<p>${description}</p>`:''}</header>`;
const section=(title,id='',text='Esplora →')=>`<div class="section-title"><h2>${title}</h2>${id?A(id,text):''}</div>`;
const metric=(n,l)=>`<div class="metric"><strong class="num">${n}</strong><span>${l}</span></div>`;
const divisionTabs=(target='league',playoff=false)=>`<nav class="tabs" aria-label="Divisioni">${(playoff?['D2','D3','D4','D5']:['D1','D2','D3','D4','D5']).map(d=>`<a class="${div===d?'current':''}" href="${target}.html?division=${d}" ${div===d?'aria-current="page"':''}>${d}</a>`).join('')}</nav>`;
const progress=(active=1)=>`<div class="progression" aria-label="Percorso dimostrativo"><div class="step ${active===0?'active':''}"><strong>01 / Preparazione</strong><small>Calendario e partecipanti</small></div><div class="step ${active===1?'active':''}"><strong>02 / Regular season</strong><small>Fase corrente · demo</small></div><div class="step ${active===2?'active':''}"><strong>03 / Final Gate</strong><small>Playoff · schema demo</small></div><div class="step ${active===3?'active':''}"><strong>04 / Traguardo</strong><small>Esito da verificare</small></div></div>`;
const score=(a='Club A',b='Club B',n='2 : 1',sub='League · D2 · demo')=>`<a class="scoreline" href="match.html"><span>${a}<small>${sub}</small></span><strong class="num">${n}</strong><span>${b}<small>Conclusa · demo</small></span></a>`;
const standings=()=>`<div class="table-wrap"><table class="data-table"><caption class="eyebrow">Classifica dimostrativa · estratto · ${div}</caption><thead><tr><th scope="col">Pos.</th><th scope="col">Club</th><th scope="col">G</th><th scope="col">Punti</th><th scope="col">Forma</th></tr></thead><tbody>${clubs.map((c,i)=>`<tr><td class="rank">${i+1}</td><td><a href="club.html?id=${i}">${c}</a></td><td>16</td><td><strong>${pts[i]}</strong></td><td>${form(forms[i])}</td></tr>`).join('')}</tbody></table></div>`;
const chart=()=>`<figure style="margin:20px 0"><svg class="chart" viewBox="0 0 500 240" role="img" aria-labelledby="chart-title chart-desc"><title id="chart-title">Posizioni nelle ultime cinque giornate · demo</title><desc id="chart-desc">Club A: 5, 4, 4, 2, 1. Club B: 2, 2, 3, 3, 2. Giornate da 12 a 16. Posizione 1 in alto.</desc>${[1,2,3,4,5].map((n,i)=>`<line class="grid" x1="45" y1="${25+i*40}" x2="475" y2="${25+i*40}"/><text x="16" y="${30+i*40}">${n}</text>`).join('')}<polyline class="plot" points="55,185 155,145 255,145 355,65 465,25"/><polyline class="plot second" points="55,65 155,65 255,105 355,105 465,65"/>${[12,13,14,15,16].map((n,i)=>`<text x="${45+i*102}" y="215">G${n}</text>`).join('')}<text x="45" y="238">Giornata →</text></svg><figcaption class="legend"><span>Club A</span><span>Club B</span></figcaption></figure>`;
const people=(type='manager')=>`<div class="people">${clubs.map((c,i)=>`<a href="${type}.html?id=${i}" data-search="${type} ${String.fromCharCode(65+i)} ${c}"><span class="initial">${type==='manager'?'M':'P'}${i+1}</span><div><h3>${type==='manager'?'Manager':'Player'} ${String.fromCharCode(65+i)}</h3><small>${c} · ${div} · profilo demo</small></div><span>${type==='manager'?form(forms[i]):`<strong class="num">${(7.8-i*.15).toFixed(2)}</strong><small>Rating demo</small>`}</span></a>`).join('')}</div>`;
const search=(label)=>`<div class="filters"><label>${label}<input id="search" type="search" placeholder="Nome o club" autocomplete="off"></label></div><p id="search-status" class="meta" aria-live="polite"></p>`;
const id=Math.max(0,Math.min(5,Number.parseInt(params.get('id'),10)||0)), letter=String.fromCharCode(65+id);
const views={
index:()=>`<section class="hero"><div class="eyebrow">GW006 / MASTERS OF THE WORLD</div><h1>THE WORLD<br>STAGE.</h1><p>Ogni competizione è un palcoscenico.<br>Ogni manager gioca per emergere.</p>${A('competitions','Entra nelle competizioni ↗','button')}<span class="hero-line" aria-hidden="true"></span><div class="hero-bottom"><span>EVERY COMPETITION IS A STAGE.</span><span>VISUAL EXPLORATION / 01</span></div></section><div class="home-body"><div>${section('Sotto i riflettori','match','Match Center ↗')}<section class="score-stage"><div class="eyebrow">Evento dimostrativo / League D2</div>${score()}<span class="label">Una partita. Il prossimo passo.</span></section>${section('La competizione avanza','data')}${progress()}<section class="editorial"><div class="eyebrow">Backstage / Prossimo ingresso</div><h2>Prima della luce,<br>la preparazione.</h2><p>Calendario, forma e protagonisti. Il contesto che precede ogni incontro.</p>${A('schedule','Consulta il calendario →','text-link')}</section></div><aside class="home-side"><div class="eyebrow">Performance / demo</div>${metric('7.80','Rating · Player A')}${A('player','Performance profile →','text-link')}<div class="row"><div><small>FORMA / CLUB A</small><p>${form('WWDWW')}</p></div></div>${section('Final Gate')}<p>La fase che apre il prossimo livello.</p>${A('playoffs','Esplora i playoff →','text-link')}<div class="row"><div><small>PROPOSAL 01</small><p>Materiali, luce e linguaggio.</p>${A('moodboard','System Moodboard →','text-link')}</div></div></aside></div>`,
competitions:()=>`${intro('The World Stage','Ogni fase.<br>Una scena.','Entra nel contesto competitivo. Le strutture illustrate sono dimostrative, non il catalogo ufficiale GW006.')}<div class="stage-list">${[['01','League','The long stage · regolarità e progressione','league'],['02','Coppa','The knockout stage · il turno successivo','results'],['03','Internazionale','The world stage · scala della competizione','schedule'],['04','Playoff','The final gate · D2–D5','playoffs']].map(([n,t,s,r])=>`<a href="${r}.html"><span class="num">${n}</span><div><h3>${t}</h3><small>${s}</small></div><span>↗</span></a>`).join('')}</div>${section('Dentro il percorso')}${progress()}<div class="pearl"><div class="eyebrow">Competition intelligence</div><h2>Non soltanto chi guida.<br>Chi sta avanzando.</h2><p>Risultati, forma e storia delle posizioni leggono la stessa competizione da prospettive differenti.</p>${A('data','Apri Data →','text-link')}</div>`,
league:()=>`${intro('Backstage / The long stage',`League.<br>${div}`,'Regular season · contesto dimostrativo. Cambia divisione per esplorare la composizione, non dati ufficiali.')}${divisionTabs()}<div class="two"><div class="surface"><div class="eyebrow">Punto di osservazione · demo</div>${metric('16','Giornata del campione')}${A('schedule','Prossimi incontri →','text-link')}</div><div>${section('Ultimo evento')}${score('Club A','Club B','2 : 1',`League · ${div} · demo`)}</div></div>${section('Posizioni','standings')}${standings()}${progress()}`,
results:()=>`${intro('World Stage / Outcomes','Il risultato.<br>La traccia.','Il verdetto e le prestazioni che spostano la competizione. Tutti gli incontri qui sono dimostrativi.')}<div class="filters"><label>Competizione <select id="result-filter"><option value="all">Tutte · demo</option><option value="league">League · demo</option><option value="cup">Coppa · demo</option></select></label></div><div data-group="league"><div class="eyebrow">League / G16 / demo</div>${score()}${score('Club C','Club D','0 : 0')}${score('Club E','Club F','1 : 3')}</div><div data-group="cup"><div class="eyebrow" style="margin-top:32px">Coppa / turno dimostrativo</div>${score('Club B','Club D','3 : 2','Coppa · demo')}</div><section class="pearl" style="margin-top:30px"><div class="eyebrow">Performance under the lights</div><h2>Player A.</h2><p>Una prestazione in evidenza nel campione dimostrativo.</p>${A('player','Leggi la prestazione →','text-link')}</section>`,
schedule:()=>`${intro('Backstage / Anticipation','Il prossimo<br>ingresso.','Agenda dimostrativa. Gli orari non rappresentano il calendario reale GW006.')}<div class="timeline">${[['18:00','League · D2','Club A — Club C'],['20:00','League · D3','Club B — Club E'],['21:00','Coppa · demo','Club D — Club F']].map(([t,c,m])=>`<article><time>${t} · data demo</time><p class="eyebrow">${c}</p><h2>${m}</h2>${A('match','Contesto partita ↗','text-link')}</article>`).join('')}</div><div class="surface"><div class="eyebrow">Prima del match</div><h2>Conosci il momento.</h2><p>Forma recente, protagonisti e posizione: la preparazione ha una pagina propria.</p>${A('managers','Entra nel backstage →','text-link')}</div>`,
match:()=>`${intro('World Stage / Match Center','Sotto<br>le luci.')}<section class="score-stage"><div class="eyebrow">League / D2 / G16 / Conclusa · demo</div>${score()}<p style="margin:10px auto 0">Manager A / Manager B · evento dimostrativo</p></section><div class="two"><section><div class="eyebrow">La partita / cronologia demo</div><div class="timeline"><article><time>23′</time><p>Club A · Player A · 1 : 0</p></article><article><time>61′</time><p>Club B · Player B · 1 : 1</p></article><article><time>82′</time><p>Club A · Player C · 2 : 1</p></article></div></section><section class="pearl"><div class="eyebrow">Match Report / demo</div><h2>Il confronto.</h2><table class="data-table"><thead><tr><th>Club A</th><th>Statistica</th><th>Club B</th></tr></thead><tbody><tr><td>54%</td><td>Possesso</td><td>46%</td></tr><tr><td>12</td><td>Tiri</td><td>8</td></tr><tr><td>5</td><td>In porta</td><td>3</td></tr></tbody></table>${A('player','Player A · performance ↗','text-link')}</section></div>`,
standings:()=>`${intro('Backstage / Position','La posizione<br>è un passaggio.','Classifica dimostrativa. Nessuna zona promozione o qualificazione viene attribuita senza regolamento verificato.')}${divisionTabs('standings')}<div class="pearl">${standings()}</div>${section('La forma racconta il momento')}<div class="two"><div class="surface">${metric('+4','posizioni · Club A · G12–G16 · demo')}${A('data','Storia delle posizioni →','text-link')}</div><p>W = vittoria · D = pareggio · L = sconfitta.<br>Il campione contiene sei club dimostrativi, non l’intera divisione reale.</p></div>`,
managers:()=>`${intro('Backstage / The people','Prima<br>dell’evento.','Manager, club e forma recente. Profili dimostrativi senza attribuzioni a persone reali.')}${search('Cerca manager')}${people('manager')}`,
manager:()=>`<div class="profile"><div class="profile-mark"><strong>M${id+1}</strong><small>RITRATTO NON DISPONIBILE / PLACEHOLDER</small></div><div class="profile-copy">${intro('Backstage / Manager profile',`Manager ${letter}.`,`${clubs[id]} · ${div} · identità dimostrativa`)}${form(forms[id])}<p style="margin-top:20px">Preparazione, prestazione e prossimo impegno. Il profilo segue la competizione, non una celebrazione permanente.</p>${A('club',`${clubs[id]} · profilo club →`,'text-link')}</div></div><div class="two"><section class="surface"><div class="eyebrow">Backstage / prossimo impegno demo</div><h2>${clubs[id]} — Club F</h2>${A('schedule','Apri Schedule →','text-link')}</section><section class="score-stage"><div class="eyebrow">On stage / evento demo</div>${score()}${A('match','Rileggi la partita →','text-link')}</section></div>`,
players:()=>`${intro('Performance discovery','Chi emerge<br>sotto le luci.','Esplora il rating dimostrativo, poi apri il contesto della prestazione.')}${search('Cerca player')}${people('player')}`,
player:()=>`<div class="profile"><div class="profile-mark"><strong>P${id+1}</strong><small>FOTO NON DISPONIBILE / PLACEHOLDER</small></div><div class="profile-copy">${intro('Performance under the lights',`Player ${letter}.`,`${clubs[id]} · dati dimostrativi`)}<div class="eyebrow">Rating medio / demo</div><strong class="num" style="font-size:7rem">${(7.8-id*.15).toFixed(2)}</strong></div></div><div class="three surface">${metric('16','presenze')}${metric(String(9-id),'gol')}${metric('4','assist')}</div><div class="two">${metric('3','MOTM · demo')}${metric('2 / 0','gialli / rossi · demo')}</div><div class="editorial"><div class="eyebrow">La prestazione ha un contesto</div><h2>Dentro la partita.</h2>${A('match','Apri Match Center ↗','text-link')}</div>`,
club:()=>`${intro('Competitor on the stage',`${clubs[id]}.`,'Identità dimostrativa · stemma non attribuito')}<div class="two"><section class="surface"><div class="eyebrow">Club context</div><h2>${div} / Manager ${letter}</h2>${form(forms[id])}<p style="margin-top:20px">Posizione e forma del campione dimostrativo.</p>${A('manager','Manager profile →','text-link')}</section><section class="pearl"><div class="eyebrow">Regular season / demo</div><strong class="num">${id+1}°</strong><p>${pts[id]} punti · 16 partite</p>${A('standings','Classifica →','text-link')}</section></div>${section('Ultimo evento','match')}${score()}${section('Il prossimo ingresso','transfers')}<p>Esplora la composizione dei trasferimenti e il contesto del club di destinazione.</p>${A('players','Key performers →','text-link')}`,
transfers:()=>`${intro('New Entrance','Un nuovo<br>ingresso.','Il trasferimento come inizio di un percorso competitivo. Nomi e movimenti sono dimostrativi.')}${['A','B','C'].map((p,i)=>`<article class="transfer"><div><div class="eyebrow">Movimento ${i+1} / demo</div><h3>${A('player',`Player ${p}`)}</h3></div><div class="route"><span>Club ${String.fromCharCode(68+i)}</span><b>→</b><strong>Club ${p}</strong></div><small>Data non reale<br>Valore non disponibile</small></article>`).join('')}<section class="editorial"><div class="eyebrow">Destination / competition</div><h2>Il club è soltanto<br>il punto di partenza.</h2>${A('club','Entra nel contesto →','text-link')}</section>`,
playoffs:()=>`${intro('The Final Gate','L’ultimo<br>passaggio.','D2–D5 · partecipanti, turni e percorso qui sotto sono esclusivamente uno schema dimostrativo.')}${divisionTabs('playoffs',true)}<section class="gate"><div class="eyebrow">${div==='D1'?'D2':div} / Playoff / demo</div><h2>THE<br>FINAL GATE.</h2><p>La luce cresce. L’esito resta da conquistare.</p><div class="gate-path"><div><div class="eyebrow">Turno illustrativo A</div><div class="gate-match"><small>Abbinamento dimostrativo 01</small><strong>Partecipante A — Partecipante B</strong><p>Esito non assegnato</p></div><div class="gate-match"><small>Abbinamento dimostrativo 02</small><strong>Partecipante C — Partecipante D</strong><p>Esito non assegnato</p></div></div><div><div class="eyebrow">Turno illustrativo B</div><div class="gate-match"><small>Finale · schema, non calendario reale</small><strong>Vincente 01 — Vincente 02</strong><p>Partecipanti da determinare</p></div></div></div></section>${progress(2)}<p class="meta">Questo schema non descrive il regolamento reale. Nessuna qualifica o vittoria è attribuita.</p>`,
data:()=>`${intro('Competition progression intelligence','Non dove sei.<br>Come ci arrivi.','Storia delle posizioni · cinque giornate dimostrative · posizione 1 in alto.')}${chart()}<details><summary>Leggi i valori del grafico</summary><div class="table-wrap"><table class="data-table"><thead><tr><th>Club</th><th>G12</th><th>G13</th><th>G14</th><th>G15</th><th>G16</th></tr></thead><tbody><tr><td>Club A</td><td>5</td><td>4</td><td>4</td><td>2</td><td>1</td></tr><tr><td>Club B</td><td>2</td><td>2</td><td>3</td><td>3</td><td>2</td></tr></tbody></table></div></details><div class="two" style="margin-top:32px"><div class="surface">${metric('+4','posizioni · Club A')}${form('WWDWW')}</div><div class="pearl"><div class="eyebrow">Regola di lettura / dal brief</div><h3>Expected Match</h3><p>Normale: (squadre − 1) × 2.<br>League scozzese GW006: × 4 quando applicabile.</p><p>Nessun totale reale calcolato senza verifica della competizione e del numero di squadre.</p></div></div>`,
archive:()=>`${intro('Completed stages','La luce<br>lascia traccia.','Archivio compositivo: nessuna stagione o vittoria reale è attribuita.')}<article class="archive-row"><strong class="num">01</strong><div><div class="eyebrow">Stagione dimostrativa / conclusa</div><h2>Il capitolo precedente.</h2><p>Risultati e performance come memoria consultabile.</p>${A('results','Esplora gli esiti demo →','text-link')}</div></article><article class="archive-row"><strong class="num">02</strong><div><div class="eyebrow">Stagione dimostrativa / in corso</div><h2>Il prossimo capitolo.</h2>${A('competitions','Torna alle competizioni →','text-link')}</div></article><div class="winner"><div class="eyebrow">Final Lock / studio di stato</div><h2>Winner state.</h2><p>Accento oro riservato a un vincitore verificato. Qui nessun vincitore viene nominato.</p></div>`,
moodboard:()=>`${intro('System Moodboard / Proposal 01','La competizione<br>accende la scena.','Scala. Attesa. Ingresso. Concentrazione. Presenza. Progressione. Tensione. Prestazione. Risonanza. Culmine.')}<div class="swatches">${[['Stage Black','#090B10'],['Deep Indigo','#171A38'],['Ultramarine','#303D8F'],['Electric Violet','#7256C7'],['Spotlight White','#F5F3EE'],['Cool Pearl','#D7D9E2'],['World Cyan','#55B6CB'],['Final Gold','#C8A65B']].map(([n,c],i)=>`<div class="swatch" style="background:${c};color:${i>3?'#090B10':'#F5F3EE'}"><strong>${n}</strong><span>${c}</span></div>`).join('')}</div>${section('Backstage × World Stage')}<div class="two"><div class="state-sample"><div class="eyebrow">Ambient / preparazione</div><h2>Il prossimo incontro.</h2><p>Indaco raccolto. Lettura prima dello spettacolo.</p><strong class="num">20:00</strong><small> · orario demo</small></div><div class="state-sample stage"><div class="eyebrow">Match / evento</div><h2>STAGE SCORE.</h2><strong class="num">2 : 1</strong><p>Perla dominante. Superficie attivata.</p></div></div>${section('Materiali e luce')}<div class="three"><div class="surface"><h3>Dark satin</h3><p>Base opaca. Nessun riflesso dietro al dato.</p></div><div class="surface" style="background:#303d8f"><h3>Anodized indigo</h3><p>Competizione attiva. Un margine ottico.</p></div><div class="pearl"><h3>Pearl surface</h3><p>Report e confronto. Una pausa luminosa.</p></div></div>${section('Progressione / non decorazione')}${progress(2)}<div class="gate"><div class="eyebrow">Signature / Final Gate</div><h2>LA SOGLIA.<br>NON IL TROFEO.</h2></div><div class="editorial"><div class="eyebrow">Typography / studio</div><h2>EVERY COMPETITION<br>IS A STAGE.</h2><p>Display Barlow Black · numeri Barlow Condensed · interfaccia Barlow. Pairing provvisorio: la larghezza cinematica resta da affinare.</p></div><p>${A('sources','Limiti, fonti e specifica completa →','text-link')}</p>`,
sources:()=>`${intro('Visual Design Exploration / Trasparenza','Dati, fonti<br>e limiti.')}<div class="surface"><h2>DEMO / PLACEHOLDER VISUAL DATA</h2><p>Club A–F, Manager A–F e Player A–F sono identità dimostrative. Risultati, rating, classifiche, orari, cronologia e percorsi non descrivono eventi reali GW006.</p><p>Non è stata eseguita una lettura MySQL Aruba per questa versione. Nessun dato competitivo è presentato come verificato.</p></div><div class="editorial"><h2>Fonte autoritativa prevista.</h2><p>MySQL Aruba · Sql1956795_3 · CUSTOM / SINGLE, attraverso il ponte Supabase IMC Nexus. Il prototipo non scrive database e non modifica Gateway.</p><p>Le regole D2–D5 e l’eccezione Expected Match scozzese provengono dal brief, non da una nuova verifica database.</p></div><h2>Identità e materiali.</h2><p>La Proposal 01 esplora THE WORLD STAGE e BACKSTAGE × WORLD STAGE. Fotografie e ritratti non sono ancora integrati: i monogrammi sono placeholder espliciti, non immagini di persone reali. Font Google Fonts: Barlow e Barlow Condensed, con fallback di sistema.</p><p>Il sistema non è definitivo. Non sono presenti aggiornamenti live, filtri collegati al database o previsioni.</p>${A('moodboard','Apri System Moodboard →','text-link')}`
};
document.title=`${pages.find(([p])=>p===page)[1]} · Masters of the World · GW006`;
document.getElementById('app').innerHTML=`<a class="skip" href="#content">Salta al contenuto</a><header class="top"><a class="brand" href="index.html"><span class="monogram">IMC<br>006</span><span><strong>MASTERS OF THE WORLD</strong><small>THE WORLD STAGE</small></span></a><span class="edition">VISUAL DESIGN EXPLORATION / 01</span><button id="menu" aria-label="Apri navigazione">Menu</button></header><div class="layout"><aside class="rail"><div class="eyebrow">GW006 / Explore</div><nav aria-label="Navigazione principale">${pages.filter(([p])=>!['manager','player','sources','moodboard'].includes(p)).map(([p,l],i)=>A(p,`<small>${String(i+1).padStart(2,'0')}</small>${l}`,p===page?'active':'')).join('')}</nav><div class="rail-bottom">${A('moodboard','Proposal 01','text-link')}<p class="meta">Every manager is playing<br>for the world.</p></div></aside><div class="main"><div class="context"><span>GW006 / ${pages.find(([p])=>p===page)[1]}</span><span>${['schedule','managers','manager','league','standings'].includes(page)?'BACKSTAGE':'WORLD STAGE'}</span></div><div class="demo">DEMO / PLACEHOLDER VISUAL DATA · ${A('sources','Leggi i limiti')}</div><main class="content" id="content">${views[page]()}</main><footer class="footer"><span>ITALIAN MASTERS CLUB / GW006</span>${A('sources','Dati e fonti')}<span>PROPOSAL 01 · NON DEFINITIVO</span></footer></div></div><nav class="mobile-nav" aria-label="Navigazione mobile">${[['index','Home'],['competitions','Stage'],['results','Results'],['playoffs','Playoff']].map(([p,l])=>A(p,l,p===page?'active':'')).join('')}<a href="moodboard.html">Concept</a></nav><dialog id="navigation"><div class="dialog-head"><strong>THE WORLD STAGE</strong><button id="close-menu" aria-label="Chiudi navigazione">Chiudi</button></div><nav aria-label="Tutte le pagine">${pages.map(([p,l])=>A(p,l)).join('')}</nav></dialog>`;
const dialog=document.getElementById('navigation');document.getElementById('menu').addEventListener('click',()=>dialog.showModal());document.getElementById('close-menu').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog&&e.offsetX>=dialog.clientWidth)dialog.close()});
const input=document.getElementById('search');if(input)input.addEventListener('input',()=>{let n=0;document.querySelectorAll('[data-search]').forEach(el=>{el.hidden=!el.dataset.search.toLowerCase().includes(input.value.trim().toLowerCase());if(!el.hidden)n++});document.getElementById('search-status').textContent=`${n} profili dimostrativi trovati`;});
const filter=document.getElementById('result-filter');if(filter)filter.addEventListener('change',()=>document.querySelectorAll('[data-group]').forEach(el=>{el.hidden=filter.value!=='all'&&el.dataset.group!==filter.value}));
})();
