(() => {
  'use strict';
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const clean=v=>String(v??'').trim();
  const worldId=()=>String(window.IMC_GAME_WORLD?.gameWorldId||'GW001').toUpperCase();
  const gateway='/api/imc-gateway/';
  const isCompetitions=()=>location.hash.replace(/^#/,'').split('/').filter(Boolean)[0]==='competitions';
  const groups=['DOMESTIC','INTERNATIONAL','NATIONS'];
  const meta={DOMESTIC:['DOMESTIC','Domestic competitions'],INTERNATIONAL:['INTERNATIONAL','International competitions'],NATIONS:['NATIONS','National teams']};
  function style(){if(document.getElementById('imc-competitions-live-style'))return;const s=document.createElement('style');s.id='imc-competitions-live-style';s.textContent=`
    .competitions-live{padding:2px 0 34px}.competitions-intro{margin:0 0 16px;color:#8194a8;font-size:11px;line-height:1.5}.competition-groups{display:grid;grid-template-columns:1fr;gap:12px}.competition-group-card{position:relative;overflow:hidden;min-height:176px;padding:18px;border:1px solid rgba(255,255,255,.14);border-radius:20px;background:radial-gradient(circle at 100% 0,rgba(48,111,166,.22),transparent 42%),linear-gradient(155deg,#0c2238,#071725 76%);box-shadow:0 18px 36px rgba(0,0,0,.2)}.competition-group-card:before{content:'';position:absolute;inset:0;background:linear-gradient(120deg,transparent 48%,rgba(214,161,73,.06));pointer-events:none}.competition-group-kicker{color:#d6a149;font-size:9px;font-weight:900;letter-spacing:.16em}.competition-group-card h3{margin:7px 0 4px;font-size:24px;letter-spacing:.02em}.competition-group-sub{color:#788ca1;font-size:10px;font-weight:800;letter-spacing:.08em}.competition-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:16px}.competition-action{padding:7px 9px;border:1px solid rgba(255,255,255,.11);border-radius:999px;background:rgba(255,255,255,.035);color:#dbe5ee;font-size:9px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.competition-empty{color:#72869a;font-size:10px;font-weight:800;margin-top:16px}.competitions-loading,.competitions-error{min-height:280px;border:1px solid rgba(255,255,255,.14);border-radius:20px;background:linear-gradient(145deg,rgba(12,30,48,.96),rgba(5,15,26,.96));display:grid;place-items:center;align-content:center;gap:10px;text-align:center;color:#90a1b4}.competitions-loading i{width:34px;height:34px;border-radius:50%;border:3px solid rgba(255,255,255,.14);border-top-color:#d6a149;animation:compSpin .8s linear infinite}@keyframes compSpin{to{transform:rotate(360deg)}}@media(min-width:760px){.competition-groups{grid-template-columns:repeat(3,minmax(0,1fr))}.competition-group-card{min-height:220px}}
  `;document.head.appendChild(s);}
  const head=()=>`<div class="section-head"><div><small>${esc(worldId())}</small><h2>Competitions</h2></div><a class="back-btn" href="#/overview" aria-label="Indietro">←</a></div>`;
  async function readRepo(repo){const rows=[];let offset=0;const limit=1000;while(true){const u=new URL(gateway,location.origin);u.searchParams.set('game_world_id',worldId());u.searchParams.set('repository',repo);u.searchParams.set('limit',String(limit));u.searchParams.set('offset',String(offset));const r=await fetch(u.toString(),{cache:'no-store',headers:{Accept:'application/json'}});const p=await r.json().catch(()=>({ok:false,error:'invalid_json'}));if(!r.ok||!p?.ok)throw new Error(p?.error||`HTTP ${r.status}`);const batch=Array.isArray(p.data)?p.data:[];rows.push(...batch);offset+=batch.length;const total=Number(p?.pagination?.total||rows.length);if(!batch.length||offset>=total||batch.length<limit)break;}return rows;}
  async function load(){const [results,schedule]=await Promise.all([readRepo('results').catch(()=>[]),readRepo('schedule').catch(()=>[])]);const all=[...results,...schedule];const out={DOMESTIC:new Set(),INTERNATIONAL:new Set(),NATIONS:new Set()};for(const r of all){const g=clean(r.competition_group).toUpperCase();const a=clean(r.sm_action);if(out[g]&&a)out[g].add(a);}return out;}
  async function paint(){if(!isCompetitions())return;style();const view=document.querySelector('main.view');if(!view)return;view.innerHTML=`${head()}<section class="competitions-live"><div class="competitions-loading"><i></i><strong>CARICAMENTO COMPETITIONS</strong><span>Gateway · MySQL Aruba</span></div></section>`;try{const data=await load();if(!isCompetitions())return;const cards=groups.map(g=>{const actions=[...data[g]].sort((a,b)=>a.localeCompare(b,'it'));return `<article class="competition-group-card"><div class="competition-group-kicker">${esc(worldId())}</div><h3>${meta[g][0]}</h3><div class="competition-group-sub">${meta[g][1]}</div>${actions.length?`<div class="competition-actions">${actions.map(a=>`<span class="competition-action">${esc(a)}</span>`).join('')}</div>`:`<div class="competition-empty">Nessuna SM Action disponibile</div>`}</article>`;}).join('');view.innerHTML=`${head()}<section class="competitions-live"><p class="competitions-intro">Competizioni organizzate per macrogruppo e SM Action presenti nei repository del Game World.</p><div class="competition-groups">${cards}</div></section>`;}catch(e){view.innerHTML=`${head()}<section class="competitions-live"><div class="competitions-error"><strong>COMPETITIONS NON DISPONIBILI</strong><span>${esc(e?.message||'gateway_error')}</span></div></section>`;}}
  function render(){if(isCompetitions())setTimeout(paint,0)}window.addEventListener('hashchange',render);setTimeout(render,0);
})();