(() => {
  'use strict';
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const clean=v=>String(v??'').trim();
  const worldId=()=>String(window.IMC_GAME_WORLD?.gameWorldId||'GW001').toUpperCase();
  const gateway='/api/imc-gateway/';
  const groups=['DOMESTIC','INTERNATIONAL','NATIONS'];
  const meta={DOMESTIC:['DOMESTIC','Domestic competitions'],INTERNATIONAL:['INTERNATIONAL','International competitions'],NATIONS:['NATIONS','National teams']};
  const path=()=>location.hash.replace(/^#/,'').split('/').filter(Boolean);
  const isCompetitions=()=>path()[0]==='competitions';
  const selectedGroup=()=>{const g=String(path()[1]||'').toUpperCase();return groups.includes(g)?g:null;};
  let cache=null;

  function labelAction(a){
    const k=clean(a).toLowerCase();
    return ({league:'League',leaguecup:'League Cup',leagueshield:'League Shield',charityshield:'Charity Shield',playoff:'Playoff',smfacup:'SMFA Champions',smfashield:'SMFA Shield',supercup:'SMFA Super Cup',interqualifier:'World Cup Qualifier',worldcup:'World Cup'})[k]||clean(a).replace(/[_-]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
  }
  function iconFor(a){
    const k=clean(a).toLowerCase();
    if(k==='league')return '1';
    if(k==='interqualifier'||k==='worldcup')return '◎';
    if(k==='charityshield'||k==='leagueshield')return '◈';
    if(k==='smfacup'||k==='smfashield'||k==='supercup'||k==='leaguecup')return '♜';
    return '◆';
  }
  function style(){if(document.getElementById('imc-competitions-live-style'))return;const s=document.createElement('style');s.id='imc-competitions-live-style';s.textContent=`
    .competitions-live{padding:2px 0 34px}.competitions-intro{margin:0 0 16px;color:#8194a8;font-size:11px;line-height:1.5}.competition-groups{display:grid;grid-template-columns:1fr;gap:12px}.competition-group-card{position:relative;overflow:hidden;min-height:176px;padding:18px;border:1px solid rgba(255,255,255,.14);border-radius:20px;background:radial-gradient(circle at 100% 0,rgba(48,111,166,.22),transparent 42%),linear-gradient(155deg,#0c2238,#071725 76%);box-shadow:0 18px 36px rgba(0,0,0,.2);text-decoration:none;color:inherit}.competition-group-card:before{content:'';position:absolute;inset:0;background:linear-gradient(120deg,transparent 48%,rgba(214,161,73,.06));pointer-events:none}.competition-group-kicker{color:#d6a149;font-size:9px;font-weight:900;letter-spacing:.16em}.competition-group-card h3{margin:7px 0 4px;font-size:24px;letter-spacing:.02em}.competition-group-sub{color:#788ca1;font-size:10px;font-weight:800;letter-spacing:.08em}.competition-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:16px}.competition-action{padding:7px 9px;border:1px solid rgba(255,255,255,.11);border-radius:999px;background:rgba(255,255,255,.035);color:#dbe5ee;font-size:9px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.competition-empty{color:#72869a;font-size:10px;font-weight:800;margin-top:16px}.competition-group-arrow{position:absolute;right:16px;bottom:16px;width:38px;height:38px;border:1px solid rgba(255,255,255,.13);border-radius:50%;display:grid;place-items:center;color:#d6a149;font-size:24px;background:rgba(255,255,255,.035)}
    .competition-tabs{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;margin:0 0 18px;padding:5px;border:1px solid rgba(255,255,255,.14);border-radius:17px;background:rgba(4,14,24,.68)}.competition-tab{height:48px;border:0;border-radius:12px;background:transparent;color:#8195aa;font:900 9px Inter,system-ui,sans-serif;letter-spacing:.09em;text-decoration:none;display:grid;place-items:center}.competition-tab.active{background:linear-gradient(145deg,#d7a24c,#b47a22);color:#06111f;box-shadow:0 10px 26px rgba(214,161,73,.18)}.competition-detail-head{display:flex;justify-content:space-between;align-items:center;margin:0 2px 12px}.competition-detail-head strong{font-size:17px;letter-spacing:.03em}.competition-detail-head span{color:#d6a149;font-size:10px;font-weight:900}.competition-list{display:grid;gap:12px}.competition-item{position:relative;display:grid;grid-template-columns:68px minmax(0,1fr) 42px;gap:12px;align-items:center;padding:16px;border:1px solid rgba(255,255,255,.14);border-radius:20px;background:radial-gradient(circle at 100% 0,rgba(48,111,166,.18),transparent 42%),linear-gradient(155deg,#0c2238,#071725 76%);box-shadow:0 16px 32px rgba(0,0,0,.18)}.competition-icon{width:68px;height:68px;border:1px solid rgba(214,161,73,.35);border-radius:16px;display:grid;place-items:center;color:#d6a149;font-size:30px;font-weight:900;background:rgba(255,255,255,.025)}.competition-item h3{margin:0;font-size:20px;line-height:1.05}.competition-item-sub{margin-top:5px;color:#d6a149;font-size:9px;font-weight:900;letter-spacing:.1em;text-transform:uppercase}.competition-item-meta{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.competition-chip{padding:5px 8px;border:1px solid rgba(255,255,255,.12);border-radius:999px;color:#9eb0c2;font-size:8px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.competition-open{width:42px;height:42px;border-radius:50%;border:1px solid rgba(255,255,255,.13);display:grid;place-items:center;color:#d6a149;font-size:24px;background:rgba(255,255,255,.035)}.competitions-loading,.competitions-error{min-height:280px;border:1px solid rgba(255,255,255,.14);border-radius:20px;background:linear-gradient(145deg,rgba(12,30,48,.96),rgba(5,15,26,.96));display:grid;place-items:center;align-content:center;gap:10px;text-align:center;color:#90a1b4}.competitions-loading i{width:34px;height:34px;border-radius:50%;border:3px solid rgba(255,255,255,.14);border-top-color:#d6a149;animation:compSpin .8s linear infinite}@keyframes compSpin{to{transform:rotate(360deg)}}@media(min-width:760px){.competition-groups{grid-template-columns:repeat(3,minmax(0,1fr))}.competition-group-card{min-height:220px}.competition-list{grid-template-columns:repeat(2,minmax(0,1fr))}}
  `;document.head.appendChild(s);}
  const head=(label='Competitions',back='#/overview')=>`<div class="section-head"><div><small>${esc(worldId())}</small><h2>${esc(label)}</h2></div><a class="back-btn" href="${back}" aria-label="Indietro">←</a></div>`;
  async function readRepo(repo){const rows=[];let offset=0;const limit=1000;while(true){const u=new URL(gateway,location.origin);u.searchParams.set('game_world_id',worldId());u.searchParams.set('repository',repo);u.searchParams.set('limit',String(limit));u.searchParams.set('offset',String(offset));const r=await fetch(u.toString(),{cache:'no-store',headers:{Accept:'application/json'}});const p=await r.json().catch(()=>({ok:false,error:'invalid_json'}));if(!r.ok||!p?.ok)throw new Error(p?.error||`HTTP ${r.status}`);const batch=Array.isArray(p.data)?p.data:[];rows.push(...batch);offset+=batch.length;const total=Number(p?.pagination?.total||rows.length);if(!batch.length||offset>=total||batch.length<limit)break;}return rows;}
  async function load(){if(cache)return cache;const [results,schedule]=await Promise.all([readRepo('results').catch(()=>[]),readRepo('schedule').catch(()=>[])]);const all=[...results,...schedule];const out={DOMESTIC:new Map(),INTERNATIONAL:new Map(),NATIONS:new Map()};for(const r of all){const g=clean(r.competition_group).toUpperCase();const a=clean(r.sm_action);if(!out[g]||!a)continue;const key=a.toLowerCase();if(!out[g].has(key))out[g].set(key,{action:a,results:0,schedule:0});const item=out[g].get(key);if(results.includes(r))item.results++;else item.schedule++;}cache=out;return out;}
  function tabs(active){return `<div class="competition-tabs">${groups.map(g=>`<a class="competition-tab ${g===active?'active':''}" href="#/competitions/${g.toLowerCase()}">${g}</a>`).join('')}</div>`;}
  function detailCard(item,group){const total=item.results+item.schedule;return `<article class="competition-item"><div class="competition-icon">${esc(iconFor(item.action))}</div><div><h3>${esc(labelAction(item.action))}</h3><div class="competition-item-sub">${esc(group)}</div><div class="competition-item-meta"><span class="competition-chip">${esc(item.action)}</span><span class="competition-chip">${total.toLocaleString('it-IT')} match</span></div></div><span class="competition-open">›</span></article>`;}
  async function paint(){if(!isCompetitions())return;style();const view=document.querySelector('main.view');if(!view)return;const group=selectedGroup();view.innerHTML=`${head(group||'Competitions',group?'#/competitions':'#/overview')}<section class="competitions-live"><div class="competitions-loading"><i></i><strong>CARICAMENTO COMPETITIONS</strong><span>Gateway · MySQL Aruba</span></div></section>`;try{const data=await load();if(!isCompetitions())return;if(group){const actions=[...data[group].values()].sort((a,b)=>labelAction(a.action).localeCompare(labelAction(b.action),'it'));view.innerHTML=`${head(group,'#/competitions')}<section class="competitions-live">${tabs(group)}<div class="competition-detail-head"><strong>${group}</strong><span>${actions.length}</span></div>${actions.length?`<div class="competition-list">${actions.map(a=>detailCard(a,group)).join('')}</div>`:`<div class="competitions-error"><strong>NESSUNA COMPETIZIONE</strong><span>Nessuna SM Action disponibile per ${group}</span></div>`}</section>`;return;}const cards=groups.map(g=>{const actions=[...data[g].values()].sort((a,b)=>a.action.localeCompare(b.action,'it'));return `<a class="competition-group-card" href="#/competitions/${g.toLowerCase()}"><div class="competition-group-kicker">${esc(worldId())}</div><h3>${meta[g][0]}</h3><div class="competition-group-sub">${meta[g][1]}</div>${actions.length?`<div class="competition-actions">${actions.map(a=>`<span class="competition-action">${esc(a.action)}</span>`).join('')}</div>`:`<div class="competition-empty">Nessuna SM Action disponibile</div>`}<span class="competition-group-arrow">›</span></a>`;}).join('');view.innerHTML=`${head()}<section class="competitions-live"><p class="competitions-intro">Competizioni organizzate per macrogruppo e SM Action presenti nei repository del Game World.</p><div class="competition-groups">${cards}</div></section>`;}catch(e){view.innerHTML=`${head()}<section class="competitions-live"><div class="competitions-error"><strong>COMPETITIONS NON DISPONIBILI</strong><span>${esc(e?.message||'gateway_error')}</span></div></section>`;}}
  function render(){if(isCompetitions())setTimeout(paint,0)}window.addEventListener('hashchange',render);setTimeout(render,0);
})();