'use strict';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),manager=params.get('manager')||'';
const rankingView=params.get('view')==='ranking'&&!manager;
const timelineView=params.get('view')==='timeline'&&!manager;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fields=['played','won','drawn','lost','gf','ga','penalty_won','penalty_lost','matched_by_id'];
const zero=()=>Object.fromEntries(fields.map(k=>[k,0]));
const sum=items=>items.reduce((a,s)=>{fields.forEach(k=>a[k]+=Number(s[k]||0));return a;},zero());
const pct=s=>s.played?(100*s.won/s.played).toLocaleString('it-IT',{maximumFractionDigits:1})+'%':'—';
const number=n=>Number(n||0).toLocaleString('it-IT');
let people=[],worldNames={},bundles={},failed=[],tab='overview',limit=25,loading=true,runId=0;
const worlds=Array.from({length:10},(_,i)=>'GW'+String(i+1).padStart(3,'0'));
const selected=()=>worlds.filter(w=>!$('world').value||w===$('world').value);
const available=()=>selected().filter(w=>bundles[w]);
const allMatches=()=>available().flatMap(w=>bundles[w].matches||[]).sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.fixture_id).localeCompare(String(a.fixture_id)));
const worldName=w=>worldNames[w]?w+' · '+worldNames[w]:w;
const dateIT=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v||''))?String(v).slice(8,10)+'/'+String(v).slice(5,7)+'/'+String(v).slice(0,4):'—';

const initials=name=>String(name||'?').split(/\s+/).slice(0,2).map(x=>x[0]).join('');
const badges=ws=>'<div class="world-badges">'+ws.map(w=>'<span class="world-badge">'+esc(w)+'</span>').join('')+'</div>';
const cup='<svg class="trophy-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3h10v5a5 5 0 0 1-10 0zM12 13v6M8 21h8M7 5H3v3a4 4 0 0 0 4 4M17 5h4v3a4 4 0 0 1-4 4"/></svg>';
function clubLogo(world,id){const src=String(bundles[world]?.clubs?.[id]?.logo||'');return /^(https:\/\/|\/(?!\/))/i.test(src)?'<img class="club-logo" src="'+esc(src)+'" alt="" loading="lazy">':'<span class="club-placeholder" aria-hidden="true">◇</span>';}
function worldLinks(){ $('world-links').innerHTML=worlds.map(w=>'<a href="../?world='+w+'"><small>'+w+' ↗</small><strong>'+esc(worldNames[w]||w)+'</strong></a>').join('');}
function wireLogos(){document.querySelectorAll('.club-logo').forEach(img=>{img.onerror=()=>img.hidden=true;if(img.complete&&!img.naturalWidth)img.hidden=true;});}
$('open-worlds').onclick=$('nav-worlds').onclick=()=>$('world-dialog').showModal();$('close-worlds').onclick=()=>$('world-dialog').close();$('world-dialog').addEventListener('click',e=>{if(e.target===$('world-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});worldLinks();

if(timelineView){$('title').textContent='IMC Timeline';document.title='Nexus · IMC Timeline';$('subtitle').textContent='La storia della community IMC, evento dopo evento.';$('directory-heading').querySelector('h2').textContent='La storia dell’Italian Masters Club';$('directory-heading').querySelector('.eyebrow').textContent='IMC TIMELINE';$('nav-club').removeAttribute('aria-current');$('nav-timeline').setAttribute('aria-current','page');$('world').closest('label').hidden=true;}
if(rankingView){document.body.classList.add('ranking-page');document.querySelector('.hero-tags').innerHTML='<span>Club + Nazionali</span><span>GW001–GW010</span>';document.querySelector('.hero-mark').innerHTML='IMC<span>RANKING</span>';document.querySelector('.source-badge').textContent='CLUB: MATCH REPORT · NAZIONALI: RESULTS';document.querySelector('footer p').textContent='Ranking: club dai Match Report, nazionali dai Results. Attribuzione tramite ID Soccer Manager. Stessi punti e moltiplicatori GW; esito prima dei rigori.';$('title').textContent='IMC Ranking';document.title='Nexus · IMC Ranking';$('subtitle').textContent='Tutti i manager. Dieci mondi. Una classifica.';$('directory-heading').querySelector('h2').textContent='La classifica globale dei manager';$('directory-heading').querySelector('.eyebrow').textContent='IMC RANKING';$('nav-club').removeAttribute('aria-current');$('nav-ranking').setAttribute('aria-current','page');}
async function get(q=''){const r=await fetch('data.php'+q,{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Dati non disponibili');return d;}
function stats(id){return sum(available().map(w=>bundles[w].managers[id]?.stats||zero()));}
function trophies(id){return available().reduce((n,w)=>n+(bundles[w].managers[id]?.trophies||0),0);}
function status(){const ready=available().length,total=selected().length,missing=selected().filter(w=>failed.includes(w));$('loading').textContent=(loading?'Caricamento · ':'')+ready+'/'+total+' GW disponibili · '+(rankingView?'Club: Match Report · Nazionali: Results':'Fonte: Match Report dei club');const excluded=manager?available().reduce((n,w)=>n+(bundles[w].managers[manager]?.excluded||0),0):0;const nationalErrors=rankingView?available().filter(w=>bundles[w].national_ranking_error):[];const trophyErrors=available().filter(w=>bundles[w].trophy_error);$('warning').textContent=[nationalErrors.length?'Results nazionali non disponibili per '+nationalErrors.join(', ')+': classifica parziale.':'',missing.length?'Dati parziali: non disponibili '+missing.join(', ')+'. Usa Aggiorna per riprovare.':'',excluded?excluded+' partite escluse dai conteggi per anomalie nei report. Vedi Panoramica.':'',trophyErrors.length?'Trofei incompleti per '+trophyErrors.join(', ')+'.':''].filter(Boolean).join(' ');}
const timelineMeta={passport:['🛂','IMC PASSPORT'],assignment_start:['●','NUOVO INCARICO'],assignment_end:['●','FINE INCARICO'],trophy:['🏆','TROFEO']};
const timelineDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v||''))?new Date(v+'T12:00:00Z').toLocaleDateString('it-IT',{day:'2-digit',month:'short',year:'numeric',timeZone:'Europe/Rome'}).replace('.','').toUpperCase():String(v||'');
function timelineTeam(e){const src=String(e.team_logo||'');const img=/^(https:\/\/|\/(?!\/))/i.test(src)?'<img class="timeline-team-logo" src="'+esc(src)+'" alt="" loading="lazy">':'';return '<span class="timeline-team">'+img+'<strong>'+esc(e.team||'—')+'</strong></span>';}
function timelineCard(e){const meta=timelineMeta[e.type]||['◆','EVENTO'],gw=e.world||'IMC',name=e.world?(worldNames[e.world]||e.world):'PASSPORT',date=timelineDate(e.date);let body='';
 if(e.type==='passport')body='<h2><a href="?manager='+encodeURIComponent(e.manager_id)+'">'+esc(e.manager_name)+'</a></h2><p>Ottiene l’IMC Passport ed entra ufficialmente nella community Italian Masters Club.</p>';
 else if(e.type==='assignment_start')body='<h2><a href="?manager='+encodeURIComponent(e.manager_id)+'">'+esc(e.manager_name)+'</a></h2><p>Nuovo incarico: <strong>'+esc(e.team||'—')+'</strong></p><small>'+esc(e.assignment_type||'')+'</small>';
 else if(e.type==='assignment_end')body='<h2><a href="?manager='+encodeURIComponent(e.manager_id)+'">'+esc(e.manager_name)+'</a></h2><p>Termina l’incarico con <strong>'+esc(e.team||'—')+'</strong></p><small>'+esc(e.assignment_type||'')+'</small>';
 else body='<h2><a href="?manager='+encodeURIComponent(e.manager_id)+'">'+esc(e.manager_name)+'</a> conquista '+esc(e.competition)+'</h2><p><strong>'+esc(e.team)+'</strong> · Season '+esc(e.season)+'</p><p class="timeline-ranking"><strong>+'+number(e.ranking_points)+' PT</strong><span>'+number(e.base_points)+' × '+number(e.multiplier)+' IMC Ranking'+(e.position?' · nuova posizione #'+number(e.position):'')+'</span></p>';
 return '<article class="timeline-card type-'+esc(e.type)+'"><header class="timeline-head"><strong>'+esc(gw)+'</strong><span>'+esc(name)+'</span><time>'+esc(date)+'</time></header><div class="timeline-body"><div class="timeline-visual"><b>'+meta[0]+'</b><span>'+meta[1]+'</span></div><div class="timeline-copy">'+body+'</div></div></article>';}
async function timeline(){try{$('loading').textContent='Caricamento IMC Timeline…';const d=await fetch('timeline.php',{cache:'no-store'}).then(r=>r.json());if(!d.ok)throw Error(d.error||'Timeline non disponibile');$('loading').textContent=d.events.length+' eventi';$('manager-count').textContent=d.events.length+' eventi';const q=$('search').value.toLocaleLowerCase('it').trim(),rows=d.events.filter(e=>JSON.stringify(e).toLocaleLowerCase('it').includes(q));$('content').innerHTML='<div class="timeline-filters"><button class="active" data-kind="">Tutto</button><button data-kind="trophy">🏆 Trofei</button><button data-kind="assignment">↔ Manager</button><button data-kind="passport">🛂 Passport</button></div><div class="timeline-feed">'+rows.map(timelineCard).join('')+'</div>';document.querySelectorAll('.timeline-filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.timeline-filters button').forEach(x=>x.classList.toggle('active',x===b));const kind=b.dataset.kind;document.querySelectorAll('.timeline-card').forEach(card=>card.hidden=kind&&!(kind==='assignment'?card.classList.contains('type-assignment_start')||card.classList.contains('type-assignment_end'):card.classList.contains('type-'+kind)));});}catch(e){$('loading').textContent=e.message;$('content').innerHTML='<p class="notice">'+esc(e.message)+'</p>';}}
function render(){if(timelineView){timeline();return;}status();if(!available().length){$('content').innerHTML='<p class="notice">'+(loading?'Lettura dei Match Report…':'Nessun GW disponibile. Riprova con Aggiorna.')+'</p>';return;}if(rankingView)return ranking();if(!manager)return directory();if(!people.some(m=>m.manager_id===manager))return;({overview,career,h2h,trophies:trophyRoom}[tab]||overview)();wireLogos();}
function rankFor(id){return available().reduce((r,w)=>{const x=bundles[w].managers[id]?.ranking;if(!x){r.incomplete=true;return r;}r.clubs+=x.club_points??x.match_points;r.nations+=x.national_points??0;r.matches+=x.match_points;r.trophies+=x.trophy_points;r.total+=x.total;r.unscored+=x.unscored_trophies;r.incomplete=r.incomplete||bundles[w].national_ranking_error||x.version!==7;return r;},{clubs:0,nations:0,matches:0,trophies:0,total:0,unscored:0,incomplete:false});}
function ranking(){
 const opened=new Set([...document.querySelectorAll('.ranking-row[open]')].map(el=>el.dataset.manager));
 const rows=people.map(m=>({...m,rank:rankFor(m.manager_id)})).sort((a,b)=>b.rank.total-a.rank.total||a.full_name.localeCompare(b.full_name,'it'));
 let previous=null,position=0;rows.forEach((m,i)=>{if(m.rank.total!==previous)position=i+1;m.position=position;previous=m.rank.total;});
 const incomplete=loading||available().length!==selected().length||available().some(w=>bundles[w].trophy_error)||rows.some(m=>m.rank.incomplete||m.rank.unscored);
 const q=$('search').value.toLocaleLowerCase('it').trim(),filtered=rows.filter(m=>(m.full_name+' '+m.manager_id).toLocaleLowerCase('it').includes(q));
 $('manager-count').textContent=filtered.length+' manager';
 $('content').innerHTML='<p class="rank-status">'+(incomplete?'Classifica provvisoria: caricamento o dati incompleti.':'Classifica aggiornata sui dati disponibili.')+' Club + Nazionali · Tutte le stagioni · Pari punti, pari posizione.</p>'+rankRules()+
 '<div class="ranking-list">'+filtered.map(m=>'<details class="ranking-row" data-manager="'+esc(m.manager_id)+'"'+(opened.has(m.manager_id)?' open':'')+'><summary><span class="rank-position">'+m.position+'</span><span class="rank-name"><strong>'+esc(m.full_name)+'</strong><small>'+esc(m.manager_id)+'</small></span><span class="rank-total">'+number(m.rank.total)+'<small>PUNTI</small></span><span class="rank-chevron" aria-hidden="true">⌄</span></summary><div class="rank-detail"><div class="rank-split">'+[['Club',m.rank.clubs],['Nazionali',m.rank.nations],['Trofei',m.rank.trophies]].map(([label,value])=>'<div><small>'+label+'</small><strong>'+number(value)+'<span> pt</span></strong></div>').join('')+'</div><div class="rank-detail-heading"><h3>Punti per Game World</h3><a href="?manager='+encodeURIComponent(m.manager_id)+'">Club House ↗</a></div><div class="rank-world-grid">'+rankWorlds(m.manager_id)+'</div>'+(m.rank.unscored?'<p class="notice">'+m.rank.unscored+' trofei senza regola riconosciuta: bonus non assegnato.</p>':'')+'</div></details>').join('')+'</div>'+(filtered.length?'':'<p class="notice">Nessun manager trovato.</p>');
}
function rankWorlds(id){return available().map(w=>{const m=bundles[w].managers[id],r=m?.ranking;if(!r)return '<p class="notice">'+esc(w)+': ranking non disponibile.</p>';const s=m.stats,n=m.national_stats||zero();
 const line=(label,v,points,source)=>'<tr><th scope="row">'+label+'<small>'+source+'</small></th><td>'+number(v.played)+'</td><td>'+number(v.won)+'</td><td>'+number(v.drawn)+'</td><td>'+number(v.lost)+'</td><td><strong>'+number(points)+'</strong></td></tr>';
 return '<section class="rank-world"><div class="rank-world-head"><div><small>'+esc(w)+' <span>×'+r.weight+'</span></small><h3>'+esc(worldNames[w]||w)+'</h3></div><strong>'+number(r.total)+'<small>punti</small></strong></div><div class="rank-table-wrap"><table class="rank-table"><thead><tr><th>Partite</th><th title="Giocate">G</th><th title="Vinte">V</th><th title="Pareggiate">N</th><th title="Perse">P</th><th>Punti</th></tr></thead><tbody>'+line('Club',s,r.club_points??r.match_points,'Match Report')+line('Nazionali',n,r.national_points??0,'Results')+'</tbody></table></div><div class="rank-trophy-total"><span>Trofei · '+r.awards.length+'</span><strong>'+number(r.trophy_points)+' pt</strong></div><details class="rank-calculation"><summary>Calcolo e trofei</summary><p>Club: ('+s.played+' + '+s.won+' × 0,5 − '+s.lost+' × 0,5) × '+r.weight+' = '+number(r.club_points??r.match_points)+'</p><p>Nazionali: ('+n.played+' + '+n.won+' × 0,5 − '+n.lost+' × 0,5) × '+r.weight+' = '+number(r.national_points??0)+'</p><p>Trofei: '+number(r.trophy_base)+' × '+r.weight+' = '+number(r.trophy_points)+'</p>'+(r.awards.length?'<ul class="rank-awards">'+r.awards.map(a=>'<li><span>'+esc(a.competition)+' · S'+esc(a.season)+'<small>'+esc(a.team)+' · '+esc(a.date)+'</small></span><strong>'+(a.points===null?'Da verificare':number(a.points)+' pt')+'</strong></li>').join('')+'</ul>':'')+'</details>'+(bundles[w].national_ranking_error?'<p class="notice">Results nazionali non disponibili: totale parziale.</p>':'')+(bundles[w].trophy_error?'<p class="notice">Trofei non disponibili: totale parziale.</p>':'')+'</section>';}).join('');}
function rankRules(){return '<details class="panel rank-rules"><summary>Come si calcolano i punti?</summary><div class="rank-rule-scores"><span><b>1,5</b> Vittoria</span><span><b>1</b> Pareggio</span><span><b>0,5</b> Sconfitta</span></div><p>Stessa regola per club e nazionali: giocata +1; vittoria +0,5 aggiuntivo; pareggio 0; sconfitta −0,5. Nessuna distinzione tra avversari. Club dai Match Report; nazionali esclusivamente dai Results, senza sommarle una seconda volta dai report.</p><p><strong>GW001 e GW008 ×3 · GW002 e GW003 ×2 · Altri GW ×1.</strong> Moltiplicatore applicato a partite e trofei.</p><ul><li>World Cup: 125</li><li>SMFA Champions Cup e Campionato Divisione 1: 100</li><li>SMFA Shield, SMFA Super Cup e Charity Shield: 75</li><li>League Cup e League Shield: 50</li><li>Campionati Divisione 2 e inferiori: 25</li><li>Playoff: 10</li></ul><p>Nessun punto per promozioni e retrocessioni. Esito prima dei rigori. Trofei attribuiti alla data della vittoria. Nessun bonus automatico per tipologie sconosciute.</p></details>';}
function directory(){const q=$('search').value.toLocaleLowerCase('it').trim();const rows=people.filter(m=>(m.full_name+' '+m.manager_id).toLocaleLowerCase('it').includes(q));$('manager-count').textContent=rows.length+' manager';$('content').innerHTML='<div class="manager-grid">'+rows.map(m=>{const s=stats(m.manager_id),ws=available().filter(w=>(bundles[w].managers[m.manager_id]?.stats.played||0)>0);return `<a class="manager-card" href="?manager=${encodeURIComponent(m.manager_id)}"><div class="identity"><span class="avatar">${esc(initials(m.full_name))}</span><div><h2>${esc(m.full_name)}</h2><small>${esc(m.manager_id)}</small></div></div><div class="mini-stats"><div><strong>${number(s.played)}</strong><small>PARTITE</small></div><div><strong>${number(s.won)}</strong><small>VITTORIE</small></div><div><strong>${pct(s)}</strong><small>% VITTORIE</small></div></div>${badges(ws)}<div class="card-foot"><span class="gold">${trophies(m.manager_id)} trofei · ${ws.length} GW</span><span class="open-profile">Profilo →</span></div>${!m.sm_manager_id?'<p class="muted">ID Soccer Manager non presente nel Codex</p>':''}</a>`;}).join('')+'</div>'+(rows.length?'':'<p class="notice">Nessun manager trovato.</p>');}
function kpis(s){return '<div class="kpis">'+[['Partite',number(s.played)],['Vittorie',number(s.won)],['Pareggi',number(s.drawn)],['Sconfitte',number(s.lost)],['Vittorie %',pct(s)],['Gol fatti',number(s.gf)],['Gol subiti',number(s.ga)],['Differenza reti',number(s.gf-s.ga)]].map(([label,value])=>`<div class="kpi"><strong>${value}</strong><span>${label}</span></div>`).join('')+'</div>';}
function matchRows(matches){return matches.map(m=>`<div class="match"><div><a href="../competitions/match.html?${new URLSearchParams({world:m.world,fixture:m.fixture_id})}">${esc(m.team)} — ${esc(m.opponent_team)}</a><small>${esc(m.date||'Data non disponibile')} · ${esc(m.world)} · S${esc(m.season??'—')}${m.opponent_id?' · '+esc(m.opponent_name):''}</small></div><div class="score">${m.gf}–${m.ga}<span class="result ${m.outcome}">${m.outcome}</span>${m.penalty_for!==null&&m.penalty_against!==null?`<small>Rigori ${m.penalty_for}–${m.penalty_against}</small>`:''}</div></div>`).join('');}
function overview(){const s=stats(manager),matches=allMatches();const issues=available().flatMap(w=>bundles[w].issues||[]);$('content').innerHTML=kpis(s)+`<p class="muted">Identificazione: ${s.matched_by_id} partite tramite ID Soccer Manager. ${trophies(manager)} trofei · Rigori vinti ${s.penalty_won} / persi ${s.penalty_lost}</p>`+'<div class="section-heading"><h2>Nei Game World</h2></div><div class="world-stats">'+available().filter(w=>(bundles[w].managers[manager]?.stats.played||0)>0).map(w=>{const x=bundles[w].managers[manager].stats;return `<div class="panel"><div class="world-title"><strong>${esc(worldName(w))}</strong><a href="../?world=${w}">Apri GW ↗</a></div><div class="stat-line"><span><strong>${x.played}</strong>partite</span><span><strong>${x.won}</strong>V</span><span><strong>${x.drawn}</strong>P</span><span><strong>${x.lost}</strong>S</span><span>${pct(x)} vittorie</span></div></div>`;}).join('')+'</div>'+`<div class="section-heading"><h2>Partite</h2><small>${matches.length} totali</small></div><div class="panel">${matches.length?matchRows(matches.slice(0,limit)):'Nessuna partita di club attribuibile a questo manager nei Match Report caricati.'}</div>`+(matches.length>limit?'<button id="more" class="more">Mostra altre 25 partite</button>':'')+(issues.length?'<details class="panel"><summary>Report esclusi · '+issues.length+'</summary>'+issues.map(i=>`<p class="muted">${esc(i.world)} · ${esc(i.date)} · Fixture ${esc(i.fixture_id)}: ${esc(i.reason)}</p>`).join('')+'</details>':'');if($('more'))$('more').onclick=()=>{limit+=25;overview();};}
function matchStats(rows){return sum(rows.map(m=>({...zero(),played:1,won:m.outcome==='V'?1:0,drawn:m.outcome==='P'?1:0,lost:m.outcome==='S'?1:0,gf:m.gf,ga:m.ga})));}
function career(){const matches=allMatches(),assignments=available().flatMap(w=>(bundles[w].assignments||[]).map(a=>({...a,world:w}))).sort((a,b)=>(Number(String(a.world).replace(/^GW/i,''))-Number(String(b.world).replace(/^GW/i,'')))||String(a.start_date).localeCompare(String(b.start_date)));$('content').innerHTML='<div class="section-heading"><div><p class="eyebrow">LA TUA STORIA</p><h2>Carriera nei club</h2></div></div><p class="muted">Periodi degli incarichi dal Manager Assignment. Statistiche calcolate sulle partite presenti nei Match Report.</p><div class="career-grid">'+(assignments.map(a=>{const rows=matches.filter(m=>m.world===a.world&&String(m.team_id||'')===String(a.team_id||'')),s=matchStats(rows),active=!a.end_date;return `<section class="panel career-card ${active?'career-active':'career-closed'}"><div class="club-heading">${clubLogo(a.world,a.team_id)}<div><h3>${esc(a.team_name||'Club')}</h3><span class="muted">${esc(worldName(a.world))}</span></div></div><div class="career-status-row"><p class="career-dates">Dal ${dateIT(a.start_date)} ${active?'a':'al'} ${active?'<strong>ACTIVE</strong>':dateIT(a.end_date)}</p><span class="career-status ${active?'active':'closed'}">${active?'ACTIVE':'ENDED'}</span></div><div class="stat-line"><span><strong>${s.played}</strong>partite</span><span><strong>${s.won}</strong>vittorie</span><span><strong>${s.drawn}</strong>pareggi</span><span><strong>${s.lost}</strong>sconfitte</span><span>Gol ${s.gf}–${s.ga}</span></div></section>`;}).join('')||'<p class="notice">Nessun incarico club disponibile.</p>')+'</div>';}
function h2h(){const matches=allMatches(),groups=new Map();for(const m of matches)if(m.opponent_id){if(!groups.has(m.opponent_id))groups.set(m.opponent_id,[]);groups.get(m.opponent_id).push(m);}const rows=[...groups.values()].sort((a,b)=>b.length-a.length);$('content').innerHTML='<h2>Head to Head globali</h2><p class="muted">Solo avversari IMC riconosciuti esclusivamente tramite ID. Gli incontri negli altri GW sono uniti nello stesso bilancio.</p>'+`<p class="notice">${rows.reduce((n,r)=>n+r.length,0)} scontri IMC–IMC · ${matches.filter(m=>!m.opponent_id).length} partite con avversario esterno o non identificato, incluse nelle statistiche generali ma non qui.</p>`+(rows.map(items=>{const s=matchStats(items),m=items[0],gws=[...new Set(items.map(x=>x.world))];return `<details class="rival" data-opponent="${esc(m.opponent_id)}" data-worlds="${esc(gws.join(','))}"><summary><div><div class="rival-title"><span class="avatar">${esc(initials(m.opponent_name))}</span><div><strong>${esc(m.opponent_name)}</strong><p class="muted">${s.played} partite · Gol ${s.gf}–${s.ga}</p></div></div><div>${badges(gws)}</div></div><div><div class="h2h-score"><span class="win"><strong>${s.won}</strong><small>VITTORIE</small></span><span><strong>${s.drawn}</strong><small>PAREGGI</small></span><span class="loss"><strong>${s.lost}</strong><small>SCONFITTE</small></span></div><div class="balance" aria-hidden="true"><span class="win" style="flex:${s.won}"></span><span style="flex:${s.drawn}"></span><span class="loss" style="flex:${s.lost}"></span></div></div></summary><div class="rival-matches"><p><a href="?manager=${encodeURIComponent(m.opponent_id)}">Apri profilo globale →</a></p><div class="hh hh-global-detail">Apri per caricare il dettaglio completo.</div></div></details>`;}).join('')||'<p class="notice">Nessuno scontro diretto IMC disponibile.</p>');
 $('content').querySelectorAll('.rival[data-opponent]').forEach(el=>el.addEventListener('toggle',async()=>{
  if(!el.open||el.dataset.loaded==='true'||el.dataset.loading==='true')return;
  el.dataset.loading='true';const body=el.querySelector('.hh-global-detail');body.textContent='Caricamento dettaglio dai Match Report…';
  try{const r=await fetch('h2h-detail.php?'+new URLSearchParams({manager,opponent:el.dataset.opponent,worlds:el.dataset.worlds}),{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw Error('Dettaglio non disponibile. Chiudi e riapri per riprovare.');if(!el.isConnected)return;NexusH2H.renderDetail(body,d);el.dataset.loaded='true';}catch(e){if(el.isConnected)body.textContent=e.message;}finally{el.dataset.loading='false';}
 }));
}
function trophyRoom(){const rows=available().flatMap(w=>bundles[w].trophies||[]).sort((a,b)=>String(b.date).localeCompare(String(a.date)));const groups=new Map();for(const t of rows){if(!groups.has(t.world))groups.set(t.world,new Map());const countries=groups.get(t.world),country=t.country||'Internazionali / paese non indicato';if(!countries.has(country))countries.set(country,new Map());const comps=countries.get(country);if(!comps.has(t.competition))comps.set(t.competition,[]);comps.get(t.competition).push(t);} $('content').innerHTML='<div class="section-heading"><div><p class="eyebrow">IL PALMARÈS</p><h2>Trophy Room</h2></div><span class="pill">'+rows.length+' trofei</span></div><p class="muted">Trofei già registrati in Nexus e attribuiti al manager in base all’incarico alla data della vittoria.</p>'+([...groups].map(([w,countries])=>'<section class="trophy-world"><h3>'+esc(worldName(w))+'</h3>'+[...countries].map(([country,comps])=>(['GW002','GW003','GW007','GW008'].includes(w)?'<h4 class="trophy-country">'+esc(country)+'</h4>':'')+[...comps].map(([name,items])=>'<div class="trophy-group"><h4>'+cup+esc(name)+' <span class="pill">'+items.length+'</span></h4>'+items.map(t=>'<article class="panel trophy"><p>'+esc(t.team)+'</p><small>Stagione '+esc(t.season)+' · '+esc(t.date)+'</small></article>').join('')+'</div>').join('')).join('')+'</section>').join('')||'<p class="notice">Nessun trofeo attribuito nei GW disponibili.</p>');}
async function load(){const token=++runId;loading=true;bundles={};failed=[];$('retry').disabled=true;render();let next=0;async function worker(){while(next<worlds.length){const w=worlds[next++];try{const d=await get('?'+new URLSearchParams({world:w,...(manager?{manager}:{})}));if(token!==runId)return;bundles[w]=d;}catch(e){if(token!==runId)return;failed.push(w);}render();}}await Promise.all([worker(),worker()]);if(token!==runId)return;loading=false;$('retry').disabled=false;render();}
$('world').addEventListener('change',()=>{limit=25;render();});$('search').addEventListener('input',render);$('retry').addEventListener('click',()=>start());document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('#tabs button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render();});
async function start(){try{const meta=await get();people=meta.managers;worldNames=Object.fromEntries(meta.worlds.map(w=>[w.id,w.name]));worldLinks();if($('world').options.length===1)worlds.forEach(w=>$('world').add(new Option(worldName(w),w)));if(timelineView){await timeline();return;}if(manager){const m=people.find(x=>x.manager_id===manager);if(!m){$('loading').textContent='Manager IMC non trovato.';$('content').replaceChildren();return;}$('directory-heading').hidden=true;$('profile-avatar').hidden=false;$('profile-avatar').textContent=initials(m.full_name);$('title').textContent=m.full_name;document.title='Club House · '+m.full_name;$('subtitle').textContent=m.manager_id+' · Carriera globale nei club';$('tabs').hidden=false;$('back').hidden=false;$('search-label').hidden=true;}await load();}catch(e){$('loading').textContent=e.message;$('retry').disabled=false;}}start();
