'use strict';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),manager=params.get('manager')||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fields=['played','won','drawn','lost','gf','ga','penalty_won','penalty_lost','matched_by_id'];
const zero=()=>Object.fromEntries(fields.map(k=>[k,0]));
const sum=items=>items.reduce((a,s)=>{fields.forEach(k=>a[k]+=Number(s[k]||0));return a;},zero());
const pct=s=>s.played?(100*s.won/s.played).toLocaleString('it-IT',{maximumFractionDigits:1})+'%':'—';
const number=n=>Number(n||0).toLocaleString('it-IT');
let people=[],worldNames={},bundles={},failed=[],tab='overview',limit=25,loading=true,runId=0;
const worlds=Array.from({length:10},(_,i)=>'GW'+String(i+1).padStart(3,'0'));
const selected=()=>worlds.filter(w=>!$('world').value||w===$('world').value);
const available=()=>selected().filter(w=>bundles[w]);
const allMatches=()=>available().flatMap(w=>bundles[w].matches||[]).sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.fixture_id).localeCompare(String(a.fixture_id)));
const worldName=w=>worldNames[w]?w+' · '+worldNames[w]:w;
async function get(q=''){const r=await fetch('data.php'+q,{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Dati non disponibili');return d;}
function stats(id){return sum(available().map(w=>bundles[w].managers[id]?.stats||zero()));}
function trophies(id){return available().reduce((n,w)=>n+(bundles[w].managers[id]?.trophies||0),0);}
function status(){const ready=available().length,total=selected().length,missing=selected().filter(w=>failed.includes(w));$('loading').textContent=(loading?'Caricamento · ':'')+ready+'/'+total+' GW disponibili · Fonte: Match Report dei club';const excluded=manager?available().reduce((n,w)=>n+(bundles[w].managers[manager]?.excluded||0),0):0;const trophyErrors=available().filter(w=>bundles[w].trophy_error);$('warning').textContent=[missing.length?'Dati parziali: non disponibili '+missing.join(', ')+'. Usa Aggiorna per riprovare.':'',excluded?excluded+' partite escluse dai conteggi per anomalie nei report. Vedi Panoramica.':'',trophyErrors.length?'Trofei incompleti per '+trophyErrors.join(', ')+'.':''].filter(Boolean).join(' ');}
function render(){status();if(!available().length){$('content').innerHTML='<p class="notice">'+(loading?'Lettura dei Match Report…':'Nessun GW disponibile. Riprova con Aggiorna.')+'</p>';return;}if(!manager)return directory();if(!people.some(m=>m.manager_id===manager))return;({overview,career,h2h,trophies:trophyRoom}[tab]||overview)();}
function directory(){const q=$('search').value.toLocaleLowerCase('it').trim();const rows=people.filter(m=>(m.full_name+' '+m.manager_id).toLocaleLowerCase('it').includes(q));$('content').innerHTML='<div class="manager-grid">'+rows.map(m=>{const s=stats(m.manager_id),active=available().filter(w=>(bundles[w].managers[m.manager_id]?.stats.played||0)>0).length,initials=m.full_name.split(/\s+/).slice(0,2).map(x=>x[0]).join('');return `<a class="manager-card" href="?manager=${encodeURIComponent(m.manager_id)}"><div class="identity"><span class="avatar">${esc(initials)}</span><div><h2>${esc(m.full_name)}</h2><small>${esc(m.manager_id)}</small></div></div><div class="mini-stats"><div><strong>${number(s.played)}</strong><small>PARTITE</small></div><div><strong>${number(s.won)}</strong><small>VITTORIE</small></div><div><strong>${pct(s)}</strong><small>% VITTORIE</small></div></div><div class="card-foot"><span>${active} GW con partite</span><span>${trophies(m.manager_id)} trofei</span></div>${!m.sm_manager_id?'<p class="muted">ID Soccer Manager non presente nel Codex</p>':''}</a>`;}).join('')+'</div>'+(rows.length?'':'<p>Nessun manager trovato.</p>');}
function kpis(s){return '<div class="kpis">'+[['Partite',number(s.played)],['Vittorie',number(s.won)],['Pareggi',number(s.drawn)],['Sconfitte',number(s.lost)],['Vittorie %',pct(s)],['Gol fatti',number(s.gf)],['Gol subiti',number(s.ga)],['Differenza reti',number(s.gf-s.ga)]].map(([label,value])=>`<div class="kpi"><strong>${value}</strong><span>${label}</span></div>`).join('')+'</div>';}
function matchRows(matches){return matches.map(m=>`<div class="match"><div><a href="../competitions/match.html?${new URLSearchParams({world:m.world,fixture:m.fixture_id})}">${esc(m.team)} — ${esc(m.opponent_team)}</a><small>${esc(m.date||'Data non disponibile')} · ${esc(m.world)} · S${esc(m.season??'—')}${m.opponent_id?' · '+esc(m.opponent_name):''}</small></div><div class="score">${m.gf}–${m.ga}<span class="result ${m.outcome}">${m.outcome}</span>${m.penalty_for!==null&&m.penalty_against!==null?`<small>Rigori ${m.penalty_for}–${m.penalty_against}</small>`:''}</div></div>`).join('');}
function overview(){const s=stats(manager),matches=allMatches();const issues=available().flatMap(w=>bundles[w].issues||[]);$('content').innerHTML=kpis(s)+`<p class="muted">Identificazione: ${s.matched_by_id} partite tramite ID Soccer Manager. ${trophies(manager)} trofei · Rigori vinti ${s.penalty_won} / persi ${s.penalty_lost}</p>`+'<div class="section-heading"><h2>Nei Game World</h2></div><div class="world-stats">'+available().filter(w=>(bundles[w].managers[manager]?.stats.played||0)>0).map(w=>{const x=bundles[w].managers[manager].stats;return `<div class="panel"><strong>${esc(worldName(w))}</strong><div class="stat-line"><span><strong>${x.played}</strong>partite</span><span><strong>${x.won}</strong>V</span><span><strong>${x.drawn}</strong>P</span><span><strong>${x.lost}</strong>S</span><span>${pct(x)} vittorie</span></div></div>`;}).join('')+'</div>'+`<div class="section-heading"><h2>Partite</h2><small>${matches.length} totali</small></div><div class="panel">${matches.length?matchRows(matches.slice(0,limit)):'Nessuna partita di club attribuibile a questo manager nei Match Report caricati.'}</div>`+(matches.length>limit?'<button id="more" class="more">Mostra altre 25 partite</button>':'')+(issues.length?'<details class="panel"><summary>Report esclusi · '+issues.length+'</summary>'+issues.map(i=>`<p class="muted">${esc(i.world)} · ${esc(i.date)} · Fixture ${esc(i.fixture_id)}: ${esc(i.reason)}</p>`).join('')+'</details>':'');if($('more'))$('more').onclick=()=>{limit+=25;overview();};}
function matchStats(rows){return sum(rows.map(m=>({...zero(),played:1,won:m.outcome==='V'?1:0,drawn:m.outcome==='P'?1:0,lost:m.outcome==='S'?1:0,gf:m.gf,ga:m.ga})));}
function career(){const groups=new Map();for(const m of allMatches()){const key=m.world+'|'+(m.team_id||m.team);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(m);} $('content').innerHTML='<h2>Carriera nei club</h2><p class="muted">Squadre e periodi ricavati dalle partite presenti nei Match Report, non dalle date degli incarichi.</p>'+([...groups.values()].map(rows=>{const s=matchStats(rows),last=rows[0],first=rows[rows.length-1];return `<section class="panel"><h3>${esc(last.team)}</h3><strong class="muted">${esc(worldName(last.world))}</strong><p class="career-dates">Report dal ${esc(first.date||'—')} al ${esc(last.date||'—')}</p><div class="stat-line"><span><strong>${s.played}</strong>partite</span><span><strong>${s.won}</strong>vittorie</span><span><strong>${s.drawn}</strong>pareggi</span><span><strong>${s.lost}</strong>sconfitte</span><span>Gol ${s.gf}–${s.ga}</span></div></section>`;}).join('')||'<p class="notice">Nessuna partita disponibile.</p>');}
function h2h(){const matches=allMatches(),groups=new Map();for(const m of matches)if(m.opponent_id){if(!groups.has(m.opponent_id))groups.set(m.opponent_id,[]);groups.get(m.opponent_id).push(m);}const rows=[...groups.values()].sort((a,b)=>b.length-a.length);$('content').innerHTML='<h2>Head to Head globali</h2><p class="muted">Solo avversari IMC riconosciuti esclusivamente tramite ID. Gli incontri negli altri GW sono uniti nello stesso bilancio.</p>'+`<p class="notice">${rows.reduce((n,r)=>n+r.length,0)} scontri IMC–IMC · ${matches.filter(m=>!m.opponent_id).length} partite con avversario esterno o non identificato, incluse nelle statistiche generali ma non qui.</p>`+(rows.map(items=>{const s=matchStats(items),m=items[0],gws=[...new Set(items.map(x=>x.world))];return `<details class="rival"><summary><div><strong>${esc(m.opponent_name)}</strong><small> · ${esc(m.opponent_id)}</small><p class="muted">${gws.join(' · ')}</p></div><div class="stat-line"><span>${s.played} partite</span><span>${s.won} V</span><span>${s.drawn} P</span><span>${s.lost} S</span><span>Gol ${s.gf}–${s.ga}</span></div></summary><div class="rival-matches"><p><a href="?manager=${encodeURIComponent(m.opponent_id)}">Apri profilo globale →</a></p>${matchRows(items)}</div></details>`;}).join('')||'<p class="notice">Nessuno scontro diretto IMC disponibile.</p>');}
function trophyRoom(){const rows=available().flatMap(w=>bundles[w].trophies||[]).sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('content').innerHTML='<h2>Trophy Room</h2><p class="muted">Trofei già registrati in Nexus e attribuiti al manager in base all’incarico alla data della vittoria.</p>'+(rows.map(t=>`<article class="panel trophy"><h3>${esc(t.competition)}</h3><p>${esc(t.team)}</p><small>${esc(worldName(t.world))} · Stagione ${esc(t.season)} · ${esc(t.date)}</small></article>`).join('')||'<p class="notice">Nessun trofeo attribuito nei GW disponibili.</p>');}
async function load(){const token=++runId;loading=true;bundles={};failed=[];$('retry').disabled=true;render();let next=0;async function worker(){while(next<worlds.length){const w=worlds[next++];try{const d=await get('?'+new URLSearchParams({world:w,...(manager?{manager}:{})}));if(token!==runId)return;bundles[w]=d;}catch(e){if(token!==runId)return;failed.push(w);}render();}}await Promise.all([worker(),worker()]);if(token!==runId)return;loading=false;$('retry').disabled=false;render();}
$('world').addEventListener('change',()=>{limit=25;render();});$('search').addEventListener('input',render);$('retry').addEventListener('click',()=>start());document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('#tabs button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render();});
async function start(){try{const meta=await get();people=meta.managers;worldNames=Object.fromEntries(meta.worlds.map(w=>[w.id,w.name]));if($('world').options.length===1)worlds.forEach(w=>$('world').add(new Option(worldName(w),w)));if(manager){const m=people.find(x=>x.manager_id===manager);if(!m){$('loading').textContent='Manager IMC non trovato.';$('content').replaceChildren();return;}$('title').textContent=m.full_name;document.title='Club House · '+m.full_name;$('subtitle').textContent=m.manager_id+' · Carriera globale nei club';$('tabs').hidden=false;$('back').hidden=false;$('search-label').hidden=true;}await load();}catch(e){$('loading').textContent=e.message;$('retry').disabled=false;}}start();
