/* GW005 Living Hall · Exploration 01. Existing window.IMC_MINISITE_DATA integration retained in legacy source history; this bounded study uses an explicitly labelled verified snapshot and isolated demo data. */
(()=>{'use strict';
const root=document.getElementById('app');
const routes={home:'Home',competitions:'Competizioni',results:'Risultati',schedule:'Calendario',match:'Match Center',standings:'Classifiche',managers:'Manager',manager:'Profilo manager',players:'Player',player:'Profilo player',club:'Club',records:'Records / Honours',transfers:'Trasferimenti',archive:'Archive / Legacy',moodboard:'System Moodboard'};
const portraits={manager:'/minisite/GW001/exploration-assets/manager.webp',player:'/minisite/GW001/exploration-assets/player.webp'};
const real=[{home:'Wigan Athletic',away:'River Plate',score:'2 — 2',date:'07.09.2026',division:'1',id:'312788412',extra:'Rigori 2–1 · Stage importato: Playoff Finale'},{home:'Liverpool',away:'ORLANDO PIRATES',score:'1 — 3',date:'30.07.2026',division:'1',id:'311937951',extra:''},{home:'Wigan Athletic',away:'Real Madrid',score:'2 — 2',date:'02.08.2026',division:'2',id:'311938011',extra:''}];
const demo='<span class="demo">DEMO / PLACEHOLDER VISUAL DATA</span>';
const link=(r,t)=>`<a class="link" href="#${r}">${t} <span aria-hidden="true">↗</span></a>`;
const head=(k,t,p='')=>`<span class="eyebrow">${k}</span><h1>${t}</h1>${p?`<p>${p}</p>`:''}`;
const photo=(kind)=>`<div class="photo"><img src="${portraits[kind]}" alt="Studio visivo di ritratto ${kind}; nessuna identità GW005 attribuita"><span class="caption">RITRATTO DIMOSTRATIVO · Nessuna identità reale attribuita</span></div>`;
const source='<p class="footnote">Campione verificato il 10.09.2026 · MySQL Aruba / GW005_IMC Results, tramite IMC Nexus. Tre fixture importate; non è un elenco completo né una classifica ufficiale.</p>';
function score(r){return `<a class="score" href="#match?id=${r.id}"><small>${r.date} · LEAGUE · DIVISION ${r.division} · FT</small><div class="teams"><strong>${r.home}</strong><b class="digits">${r.score}</b><strong>${r.away}</strong></div>${r.extra?`<div class="context">${r.extra}</div>`:''}</a>`}
const forms=()=>'<div class="form" aria-label="Forma dimostrativa: vittoria, vittoria, pareggio, vittoria, sconfitta"><span class="win">V</span><span class="win">V</span><span>P</span><span class="win">V</span><span>S</span></div>';
const bars=()=>`<div class="bars" aria-label="Confronto gol dimostrativo">${[['Player A',27],['Player B',22],['Player C',18],['Player D',13]].map(([n,v])=>`<div class="bar-row"><span>${n}</span><div class="bar-track"><i style="width:${v/27*100}%"></i></div><b>${v}</b></div>`).join('')}</div>`;
function ranks(){return `<div class="table-scroll"><table><caption class="footnote">Divisione dimostrativa · punti, giocate e differenza reti</caption><thead><tr><th>POS</th><th>CLUB</th><th>G</th><th class="optional">V</th><th class="optional">P</th><th class="optional">S</th><th>DR</th><th>PT</th></tr></thead><tbody>${[['A',14,10,2,2,18,32],['B',14,9,3,2,14,30],['C',14,8,2,4,9,26],['D',14,6,3,5,3,21],['E',14,5,3,6,-2,18],['F',14,4,2,8,-9,14],['G',14,3,3,8,-13,12],['H',14,2,2,10,-20,8]].map((r,i)=>`<tr><td>${String(i+1).padStart(2,'0')}</td><td><a href="#club">Club ${r[0]} ↗</a></td>${r.slice(1).map((n,j)=>`<td${j>0&&j<4?' class="optional"':''}>${n}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function home(){return `<section class="arena hero"><div class="hero-copy"><span class="eyebrow">GW005 / HALL OF FAMERS<br>THE LIVING HALL</span><h1>Greatness<br>is earned.</h1><p>Il risultato è l’inizio.<br>Quello che resta ha un volto.</p>${link('results','Dentro la competizione')}</div><div class="hero-photo"><img src="${portraits.manager}" alt="Ritratto dimostrativo per lo studio della luce e del taglio"><span class="caption">PORTRAIT STUDY 01 / IMMAGINE DIMOSTRATIVA<br>Nessuna identità o prestazione reale attribuita.</span></div></section><section class="arena"><div class="wrap"><div class="section-head"><div><span class="eyebrow">THE ARENA / DATI VERIFICATI</span><h2>Il campo decide.</h2></div>${link('results','Risultati disponibili')}</div>${score(real[0])}${source}</div></section><section class="portrait-stage gallery">${photo('player')}<div class="portrait-copy">${demo}<span class="eyebrow">THE PERFORMANCE / PLAYER A</span><div class="big">27</div><span class="metric-label">GOL · STAGIONE DIMOSTRATIVA</span><h2>Un numero.<br>Una presenza.</h2><p>La prestazione entra in primo piano. Il contesto resta accanto al numero.</p>${link('player','Esplora il profilo')}</div></section><section class="wrap"><div class="section-head"><h2>Recognition in motion.</h2>${link('standings','Classifiche')}</div>${demo}<div class="grid2"><div><span class="eyebrow">CONFRONTO / GOL</span>${bars()}</div><div class="proof"><span class="eyebrow">RECORD WATCH / STUDIO</span><div class="big">01</div><p>Un traguardo da dimostrare.</p><p class="footnote">I record ufficiali richiedono copertura completa e criteri verificati.</p>${link('records','Wall of Numbers')}</div></div></section><section class="plum"><div class="wrap"><span class="eyebrow">THE LEGACY</span><h2>Ciò che resta.<br>Chi lo ha costruito.</h2><p class="statement">Ogni carriera comincia dalla prossima partita.</p>${link('archive','Esplora Legacy')}</div></section>`}
function competitions(){return `<section class="arena"><div class="wrap">${head('THE ARENA','Stages of<br>distinction.','League e coppe: la competizione prima del riconoscimento.')}${demo}<div class="grid3">${[1,2,3].map(n=>`<article class="record"><span class="eyebrow">LEAGUE / STUDIO</span><div class="big">0${n}</div><h3>Division ${n}</h3>${link('standings','Classifica demo')}</article>`).join('')}</div></div></section><section class="wrap"><h2>La strada alla finale.</h2>${demo}<div class="timeline"><article><b>04</b><div><h3>Semifinali</h3><p>Club A — Club B / Club C — Club D</p></div></article><article><b>02</b><div><h3>Finale</h3><p>Finaliste da determinare · nessun vincitore attribuito.</p></div></article></div>${link('schedule','Calendario')}</section>`}
function results(){return `<section class="arena"><div class="wrap">${head('RESULTS / CAMPIONE VERIFICATO','Il risultato.<br>La sua prova.')}${source}<div class="filter"><label for="division">Divisione</label><select id="division"><option value="all">Tutte</option><option value="1">Division 1</option><option value="2">Division 2</option></select></div><div id="results-list">${real.map(score).join('')}</div></div></section><section class="wrap"><h2>Oltre lo score.</h2><p>Protagonista, evento decisivo e conseguenze di classifica entrano nel racconto soltanto quando sono documentati.</p>${link('match','Apri il Match Center')}</section>`}
function schedule(){return `<section class="wrap">${head('FIXTURES','La prossima<br>occasione.')}${demo}<p>Calendario esclusivamente dimostrativo. Questi incontri non rappresentano partite programmate in GW005.</p>${['Giornata A','Giornata B'].map((d,i)=>`<article class="score"><span class="eyebrow">${d} / DATA DA DEFINIRE</span><div class="teams"><strong>Club ${i?'C':'A'}</strong><b class="digits">VS</b><strong>Club ${i?'D':'B'}</strong></div></article>`).join('')}<div class="proof"><h3>Next Match Object</h3><p>Competizione, avversario, giorno e stato: tutto nello stesso colpo d’occhio.</p></div>${link('competitions','Competition Hub')}</section>`}
function match(){let r=real.find(x=>x.id===new URLSearchParams(location.hash.split('?')[1]).get('id'))||real[0];return `<section class="arena matchhero"><span class="eyebrow">MATCH CENTER / ${r.date} / FT</span><div class="teams"><strong>${r.home}</strong><b class="digits">${r.score}</b><strong>${r.away}</strong></div><p style="margin:24px auto">${r.extra||'League · Division '+r.division}</p><span class="footnote">Fixture ${r.id} · dato importato verificato</span></section><section class="wrap"><div class="grid2"><div><span class="eyebrow">THE EVIDENCE</span><h2>Il dato resta<br>al centro.</h2>${source}</div><div><h3>Report e protagonisti</h3><p>In questo campione non sono stati acquisiti eventi, formazioni o statistiche individuali del match. Nessun protagonista viene assegnato.</p>${link('results','Tutti i risultati del campione')}</div></div></section>`}
function standings(){return `<section class="wrap">${head('RANK / RECOGNITION IN MOTION','Ogni posizione<br>si conquista.')}${demo}${ranks()}<p class="footnote">Simulazione coerente di 8 club e 14 giornate. Nessuna posizione è attribuita ai club reali.</p></section><section class="plum"><div class="wrap"><span class="eyebrow">THE GAP / DEMO</span><div class="big">02</div><h2>Punti tra prima e seconda.</h2><p>La distanza introduce tensione senza trasformare la classifica in un podio.</p></div></section>`}
function people(kind){let manager=kind==='manager';return `<section class="wrap">${head(manager?'THE MANAGERS':'THE PLAYERS',manager?'The portrait of<br>performance.':'Performance worth<br>remembering.')}${demo}<div class="filter"><label for="search">Cerca nello studio</label><input id="search" type="search" placeholder="${manager?'Manager':'Player'} A"></div><div class="listing" id="people">${['A','B','C'].map((n,i)=>`<a data-person="${kind} ${n}" href="#${kind}?demo=${n}">${i===0?photo(kind):`<div class="type-portrait">${manager?'M':'P'} / ${n}</div>`}<h3>${manager?'Manager':'Player'} ${n}</h3><p>Profilo dimostrativo · Club ${n}</p><span class="footnote">${manager?'Arena / Legacy':'Performance / signature stat'} ↗</span></a>`).join('')}</div></section>`}
function profile(kind){let manager=kind==='manager',n=new URLSearchParams(location.hash.split('?')[1]).get('demo')||'A';n=['A','B','C'].includes(n)?n:'A';return `<section class="portrait-stage arena">${photo(kind)}<div class="portrait-copy">${demo}<span class="eyebrow">THE PORTRAIT / CLUB ${n}</span><h1>${manager?'Manager':'Player'} ${n}</h1><div class="big">${manager?'10':'27'}</div><span class="metric-label">${manager?'VITTORIE / 14 PARTITE':'GOL / 24 PRESENZE'} · DEMO</span><p>Ritratto di studio: il soggetto fotografico non identifica una persona iscritta a GW005.</p></div></section><section class="wrap"><div class="tabs"><button data-profile="arena" aria-pressed="true">Arena</button><button data-profile="legacy" aria-pressed="false">Legacy</button></div><div id="profile-detail">${arenaDetail(manager)}</div></section>`}
function arenaDetail(manager){return `${demo}<div class="grid2"><div><span class="eyebrow">STATO COMPETITIVO / DEMO</span><h2>${manager?'Continuità.':'Presenza decisiva.'}</h2>${forms()}<p>${manager?'10 vittorie, 2 pareggi, 2 sconfitte.':'27 gol, 8 assist, voto medio 8.12.'}</p>${link('club','Club dimostrativo')}</div><div><span class="eyebrow">${manager?'ANDAMENTO':'GOL A CONFRONTO'} / DEMO</span>${bars()}</div></div>`}
function legacyDetail(){return `${demo}<h2>Una carriera, per momenti.</h2><div class="timeline"><article><b>01</b><div><h3>Il primo capitolo</h3><p>Tappa dimostrativa senza data né achievement ufficiale.</p></div></article><article><b>02</b><div><h3>Il riconoscimento</h3><p>Spazio riservato a risultati verificabili.</p></div></article></div>${link('archive','Archive / Legacy')}`}
function club(){return `<section class="plum"><div class="wrap">${demo}${head('CLUB / STUDIO','Club A.','Identità tipografica dimostrativa. Nessuno stemma o risultato storico attribuito.')}<div class="grid3"><div><div class="big">01</div><span class="metric-label">POSIZIONE DEMO</span></div><div><div class="big">32</div><span class="metric-label">PUNTI DEMO</span></div><div><span class="eyebrow">MANAGER A</span>${forms()}${link('manager','Profilo manager')}</div></div></div></section><section class="wrap"><div class="grid2"><div><h2>Le persone<br>del club.</h2>${link('players','Player demo')}</div><div><h3>Latest / Next</h3><p>Club A 2–0 Club B · risultato demo</p><p>Club A — Club C · calendario demo</p>${link('schedule','Prossime occasioni')}</div></div></section>`}
function records(){return `<section class="wrap">${head('RECORDS / HONOURS','The wall<br>of numbers.')}<p>Nessun record ufficiale viene dichiarato in questa esplorazione. Gli oggetti seguenti mostrano la forma del riconoscimento.</p>${demo}<div class="grid3">${[['27','Gol','Player A'],['14','Presenze','Manager A'],['08','Assist','Player A']].map(([v,t,n])=>`<article class="record"><div class="big">${v}</div><h3>${t}</h3><p>${n} · periodo dimostrativo</p><span class="footnote">Non è un primato GW005.</span></article>`).join('')}</div></section><section class="plum"><div class="wrap"><span class="eyebrow">HONOUR OBJECT / STUDIO</span><h2>The spotlight<br>is earned.</h2><div class="proof">${demo}<h3>Performance selezionata</h3><p>Soggetto · risultato · valore · competizione · periodo.</p><p class="footnote">Il trattamento champagne richiede un criterio di riconoscimento esplicito.</p></div></div></section>`}
function transfers(){return `<section class="wrap">${head('TRANSFERS','A new chapter.')}${demo}<div class="portrait-stage">${photo('player')}<div class="portrait-copy"><span class="eyebrow">PLAYER A / STUDIO</span><h2>Un’altra maglia.<br>La stessa ambizione.</h2><div class="transfer"><strong>Club B → Club A</strong><div>Data da verificare<br><span class="footnote">Valore e stato non disponibili</span></div></div>${link('player','Il profilo')}</div></div></section>`}
function archive(){return `<section class="plum"><div class="wrap">${head('ARCHIVE / LEGACY','Worth<br>remembering.')}<p class="statement">La memoria ha bisogno di prove.</p></div></section><section class="wrap">${legacyDetail()}<div class="proof"><h3>Copertura storica</h3><p>Carriere, campioni e record storici non sono stati ricostruiti. Le tappe di questa pagina sono placeholder visuali.</p></div>${link('records','Records / Honours')}</section>`}
function moodboard(){return `<section class="wrap">${head('SYSTEM MOODBOARD / PROPOSAL 01','The Living Hall.','Greatness is earned. Arena × Gallery.')}<div class="swatches">${[['Obsidian','#0D0D10'],['Deep Plum','#261923'],['Burgundy','#44232D'],['Porcelain','#F2EFE8'],['Ivory','#E6DED0'],['Platinum','#C2C2C0'],['Champagne','#C6A870'],['Bronze','#8A7050'],['Signal Red','#BD454A'],['Active Green','#43886B']].map(([n,c],i)=>`<div class="swatch" style="background:${c};color:${[0,1,2,7,8,9].includes(i)?'#fff':'#0d0d10'}">${n}<br>${c}</div>`).join('')}</div></section><section class="arena"><div class="wrap"><span class="eyebrow">TYPOGRAPHY / NAME × NUMBER × STORY</span><h2>THE PORTRAIT</h2><div class="big">9.12</div><p class="statement">Performance worth remembering.</p><p>DM Sans / Barlow Condensed / Playfair Display. Pairing esplorativo, non definitivo.</p></div></section><section class="wrap"><h2>Objects of distinction.</h2><div class="grid2"><div><h3>Arena</h3><p>Score immediato, struttura platinum, contrasto sportivo. Sistemi precisi e controlli leggibili.</p></div><div><h3>Gallery</h3><p>Porcelain, ritratto ampio, numero dominante e contesto. Champagne soltanto sulla prova.</p></div></div><p class="footnote">Ritratti dimostrativi riutilizzati dagli asset di esplorazione del repository IMC; non sono fotografie verificate di iscritti GW005.</p>${link('home','Esplora il sistema')}</section>`}
function render(){const aliases={scores:'results',calendar:'schedule',reports:'match',clubs:'club'};let r=location.hash.slice(1).split('?')[0]||'home';r=aliases[r]||r;if(!routes[r])r='home';document.title=routes[r]+' · Hall Of Famers · GW005';root.innerHTML=`<header class="top"><a class="brand" href="#home"><span class="imc">IMC</span><span>HALL OF FAMERS<small>GW005 / THE LIVING HALL</small></span></a><nav class="topnav" aria-label="Principale">${['home','results','standings','managers','records'].map(k=>`<a href="#${k}" ${k===r?'aria-current="page"':''}>${routes[k]}</a>`).join('')}</nav><button class="menu" aria-expanded="false" aria-controls="allnav">Menu +</button></header><nav id="allnav" class="allnav" aria-label="Tutte le pagine" hidden>${Object.entries(routes).map(([k,v])=>`<a href="#${k}" ${k===r?'aria-current="page"':''}>${v}</a>`).join('')}</nav><div class="notice">VISUAL DESIGN EXPLORATION 01 · Dati dimostrativi marcati DEMO · Risultati: campione verificato</div><main id="content" tabindex="-1" class="reveal">${({home,competitions,results,schedule,match,standings,managers:()=>people('manager'),manager:()=>profile('manager'),players:()=>people('player'),player:()=>profile('player'),club,records,transfers,archive,moodboard})[r]()}</main><footer class="footer"><div>IMC / GW005<br><p>HALL OF FAMERS · GREATNESS IS EARNED.</p></div><div>${link('moodboard','System Moodboard 01')}<p>Esplorazione visuale · 10.09.2026</p></div></footer>`;
document.querySelector('.menu').onclick=e=>{const open=e.currentTarget.getAttribute('aria-expanded')!=='true';e.currentTarget.setAttribute('aria-expanded',String(open));e.currentTarget.textContent=open?'Chiudi −':'Menu +';document.getElementById('allnav').hidden=!open};
document.getElementById('division')?.addEventListener('change',e=>document.getElementById('results-list').innerHTML=real.filter(x=>e.target.value==='all'||x.division===e.target.value).map(score).join(''));
document.getElementById('search')?.addEventListener('input',e=>document.querySelectorAll('[data-person]').forEach(x=>x.hidden=!x.dataset.person.includes(e.target.value.toLowerCase())));
document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-profile]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.getElementById('profile-detail').innerHTML=b.dataset.profile==='legacy'?legacyDetail():arenaDetail(r==='manager')});window.scrollTo(0,0)}
window.addEventListener('hashchange',()=>{render();document.getElementById('content').focus({preventScroll:true})});render();
})();
