<?php
declare(strict_types=1);

function mr_json(mixed $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
function mr_sha(mixed $v):string{return hash('sha256',is_string($v)?$v:mr_json($v));}
function mr_date(mixed $v):string{$s=trim((string)$v);$d=DateTimeImmutable::createFromFormat('!Y-m-d',$s);if(!$d||$d->format('Y-m-d')!==$s)ingestion_fail('matchDate invalid.');return $s;}
function mr_side(mixed $v):?string{$s=strtoupper(trim((string)$v));return in_array($s,['HOME','AWAY'],true)?$s:null;}
function mr_type(mixed $v):?string{$s=strtolower(trim((string)$v));return in_array($s,['club','national'],true)?$s:null;}
function mr_page_type(mysqli $db):int{$code='MATCH_REPORT';$q=$db->prepare("INSERT INTO gw_source_page_types(function_description,page_code,page_name,scope_status,url_pattern) VALUES('Soccer Manager Match Report','MATCH_REPORT','Match Report','ACTIVE',NULL) ON DUPLICATE KEY UPDATE page_type_id=LAST_INSERT_ID(page_type_id)");$q->execute();$id=(int)$db->insert_id;$q->close();if($id<1){$r=$db->query("SELECT page_type_id FROM gw_source_page_types WHERE page_code='MATCH_REPORT'")->fetch_assoc();$id=(int)$r['page_type_id'];}return $id;}
function mr_context(mysqli $db,array $b):array{$gw=ingestion_world($b['game_world_id']??null);$season=isset($b['imc_season'])?ingestion_uint($b['imc_season'],false):ingestion_current_imc_season($db,$gw);return ingestion_context($db,$gw,$season);}
function mr_assignments(string $gw,?string $start=null,?string $end=null):array{$core=smm_db();$sql='SELECT a.id AS assignment_id,a.manager_id,a.club_id AS team_id,a.national_team_id AS nation_id,a.assignment_type,a.start_date,a.end_date,m.sm_manager_id,NULL AS sm_username FROM `IMC Manager Assignment Global` a LEFT JOIN `IMC Manager Codex Global` m ON m.manager_id=a.manager_id WHERE a.game_world_id=?';$params=[$gw];if($start!==null){$sql.=' AND (a.end_date IS NULL OR a.end_date>=?)';$params[]=$start;}if($end!==null){$sql.=' AND a.start_date<=?';$params[]=$end;}$q=$core->prepare($sql.' ORDER BY a.start_date,a.assignment_id');$q->execute($params);$rows=$q->get_result()->fetch_all(MYSQLI_ASSOC);$q->close();return array_map(static fn($r)=>['assignmentId'=>(int)$r['assignment_id'],'managerId'=>$r['manager_id'],'smManagerId'=>$r['sm_manager_id']===null?null:(int)$r['sm_manager_id'],'smWorldClubId'=>$r['team_id']===null?null:(int)$r['team_id'],'nationId'=>$r['nation_id']===null?null:(int)$r['nation_id'],'assignmentType'=>$r['assignment_type'],'startDate'=>$r['start_date'],'endDate'=>$r['end_date'],'smUsername'=>$r['sm_username']],$rows);}
function mr_setup(mysqli $db,array $b):never{$ctx=mr_context($db,$b);$a=mr_assignments($ctx['game_world_id'],$ctx['start_date'],$ctx['end_date']);ingestion_reply(['ok'=>true,'type'=>'match_report','game_world_id'=>$ctx['game_world_id'],'gameWorldType'=>$ctx['game_world_type'],'imcSeason'=>$ctx['imc_season'],'imc_season'=>$ctx['imc_season'],'sm_game_world_id'=>$ctx['sm_game_world_id'],'soccer_manager_season'=>$ctx['soccer_manager_season'],'sm_season_id'=>$ctx['sm_season_id'],'activeAssignments'=>$a]);}
function mr_worlds():never{ingestion_reply(['ok'=>true,'type'=>'match_report','worlds'=>['GW001','GW002','GW003','GW004','GW005','GW006','GW007','GW008','GW009']]);}
function mr_result_payloads(mysqli $db,string $gw,array $ids):array{$wanted=array_fill_keys(array_map('strval',$ids),true);$found=[];$q=$db->prepare("SELECT p.payload_json FROM gw_source_payloads p JOIN gw_source_captures c ON c.capture_id=p.capture_id WHERE c.game_world_id=? AND p.payload_type='RESULTS_BATCH' ORDER BY p.source_payload_id DESC");$q->bind_param('s',$gw);$q->execute();$rs=$q->get_result();while($row=$rs->fetch_assoc()){try{$b=json_decode((string)$row['payload_json'],true,64,JSON_THROW_ON_ERROR);}catch(Throwable){continue;}foreach(($b['items']??[]) as $item){$id=(string)($item['fixtureId']??'');if(isset($wanted[$id])&&!isset($found[$id]))$found[$id]=$item;}if(count($found)===count($wanted))break;}$q->close();return $found;}
function mr_probe_results(mysqli $db,array $b):never{$gw=ingestion_world($b['game_world_id']??null);$ids=$b['sm_fixture_ids']??[];if(!is_array($ids)||count($ids)>100)ingestion_fail('sm_fixture_ids invalid.');$ids=array_values(array_unique(array_map(fn($x)=>ingestion_uint($x,false),$ids)));$raw=mr_result_payloads($db,$gw,$ids);$rows=[];$q=$db->prepare('SELECT f.fixture_id,f.home_name,f.away_name,f.home_world_club_id,f.away_world_club_id,f.round_label,f.competition_id,c.competition_type,c.country_code,c.division_value,c.local_competition_id FROM gw_fixtures f LEFT JOIN gw_competitions c ON c.gw_competition_row_id=f.competition_id WHERE f.game_world_id=? AND f.fixture_id=?');foreach($ids as $id){$q->execute([$gw,$id]);$f=$q->get_result()->fetch_assoc();if(!$f&&!isset($raw[(string)$id]))continue;$p=$raw[(string)$id]??[];$homeType=mr_type($p['homeEntityType']??null);$awayType=mr_type($p['awayEntityType']??null);$p+=['homeTeam'=>$f['home_name']??null,'awayTeam'=>$f['away_name']??null,'homeTeamId'=>$f['home_world_club_id']??null,'awayTeamId'=>$f['away_world_club_id']??null];if($homeType===null&&($f['home_world_club_id']??null)!==null)$p['homeEntityType']='club';if($awayType===null&&($f['away_world_club_id']??null)!==null)$p['awayEntityType']='club';$rows[]=['sm_fixture_id'=>$id,'sm_action'=>$p['sm_action']??($f['competition_type']??null),'sm_country'=>$p['sm_country']??($f['country_code']??null),'sm_division'=>$p['sm_division']??($f['division_value']??null),'sm_round_label'=>$p['sm_round_label']??($f['round_label']??null),'competition_key'=>$p['competition_key']??($f['competition_id']??null),'result_payload'=>$p];}$q->close();ingestion_reply(['ok'=>true,'rows'=>$rows]);}
function mr_probe_reports(mysqli $db,array $b):never{$gw=ingestion_world($b['game_world_id']??null);$ids=$b['sm_fixture_ids']??[];if(!is_array($ids)||count($ids)>100)ingestion_fail('sm_fixture_ids invalid.');$rows=[];$q=$db->prepare("SELECT fixture_id FROM gw_match_reports WHERE game_world_id=? AND fixture_id=? LIMIT 1");foreach($ids as $id){$n=ingestion_uint($id,false);$q->execute([$gw,$n]);if($q->get_result()->fetch_assoc())$rows[]=['sm_fixture_id'=>$n,'parser_status'=>'complete'];}$q->close();ingestion_reply(['ok'=>true,'rows'=>$rows]);}
function mr_certified_ids(array $report):array{$result=is_array($report['result']??null)?$report['result']:[];$match=is_array($report['match']??null)?$report['match']:[];$ht=mr_type($result['homeEntityType']??null);$at=mr_type($result['awayEntityType']??null);$hid=$ht==='club'?ingestion_uint($result['homeTeamId']??$match['homeSmClubId']??null):null;$aid=$at==='club'?ingestion_uint($result['awayTeamId']??$match['awaySmClubId']??null):null;return [$hid,$aid,$ht,$at];}
function mr_is_final(mysqli $db,string $gw,int $fixture,array $report):bool{$result=is_array($report['result']??null)?$report['result']:[];$round=mb_strtolower(trim((string)($result['sm_round_label']??'')));$round=preg_replace('/[^a-z]+/','',$round);$action=mb_strtolower(trim((string)($result['sm_action']??'')));if(in_array($round,['final','finale'],true)&&$action!==''&&!in_array($action,['league','lega'],true))return true;$q=$db->prepare('SELECT c.competition_type,f.round_label FROM gw_fixtures f LEFT JOIN gw_competitions c ON c.gw_competition_row_id=f.competition_id WHERE f.game_world_id=? AND f.fixture_id=? LIMIT 1');$q->execute([$gw,$fixture]);$r=$q->get_result()->fetch_assoc();$q->close();if(!$r)return false;$t=mb_strtolower(trim((string)$r['competition_type']));$rl=mb_strtolower(trim((string)$r['round_label']));$rl=preg_replace('/[^a-z]+/','',$rl);return !in_array($t,['league','lega',''],true)&&in_array($rl,['final','finale'],true);}
function mr_managed_on_date(string $gw,string $date,?int $homeClub,?int $awayClub,?int $homeManager,?int $awayManager):bool{$core=smm_db();$q=$core->prepare('SELECT 1 FROM `IMC Manager Assignment Global` a LEFT JOIN `IMC Manager Codex Global` m ON m.manager_id=a.manager_id WHERE a.game_world_id=? AND a.start_date<=? AND (a.end_date IS NULL OR a.end_date>=?) AND ((a.club_id IS NOT NULL AND a.club_id IN (?,?)) OR (m.sm_manager_id IS NOT NULL AND m.sm_manager_id IN (?,?))) LIMIT 1');$q->execute([$gw,$date,$date,$homeClub??0,$awayClub??0,$homeManager??0,$awayManager??0]);$ok=(bool)$q->get_result()->fetch_assoc();$q->close();return $ok;}
function mr_capture(mysqli $db,array $b,array $ctx,int $fixture,array $report):int{$page=mr_page_type($db);$identity=mr_sha(['MATCH_REPORT',$ctx['game_world_id'],$fixture]);$payload=mr_json($b);$sha=mr_sha(['MATCH_REPORT',$ctx['game_world_id'],$fixture]);$raw=is_array($report['raw']??null)?implode("\n",array_filter($report['raw'],'is_string')):'';$name='match_report_'.$ctx['game_world_id'].'_'.$fixture.'.json';$q=$db->prepare("INSERT INTO gw_source_captures(capture_json,capture_status,created_at,full_html,game_world_id,generated_at,page_type_id,parser_version,report_type,sm_game_world_id,source_file_name,source_file_sha256,source_identity_fingerprint) VALUES(?,'complete',NOW(6),?,?,NOW(6),?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE capture_id=LAST_INSERT_ID(capture_id),capture_json=VALUES(capture_json),full_html=VALUES(full_html),parser_version=VALUES(parser_version)");$q->execute([$payload,$raw,$ctx['game_world_id'],$page,$report['version']??null,'MATCH_REPORT',$ctx['sm_game_world_id'],$name,$sha,$identity]);$id=(int)$db->insert_id;$q->close();return $id;}
function mr_ensure_club(mysqli $db,array $ctx,int $capture,?int $id,?string $name):?int{if($id===null)return null;$q=$db->prepare('INSERT INTO gw_world_clubs(capture_id,club_name,created_at,game_world_id,sm_game_world_id,world_club_id) VALUES(?,?,NOW(6),?,?,?) ON DUPLICATE KEY UPDATE club_name=COALESCE(VALUES(club_name),club_name),capture_id=COALESCE(capture_id,VALUES(capture_id))');$q->execute([$capture,$name,$ctx['game_world_id'],$ctx['sm_game_world_id'],$id]);$q->close();return $id;}
function mr_ensure_player(mysqli $db,array $ctx,int $capture,int $id,?string $name=null):void{$q=$db->prepare('INSERT INTO gw_players(created_at,first_seen_capture_id,game_world_id,last_seen_capture_id,player_id,sm_game_world_id) VALUES(NOW(6),?,?,?,?,?) ON DUPLICATE KEY UPDATE last_seen_capture_id=VALUES(last_seen_capture_id)');$q->execute([$capture,$ctx['game_world_id'],$capture,$id,$ctx['sm_game_world_id']]);$q->close();if($name!==null&&trim($name)!==''){$name=mb_substr(trim($name),0,255);$p=$db->prepare('INSERT INTO gw_player_profile_snapshots(capture_id,created_at,game_world_id,observed_at,player_id,player_name,sm_game_world_id) VALUES(?,NOW(6),?,NOW(6),?,?,?) ON DUPLICATE KEY UPDATE player_name=VALUES(player_name),observed_at=VALUES(observed_at)');$p->execute([$capture,$ctx['game_world_id'],$id,$name,$ctx['sm_game_world_id']]);$p->close();}}
function mr_competition_id(mysqli $db,string $gw,array $ctx,array $report):?int{$result=is_array($report['result']??null)?$report['result']:[];$raw=$result['competition_key']??null;if(is_int($raw)||(is_string($raw)&&ctype_digit($raw))){$id=(int)$raw;if($id>0){$q=$db->prepare('SELECT gw_competition_row_id FROM gw_competitions WHERE game_world_id=? AND gw_competition_row_id=? LIMIT 1');$q->execute([$gw,$id]);$ok=(bool)$q->get_result()->fetch_assoc();$q->close();if($ok)return $id;}}$action=trim((string)($result['sm_action']??''));if($action==='')return null;$safe=static function(mixed $v,int $max):?string{$s=trim((string)($v??''));return $s!==''&&mb_strlen($s)<=$max?$s:null;};$country=$safe($result['sm_country']??null,8);$division=$safe($result['sm_division']??null,32);$compid=$safe($result['sm_compid']??null,64);$round=$safe($result['sm_round_label']??null,255);$identity=['game_world_id'=>$gw,'sm_action'=>$action,'sm_country'=>$country,'sm_division'=>$division,'sm_compid'=>$compid,'sm_round_label'=>$round];$fp=mr_sha($identity);$name=$safe(($report['match']['competition']??null),255);$q=$db->prepare('INSERT INTO gw_competitions(competition_identity_fingerprint,competition_name,competition_type,country_code,created_at,division_value,game_world_id,is_active,local_competition_id,sm_game_world_id) VALUES(?,?,?,?,NOW(6),?,?,1,?,?) ON DUPLICATE KEY UPDATE gw_competition_row_id=LAST_INSERT_ID(gw_competition_row_id),competition_name=COALESCE(VALUES(competition_name),competition_name)');$q->execute([$fp,$name,$action,$country,$division,$gw,$compid,$ctx['sm_game_world_id']]);$id=(int)$db->insert_id;$q->close();return $id>0?$id:null;}
function mr_store(mysqli $db,array $b):never{$ctx=mr_context($db,$b);$gw=$ctx['game_world_id'];$fixture=ingestion_uint($b['sm_fixture_id']??null,false);$date=mr_date($b['matchDate']??null);$report=$b['report']??null;if(!is_array($report))ingestion_fail('report object required.');$match=is_array($report['match']??null)?$report['match']:[];[$homeClub,$awayClub,$homeType,$awayType]=mr_certified_ids($report);$homeManager=ingestion_uint($match['homeManagerSmId']??null);$awayManager=ingestion_uint($match['awayManagerSmId']??null);$isGold=in_array($gw,['GW002','GW003','GW007','GW008'],true);$managed=$isGold?mr_managed_on_date($gw,$date,$homeClub,$awayClub,$homeManager,$awayManager):true;$final=$isGold?mr_is_final($db,$gw,$fixture,$report):false;if($isGold&&!$managed&&!$final)ingestion_reply(['ok'=>true,'stored'=>false,'status'=>'ineligible_gold','eligibility'=>['imc_managed'=>false,'cup_final'=>false]]);
$db->begin_transaction();try{$capture=mr_capture($db,$b,$ctx,$fixture,$report);$homeClub=mr_ensure_club($db,$ctx,$capture,$homeClub,$match['homeTeam']??null);$awayClub=mr_ensure_club($db,$ctx,$capture,$awayClub,$match['awayTeam']??null);$competitionId=mr_competition_id($db,$gw,$ctx,$report);$result=is_array($report['result']??null)?$report['result']:[];$fq=$db->prepare("INSERT INTO gw_fixtures(away_name,away_world_club_id,capture_id,competition_id,created_at,date,fixture_id,game_world_id,gw_season_row_id,home_name,home_world_club_id,imc_season,round_label,sm_game_world_id,sm_season_id,soccer_manager_season,status,attendance,competition_name,venue_name) VALUES(?,?,?,?,NOW(6),?,?,?,?,?,?,?,?,?,?,?,'played',?,?,?) ON DUPLICATE KEY UPDATE fixture_row_id=LAST_INSERT_ID(fixture_row_id),attendance=COALESCE(VALUES(attendance),attendance),competition_id=COALESCE(competition_id,VALUES(competition_id)),competition_name=COALESCE(VALUES(competition_name),competition_name),round_label=COALESCE(round_label,VALUES(round_label)),venue_name=COALESCE(VALUES(venue_name),venue_name),home_world_club_id=COALESCE(home_world_club_id,VALUES(home_world_club_id)),away_world_club_id=COALESCE(away_world_club_id,VALUES(away_world_club_id))");$fq->execute([$match['awayTeam']??null,$awayClub,$capture,$competitionId,$date,$fixture,$gw,$ctx['gw_season_row_id'],$match['homeTeam']??null,$homeClub,$ctx['imc_season'],$result['sm_round_label']??null,$ctx['sm_game_world_id'],$ctx['sm_season_id'],$ctx['soccer_manager_season'],$match['attendance']??null,$match['competition']??null,$match['stadium']??null]);$fq->close();
foreach([[$homeManager,$match['homeManager']??null],[$awayManager,$match['awayManager']??null]] as [$mid,$name])if($mid!==null&&$name){$uq=$db->prepare('INSERT INTO gw_sm_users(created_at,sm_manager_id,sm_username) VALUES(NOW(6),?,?) ON DUPLICATE KEY UPDATE sm_username=VALUES(sm_username)');$uq->execute([$mid,$name]);$uq->close();}
$rawHtml=is_array($report['raw']??null)?implode("\n",array_filter($report['raw'],'is_string')):null;$rq=$db->prepare('INSERT INTO gw_match_reports(away_sm_manager_id,capture_id,created_at,fixture_id,game_world_id,home_sm_manager_id,raw_report_html,sm_game_world_id) VALUES(?,?,NOW(6),?,?,?,?,?) ON DUPLICATE KEY UPDATE match_report_id=LAST_INSERT_ID(match_report_id),away_sm_manager_id=VALUES(away_sm_manager_id),home_sm_manager_id=VALUES(home_sm_manager_id),raw_report_html=VALUES(raw_report_html)');$rq->execute([$awayManager,$capture,$fixture,$gw,$homeManager,$rawHtml,$ctx['sm_game_world_id']]);$reportId=(int)$db->insert_id;$rq->close();
$stats=is_array($report['teamStats']??null)?$report['teamStats']:[];foreach(['HOME'=>'home','AWAY'=>'away'] as $side=>$key){$s=is_array($stats[$key]??null)?$stats[$key]:[];$team=$side==='HOME'?$homeClub:$awayClub;$q=$db->prepare('INSERT INTO gw_match_team_stats(capture_id,corners,created_at,fouls,game_world_id,match_report_id,offside,possession,shots,shots_on_target,side,sm_game_world_id,world_team_id) VALUES(?,?,NOW(6),NULL,?,?,NULL,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE corners=VALUES(corners),possession=VALUES(possession),shots=VALUES(shots),shots_on_target=VALUES(shots_on_target),world_team_id=VALUES(world_team_id)');$q->execute([$capture,$s['corners']??null,$gw,$reportId,$s['possession']??null,$s['totalShots']??null,$s['shotsOnTarget']??null,$side,$ctx['sm_game_world_id'],$team]);$q->close();}
$players=is_array($report['players']??null)?$report['players']:[];foreach(['HOME'=>'home','AWAY'=>'away'] as $side=>$key){$team=$side==='HOME'?$homeClub:$awayClub;$formation=null;foreach(($report['tactics']??[]) as $t)if(($t['side']??null)===$key&&(int)($t['minute']??-1)===0)$formation=$t['formation']??null;$sidePlayers=array_values(array_filter($players,fn($p)=>is_array($p)&&($p['side']??null)===$key));$lq=$db->prepare('INSERT INTO gw_match_lineups(created_at,formation,game_world_id,lineups,match_report_id,raw_lineup_html,side,sm_game_world_id,world_team_id) VALUES(NOW(6),?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE match_lineup_id=LAST_INSERT_ID(match_lineup_id),formation=VALUES(formation),lineups=VALUES(lineups),raw_lineup_html=VALUES(raw_lineup_html),world_team_id=VALUES(world_team_id)');$lq->execute([$formation,$gw,mr_json($sidePlayers),$reportId,$report['raw']['lineupsHtml']??null,$side,$ctx['sm_game_world_id'],$team]);$lineupId=(int)$db->insert_id;$lq->close();foreach($sidePlayers as $p){$pid=ingestion_uint($p['smPlayerId']??null);if($pid!==null)mr_ensure_player($db,$ctx,$capture,$pid,$p['playerName']??null);$fp=mr_sha([$gw,$fixture,$side,$p['lineupSlot']??null,$pid,$p['isStarter']??null]);$pq=$db->prepare('INSERT INTO gw_match_lineup_players(created_at,game_world_id,is_substitute,lineup_player_fingerprint,match_lineup_id,player_id,position_label,rating_raw,slot_order,sm_game_world_id) VALUES(NOW(6),?,?,?,?,?,NULL,?,?,?) ON DUPLICATE KEY UPDATE is_substitute=VALUES(is_substitute),rating_raw=VALUES(rating_raw),slot_order=VALUES(slot_order)');$pq->execute([$gw,empty($p['isStarter'])?1:0,$fp,$lineupId,$pid,$p['rating']===null?null:(string)$p['rating'],$p['lineupSlot']??null,$ctx['sm_game_world_id']]);$pq->close();}}
$events=is_array($report['events']??null)?$report['events']:[];foreach($events as $i=>$e){if(!is_array($e))continue;$pid=ingestion_uint($e['primarySmPlayerId']??null);$rel=ingestion_uint($e['secondarySmPlayerId']??null);if($pid!==null)mr_ensure_player($db,$ctx,$capture,$pid,$e['primaryPlayerName']??null);if($rel!==null)mr_ensure_player($db,$ctx,$capture,$rel,$e['secondaryPlayerName']??null);$side=mr_side($e['side']??null);$team=$side==='HOME'?$homeClub:($side==='AWAY'?$awayClub:null);$fp=mr_sha([$gw,$fixture,$i,$e['eventType']??null,$e['minute']??null,$pid,$side]);$meta=is_array($e['metadata']??null)?$e['metadata']:[];$goalType=!empty($meta['penalty'])?'penalty':null;$eq=$db->prepare('INSERT INTO gw_match_events(created_at,event_order,event_type,game_world_id,goal_minute,goal_type,match_event_fingerprint,match_report_id,minute_raw,player_id,raw_event_html,related_player_id,sm_game_world_id,substitutions,world_team_id) VALUES(NOW(6),?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE event_type=VALUES(event_type),goal_minute=VALUES(goal_minute),goal_type=VALUES(goal_type),player_id=VALUES(player_id),related_player_id=VALUES(related_player_id),raw_event_html=VALUES(raw_event_html),world_team_id=VALUES(world_team_id)');$eq->execute([$i+1,$e['eventType']??'unknown',$gw,$e['minute']??null,$goalType,$fp,$reportId,$e['minute']===null?null:(string)$e['minute'],$pid,$meta['rawHtml']??($e['rawText']??null),$rel,$ctx['sm_game_world_id'],($e['eventType']??'')==='substitution'?mr_json($e):null,$team]);$eq->close();}
foreach(($report['commentary']??[]) as $i=>$c){if(!is_array($c))continue;$cq=$db->prepare('INSERT INTO gw_match_commentary(commentary_event_minute,commentary_text,created_at,event_order,game_world_id,match_report_id,raw_event_html,sm_game_world_id) VALUES(?,?,NOW(6),?,?,?,?,?) ON DUPLICATE KEY UPDATE commentary_event_minute=VALUES(commentary_event_minute),commentary_text=VALUES(commentary_text),raw_event_html=VALUES(raw_event_html)');$text=mb_substr((string)($c['rawText']??''),0,255);$cq->execute([$c['minute']??null,$text,$i+1,$gw,$reportId,$c['metadata']['rawHtml']??null,$ctx['sm_game_world_id']]);$cq->close();}
foreach(($report['tactics']??[]) as $t){if(!is_array($t))continue;$side=mr_side($t['side']??null);$minute=isset($t['minute'])?(int)$t['minute']:null;$fp=mr_sha([$gw,$fixture,$side,$minute]);$tq=$db->prepare('INSERT INTO gw_match_tactics_snapshots(created_at,formation_name,game_world_id,match_report_id,match_tactics_fingerprint,minute_from,raw_tactics_html,side,sm_game_world_id,tactics_snapshot) VALUES(NOW(6),?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE formation_name=VALUES(formation_name),raw_tactics_html=VALUES(raw_tactics_html),tactics_snapshot=VALUES(tactics_snapshot)');$tq->execute([$t['formation']??null,$gw,$reportId,$fp,$minute,$t['rawText']??null,$side,$ctx['sm_game_world_id'],mr_json($t['tactics']??[])]);$tq->close();}
$payload=mr_json($b);$ph=mr_sha($payload);$pf=mr_sha([$capture,'MATCH_REPORT_STRUCTURED']);$pq=$db->prepare("INSERT INTO gw_source_payloads(capture_id,created_at,payload_fingerprint,payload_hash,payload_json,payload_key,payload_text,payload_type) VALUES(?,NOW(6),?,?,?,?,?,'MATCH_REPORT_STRUCTURED') ON DUPLICATE KEY UPDATE payload_hash=VALUES(payload_hash),payload_json=VALUES(payload_json),payload_text=VALUES(payload_text)");$pq->execute([$capture,$pf,$ph,$payload,$gw.'|'.$fixture,$payload]);$pq->close();$db->commit();ingestion_reply(['ok'=>true,'stored'=>true,'status'=>'complete','match_report_id'=>$reportId,'capture_id'=>$capture,'eligibility'=>['imc_managed'=>$managed,'cup_final'=>$final]]);}catch(Throwable $e){$db->rollback();ingestion_fail('MATCH REPORT transaction failed: '.$e->getMessage(),500);}}
function mr_audit_rows(mysqli $db,string $sql,array $params=[]):array{$q=$db->prepare($sql);$q->execute($params);$rows=$q->get_result()->fetch_all(MYSQLI_ASSOC);$q->close();return $rows;}
function mr_audit_row(mysqli $db,string $sql,array $params=[]):array{return mr_audit_rows($db,$sql,$params)[0]??[];}
function mr_audit_ints(array $row):array{foreach($row as $k=>$v)$row[$k]=$v===null?null:(int)$v;return $row;}
function mr_audit_identifier(string $name):string{return '`'.str_replace('`','``',$name).'`';}
function mr_audit_columns(mysqli $db,string $table,string $from,array $params):array{
    $columns=mr_audit_rows($db,'SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? ORDER BY ORDINAL_POSITION',[$table]);
    if(!$columns)return ['rows'=>0,'columns'=>[]];
    $parts=['COUNT(*) AS __rows'];foreach($columns as $column){$name=(string)$column['COLUMN_NAME'];$id=mr_audit_identifier($name);$parts[]="COALESCE(SUM(t.$id IS NULL),0) AS ".mr_audit_identifier('null__'.$name);$parts[]="COALESCE(SUM(t.$id IS NOT NULL),0) AS ".mr_audit_identifier('valued__'.$name);}
    $raw=mr_audit_row($db,'SELECT '.implode(',',$parts).' FROM '.$from,$params);$out=['rows'=>(int)($raw['__rows']??0),'columns'=>[]];
    foreach($columns as $column){$name=(string)$column['COLUMN_NAME'];$out['columns'][$name]=['valued'=>(int)($raw['valued__'.$name]??0),'null'=>(int)($raw['null__'.$name]??0)];}return $out;
}
function mr_audit_duplicate(mysqli $db,string $inner,array $params):array{$r=mr_audit_row($db,'SELECT COUNT(*) duplicate_groups,COALESCE(SUM(n-1),0) duplicate_rows FROM ('.$inner.') d',$params);return mr_audit_ints($r+['duplicate_groups'=>0,'duplicate_rows'=>0]);}
function mr_audit_constraints(mysqli $db,array $tables):array{
    $quoted=implode(',',array_map(fn($v)=>"'".$db->real_escape_string($v)."'",$tables));
    $declared=mr_audit_rows($db,"SELECT TABLE_NAME table_name,CONSTRAINT_NAME constraint_name,CONSTRAINT_TYPE constraint_type FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME IN ($quoted) ORDER BY TABLE_NAME,CONSTRAINT_TYPE,CONSTRAINT_NAME");
    $fkRows=mr_audit_rows($db,"SELECT CONSTRAINT_NAME constraint_name,TABLE_NAME table_name,COLUMN_NAME column_name,REFERENCED_TABLE_NAME referenced_table_name,REFERENCED_COLUMN_NAME referenced_column_name,ORDINAL_POSITION ordinal_position FROM information_schema.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA=DATABASE() AND REFERENCED_TABLE_NAME IS NOT NULL AND TABLE_NAME IN ($quoted) ORDER BY TABLE_NAME,CONSTRAINT_NAME,ORDINAL_POSITION");
    $groups=[];foreach($fkRows as $r){$key=$r['table_name'].'|'.$r['constraint_name'];$groups[$key]['table_name']=$r['table_name'];$groups[$key]['constraint_name']=$r['constraint_name'];$groups[$key]['referenced_table_name']=$r['referenced_table_name'];$groups[$key]['pairs'][]=[$r['column_name'],$r['referenced_column_name']];}
    $checks=[];foreach($groups as $g){$conditions=[];$notNull=[];foreach($g['pairs'] as [$child,$parent]){$conditions[]='p.'.mr_audit_identifier($parent).'=c.'.mr_audit_identifier($child);$notNull[]='c.'.mr_audit_identifier($child).' IS NOT NULL';}$sql='SELECT COUNT(*) violations FROM '.mr_audit_identifier($g['table_name']).' c LEFT JOIN '.mr_audit_identifier($g['referenced_table_name']).' p ON '.implode(' AND ',$conditions).' WHERE ('.implode(' AND ',$notNull).') AND p.'.mr_audit_identifier($g['pairs'][0][1]).' IS NULL';$r=mr_audit_row($db,$sql);$checks[]=['table_name'=>$g['table_name'],'constraint_name'=>$g['constraint_name'],'referenced_table_name'=>$g['referenced_table_name'],'violations'=>(int)($r['violations']??0)];}
    $summary=['PRIMARY KEY'=>0,'UNIQUE'=>0,'FOREIGN KEY'=>0];foreach($declared as $r)if(isset($summary[$r['constraint_type']]))$summary[$r['constraint_type']]++;
    return ['scope'=>'entire_routed_database','summary'=>$summary,'declared'=>$declared,'foreign_key_checks'=>$checks,'foreign_key_violations'=>array_sum(array_column($checks,'violations'))];
}
function mr_audit_gold_eligibility(mysqli $db,string $gw):array{
    $isGold=in_array($gw,['GW002','GW003','GW007','GW008'],true);if(!$isGold)return ['applicable'=>false,'rule'=>'GOLD only','persisted_reports'=>0,'violations'=>0,'violation_fixture_ids'=>[]];
    $reports=mr_audit_rows($db,'SELECT r.fixture_id,r.home_sm_manager_id,r.away_sm_manager_id,f.date,f.home_world_club_id,f.away_world_club_id,f.round_label,c.competition_type FROM gw_match_reports r JOIN gw_fixtures f ON f.game_world_id=r.game_world_id AND f.fixture_id=r.fixture_id LEFT JOIN gw_competitions c ON c.gw_competition_row_id=f.competition_id WHERE r.game_world_id=? ORDER BY r.fixture_id',[$gw]);
    $assignments=mr_assignments($gw);$managedCount=0;$finalCount=0;$bothCount=0;$violations=[];
    foreach($reports as $r){$date=(string)$r['date'];$managed=false;foreach($assignments as $a){if((string)$a['startDate']>$date||($a['endDate']!==null&&(string)$a['endDate']<$date))continue;$club=$a['smWorldClubId'];$manager=$a['smManagerId'];if(($club!==null&&in_array((int)$club,[(int)($r['home_world_club_id']??0),(int)($r['away_world_club_id']??0)],true))||($manager!==null&&in_array((int)$manager,[(int)($r['home_sm_manager_id']??0),(int)($r['away_sm_manager_id']??0)],true))){$managed=true;break;}}
        $round=preg_replace('/[^a-z]+/','',mb_strtolower(trim((string)$r['round_label'])));$type=mb_strtolower(trim((string)$r['competition_type']));$final=in_array($round,['final','finale'],true)&&!in_array($type,['','league','lega'],true);if($managed)$managedCount++;if($final)$finalCount++;if($managed&&$final)$bothCount++;if(!$managed&&!$final)$violations[]=(int)$r['fixture_id'];
    }
    return ['applicable'=>true,'rule'=>'IMC-managed on fixture date OR certified cup final','persisted_reports'=>count($reports),'imc_managed'=>$managedCount,'cup_final'=>$finalCount,'both'=>$bothCount,'violations'=>count($violations),'violation_fixture_ids'=>array_slice($violations,0,200),'violation_list_truncated'=>count($violations)>200];
}
function mr_audit(mysqli $db,array $b):never{
    $gw=ingestion_world($b['game_world_id']??null);$database=(string)($db->query('SELECT DATABASE() db')->fetch_assoc()['db']??'');$expected=ingestion_storage_key($gw)==='gold'?'Sql1956795_2':'Sql1956795_3';if($database!==$expected)ingestion_fail('Database routing mismatch.',500);
    $scopes=[
        'gw_source_captures'=>["gw_source_captures t WHERE t.game_world_id=? AND t.report_type='MATCH_REPORT'",[$gw]],
        'gw_source_payloads'=>["gw_source_payloads t JOIN gw_source_captures c ON c.capture_id=t.capture_id WHERE c.game_world_id=? AND t.payload_type='MATCH_REPORT_STRUCTURED'",[$gw]],
        'gw_match_reports'=>['gw_match_reports t WHERE t.game_world_id=?',[$gw]],
        'gw_fixtures'=>['gw_fixtures t WHERE t.game_world_id=? AND EXISTS(SELECT 1 FROM gw_match_reports r WHERE r.game_world_id=t.game_world_id AND r.fixture_id=t.fixture_id)',[$gw]],
        'gw_match_team_stats'=>['gw_match_team_stats t WHERE t.game_world_id=?',[$gw]],
        'gw_match_lineups'=>['gw_match_lineups t WHERE t.game_world_id=?',[$gw]],
        'gw_match_lineup_players'=>['gw_match_lineup_players t WHERE t.game_world_id=?',[$gw]],
        'gw_match_events'=>['gw_match_events t WHERE t.game_world_id=?',[$gw]],
        'gw_match_commentary'=>['gw_match_commentary t WHERE t.game_world_id=?',[$gw]],
        'gw_match_tactics_snapshots'=>['gw_match_tactics_snapshots t WHERE t.game_world_id=?',[$gw]],
        'gw_players'=>["gw_players t WHERE t.game_world_id=? AND (EXISTS(SELECT 1 FROM gw_source_captures c WHERE c.capture_id=t.first_seen_capture_id AND c.report_type='MATCH_REPORT') OR EXISTS(SELECT 1 FROM gw_source_captures c WHERE c.capture_id=t.last_seen_capture_id AND c.report_type='MATCH_REPORT'))",[$gw]],
        'gw_player_profile_snapshots'=>["gw_player_profile_snapshots t JOIN gw_source_captures c ON c.capture_id=t.capture_id WHERE t.game_world_id=? AND c.report_type='MATCH_REPORT'",[$gw]],
        'gw_world_clubs'=>["gw_world_clubs t JOIN gw_source_captures c ON c.capture_id=t.capture_id WHERE t.game_world_id=? AND c.report_type='MATCH_REPORT'",[$gw]],
        'gw_sm_users'=>['gw_sm_users t WHERE EXISTS(SELECT 1 FROM gw_match_reports r WHERE r.game_world_id=? AND (r.home_sm_manager_id=t.sm_manager_id OR r.away_sm_manager_id=t.sm_manager_id))',[$gw]],
        'gw_competitions'=>['gw_competitions t WHERE t.game_world_id=? AND EXISTS(SELECT 1 FROM gw_fixtures f JOIN gw_match_reports r ON r.game_world_id=f.game_world_id AND r.fixture_id=f.fixture_id WHERE f.competition_id=t.gw_competition_row_id)',[$gw]],
    ];
    $datasets=[];foreach($scopes as $table=>[$from,$params])$datasets[$table]=mr_audit_columns($db,$table,$from,$params);
    $duplicates=[
        'captures_identity'=>mr_audit_duplicate($db,"SELECT COUNT(*) n FROM gw_source_captures WHERE game_world_id=? AND report_type='MATCH_REPORT' GROUP BY source_identity_fingerprint HAVING COUNT(*)>1",[$gw]),
        'payloads_identity'=>mr_audit_duplicate($db,"SELECT COUNT(*) n FROM gw_source_payloads p JOIN gw_source_captures c ON c.capture_id=p.capture_id WHERE c.game_world_id=? AND p.payload_type='MATCH_REPORT_STRUCTURED' GROUP BY p.capture_id,p.payload_fingerprint HAVING COUNT(*)>1",[$gw]),
        'reports_fixture'=>mr_audit_duplicate($db,'SELECT COUNT(*) n FROM gw_match_reports WHERE game_world_id=? GROUP BY fixture_id HAVING COUNT(*)>1',[$gw]),
        'team_stats_side'=>mr_audit_duplicate($db,'SELECT COUNT(*) n FROM gw_match_team_stats WHERE game_world_id=? GROUP BY match_report_id,side HAVING COUNT(*)>1',[$gw]),
        'lineups_side'=>mr_audit_duplicate($db,'SELECT COUNT(*) n FROM gw_match_lineups WHERE game_world_id=? GROUP BY match_report_id,side HAVING COUNT(*)>1',[$gw]),
        'lineup_players_identity'=>mr_audit_duplicate($db,'SELECT COUNT(*) n FROM gw_match_lineup_players WHERE game_world_id=? GROUP BY lineup_player_fingerprint HAVING COUNT(*)>1',[$gw]),
        'events_identity'=>mr_audit_duplicate($db,'SELECT COUNT(*) n FROM gw_match_events WHERE game_world_id=? GROUP BY match_event_fingerprint HAVING COUNT(*)>1',[$gw]),
        'commentary_order'=>mr_audit_duplicate($db,'SELECT COUNT(*) n FROM gw_match_commentary WHERE game_world_id=? GROUP BY match_report_id,event_order HAVING COUNT(*)>1',[$gw]),
        'tactics_identity'=>mr_audit_duplicate($db,'SELECT COUNT(*) n FROM gw_match_tactics_snapshots WHERE game_world_id=? GROUP BY match_tactics_fingerprint HAVING COUNT(*)>1',[$gw]),
    ];
    $linkage=mr_audit_ints(mr_audit_row($db,"SELECT COUNT(*) structured_reports,COUNT(DISTINCT r.fixture_id) distinct_fixture_ids,COALESCE(SUM(f.fixture_id IS NULL),0) missing_fixtures,COALESCE(SUM(fr.fixture_id IS NOT NULL),0) with_results,COALESCE(SUM(fr.fixture_id IS NULL),0) without_results,COALESCE(SUM(UPPER(COALESCE(src.report_type,''))='RESULTS'),0) fixture_origin_results,COALESCE(SUM(UPPER(COALESCE(src.report_type,''))='SCHEDULE'),0) fixture_origin_schedule,COALESCE(SUM(UPPER(COALESCE(src.report_type,''))='MATCH_REPORT'),0) fixture_created_by_match_report FROM gw_match_reports r LEFT JOIN gw_fixtures f ON f.game_world_id=r.game_world_id AND f.fixture_id=r.fixture_id LEFT JOIN gw_fixture_results fr ON fr.game_world_id=r.game_world_id AND fr.fixture_id=r.fixture_id LEFT JOIN gw_source_captures src ON src.capture_id=f.capture_id WHERE r.game_world_id=?",[$gw]));
    $evidence=mr_audit_ints(mr_audit_row($db,"SELECT COALESCE(SUM(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(c.capture_json,'$.sm_fixture_id')),'null') IS NOT NULL AND CAST(JSON_UNQUOTE(JSON_EXTRACT(c.capture_json,'$.sm_fixture_id')) AS UNSIGNED)<>r.fixture_id),0) fixture_id_payload_mismatches,COALESCE(SUM(LOWER(JSON_UNQUOTE(JSON_EXTRACT(c.capture_json,'$.report.result.homeEntityType')))='national' AND f.home_world_club_id IS NOT NULL),0) national_home_in_world_club,COALESCE(SUM(LOWER(JSON_UNQUOTE(JSON_EXTRACT(c.capture_json,'$.report.result.awayEntityType')))='national' AND f.away_world_club_id IS NOT NULL),0) national_away_in_world_club,COALESCE(SUM(LOWER(JSON_UNQUOTE(JSON_EXTRACT(c.capture_json,'$.report.result.homeEntityType')))='club' AND NULLIF(JSON_UNQUOTE(JSON_EXTRACT(c.capture_json,'$.report.result.homeTeamId')),'null') IS NOT NULL AND (f.home_world_club_id IS NULL OR f.home_world_club_id<>CAST(JSON_UNQUOTE(JSON_EXTRACT(c.capture_json,'$.report.result.homeTeamId')) AS UNSIGNED))),0) club_home_id_mismatches,COALESCE(SUM(LOWER(JSON_UNQUOTE(JSON_EXTRACT(c.capture_json,'$.report.result.awayEntityType')))='club' AND NULLIF(JSON_UNQUOTE(JSON_EXTRACT(c.capture_json,'$.report.result.awayTeamId')),'null') IS NOT NULL AND (f.away_world_club_id IS NULL OR f.away_world_club_id<>CAST(JSON_UNQUOTE(JSON_EXTRACT(c.capture_json,'$.report.result.awayTeamId')) AS UNSIGNED))),0) club_away_id_mismatches FROM gw_match_reports r JOIN gw_fixtures f ON f.game_world_id=r.game_world_id AND f.fixture_id=r.fixture_id JOIN gw_source_captures c ON c.capture_id=r.capture_id WHERE r.game_world_id=?",[$gw]));
    $evidence['artificial_id_evidence_mismatches']=$evidence['fixture_id_payload_mismatches']+$evidence['club_home_id_mismatches']+$evidence['club_away_id_mismatches'];$evidence['artificial_ids_detected']=$evidence['artificial_id_evidence_mismatches']>0;
    $seasonRows=mr_audit_rows($db,'SELECT f.imc_season,COUNT(*) structured_reports FROM gw_match_reports r JOIN gw_fixtures f ON f.game_world_id=r.game_world_id AND f.fixture_id=r.fixture_id WHERE r.game_world_id=? GROUP BY f.imc_season ORDER BY f.imc_season',[$gw]);foreach($seasonRows as &$row){$row['imc_season']=$row['imc_season']===null?null:(int)$row['imc_season'];$row['structured_reports']=(int)$row['structured_reports'];}unset($row);
    $issues=mr_audit_ints(mr_audit_row($db,"SELECT COUNT(*) persisted_issues,COALESCE(SUM(LOWER(i.severity) IN ('error','fatal')),0) persisted_errors FROM gw_import_issues i JOIN gw_source_captures c ON c.capture_id=i.capture_id WHERE c.game_world_id=? AND c.report_type='MATCH_REPORT'",[$gw]));
    $rejected=mr_audit_ints(mr_audit_row($db,"SELECT COALESCE(SUM(capture_status<>'complete'),0) persisted_rejected_captures FROM gw_source_captures WHERE game_world_id=? AND report_type='MATCH_REPORT'",[$gw]));
    $auditTables=array_keys($scopes);$constraints=mr_audit_constraints($db,$auditTables);
    ingestion_reply(['ok'=>true,'read_only'=>true,'type'=>'match_report','action'=>'audit_match_report','generated_at'=>gmdate('c'),'game_world_id'=>$gw,'routing'=>['database'=>$database,'family'=>ingestion_storage_key($gw)==='gold'?'multi_league':'single_league'],'game_world_received'=>$datasets['gw_match_reports']['rows']>0,'seasons'=>$seasonRows,'datasets'=>$datasets,'fixture_linkage_and_enrichment'=>$linkage,'duplicates'=>$duplicates,'constraints'=>$constraints,'identity_and_entity_evidence'=>$evidence,'gold_eligibility'=>mr_audit_gold_eligibility($db,$gw),'rejections_and_errors'=>$rejected+$issues+['transport_or_rolled_back_failures_persisted'=>false]]);
}
function match_report_handle(mysqli $db,array $body,string $action):never{if($action==='worlds')mr_worlds();if($action==='audit_match_report')mr_audit($db,$body);if($action==='setup')mr_setup($db,$body);if($action==='probe_reports')mr_probe_reports($db,$body);if($action==='probe_results')mr_probe_results($db,$body);if($action==='validate_match_report'){$ctx=mr_context($db,$body);ingestion_reply(['ok'=>true,'validation'=>'PASS','context'=>$ctx]);}if($action==='store_report')mr_store($db,$body);ingestion_fail('Unknown MATCH REPORT action.',404);}
