(function(){
"use strict";
if(window.IMC_ADMIN)return;

const VERSION="1.0.2";
const WORLDS=[
  ["GW001","Road To History"],["GW002","Gold 558"],["GW003","Gold 557"],["GW004","World League"],["GW005","Hall Of Famers"],
  ["GW006","Master League World"],["GW007","The Four Kingdoms"],["GW008","Gold 1"],["GW009","Kick Off"]
];
let state={container:null,client:null,user:null,page:"home",worldId:"",data:null,newEditor:null};

const clean=v=>String(v==null?"":v).trim();
const esc=v=>clean(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmtDate=v=>{if(!v)return"—";const d=new Date(String(v).slice(0,10)+"T12:00:00");return Number.isNaN(d.getTime())?esc(v):new Intl.DateTimeFormat("it-IT",{day:"2-digit",month:"2-digit",year:"numeric"}).format(d)};
const fmtDateTime=v=>{if(!v)return"Mai";const d=new Date(v);return Number.isNaN(d.getTime())?esc(v):new Intl.DateTimeFormat("it-IT",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)};
async function rpc(action,args){const r=await state.client.rpc("imc_nexus_gateway",{p_action:action,p_args:args||{}});if(r.error)throw r.error;return r.data||{};}
function dispatchExit(){document.dispatchEvent(new CustomEvent("nexus:navigate",{detail:{target:"clubhouse"}}));}
function setStatus(message,type){const n=state.container&&state.container.querySelector("[data-admin-status]");if(!n)return;n.className="nxa-status"+(type?" "+type:"");n.textContent=message||"";}
function worldOptions(){return WORLDS.map(([id,name])=>`<option value="${id}" ${state.worldId===id?"selected":""}>${id} · ${esc(name)}</option>`).join("");}

function shell(content){return `<section class="nxa-shell" data-admin-version="${VERSION}">
  <header class="nxa-head"><button type="button" class="nxa-back" data-admin-exit>‹ NEXUS</button><div><small>PRIVATE SYSTEM AREA</small><h1>ADMIN</h1></div></header>
  <nav class="nxa-tabs" aria-label="Admin"><button type="button" data-admin-page="assignments" class="${state.page==="assignments"?"active":""}">MANAGER</button><button type="button" data-admin-page="users" class="${state.page==="users"?"active":""}">USERS</button><button type="button" data-admin-page="analytics" class="${state.page==="analytics"?"active":""}">ANALYTICS</button></nav>
  <div class="nxa-status" data-admin-status></div>${content}</section>`;}

function home(){return shell(`<main class="nxa-home"><p class="nxa-intro">Area amministrativa Nexus.</p><div class="nxa-grid">
  <button type="button" class="nxa-card" data-admin-page="assignments"><span>♙</span><strong>Manager Assignments</strong><small>Club, nazionali e storico per Game World</small></button>
  <button type="button" class="nxa-card" data-admin-page="users"><span>◉</span><strong>Nexus Users</strong><small>Account, password, accessi e ultima visita</small></button>
  <button type="button" class="nxa-card" data-admin-page="analytics"><span>⌁</span><strong>Weekly Analytics</strong><small>Visite e visitatori unici, in forma anonima</small></button>
</div></main>`);}

function assignmentEntity(a){return a.assignment_type==="club"?clean(a.team_name)||"Club":clean(a.nation_name)||"Nazionale";}
function currentAssignment(assignments,type){return assignments.filter(a=>a.assignment_type===type&&!a.end_date).sort((a,b)=>clean(b.start_date).localeCompare(clean(a.start_date)))[0]||null;}
function targetOptions(type){const rows=type==="club"?(state.data?.teams||[]):(state.data?.nations||[]);return rows.map(x=>`<option value="${esc(type==="club"?x.team_id:x.nation_id)}">${esc(type==="club"?x.team_name:x.nation_name)}</option>`).join("");}
function existingAssignmentRow(a){return `<div class="nxa-assignment-row" data-assignment-id="${esc(a.assignment_id)}"><div class="nxa-assignment-name"><strong>${esc(assignmentEntity(a))}</strong><small>${a.end_date?"STORICO":"ATTIVO"}</small></div><label>INIZIO<input type="date" data-assignment-start value="${esc(a.start_date||"")}"></label><label class="nxa-end-date">FINE<div><input type="date" data-assignment-end value="${esc(a.end_date||"")}"><button type="button" data-clear-assignment-end aria-label="Cancella data di fine">×</button></div></label><button type="button" data-save-assignment>Salva</button></div>`;}
function newAssignmentRow(managerId,type){if(!state.newEditor||state.newEditor.managerId!==managerId||state.newEditor.type!==type)return"";const options=targetOptions(type);return `<div class="nxa-new-assignment" data-new-manager="${esc(managerId)}" data-new-type="${esc(type)}"><label>${type==="club"?"CLUB":"NAZIONALE"}<select data-new-target>${options||'<option value="">Nessuna opzione disponibile</option>'}</select></label><label>INIZIO<input type="date" data-new-start></label><label>FINE<input type="date" data-new-end></label><div><button type="button" class="primary" data-save-new>Salva nuovo incarico</button><button type="button" data-cancel-new>Annulla</button></div></div>`;}
function assignmentSection(manager,type,assignments){const rows=assignments.filter(a=>a.assignment_type===type).sort((a,b)=>clean(b.start_date).localeCompare(clean(a.start_date)));return `<section class="nxa-assignment-section"><div class="nxa-assignment-title"><div><small>${type==="club"?"CLUB":"NAZIONALE"}</small><strong>${rows.length?esc(assignmentEntity(currentAssignment(rows,type)||rows[0])):"Nessun incarico"}</strong></div><button type="button" data-add-assignment="${type}" data-manager-id="${esc(manager.manager_id)}">＋ Aggiungi</button></div>${rows.length?rows.map(existingAssignmentRow).join(""):'<div class="nxa-empty-mini">Nessun incarico registrato.</div>'}${newAssignmentRow(manager.manager_id,type)}</section>`;}
function managerCard(manager){const assignments=(state.data?.assignments||[]).filter(a=>a.manager_id===manager.manager_id);const club=currentAssignment(assignments,"club"),nation=currentAssignment(assignments,"national_team");const summary=[club&&assignmentEntity(club),nation&&assignmentEntity(nation)].filter(Boolean).join(" · ")||"Nessun incarico attivo";return `<details class="nxa-manager" data-manager-search="${esc((manager.full_name+" "+manager.manager_id+" "+summary).toLowerCase())}"><summary><div><strong>${esc(manager.full_name)}</strong><small>${esc(manager.manager_id)}${manager.sm_manager_id?" · SM "+esc(manager.sm_manager_id):""}</small></div><span>${esc(summary)}</span><b>⌄</b></summary><div class="nxa-manager-body">${assignmentSection(manager,"club",assignments)}${assignmentSection(manager,"national_team",assignments)}</div></details>`;}
function assignmentsPage(){const body=state.data?`<div class="nxa-manager-tools"><input type="search" data-manager-filter placeholder="Cerca manager, ID, club o nazionale"><span>${state.data.managers.length} manager</span></div><div class="nxa-manager-list">${state.data.managers.map(managerCard).join("")}</div>`:'<div class="nxa-empty">Seleziona un Game World e apri il pannello.</div>';return shell(`<main class="nxa-page"><div class="nxa-page-title"><small>MANAGER REGISTRY</small><h2>Assignments</h2><p>Scegli il Game World, poi gestisci club e nazionali con data di inizio e fine.</p></div><div class="nxa-world-picker"><select data-world-select><option value="">Seleziona Game World</option>${worldOptions()}</select><button type="button" class="primary" data-load-world>Apri</button></div>${body}</main>`);}
async function loadAssignments(){const select=state.container.querySelector("[data-world-select]");state.worldId=clean(select&&select.value);if(!state.worldId){setStatus("Seleziona un Game World.","error");return;}setStatus("Caricamento Manager Registry…","");try{state.data=await rpc("admin_manager_assignments",{gameWorld:state.worldId});state.newEditor=null;render();}catch(e){setStatus(e.message||"Caricamento non riuscito.","error");}}
async function saveExisting(row){const id=clean(row.getAttribute("data-assignment-id")),start=row.querySelector("[data-assignment-start]").value,end=row.querySelector("[data-assignment-end]").value;if(!start){setStatus("La data di inizio è obbligatoria.","error");return;}setStatus("Salvataggio incarico…","");try{await rpc("admin_assignment_save",{gameWorld:state.worldId,assignmentId:id,startDate:start,endDate:end||null});state.data=await rpc("admin_manager_assignments",{gameWorld:state.worldId});render();setStatus("✓ Modifica salvata.","success");}catch(e){setStatus(e.message||"Salvataggio non riuscito.","error");}}
async function saveNew(row){const managerId=clean(row.getAttribute("data-new-manager")),type=clean(row.getAttribute("data-new-type")),target=row.querySelector("[data-new-target]").value,start=row.querySelector("[data-new-start]").value,end=row.querySelector("[data-new-end]").value;if(!target||!start){setStatus("Seleziona squadra/nazionale e data di inizio.","error");return;}setStatus("Creazione incarico…","");try{await rpc("admin_assignment_save",{gameWorld:state.worldId,managerId,assignmentType:type,targetId:target,startDate:start,endDate:end});state.data=await rpc("admin_manager_assignments",{gameWorld:state.worldId});state.newEditor=null;render();}catch(e){setStatus(e.message||"Creazione non riuscita.","error");}}

function userState(x){if(!x.user_id)return{label:"NESSUN ACCOUNT",cls:"muted"};if(!x.is_active)return{label:"DISATTIVATO",cls:"off"};if(x.must_change_password)return{label:"DA ATTIVARE",cls:"wait"};return{label:"ATTIVO",cls:"ok"};}
function usersMarkup(rows){const total=rows.length,accounts=rows.filter(x=>x.user_id).length,activated=rows.filter(x=>x.user_id&&x.is_active&&!x.must_change_password).length,never=rows.filter(x=>!x.last_access_at&&!x.last_sign_in_at).length;return `<div class="nxa-kpis"><article><strong>${total}</strong><span>Manager</span></article><article><strong>${accounts}</strong><span>Account</span></article><article><strong>${activated}</strong><span>Attivati</span></article><article><strong>${never}</strong><span>Mai entrati</span></article></div><div class="nxa-manager-tools"><input type="search" data-user-filter placeholder="Cerca manager, ID o username"><span>${rows.length} utenti</span></div><div class="nxa-user-list">${rows.map(x=>{const s=userState(x),last=x.last_access_at||x.last_sign_in_at;return `<article class="nxa-user" data-user-search="${esc((x.full_name+" "+x.manager_id+" "+clean(x.username)).toLowerCase())}"><div class="nxa-user-main"><strong>${esc(x.full_name)}</strong><small>${esc(x.manager_id)} · ${esc(x.username||"—")}</small></div><span class="nxa-badge ${s.cls}">${s.label}</span><div class="nxa-user-stat"><b>${Number(x.access_count||0).toLocaleString("it-IT")}</b><small>ACCESSI</small></div><div class="nxa-user-stat wide"><b>${fmtDateTime(last)}</b><small>ULTIMA VISITA</small></div><div class="nxa-user-stat wide"><b>${x.password_changed_at?fmtDateTime(x.password_changed_at):(x.must_change_password?"Da cambiare":"—")}</b><small>PASSWORD</small></div></article>`}).join("")}</div>`;}
async function usersPage(){state.container.innerHTML=shell(`<main class="nxa-page"><div class="nxa-page-title"><small>NEXUS USERS</small><h2>Account & Accessi</h2><p>Stato account, cambio password, numero di sessioni e ultima visita.</p></div><div class="nxa-empty">Caricamento utenti…</div></main>`);try{const d=await rpc("admin_nexus_users",{});state.container.innerHTML=shell(`<main class="nxa-page"><div class="nxa-page-title"><small>NEXUS USERS</small><h2>Account & Accessi</h2><p>Stato account, cambio password, numero di sessioni e ultima visita.</p></div>${usersMarkup(d.rows||[])}</main>`);}catch(e){setStatus(e.message||"Utenti non disponibili.","error");}}

function analyticsMarkup(rows){const now=new Date(),today=now.toISOString().slice(0,10);const current=rows.find(r=>clean(r.week_start)<=today&&clean(r.week_end)>=today)||{visits:0,unique_visitors:0};return `<div class="nxa-kpis nxa-kpis-two"><article><strong>${Number(current.visits||0).toLocaleString("it-IT")}</strong><span>Visite questa settimana</span></article><article><strong>${Number(current.unique_visitors||0).toLocaleString("it-IT")}</strong><span>Visitatori unici</span></article></div><div class="nxa-week-list"><div class="nxa-week-head"><span>SETTIMANA</span><span>VISITE</span><span>UNICI</span></div>${rows.length?rows.map(r=>`<div class="nxa-week-row"><strong>${fmtDate(r.week_start)} → ${fmtDate(r.week_end)}</strong><b>${Number(r.visits||0).toLocaleString("it-IT")}</b><b>${Number(r.unique_visitors||0).toLocaleString("it-IT")}</b></div>`).join(""):'<div class="nxa-empty">Nessun dato disponibile.</div>'}</div>`;}
async function analyticsPage(){state.container.innerHTML=shell(`<main class="nxa-page"><div class="nxa-page-title"><small>ANALYTICS ANONIME</small><h2>Weekly Analytics</h2><p>Una visita per sessione browser. Nessun nome manager è collegato a questi dati.</p></div><div class="nxa-empty">Caricamento analytics…</div></main>`);try{const d=await rpc("admin_analytics_weekly",{});state.container.innerHTML=shell(`<main class="nxa-page"><div class="nxa-page-title"><small>ANALYTICS ANONIME</small><h2>Weekly Analytics</h2><p>Una visita per sessione browser. Nessun nome manager è collegato a questi dati.</p></div>${analyticsMarkup(d.rows||[])}</main>`);}catch(e){setStatus(e.message||"Analytics non disponibili.","error");}}

function render(){if(!state.container)return;if(state.page==="home"){state.container.innerHTML=home();return;}if(state.page==="assignments"){state.container.innerHTML=assignmentsPage();return;}if(state.page==="users"){usersPage();return;}if(state.page==="analytics"){analyticsPage();return;}}
async function mount(o){if(!o||!o.container||!o.client)throw Error("Admin: parametri mancanti");state={container:o.container,client:o.client,user:o.user||null,page:"home",worldId:"",data:null,newEditor:null};render();}
function unmount(){if(state.container)state.container.innerHTML="";state={container:null,client:null,user:null,page:"home",worldId:"",data:null,newEditor:null};}

document.addEventListener("click",e=>{
  if(!state.container||!state.container.contains(e.target))return;
  const exit=e.target.closest("[data-admin-exit]");if(exit){dispatchExit();return;}
  const page=e.target.closest("[data-admin-page]");if(page){state.page=clean(page.getAttribute("data-admin-page"));state.newEditor=null;render();return;}
  if(e.target.closest("[data-load-world]")){loadAssignments();return;}
  const add=e.target.closest("[data-add-assignment]");if(add){state.newEditor={managerId:clean(add.getAttribute("data-manager-id")),type:clean(add.getAttribute("data-add-assignment"))};render();return;}
  if(e.target.closest("[data-cancel-new]")){state.newEditor=null;render();return;}
  const clearEnd=e.target.closest("[data-clear-assignment-end]");if(clearEnd){const row=clearEnd.closest("[data-assignment-id]"),input=row&&row.querySelector("[data-assignment-end]");if(input)input.value="";return;}
  const save=e.target.closest("[data-save-assignment]");if(save){saveExisting(save.closest("[data-assignment-id]"));return;}
  const saveNewBtn=e.target.closest("[data-save-new]");if(saveNewBtn){saveNew(saveNewBtn.closest("[data-new-manager]"));return;}
});
document.addEventListener("input",e=>{
  if(!state.container||!state.container.contains(e.target))return;
  if(e.target.matches("[data-manager-filter]")){const q=clean(e.target.value).toLowerCase();state.container.querySelectorAll("[data-manager-search]").forEach(n=>n.hidden=!!q&&!clean(n.getAttribute("data-manager-search")).includes(q));}
  if(e.target.matches("[data-user-filter]")){const q=clean(e.target.value).toLowerCase();state.container.querySelectorAll("[data-user-search]").forEach(n=>n.hidden=!!q&&!clean(n.getAttribute("data-user-search")).includes(q));}
});

window.IMC_ADMIN={version:VERSION,mount,unmount};
})();